ALTER TABLE ISTITUTI_CREDITO
ADD (NOTE VARCHAR2(2000));

ALTER TABLE ISTITUTI_CREDITO
ADD (NOTE_AL1 VARCHAR2(2000));

ALTER TABLE ISTITUTI_CREDITO
ADD (NOTE_AL2 VARCHAR2(2000));

ALTER TABLE SPORTELLI
ADD (NOTE VARCHAR2(2000));

ALTER TABLE SPORTELLI
ADD (NOTE_AL1 VARCHAR2(2000));

ALTER TABLE SPORTELLI
ADD (NOTE_AL2 VARCHAR2(2000));

-- viene startato in automatico dall'aggiornamento
-- start gp4_alter_note.sql




