-- Form PECAADMQ
delete from a_voci_menu where voce_menu = 'PECAADMQ';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECAADMQ';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECAADMQ';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECAADMQ' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECAADMQ');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

delete from a_guide_o where voce_menu = 'PECAADMQ';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECAADMQ');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECAADMQ'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECAADMQ','P00','AADMQ','Aggiornamento Archivio DMA Sezione F1','F','F','PECAADMQ','',1,'P_DECQ');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1013754','1013769','PECAADMQ','3','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1013754','1013769','PECAADMQ','3','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1013754','1013769','PECAADMQ','3','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF,
PROPRIETA, TITOLO_ESTESO ) VALUES ( 
'P_DECQ', 1, 'GEST', 'G', 'Gestioni', 'P_GEST', NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF,
PROPRIETA, TITOLO_ESTESO ) VALUES ( 
'P_DECQ', 2, 'RIRE', 'M', 'Mese', NULL, 'PECRMERE', NULL, NULL, NULL); 

insert into a_guide_v (guida_v,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_GEST','1','','','Definizione','PGMDGEST','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
insert into a_guide_v (guida_v,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_GEST','2','','','Elenco','PGMEGEST','PGMDGEST');

-- Nuova voce in PECAADMA per richiamare la PECAADMQ

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECAADMA');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF,
PROPRIETA, TITOLO_ESTESO ) VALUES ( 
'P_DECP', 1, 'GEST', 'G', 'Gestioni', 'P_GEST', NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF,
PROPRIETA, TITOLO_ESTESO ) VALUES ( 
'P_DECP', 2, 'RIRE', 'M', 'Mese', NULL, 'PECRMERE', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF,
PROPRIETA, TITOLO_ESTESO ) VALUES ( 
'P_DECP', 3, 'DEDQ', 'S', 'Sez. F1', NULL, 'PECAADMQ', NULL, NULL, NULL);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
