start crp_peccmore10.sql
start crp_peccmore11.sql

start crp_PECCADED.sql


delete from a_voci_menu where voce_menu = 'PECCADED';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECCADED';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECCADED';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECCADED' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECCADED');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

delete from a_guide_o where voce_menu = 'PECCADED';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECCADED');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECCADED'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECCADED','P00','CADED','Caricamento Assestam. Deduzioni','F','D','','',1,'');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCADED','1','Caricamento Assestam. Deduzioni','E','PECCADED','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000548','1013774','PECCADED','2','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000548','1013774','PECCADED','2','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000548','1013774','PECCADED','2','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
