ALTER TABLE POSIZIONI
ADD (AMM_CONS VARCHAR2(2));

INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'NO', NULL, 'N', 'POSIZIONI.AMM_CONS', 'Nè Amministratore nè Consigliere', '', NULL, NULL); 

INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'SI', NULL, 'S', 'POSIZIONI.AMM_CONS', 'Amministratore o Consigliere', '', NULL, NULL); 


start crp_peccnocu.sql