INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_ESC_MEN', 'PECSIMBA', 10, 'Escludi mens. di Rettifica', NULL, NULL, 1, 'U', 'N'
, NULL, 'P_X', NULL, NULL, NULL);

