start crv_vsog.sql

CREATE UNIQUE INDEX SOGI_PK ON 
  SOSTITUZIONI_GIURIDICHE(SOGI_ID) ;

CREATE INDEX SOGI_IK1 ON 
  SOSTITUZIONI_GIURIDICHE(TITOLARE) 
; 

CREATE INDEX SOGI_IK2 ON 
  SOSTITUZIONI_GIURIDICHE(SOSTITUTO, DAL) 
;

CREATE INDEX SOGI_IK3 ON 
  SOSTITUZIONI_GIURIDICHE(RILEVANZA_ASTENSIONE) 
; 

CREATE INDEX SOGI_IK4 ON 
  SOSTITUZIONI_GIURIDICHE(SOSTITUTO, TITOLARE) 
; 

CREATE INDEX SOGI_PEGI_FK ON 
  SOSTITUZIONI_GIURIDICHE(TITOLARE, DAL_ASTENSIONE) 
; 