INSERT INTO ESTRAZIONE_VALORI_CONTABILI 
( ESTRAZIONE, COLONNA, DAL, AL, DESCRIZIONE, SEQUENZA, NOTE, MOLTIPLICA, ARROTONDA, DIVIDE ) 
VALUES 
( 'DENUNCIA_EMENS', 'FONDI_ANTE95',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 'Fondi Speciali per Enti Privati', 10, NULL, NULL, NULL, NULL);

INSERT INTO ESTRAZIONE_VALORI_CONTABILI 
( ESTRAZIONE, COLONNA, DAL, AL, DESCRIZIONE, SEQUENZA, NOTE, MOLTIPLICA, ARROTONDA, DIVIDE ) 
VALUES 
( 'DENUNCIA_EMENS', 'FONDI_ANTE95_ARR',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 'Fondi Speciali per Enti Privati', 10, NULL, NULL, NULL, NULL);

-- inserita nel file A10978
-- start crp_peccadmi.sql