delete from a_selezioni where voce_menu = 'PECCADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_ANNO','PECCADMA','1','Elaborazione: Anno','4','N','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_MESE','PECCADMA','2','                      Mese','2','N','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_GESTIONE','PECCADMA','3','Gestione','8','U','N','%','','GEST','1','1');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_RAPPORTO','PECCADMA','4','Rapporto','4','U','N','%','','CLRA','1','1');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_GRUPPO','PECCADMA','5','Gruppo','12','U','N','%','','GRRA','1','1');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_PREVIDENZA','PECCADMA','6','Previdenza','6','U','N','CP%','P_CP_PREV','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_TIPO','PECCADMA','7','Tipo Elaborazione','1','U','S','','P_CADMA','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_CI','PECCADMA','8','Singolo Individuo: Codice','8','N','N','','','RAIN','0','1');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_CASSA','PECCADMA','9','Archiviazione Econ. Per Cassa','1','U','N','','P_X','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values('P_POSTICIPATO','PECCADMA','10','Rif. denuncia Posticipato','1','U','N','','','','','');
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) 
values ('P_SFASATO','PECCADMA','11','Rif. denuncia Anticipato','1','U','N','','','','','');


-- contiene la start anche per le att 10904 - 10920 - 10940 - 10965 - 11106 -- 11130
start crp_peccadma.sql
start crp_cursore_dma.sql