INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'041', NULL, NULL, 'DENUNCIA_DMA.MAGGIORAZIONI', 'Lavoratori precoci (L.335/95 art.1 c.7)'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'042', NULL, NULL, 'DENUNCIA_DMA.MAGGIORAZIONI', 'Lavoratori sordomuti e invalidi (L.n. 388/2000, art.80, comma 3) 1/6'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'043', NULL, NULL, 'DENUNCIA_DMA.MAGGIORAZIONI', 'Servizio scolastico avente particolari finalita (L.n. 312/80, art. 63) 1/3'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'044', NULL, NULL, 'DENUNCIA_DMA.MAGGIORAZIONI', 'Servizio a bordo di navi (DPR n. 1092/73, art.19, commi 1 e 2) 1/3'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'045', NULL, NULL, 'DENUNCIA_DMA.MAGGIORAZIONI', 'Servizio all estero con compiti di cooperazione con paesi in via di sviluppo in sedi disagiate (L.n.49/87, art.23) 1/2'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'046', NULL, NULL, 'DENUNCIA_DMA.MAGGIORAZIONI', 'Servizio all estero con compitri di cooperazione con paesi in via di sviluppo in sedi particolarmente disagiate (L.n. 49/87, art.23) 3/4'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'047', NULL, NULL, 'DENUNCIA_DMA.MAGGIORAZIONI', 'Servizio in presenza di amianto (art. 47 D.L. 269/03 convertito in L.326/03) 1/4'
, NULL, NULL, NULL); 

