delete from pec_ref_codes where rv_domain='DENUNCIA_DMA.CAUSA_CESSAZIONE';


INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'1', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Decesso', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'10', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', '(2000) Infermit` non dipendente da causa di servizio'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'11', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Esubero Portuali L.n. 647 23/12/96'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'12', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Mobilit`', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'13', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Passaggio ad Altra Amministrazione'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'14', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Licenziamento', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'15', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Fine ferma', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'16', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Altre Cause', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'17', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Dispensa dal servizio per inabilita'' permanente assoluta a proficuo lavoro (minimo 15 anni)'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'18', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Fine incarico', NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'19', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Superi limiti di eta''', NULL
, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'2', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Dimissioni volontarie', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'20', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Superi limiti di eta'' (in base a vigenti disposizioni di legge)'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'21', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Scarso rendimento', NULL, NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'22', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Provvedimennto disciplinare', NULL
, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'23', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Incapacita'' professionale', NULL
, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'24', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Lavoro usurante (art. 1, comma 35, L. 335/95)
'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'25', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Trasformazione del rapporto di lavoro in tempo parziale (D.M. n. 331/97)
'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'26', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Dimissioni volontarie ( art. 59, comma 7, lettera c, L. 449/97)
'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'27', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Dimissioni volontarie ( art. 59, comma 7, lettere a e b, L. 449/97) Precoci ecc.
'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'28', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Cessazione per trasformazione o chiusura ente'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'29', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Risoluzione consensuale per i dirigenti'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'3', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Limiti di eta''', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'31', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Prosecuzione del rapporto di lavoro oltre i limiti di eta'' per il collocamento a riposo (L:186/2004)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'32', NULL, '30_SOSPENSIONE', 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Sospensione di periodo lavorativo utile'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'33', NULL, '33_SOSPENSIONE', 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Carica elettiva art.86 L.267/2000 (T.U. Enti Locali)'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'4', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Limiti di servizio', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'5', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Dispensa del servizio', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'6', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Invalidita''', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'7', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', '(2000) Esodo legge n.26 del 1987'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'8', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Soppressione di posto', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'9', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Destituzione', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'30', NULL, NULL, 'DENUNCIA_DMA.CAUSA_CESSAZIONE', 'Perdita della cittadinanza nel rispetto della normativa comunitaria.', 'CFG', NULL, NULL);

