delete from A_SELEZIONI
where voce_menu = 'PECSDSRE';

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) VALUES ( 
'P_ANNO', 'PECSDSRE', 1, 'Elaborazione   : Anno', 4, 'N', 'N', NULL, NULL, 'RIRE'
, 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) VALUES ( 
'P_MENSILITA', 'PECSDSRE', 2, '                 Mensilita`', 4, 'U', 'N', NULL, NULL
, 'RIRE', 1, 2); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) VALUES ( 
'P_SENSIBILI', 'PECSDSRE', 3, 'Esposizione dati Sensibili :', 2, 'U', 'S', 'SI', 'P_SI_NO'
, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) VALUES ( 
'P_INDIRIZZO', 'PECSDSRE', 5, 'Stampa Indirizzo/Domicilio', 2, 'U', 'S', 'SI', 'P_SI_NO'
, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) VALUES ( 
'P_FIGURA', 'PECSDSRE', 6, 'Stampa Figura', 2, 'U', 'S', 'SI', 'P_SI_NO', NULL, NULL
, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) VALUES ( 
'P_LIVELLO', 'PECSDSRE', 7, 'Stampa Livello/Qualifica', 2, 'U', 'S', 'SI', 'P_SI_NO'
, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) VALUES ( 
'P_FILTRO_1', 'PECSDSRE', 8, 'Raggruppamento : 1)', 15, 'U', 'S', '%', NULL, NULL
, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) VALUES ( 
'P_FILTRO_2', 'PECSDSRE', 9, '                 2)', 15, 'U', 'S', '%', NULL, NULL
, NULL, NULL); 

