delete from CASELLE_FISCALI
where anno = 2004
/
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 1, 'Casella 1', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 2, 'Casella 2', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 3, 'Casella 3', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 4, 'Casella 4', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 5, 'Casella 5', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 6, 'Casella 6', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 7, 'Casella 7', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 8, 'Casella 8', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 9, '770 Casella 9', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 10, '770 Casella 10', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 11, '770 Casella 11', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 12, 'Casella 12', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 13, 'Casella 13', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 14, 'Casella 14', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 15, 'Casella 15', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 16, 'Casella 16', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 17, 'Casella 17', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 18, 'Casella 18', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 19, 'Casella 19', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 20, 'Casella 20', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 21, 'Casella 21', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 22, 'Casella 22', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 23, 'Casella 23', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 24, 'Casella 24', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 25, 'Casella 25', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 26, 'Casella 26', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 27, 'Casella 27', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 28, 'Casella 28', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 29, 'Casella 29', 'T', '101'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 31, 'Casella 31', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 32, 'Casella 32', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 33, 'Casella 33', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 34, 'Casella 34', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 35, 'Casella 35', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 36, 'Casella 36', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 37, 'Casella 37', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 38, 'Casella 38', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 39, 'Casella 39', 'T', '104'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 41, '770 Casella 41', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 42, '770 Casella 42', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 43, '770 Casella 43', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 44, '770 Casella 44', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 45, '770 Casella 45', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 46, 'Casella 46', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 47, 'Casella 47', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 48, 'Casella 48', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 49, 'Casella 49', 'T', '102'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 51, '770 Casella 51', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 52, '770 Casella 52', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 53, '770 Casella 53', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 54, '770 Casella 54', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 55, '770 Casella 55', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 56, '770 Casella 56', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 57, '770 Casella 57', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 58, '770 Casella 58', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 59, '770 Casella 59', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 60, 'Casella 60', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 61, 'Casella 61', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 62, 'Casella 62', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 63, 'Casella 63', 'D', '68'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 68, '770 Casella 68', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 69, '770 Casella 69', 'D', '105'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 70, 'Casella 71', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 71, 'Casella 72', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 72, 'Casella 73', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 73, 'Casella 74', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 74, 'Casella 75', 'T', '103'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 75, 'Prev.Casella 51', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 76, 'Prev.Cas. 51a', 'T', '141'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 77, 'Prev.Casella 58', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 78, 'Prev.Casella 59', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 79, 'Prev.Casella 60', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 80, 'Prev.Casella 61', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 81, 'Prev.Casella 97', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 82, 'Prev.Casella 98', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 83, 'Prev.Casella 99', 'T', '136'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 84, 'Casella 78 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 85, 'Casella 79 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 86, 'Casella 80 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 87, 'Casella 81 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 88, 'Casella 82 TFR', 'T', '142'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 89, 'Casella 84 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 90, 'Casella 86 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 91, 'Casella 88 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 92, 'Casella 89 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 93, 'Casella 91 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 94, 'Casella 93 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 95, 'Casella 94 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 96, 'Casella 95 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 97, 'Casella 96 TFR', 'T', '140'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 98, 'Casella 98 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 99, 'Casella 99 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 100, 'Casella 101TFR', 'T', '111'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 101, '770 Casella 30', 'T', '31'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 102, '770 Casella 50', 'D', '51'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 103, 'Cas.8 Prev.Com.', 'T', '75'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 104, '770 Casella 40', 'T', '41'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 105, '770 -Casella 70', 'D', '70'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 106, 'Prev.Casella 56', 'T', '107'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 107, 'Prev.Casella 57', 'T', '77'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 108, 'Casella 76 TFR', 'T', '109'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 109, 'Casella 77 TFR', 'T', '84'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 111, 'Casella 103 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 112, 'Casella 104 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 113, 'Casella 106 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 114, 'Casella 107 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 115, 'Casella 117 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 116, 'Casella 118 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 117, 'Casella 120 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 118, 'Casella 121 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 119, 'Casella 122 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 120, 'Casella 123 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 121, 'Casella 124 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 122, 'Casella 125 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 123, 'Casella 126 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 124, 'Casella 127 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 125, 'Casella 128 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 126, 'Casella 129 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 127, 'Casella 130 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 128, 'Casella 131 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 129, 'Casella 132 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 130, 'Casella 133 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 131, 'Casella 134 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 132, 'Casella 135 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 133, 'Casella 136 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 134, 'Casella 137 TFR', 'T', '139'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 135, 'Prev.Casella 55', 'T', '106'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 136, 'Prev.Cas.103', 'T', '137'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 137, 'Prev.Cas.104', 'T', '138'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 138, 'Prev.Cas.105', 'T', '108'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 139, 'App. per Note', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 140, 'Casella 97 TFR', 'T', '98'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 141, 'Prev - Cas.52', 'T', '135'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'C', 142, 'Casella 83 TFR', 'T', '89'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 1, 'Casella 1', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 2, 'Casella 2', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 3, 'Casella 3', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 4, 'Casella 4', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 5, 'Casella 5', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 6, 'Casella 6', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 7, 'Casella 7', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 8, 'Casella 8', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 9, '770 Casella 9', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 10, '770 Casella 10', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 11, '770 Casella 11', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 12, 'Casella 12', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 13, 'Casella 13', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 14, 'Casella 14', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 15, 'Casella 15', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 16, 'Casella 16', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 17, 'Casella 17', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 18, 'Casella 18', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 19, 'Casella 19', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 20, 'Casella 20', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 21, 'Casella 21', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 22, 'Casella 22', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 23, 'Casella 23', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 24, 'Casella 24', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 25, 'Casella 25', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 26, 'Casella 26', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 27, 'Casella 27', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 28, 'Casella 28', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 29, 'Casella 29', 'T', '101'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 31, 'Casella 31', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 32, 'Casella 32', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 33, 'Casella 33', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 34, 'Casella 34', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 35, 'Casella 35', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 36, 'Casella 36', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 37, 'Casella 37', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 38, 'Casella 38', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 39, 'Casella 39', 'T', '104'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 41, '770 Casella 41', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 42, '770 Casella 42', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 43, '770 Casella 43', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 44, '770 Casella 44', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 45, '770 Casella 45', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 46, 'Casella 46', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 47, 'Casella 47', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 48, 'Casella 48', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 49, 'Casella 49', 'T', '102'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 51, '770 Casella 51', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 52, '770 Casella 52', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 53, '770 Casella 53', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 54, '770 Casella 54', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 55, '770 Casella 55', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 56, '770 Casella 56', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 57, '770 Casella 57', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 58, '770 Casella 58', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 59, '770 Casella 59', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 60, 'Casella 60', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 61, 'Casella 61', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 62, 'Casella 62', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 63, 'Casella 63', 'D', '68'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 68, '770 Casella 68', 'D', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 69, '770 Casella 69', 'D', '105'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 70, 'Casella 71', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 71, 'Casella 72', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 72, 'Casella 73', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 73, 'Casella 74', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 74, 'Casella 75', 'T', '103'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 75, 'Prev.Casella 51', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 76, 'Prev.Cas. 51a', 'T', '141'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 77, 'Prev.Casella 58', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 78, 'Prev.Casella 59', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 79, 'Prev.Casella 60', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 80, 'Prev.Casella 61', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 81, 'Prev.Casella 97', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 82, 'Prev.Casella 98', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 83, 'Prev.Casella 99', 'T', '136'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 84, 'Casella 78 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 85, 'Casella 79 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 86, 'Casella 80 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 87, 'Casella 81 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 88, 'Casella 82 TFR', 'T', '142'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 89, 'Casella 84 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 90, 'Casella 86 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 91, 'Casella 88 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 92, 'Casella 89 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 93, 'Casella 91 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 94, 'Casella 93 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 95, 'Casella 94 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 96, 'Casella 95 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 97, 'Casella 96 TFR', 'T', '140'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 98, 'Casella 98 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 99, 'Casella 99 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 100, 'Casella 101TFR', 'T', '111'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 101, '770 Casella 30', 'T', '31'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 102, '770 Casella 50', 'D', '51'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 103, 'Cas.8 Prev.Com.', 'T', '75'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 104, '770 Casella 40', 'T', '41'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 105, '770 -Casella 70', 'D', '70'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 106, 'Prev.Casella 56', 'T', '107'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 107, 'Prev.Casella 57', 'T', '77'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 108, 'Casella 76 TFR', 'T', '109'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 109, 'Casella 77 TFR', 'T', '84'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 111, 'Casella 103 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 112, 'Casella 104 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 113, 'Casella 106 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 114, 'Casella 107 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 115, 'Casella 117 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 116, 'Casella 118 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 117, 'Casella 120 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 118, 'Casella 121 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 119, 'Casella 122 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 120, 'Casella 123 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 121, 'Casella 124 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 122, 'Casella 125 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 123, 'Casella 126 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 124, 'Casella 127 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 125, 'Casella 128 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 126, 'Casella 129 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 127, 'Casella 130 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 128, 'Casella 131 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 129, 'Casella 131 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 130, 'Casella 133 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 131, 'Casella 134 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 132, 'Casella 135 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 133, 'Casella 136 TFR', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 134, 'Casella 137 TFR', 'T', '139'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 135, 'Prev.Casella 55', 'T', '106'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 136, 'Prev.Cas.103', 'T', '137'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 137, 'Prev.Cas.104', 'T', '138'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 138, 'Prev.Cas.105', 'T', '108'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 139, 'App. per Note', 'T', NULL); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 140, 'Casella 97 TFR', 'T', '98'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 141, 'Prev - Cas.52', 'T', '135'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, TIPO_CASELLA,CASELLA_DETT )
values ( 2004, 'S', 142, 'Casella 83 TFR', 'T', '89'); 
COMMIT;

