ALTER TABLE CALCOLI_CONTABILI ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE CALCOLI_CONTABILI_BP ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE CALCOLI_CONTABILI_DEP ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE CONTABILITA_VOCE ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE DELIBERE_RETRIBUTIVE ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE DEPOSITO_VARIABILI_ECONOMICHE ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE DEPOSITO_VARIABILI_INCENTIVO ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE IMPEGNI_PROGETTO_INCENTIVO ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE IMPUTAZIONI_CONTABILI ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE MOVIMENTI_BILANCIO_PREVISIONE ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE MOVIMENTI_CONTABILI ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE MOVIMENTI_CONTABILI_PREVISIONE ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE RACCOLTA_MODULI ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE RIGHE_DELIBERA_RETRIBUTIVA ADD (CODICE_SIOPE NUMBER(4));
ALTER TABLE RIPARTIZIONI_CONTABILI ADD (CODICE_SIOPE NUMBER(4));


-- start crp_gp4_rdre.sql
start crv_mobi.sql
start crv_mopr.sql
start crp_peccmoip.sql
start crp_peccmore.sql
start crp_peccmore1.sql
start crp_peccmore4.sql
start crp_peccmore5.sql
start crp_peccmore6.sql
start crp_peccmore9.sql
start crp_peccmocp.sql
start crp_peccmocp1.sql
start crp_peccmocp4.sql
start crp_peccmocp5.sql
start crp_peccmocp6.sql
start crp_peccmocp9.sql
start crp_peccvarm.sql
start crp_peccimco.sql


