delete from A_PASSI_PROC where voce_menu = 'PECL70SA';
INSERT INTO A_PASSI_PROC 
( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,STAMPA, GRUPPO_LING ) 
VALUES ( 'PECL70SA', 1, 'Elenco nominativo e File 770/SA', NULL, NULL, 'Q', 'PECSMFA1', NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC 
( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,STAMPA, GRUPPO_LING ) 
VALUES ( 'PECL70SA', 2, 'Elenco nominativo e File 770/SA', NULL, NULL, 'Q', 'PECSMFA2', NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC
( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,STAMPA, GRUPPO_LING ) VALUES ( 
'PECL70SA', 3, 'Elenco nominativo e File 770/SA', NULL, NULL, 'R', 'PECL70SA', NULL
, 'PECL70SA', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECL70SA', 4, 'Elenco nominativo e File 770/SA', NULL, NULL, 'Q', 'PECCF770', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECL70SA', 5, 'Elenco nominativo e File 770/SA', NULL, NULL, 'R', 'SI4V3WAS', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECL70SA', 6, 'Elenco nominativo e File 770/SA', NULL, NULL, 'Q', 'ACACANAS', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECL70SA', 91, 'Elenco nominativo e File 770/SA', NULL, NULL, 'R', 'ACARAPPR', NULL
, 'ACARAPPR', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECL70SA', 92, 'Elenco nominativo e File 770/SA', NULL, NULL, 'Q', 'ACACANRP', NULL
, NULL, 'N'); 
