start crp_gp4_cost.sql
start crf_pegi_pedo_tma.sql
start crp_gp4do.sql
start crp_peccrein.sql
start crv_dhdu.sql
start crv_dhfu.sql
start crv_dodu.sql
start crv_dofu.sql
start crv_doxh.sql
start crv_gp4do2.sql