INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
PROPRIETA ) VALUES ( 
'P05145', 'Impossibile inserire il record senza caricare i dati di riferimento'
, NULL, NULL, NULL); 

ALTER TABLE FONDI_SPECIALI_EMENS
  MODIFY (FONDO   NOT NULL);
