INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sys.imb1m', '<V:', '5', 'MODELLI_STAMPA.DEFINIZIONE', 'Primo Simbolo per Imbustatrice Automatica Serie 2'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sys.imb2m', '<V:', '5', 'MODELLI_STAMPA.DEFINIZIONE', 'Secondo Simbolo per Imbustatrice Automatica Serie 2'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sys.imb3m', '<V:', '5', 'MODELLI_STAMPA.DEFINIZIONE', 'Terzo Simbolo per Imbustatrice Automatica Serie 2'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sys.imb4m', '<V:', '5', 'MODELLI_STAMPA.DEFINIZIONE', 'Quarto Simbolo per Imbustatrice Automatica Serie 2'
, 'CFG', NULL, NULL);
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sys.imb5m', '<V:', '5', 'MODELLI_STAMPA.DEFINIZIONE', 'Quinto Simbolo per Imbustatrice Automatica Serie 2'
, 'CFG', NULL, NULL);
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sys.imb6m', '<V:', '5', 'MODELLI_STAMPA.DEFINIZIONE', 'Sesto Simbolo per Imbustatrice Automatica Serie 2'
, 'CFG', NULL, NULL);

start crp_pecsmor6.sql

