INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'01', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa in accomandita per anziani'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'02', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa a responsabilita limitata'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'03', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa per azioni', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'04', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa cooperative e loro consorzi iscritti nei registri prefettizi e nello schedario della Cooperazione'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'05', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Altre societa cooperative', NULL, NULL
, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'06', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Mutue assicuratrici ', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'07', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Consorzi con personalita giuridica'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'08', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Associazioni riconosciute', NULL, NULL
, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'09', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Fondazioni', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'10', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Altri enti ed istituti con personalita giuridica'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'11', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Consorzi senza personalita giuridica'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'12', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Associazioni non riconosciute e comitati'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'13', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Altre organizzazioni di persone o di beni senza personalita giuridica(escluse le comunioni)'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'14', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Enti pubblici economici', NULL, NULL
, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'15', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Enti Pubblici non Economici', NULL
, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'16', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Casse mutue e fondi di previdenza, assistenza, pensioni o simili con o senza personalita giuridica'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'17', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Opere pie e societa di mutuo soccorso'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'18', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Enti Ospedalieri', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'19', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Enti ed Istituzioni di Previdenza e Assistenza sociale'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'20', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Aziende autonome di cura, soggiorno e turismo'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'21', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Aziende Regionali, Provinciali, Comunali e loro consorzi'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'22', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa, organizzazioni ed enti costituiti all estero non altrimenti classificabili con sede dell amministrazione ad oggetto principale in Italia'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'23', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa semplici ed equiparate ai sensi dell art.5, comma 3, lett. B), del TUIR'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'24', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa in nome collettivo ed equiparate ai sensi dell art. 5, comma 3, lett. B), del TUIR'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'25', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa in accomandita semplice', NULL
, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'26', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa di armamento', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'27', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Associazione fra artisti e professionisti'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'28', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Aziende coniugali', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'29', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'GEIE (Gruppi europei di interesse economico)'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'30', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa semplici, irregolari e di fatto'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'31', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa in nome collettivo', NULL, NULL
, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'32', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa in accomandita sepmlice', NULL
, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'33', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa di armamento', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'34', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Associazione fra professionisti', NULL
, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'35', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa in accomandita per azioni'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'36', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa a responsabilita limitata'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'37', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa per azioni', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'38', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Consorzi', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'39', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Altri enti ed istituti', NULL, NULL
, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'40', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Associazioni riconosciute, non riconosciute e di fatto'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'41', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Fondazioni', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'42', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Opere pie e societa di mutuo soccorso'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'43', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Altre organizzazioni di persone e di beni'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'50', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa per azioni, aziende speciali e consorzi (artt.31, 113, 114, 115 e 166 D.Lgs.18/8/2000)'
, NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'51', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Condomini', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'52', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Depositi I.V.A.', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'53', NULL, NULL, 'GESTIONI.FORMA_GIURIDICA', 'Societa sportive dilettantistiche costituite in societa di capitali senza fine di lucro'
, NULL, NULL, NULL); 