-- salvataggio dati pregressi per sicurezza
DECLARE
V_esiste varchar2(2);
BEGIN
   BEGIN
   select 'SI'
    into V_esiste 
     from obj
    where object_name = 'IMCC_ANTE_A11916';
   EXCEPTION WHEN NO_DATA_FOUND THEN V_esiste := 'NO';
   END;
   IF V_esiste = 'NO' THEN 
     si4.sql_execute('create table imcc_ante_A11916 as select * from imputazioni_centro_costo');
   END IF;
END;
/

delete from A_SELEZIONI where voce_menu = 'PECCARCC';
delete from A_DOMINI_SELEZIONI where dominio = 'P_CARCC';

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_ANNO', 'PECCARCC', 1, 'Elaborazione: Anno', 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_DA_MESE', 'PECCARCC', 2, '              da mese', 2, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_A_MESE', 'PECCARCC', 3, '               a mese', 2, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO,
VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_ARRETRATI', 'PECCARCC', 4, 'Gestione degli Arretrati:', 1, 'U', 'N', NULL, 'P_CARCC', NULL, NULL, NULL); 

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH,DESCRIZIONE ) 
VALUES ( 'P_CARCC', 'A', NULL, 'Arretrati su Esercizio AP'); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH,DESCRIZIONE )
VALUES ( 'P_CARCC', 'C', NULL, 'Archiviazione per Competenza'); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH,DESCRIZIONE )
 VALUES ( 'P_CARCC', 'P', NULL, 'Archiviazione Anni Precedenti'); 
COMMIT;

start crp_peccarcc.sql