-- Parametro MODELLO_STAMPA per la voce PECSCER6
DELETE from a_selezioni
where voce_menu = 'PECSCER6'
and parametro = 'P_MODELLO_STAMPA';

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_MODELLO_STAMPA', 'PECSCER6', 13, 'Modello Stampa', NULL, NULL, 8, 'U', 'N', NULL
, NULL, 'UNO', NULL, 1); 

-- Nuovo parametro MODELLO_STAMPA per la voce PECSMOR6
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_MODELLO_STAMPA', 'PECSMOR6', 3, 'Modello Stampa', NULL, NULL, 8, 'U', 'N', NULL
, NULL, 'UNO', NULL, 1);

-- Attacco la nuova guida alla voce PECSMOR6
update a_voci_menu set guida_o = 'P_SMOR6'
where voce_menu = 'PECSMOR6';

-- nuova guida orizzontale per la voce PECSMOR6
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_SMOR6', 1, 'UNO', 'D', NULL, NULL, 'moDello', NULL, NULL, NULL, 'PECDSTMS', NULL
, NULL, NULL, NULL, NULL); 


-- nuova guida orizzontale per la voce P_CED6 per la voce PECSSCE6
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CED6', 1, 'PREN', 'P', NULL, NULL, 'Prenot.', NULL, NULL, NULL, 'ACAEPRPA', '*'
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CED6', 2, 'RIRE', 'M', NULL, NULL, 'Mese', NULL, NULL, NULL, 'PECRMERE', NULL, NULL
, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CED6', 3, 'RAIN', 'I', NULL, NULL, 'Individuo', NULL, NULL, NULL, 'P00RANAG', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CED6', 4, 'RECE', 'G', NULL, NULL, 'raGgrupp.', NULL, NULL, NULL, 'PECERECE', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CED6', 5, 'UNO', 'D', NULL, NULL, 'moDello', NULL, NULL, NULL, 'PECDSTMS', NULL
, NULL, NULL, NULL, NULL); 

-- Attacco la nuova guida alla voce PECSCER6
update a_voci_menu set guida_o = 'P_CED6'
where voce_menu = 'PECSCER6';