start crp_pecsmdma.sql

delete from a_selezioni where voce_menu = 'PECSMDMA';

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('SE_RTRIM','PECSMDMA','0','Abilita rtrim','2','C','S','SI','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('TXTFILE','PECSMDMA','0','Nome File','80','C','S','00311430375-022005.txt','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO','PECSMDMA','1','Elaborazione Anno: ..........','4','N','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MESE','PECSMDMA','2','Mese: ........................','2','N','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GESTIONE','PECSMDMA','3','Gestione : ...................','8','U','N','%','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_FORZA_CREDITO','PECSMDMA','4','Forza Contr. Cassa Credito','1','U','S','N','P_FORZA_CREDITO','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_TARDIVO','PECSMDMA','5','Tardivo:......................','1','U','N','','P_X','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_CF_INTE','PECSMDMA','6','Cod.Fis. Intermediario','16','U','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DATA_INTE','PECSMDMA','7','Data impegno Intermediario','10','D','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_FORZA_CREDITO','A','','Azzera Imponibile Cassa Credito');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_FORZA_CREDITO','F','','Forza Contributo Cassa Credito');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_FORZA_CREDITO','N','','Lascia Valori Originali');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        


