delete from RELAZIONE_COND_OGGETTO 
where  OGGETTO = 'REIN'
and RIFERIMENTO =  'CECO' ; 

delete from RELAZIONE_RIFE_OGGETTO 
where  OGGETTO = 'REIN'
and RIFERIMENTO =  'CECO' ; 


INSERT INTO RELAZIONE_OGGETTI ( OGGETTO, DESCRIZIONE, TABELLA ) 
VALUES ( 'CECO_REIN', 'Centri di Costo', 'CENTRI_COSTO'); 

INSERT INTO RELAZIONE_ATTRIBUTI ( ATTRIBUTO, DESCRIZIONE, OGGETTO, COLONNA )
VALUES ( 'CDC_REIN', 'Codice del Centro di Costo', 'CECO_REIN', 'CECO_REIN.codice'); 
INSERT INTO RELAZIONE_ATTRIBUTI ( ATTRIBUTO, DESCRIZIONE, OGGETTO, COLONNA ) 
VALUES ( 'CDC_D_REIN', 'Descrizione del Centro di Costo', 'CECO_REIN', 'CECO_REIN.descrizione'); 
INSERT INTO RELAZIONE_ATTRIBUTI ( ATTRIBUTO, DESCRIZIONE, OGGETTO,COLONNA ) 
VALUES ( '_CDC_REIN', 'Sequenza del Centro di Costo', 'CECO_REIN', 'nvl(CECO_REIN.codice,''ZZZZZZZZ'')'); 

INSERT INTO RELAZIONE_CHIAVI ( CHIAVE, DESCRIZIONE, NOME )
VALUES ( 'CDC_REIN', 'Centro di Costo di imputazione', 'C.d.C.'); 

INSERT INTO RELAZIONE_ATTR_CHIAVE ( CHIAVE, SEQUENZA, ATTRIBUTO, DESCRIZIONE, ALIAS )
VALUES ( 'CDC_REIN', 1, '_CDC_REIN', 'Sequenza di Esposizione', 'S'); 
INSERT INTO RELAZIONE_ATTR_CHIAVE ( CHIAVE, SEQUENZA, ATTRIBUTO, DESCRIZIONE, ALIAS )
VALUES ( 'CDC_REIN', 2, 'CDC_REIN', 'Codice', 'C'); 
INSERT INTO RELAZIONE_ATTR_CHIAVE ( CHIAVE, SEQUENZA, ATTRIBUTO, DESCRIZIONE, ALIAS )
VALUES ( 'CDC_REIN', 3, 'CDC_D_REIN', 'Descrizione', 'D'); 

INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'REIN', 'CECO_REIN'); 

INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE )
VALUES ( 'REIN', 'CECO_REIN', 1, 'and REIN.cdc = CECO_REIN.codice (+)');
