delete from PEC_REF_CODES 
where rv_domain= 'ESTRAZIONE_RIGHE_CONTABILI.ANNO';

INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE ) 
VALUES ( 'A', NULL, '1', 'ESTRAZIONE_RIGHE_CONTABILI.ANNO', 'Arretrati correnti e precedenti', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE )
VALUES ( 'C', NULL, '2', 'ESTRAZIONE_RIGHE_CONTABILI.ANNO', 'Riferimento ad anno Corrente', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE ) 
VALUES ( 'K', NULL, '3', 'ESTRAZIONE_RIGHE_CONTABILI.ANNO', 'Arr. Correnti (Tass. Corrente)', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE ) 
VALUES ( 'M', NULL, '4', 'ESTRAZIONE_RIGHE_CONTABILI.ANNO', 'Competenze del Mese', 'CFG');
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE ) 
VALUES ( 'P', NULL, '5', 'ESTRAZIONE_RIGHE_CONTABILI.ANNO', 'Riferimento ad anni Precedenti', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE ) 
VALUES ( 'S', NULL, '6', 'ESTRAZIONE_RIGHE_CONTABILI.ANNO', 'Arr. Precedenti (Tass. Separata)', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE ) 
VALUES ( 'U', NULL, '7', 'ESTRAZIONE_RIGHE_CONTABILI.ANNO', 'Riferimento Uguale dal Mese', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE )
VALUES ( 'D', NULL, '8', 'ESTRAZIONE_RIGHE_CONTABILI.ANNO', 'Riferimento Diverso dal Mese', 'CFG'); 
COMMIT;

start crv_vaca.sql
start crv_vacm.sql
