-- Si e' deciso di disabilitare dal menu la vecchia PECDONAO non piu' utilizzabile

delete from a_voci_menu where voce_menu = 'PECDONAO';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECDONAO';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECDONAO';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECDONAO';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

delete from a_catalogo_stampe where stampa = 'PECDONAO';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        


start crp_peccmore9.sql
start crp_pecdon05.sql

delete from a_voci_menu where voce_menu = 'PECDON05';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECDON05';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECDON05';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECDON05';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

delete from a_catalogo_stampe where stampa = 'PECDON05';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECDON05','P00','DON05','Duplica voci per Nuova ONAOSI 2005','F','D','ACAPARPR','',1,'P_VOEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECDON05','1','Duplica voci Nuova ONAOSI 2005','Q','PECDON05','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECDON05','91','Stampa Segnalazioni Anomalie','R','ACARAPPR','','PECDON05','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECDON05','92','Cancellazione Segnalazioni','Q','ACACANRP','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_VOCE_MODELLO','PECDON05','1','Voce Modello :','10','U','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_VOCE_NUOVA','PECDON05','2','Voce Nuova :','10','U','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_TITOLO','PECDON05','3','Titolo :','30','U','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000350','1013820','PECDON05','17','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000350','1013820','PECDON05','17','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000350','1013820','PECDON05','17','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

insert into a_catalogo_stampe (stampa,titolo,tipo_proprieta,tipo_visura,classe,stampa_bloccata,stampa_protetta,sequenziale) values ('PECDON05','SEGNALAZIONI DUPLICA VOCI ONAOSI 2005','U','U','A_C','N','N','S');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','1','VOCO','V','Voci','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','2','CVOE','D','Duplica','PECCVOEC','PECDVOEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','3','AUVO','A','Automat.','PECDAUVO','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','4','BAVO','B','Basi','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','5','TAVO','T','Tariffe','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','6','IMVO','I','Imponib.','PECDIMVO','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','7','RIVO','R','Ritenute','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','8','TOVO','Z','totalizZ.','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','9','ESVO','S','eStraz.','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_VOEC','10','MENS','M','Mensilita','PECDMENS','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
