INSERT INTO RELAZIONE_ATTRIBUTI ( ATTRIBUTO, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, OGGETTO,
COLONNA ) VALUES ( 
'CODICE_SIOPE', 'Codice Siope', NULL, NULL, 'VARE', 'VARE.CODICE_SIOPE'); 
INSERT INTO RELAZIONE_ATTR_ESTRAZIONE ( ESTRAZIONE, SEQUENZA, ATTRIBUTO, ALIAS, DESCRIZIONE,
DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) VALUES ( 
'ELENCO_DELIBERA', 24, 'CODICE_SIOPE', 'CODICE_SIOPE', NULL, NULL, NULL); 
COMMIT;