delete from PEC_REF_CODES where RV_DOMAIN = 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE';

INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '1', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Destituzione per motivi disciplinari ( Ante 2005: Decesso ) ', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '2', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Licenziamento art. 52 cc.nnl. con preavviso ( Ante 2005: Dimissioni volontarie )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '3', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Licenziamento art. 52 cc.nnl. senza preavviso ( Ante 2005: Limiti di eta'')', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '4', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Risoluzione Consensuale ( Anet 2005: Limiti di servizio)', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '5', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Invalidita'' totale e permanente ( Ante 2005: Dispensa del servizio )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '6', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Giusta causa ( Ante 2005: Invalidita'' )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '7', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Giustificato Motivo ( 2000: Esodo legge n.26 del 1987 )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '8', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Licenziamento ( Ante 2005: Soppressione di posto)', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '9', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Passaggio ad altra Amministrazione (Ante 2005: Destituzione)', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '10', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Decesso ( 2000: Infermita'' non dipendente da causa di servizio )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '11', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Collocamento a riposo per motivi disciplinari ( Ante 2005: Esubero Portuali L.n. 647 23/12/96 )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '12', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Dispensa Servizio ( Ante 2005: Mobilita'' )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '13', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Dimissioni ( Ante 2005: Passaggio ad Altra Amministrazione )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '14', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Decadenza ( Ante 2005: Licenziamento )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '15', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Cessazione per anzianita'' ante Poste ( Ante 2005: Fine ferma )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '16', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Cessazione per limiti di eta'' ante Poste ( Ante 2005: Altre Cause )', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '17', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Cessazione per limiti di eta'' ( Ante 2005:Dispensa dal servizio per inabilita'' permanente assoluta a proficuo lavoro (minimo 15 anni))', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '18', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Cessazione per anzianita'' contributiva ( Ante 2005: Fine incarico )', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '19', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Cessazione perido prova ( Ante 2005: Superi limiti di eta'' )', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '20', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Fine contratto t.d. ( Ante 2005: Superi limiti di eta'' (in base a vigenti disposizioni di legge)) ', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '21', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Servizio militare ( Ante 2005: Scarso rendimento )', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '22', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Rinuncia assunzione ( Ante 2005: Provvedimennto disciplinare )', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '23', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Passaggio a Postecom ( Ante 2005: Incapacita'' professionale )', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '24', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Passaggio a Egi Spa ( Ante 2005: Lavoro usurante (art. 1, comma 35, L. 335/95) )', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '25', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , 'Passaggio a Postevita (Ante 2005: Trasformazione del rapporto di lavoro in tempo parziale (D.M. n. 331/97) )', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '26', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , '(Ante 2005: Dimissioni volontarie ( art. 59, comma 7, lettera c, L. 449/97) ) ', NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '27', NULL, NULL, 'DENUNCIA_INPDAP.CAUSA_CESSAZIONE'
       , '(Ante 2005: Dimissioni volontarie ( art. 59, comma 7, lettere a e b, L. 449/97) Precoci ecc.)', NULL);

