INSERT INTO PAM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'NO', NULL, 'N', 'CLASSI_RAPPORTO.VORTALE', 'Rapporto non visibile su Vortale', 'CFG'
, NULL, NULL); 
INSERT INTO PAM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'SI', NULL, 'S', 'CLASSI_RAPPORTO.VORTALE', 'Rapporto visibile su Vortale', 'CFG'
, NULL, NULL);