-- Attività 13003 Inserimento di revisioni di dotazione già obsolete


INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'A', NULL, NULL, 'REVISIONI.STATO', 'Revisione Attiva', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'M', NULL, NULL, 'REVISIONI.STATO', 'Revisione in Modifica', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'O', NULL, NULL, 'REVISIONI.STATO', 'Revisione Obsoleta', 'CFG', NULL, NULL); 


start crp_gp4do.sql