INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'rare.delega', '<V:', '55', 'MODELLI_STAMPA.DEFINIZIONE', 'Delega (ARARE)', 'CFG'
, NULL, NULL);
 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'rare.descrizione_banca2', '<V:', '60', 'MODELLI_STAMPA.DEFINIZIONE', 'Dati Bancari Del Dipendente senza Delega (ARARE)'
, 'CFG', NULL, NULL); 

start crp_pecsmor6.sql
