start crp_pecconfr.sql

delete from a_voci_menu where voce_menu = 'PECCONFR';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECCONFR';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECCONFR';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECCONFR' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECCONFR');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

delete from a_guide_o where voce_menu = 'PECCONFR';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECCONFR');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECCONFR'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECCONFR','P00','CONFR','Carica contributi Onaosi fuori Rapporto','F','D','ACAPARPR','',1,'P_RCNON');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCONFR','1','Carica contributi Onaosi fuori Rapporto','Q','PECCONFR','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCONFR','91','Stampa Segnalazioni Anomalie','R','ACARAPPR','','PECCONFR','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCONFR','92','Cancellazione Segnalazioni','Q','ACACANRP','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_CI','PECCONFR','1','Codice Individuale :','8','N','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DATA_INIZIO','PECCONFR','2','Data Inizio :','10','D','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DATA_FINE','PECCONFR','3','Data Fine :','10','D','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO','PECCONFR','4','Anno :','4','N','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MENSILITA','PECCONFR','5','Cod.Mensilita :','4','U','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000506','1013822','PECCONFR','13','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000506','1013822','PECCONFR','13','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000506','1013822','PECCONFR','13','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

insert into a_catalogo_stampe (stampa,titolo,tipo_proprieta,tipo_visura,classe,stampa_bloccata,stampa_protetta,sequenziale) values ('PECCONFR','SEGNALAZIONI RICHIESTA CONGUAGLIO ONAOSI','U','U','A_C','N','N','S');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_RCNON','1','PREN','P','Pren.','ACAEPRPA','*');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_RCNON','2','TRPR','T','Trattam.','PECDTRPR','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

