delete from A_PASSI_PROC where voce_menu = 'PECCIMCE';

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TIPO, MODULO, STRINGA, STAMPA, GRUPPO_LING ) 
VALUES ( 'PECCIMCE', 1, 'Caricamento Imputazione Contab.Economica', 'F', 'PECCIMCE', NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TIPO, MODULO, STRINGA, STAMPA, GRUPPO_LING ) 
VALUES ( 'PECCIMCE', 2, 'Verifica presenza segnalazioni', 'Q', 'CHK_ERR', NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TIPO, MODULO, STRINGA, STAMPA, GRUPPO_LING ) 
VALUES ( 'PECCIMCE', 91, 'Segnalazioni Imputazione Conta.Economica', 'R', 'ACARAPPR', NULL, 'PECELASE', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TIPO, MODULO, STRINGA, STAMPA, GRUPPO_LING ) 
VALUES ( 'PECCIMCE', 92, 'Cancellazione Segnalazioni', 'Q', 'ACACANRP', NULL, NULL, 'N'); 

start crp_peccimce.sql