delete from a_guide_o
where guida_o = 'P_RICO';

INSERT INTO A_GUIDE_O 
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO ) 
VALUES ( 'P_RICO', 1, 'RICO', 'E', 'Elenco', NULL, 'PECERICO', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O 
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO ) 
VALUES ( 'P_RICO', 2, 'GEST', 'G', 'Gestioni', NULL, 'PGMEGEST', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO )
VALUES ( 'P_RICO', 3, 'RUOL', 'R', 'Ruoli', NULL, 'PGMERUOL', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O 
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO )
VALUES ( 'P_RICO', 4, 'CONT', 'C', 'Contratti', NULL, 'PGMDCONT', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO )
VALUES ( 'P_RICO', 5, 'CLFU', 'F', 'Cod. Funz', NULL, 'PGMDCLFU', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO )
VALUES ( 'P_RICO', 6, 'COBI', 'C', 'Cod. Bil.', NULL, 'PECDCOBI', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO )
VALUES ( 'P_RICO', 7, 'ISCR', 'I', 'Ist. Cred', NULL, 'PECDISCR', NULL, NULL, NULL); 