INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '1', 'CALENDARI.MESE', 'Gennaio' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '2', 'CALENDARI.MESE', 'Febbraio' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '3', 'CALENDARI.MESE', 'Marzo' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '4', 'CALENDARI.MESE', 'Aprile' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '5', 'CALENDARI.MESE', 'Maggio' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '6', 'CALENDARI.MESE', 'Giugno' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '7', 'CALENDARI.MESE', 'Luglio' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '8', 'CALENDARI.MESE', 'Agosto' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '9', 'CALENDARI.MESE', 'Settembre' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
VALUES ( '10', 'CALENDARI.MESE', 'Ottobre' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
 VALUES ( '11', 'CALENDARI.MESE', 'Novembre' );
INSERT INTO PPA_REF_CODES 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING ) 
 VALUES ( '12', 'CALENDARI.MESE', 'Dicembre' );
