start crp_pecrcnon.sql

delete from a_voci_menu where voce_menu = 'PECRCNON';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECRCNON';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECRCNON';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECRCNON' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECRCNON');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

delete from a_guide_o where voce_menu = 'PECRCNON';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECRCNON');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECRCNON'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECRCNON','P00','RCNON','Richiesta Conguaglio ONAOSI','F','D','ACAPARPR','',1,'P_RCNON');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECRCNON','1','Richiesta Conguaglio ONAOSI','Q','PECRCNON','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECRCNON','91','Stampa Segnalazioni Anomalie','R','ACARAPPR','','PECRCNON','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECRCNON','92','Cancellazione Segnalazioni','Q','ACACANRP','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_CI','PECRCNON','1','Codice Individuale :','8','N','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_TRATT_PREV','PECRCNON','2','Trattamento Prev. :','4','U','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DATA_INIZIO','PECRCNON','3','Data Inizio :','10','D','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO','PECRCNON','4','Anno :','4','N','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MENSILITA','PECRCNON','5','Cod.Mensilita :','4','U','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000506','1013821','PECRCNON','12','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000506','1013821','PECRCNON','12','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000506','1013821','PECRCNON','12','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

insert into a_catalogo_stampe (stampa,titolo,tipo_proprieta,tipo_visura,classe,stampa_bloccata,stampa_protetta,sequenziale) values ('PECRCNON','SEGNALAZIONI RICHIESTA CONGUAGLIO ONAOSI','U','U','A_C','N','N','S');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,guida_v,voce_menu,voce_rif,proprieta) values ('P_RCNON','1','PREN','P','Pren.','','ACAEPRPA','*','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,guida_v,voce_menu,voce_rif,proprieta) values ('P_RCNON','2','TRPR','T','Trattam.','','PECDTRPR','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

