delete from PEC_REF_CODES
where RV_DOMAIN = 'RIPARTIZIONI_CONTABILI.ARR';

INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '%', NULL, NULL, 'RIPARTIZIONI_CONTABILI.ARR', 'Somme correnti ed arretrate', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '1', '9', NULL, 'RIPARTIZIONI_CONTABILI.ARR', 'Solo somme relative al numero di anni precedenti indicato', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ('C', NULL, NULL, 'RIPARTIZIONI_CONTABILI.ARR', 'Solo somme relative al mese corrente', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ('A', NULL, NULL, 'RIPARTIZIONI_CONTABILI.ARR', 'Solo somme relative all''anno corrente', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ('P', NULL, NULL, 'RIPARTIZIONI_CONTABILI.ARR', 'Solo somme relative ad anni precedenti tass. corrente', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ('S', NULL, NULL, 'RIPARTIZIONI_CONTABILI.ARR', 'Solo somme relative ad anni precedenti tass. separata', 'CFG'); 

commit;