INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2 ) VALUES ( 
'D_LVAEM', 'D', NULL, 'Stampa Dettaglio Individuale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2 ) VALUES ( 
'D_LVAEM', 'Q', NULL, 'Stampa Quadrature', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2 ) VALUES ( 
'D_LVAEM', 'T', NULL, 'Solo Totali', NULL, NULL); 

INSERT INTO A_CATALOGO_STAMPE ( STAMPA, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO_PROPRIETA, TIPO_VISURA,
CLASSE, STAMPA_BLOCCATA, STAMPA_PROTETTA, SEQUENZIALE ) VALUES ( 
'PECLVAEM', 'Lista Verifiche Annuali Denuncia EMENS', NULL, NULL, 'U', 'U', 'A_C'
, 'N', 'N', 'S'); 

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_LVAEM', 1, 'PREN', 'P', NULL, NULL, 'Pren.', NULL, NULL, NULL, 'ACAEPRPA', '*'
, NULL, 'Prenotazioni', NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_LVAEM', 2, 'GEST', 'G', NULL, NULL, 'Gestioni', NULL, NULL, NULL, 'PGMEGEST', NULL
, NULL, NULL, NULL, NULL); 

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,
PROPRIETA ) VALUES ( 
'PECLVAEM', 'P00', 'LVAEM', NULL, NULL, 'Lista Verifiche Annuali Denuncia EMENS', NULL
, NULL, 'F', 'D', 'ACAPARPR', NULL, 1, 'P_LVAEM', NULL);

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECLVAEM', 1, 'Lista Verifiche Annuali Denuncia EMENS', NULL, NULL, 'R', 'PECLVAEM'
, NULL, 'PECLVAEM', 'N');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_ANNO', 'PECLVAEM', 1, 'Elaborazione Anno: ...........', NULL, NULL, 4, 'N', 'N'
, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_ANNO_DENUNCIA', 'PECLVAEM', 2, 'Anno Denuncia: ...............', NULL, NULL, 4
, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_GESTIONE', 'PECLVAEM', 3, 'Gestione: ....................', NULL, NULL, 8, 'U'
, 'N', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_ORDINAMENTO', 'PECLVAEM', 5, 'Ordinamento: .................', NULL, NULL, 1, 'U'
, 'N', 'C', 'P_LNDMI', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_TIPO', 'PECLVAEM', 4, 'Tipo Elaborazione:............', NULL, NULL, 1, 'U', 'N'
, NULL, 'D_LVAEM', NULL, NULL, NULL);

INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA,
STAMPANTE ) VALUES ( 
'GP4', 'AMM', 1013748, 1013834, 'PECLVAEM', 6, NULL); 
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA,
STAMPANTE ) VALUES ( 
'GP4', '*', 1013748, 1013834, 'PECLVAEM', 6, NULL); 
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA,
STAMPANTE ) VALUES ( 
'GP4', 'PEC', 1013748, 1013834, 'PECLVAEM', 6, NULL); 

INSERT INTO ESTRAZIONE_VALORI_CONTABILI ( ESTRAZIONE, COLONNA, DAL, AL, DESCRIZIONE, SEQUENZA, NOTE,
MOLTIPLICA, ARROTONDA, DIVIDE ) VALUES ( 
'DENUNCIA_EMENS', 'Q_C_INPS',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 'Colonna di controllo su contributi INPS', 103, NULL, NULL, NULL, NULL); 
INSERT INTO ESTRAZIONE_VALORI_CONTABILI ( ESTRAZIONE, COLONNA, DAL, AL, DESCRIZIONE, SEQUENZA, NOTE,
MOLTIPLICA, ARROTONDA, DIVIDE ) VALUES ( 
'DENUNCIA_EMENS', 'Q_INPS',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 'Colonna di controllo su imponibili INPS', 101, NULL, NULL, NULL, NULL); 
INSERT INTO ESTRAZIONE_VALORI_CONTABILI ( ESTRAZIONE, COLONNA, DAL, AL, DESCRIZIONE, SEQUENZA, NOTE,
MOLTIPLICA, ARROTONDA, DIVIDE ) VALUES ( 
'DENUNCIA_EMENS', 'Q_R_INPS',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 'Colonna di controllo su ritenute INPS', 102, NULL, NULL, NULL, NULL); 

 


