INSERT INTO PEC_REF_CODES 
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( 'INPGI', '18', 'DEF_ISTITUTI_PREVIDENZIALI.ISTITUTO',
         'Istituto Nazionale Previdenza Giornalisti Italiani');
