ALTER TABLE ARCHIVIO_DOCUMENTI_GIURIDICI
MODIFY(EVENTO VARCHAR2(6));

ALTER TABLE ASTENSIONI
MODIFY(EVENTO VARCHAR2(6));

ALTER TABLE DEPOSITO_PERIODI_PRESENZA
MODIFY(EVENTO VARCHAR2(6));

ALTER TABLE PERIODI_BLOCCO
MODIFY(EVENTO VARCHAR2(6));

ALTER TABLE PERIODI_DOTAZIONE
MODIFY(EVENTO VARCHAR2(6));

ALTER TABLE SOTTOCODICI_DOCUMENTO
MODIFY(EVENTO VARCHAR2(6));


