DELETE FROM A_SELEZIONI WHERE VOCE_MENU='PECSQUIN';

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_ANNO', 'PECSQUIN', 1, 'Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_GESTIONE', 'PECSQUIN', 2, 'Gestione', NULL, NULL, 8, 'U', 'N', '%', NULL, NULL
, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_FILTRO_1', 'PECSQUIN', 3, 'Raggruppamento : 1)', NULL, NULL, 15, 'U', 'N', '%'
, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_FILTRO_2', 'PECSQUIN', 4, '2)', NULL, NULL, 15, 'U', 'N', '%', NULL, NULL, NULL
, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_FILTRO_3', 'PECSQUIN', 5, '3)', NULL, NULL, 15, 'U', 'N', '%', NULL, NULL, NULL
, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_FILTRO_4', 'PECSQUIN', 6, '4)', NULL, NULL, 15, 'U', 'N', '%', NULL, NULL, NULL
, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_NOMINATIVO', 'PECSQUIN', 7, 'Dettaglio Nominativo', NULL, NULL, 1, 'U', 'N', 'X'
, NULL, NULL, NULL, NULL); 

INSERT INTO RELAZIONE_ATTRIBUTI ( ATTRIBUTO, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, OGGETTO,
COLONNA ) VALUES ( 
'REIN.CONTO_F', 'Conto delle retribuzioni inai per contabilita finanziarial', NULL
, NULL, 'REIN', 'REIN.RISORSA_INTERVENTO||''.''||REIN.CAPITOLO||''/''||REIN.ARTICOLO||''-''||REIN.CONTO||'' ''||REIN.IMPEGNO||''/''||REIN.ANNO_IMPEGNO||'' ''||REIN.SUB_IMPEGNO||''/''||REIN.ANNO_SUB_IMPEGNO||'' ''||REIN.CODICE_SIOPE'); 

INSERT INTO RELAZIONE_ATTR_ESTRAZIONE ( ESTRAZIONE, SEQUENZA, ATTRIBUTO, ALIAS, DESCRIZIONE,
DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) VALUES ( 
'QUADRATURA_INAIL', 14, 'REIN.CONTO_F', 'CONTO_F', NULL, NULL, NULL); 

INSERT INTO RELAZIONE_ATTR_ESTRAZIONE ( ESTRAZIONE, SEQUENZA, ATTRIBUTO, ALIAS, DESCRIZIONE,
DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) VALUES ( 
'LIS_AUTOLIQUIDAZIONE', 12, 'REIN.CONTO_F', 'CONTO_F', NULL, NULL, NULL); 

COMMIT;
