INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'A', NULL, NULL, 'VOCABOLO', 'a', NULL, 'x', 'y'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'AL', NULL, NULL, 'VOCABOLO', 'al', NULL, 'xx', 'yy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'ANNI', NULL, NULL, 'VOCABOLO', 'anni', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'CHE', NULL, NULL, 'VOCABOLO', 'che', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'COD.IND.', NULL, NULL, 'VOCABOLO', 'Cod.Ind.', NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'CON', NULL, NULL, 'VOCABOLO', 'con', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'CONTESTUALMENTE', NULL, NULL, 'VOCABOLO', 'E contestualmente', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'DAL', NULL, NULL, 'VOCABOLO', 'dal', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'DECORRE', NULL, NULL, 'VOCABOLO', 'a decorrere dal', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'DEL', NULL, NULL, 'VOCABOLO', 'del', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'EURO', NULL, NULL, 'VOCABOLO', 'Euro', NULL, 'xxxx', 'yyyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'GIORNI', NULL, NULL, 'VOCABOLO', 'giorni', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'IL', NULL, NULL, 'VOCABOLO', 'il', NULL, 'xx', 'yy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'LA', NULL, NULL, 'VOCABOLO', 'la', NULL, 'xx', 'yy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'MESI', NULL, NULL, 'VOCABOLO', 'mesi', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'NASCITA_F', NULL, NULL, 'VOCABOLO', 'nata a', NULL, 'xxxx x', 'yyyy y'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'NASCITA_M', NULL, NULL, 'VOCABOLO', 'nato a', NULL, 'xxxx x', 'yyyy y'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'NUMERO', NULL, NULL, 'VOCABOLO', 'n.', NULL, 'x.', 'y.'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'RESIDENZA', NULL, NULL, 'VOCABOLO', 'residente in', NULL, 'xxxxxxxxx xx', 'yyyyyyyyy yy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'SIGNOR', NULL, NULL, 'VOCABOLO', 'Sig.', NULL, 'xxxx', 'yyyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'SIGNORA', NULL, NULL, 'VOCABOLO', 'Sig.ra', NULL, 'xxxx.xx', 'yyyy.yy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'SOTTOLINEA', NULL, NULL, 'VOCABOLO', '--------------------', NULL, 'xxx', 'yyy'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'SOTTOSCRITTA', NULL, NULL, 'VOCABOLO', 'io sottoscritta', NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) 
VALUES ( 'SOTTOSCRITTO', NULL, NULL, 'VOCABOLO', 'io sottoscritto', NULL, NULL, NULL); 