INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_RIBASSATE', 'PECSMCU6', 22, 'Stampa note ribassate', NULL, NULL, 2, 'U', 'S', 'NO'
, 'P_SI_NO', NULL, NULL, NULL);