-- sistemazione voce per WIN PGMLSETT
delete from a_voci_menu where voce_menu = 'PGMLSETT';
insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o)
values ('PGMLSETT','P00','LSETT','Lista Suddivisioni Settoriali','F','D','ACAPARPR','',1,'P_LSETT');

delete from a_selezioni where  voce_menu = 'PGMLSETT';
INSERT INTO A_SELEZIONI 
( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK ) 
VALUES ( 'P_GESTIONE', 'PGMLSETT', 6, 'Gestione', 4, 'U', 'N', '%', NULL, 'GEST', 1, 1);

DELETE FROM A_GUIDE_O WHERE GUIDA_O  = 'P_LSETT';
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO ) 
VALUES ( 'P_LSETT', 1, 'GEST', 'G', 'Gestioni', NULL, 'PGMEGEST', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO ) 
VALUES ( 'P_LSETT', 2, 'PARA', 'P', 'Prenot.', NULL, 'ACAEPRPA', '*', NULL, NULL); 

-- sistemazione voce per WEB PGMLSET6
update a_voci_menu
set guida_o = 'P_LSET6'
where voce_menu = 'PGMLSET6';

delete from A_DOMINI_SELEZIONI
 where dominio = 'P_RILEVANZA';

INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_RILEVANZA', 'A', NULL, 'Astensione dal Servizio ( APEAS )'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_RILEVANZA', 'E', NULL, 'Incarico di Diritto ( APESI )'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_RILEVANZA', 'I', NULL, 'Servizio effettivo Incarico  ( APESE )'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_RILEVANZA', 'P', NULL, 'Rapporto di Lavoro ( APERL )'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_RILEVANZA', 'Q', NULL, 'Inquadramento di Diritto ( APESQ )'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_RILEVANZA', 'S', NULL, 'Servizio di Fatto in Inquad. ( APESS )'); 

delete from A_SELEZIONI
 where voce_menu = 'PGMLSET6';

INSERT INTO A_SELEZIONI 
( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_REVISIONE', 'PGMLSET6', 1, 'Revisione', 8, 'N', 'N', NULL, NULL, 'REST', 0, 1); 
INSERT INTO A_SELEZIONI 
( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_GESTIONE', 'PGMLSET6', 2, 'Gestione', 4, 'U', 'N', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI 
( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_COMPONENTI', 'PGMLSET6', 3, 'Componenti', 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI 
( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES (  'P_ASSEGNATI', 'PGMLSET6', 4, 'Assegnati', 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI 
( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_IN_SERVIZIO', 'PGMLSET6', 5, 'In Servizio', 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI 
( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK ) 
VALUES ( 'P_RILEVANZA', 'PGMLSET6', 6, 'Rilevanza', 1, 'U', 'S', 'Q', 'P_RILEVANZA', NULL, NULL
, NULL);

DELETE FROM A_GUIDE_O WHERE GUIDA_O  = 'P_LSET6';

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO )
VALUES ( 'P_LSET6', 1, 'REST', 'V', 'reVisioni', NULL, 'PGMDREST', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO ) 
VALUES ( 'P_LSET6', 2, 'GEST', 'G', 'Gestioni', NULL, 'PGMEGEST', NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, TITOLO, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO ) 
VALUES ( 'P_LSET6', 3, 'PARA', 'P', 'Prenot.', NULL, 'ACAEPRPA', '*', NULL, NULL); 

