
delete from a_voci_menu where voce_menu = 'PECUADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECUADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECUADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where ruolo in ('AMM','PEC') and  voce_menu = 'PECUADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

delete from a_catalogo_stampe where stampa = 'PECUADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECUADMA','P00','UADMA','Unificazione Archivio DMA','F','D','ACAPARPR','',1,'P_UADMA');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECUADMA','1','Unificazione Archivio DMA','Q','PECUADMA','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_A_ANNO','PECUADMA','3','A  Anno','4','N','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_A_MESE','PECUADMA','4','A  Mese','2','N','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DA_ANNO','PECUADMA','1','Da Anno','4','N','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DA_MESE','PECUADMA','2','Da Mese','2','N','S','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GESTIONE','PECUADMA','5','Gestione','8','U','N','%','','GEST','1','1');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GRUPPO','PECUADMA','7','Gruppo','12','U','N','%','','GRRA','1','1');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_PREVIDENZA','PECUADMA','8','Previdenza','6','U','N','CP%','P_CP_PREV','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_RAPPORTO','PECUADMA','6','Rapporto','4','U','N','%','','CLRA','1','1');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1013754','19437','PECUADMA','7','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1013754','19437','PECUADMA','7','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1013754','19437','PECUADMA','7','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_UADMA','1','PREN','P','Pren.','ACAEPRPA','*');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_UADMA','2','GEST','G','Gestioni','PGMEGEST','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_UADMA','3','CLRA','R','Rapporti','PAMDCLRA','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_UADMA','4','GRRA','U','grUppi','PAMDGRRA','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CP_PREV','%','','Elabora tutti gli Enti Previdenziali');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CP_PREV','CP%','','Elabora tutte le Casse Pensioni');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CP_PREV','CPDEL','','Cassa Pensione Dipendenti Enti Locali');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CP_PREV','CPFPC','','Fondo Previdenza e Credito');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CP_PREV','CPI','','Cassa Pensione Insegnanti');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CP_PREV','CPS','','Cassa Pensione Sanitari');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CP_PREV','CPSTAT','','Cassa Pensione Statali');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
PROPRIETA ) VALUES ( 
'P00151', 'Periodo DAL maggiore di periodo AL', NULL, NULL, NULL);

start crp_pecuadma.sql
