INSERT INTO GIP_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'CONP', NULL, NULL, 'PTCXXYY.ALIAS', 'Condizioni non Professionali', 'CFG', NULL, NULL);
INSERT INTO GIP_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'PARE', NULL, NULL, 'PTCXXYY.ALIAS', 'Parentele', 'CFG', NULL, NULL);
