INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'REIN', 'ASIN');
INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'REIN', 'CECO_REIN');
INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'REIN', 'GEST');
INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'REIN', 'RAGI');
INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'REIN', 'RAIN');

INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'ASIN', 'REIN');
INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'CECO_REIN', 'REIN');
INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'GEST', 'REIN');
INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'RAGI', 'REIN');
INSERT INTO RELAZIONE_RIFE_OGGETTO ( OGGETTO, RIFERIMENTO ) 
VALUES ( 'RAIN', 'REIN');

INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'REIN', 'ASIN', 1, 'and REIN.POSIZIONE_INAIL = ASIN.codice');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'ASIN', 'REIN', 1, 'and REIN.POSIZIONE_INAIL = ASIN.codice');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'REIN', 'RAIN', 1, 'and REIN.CI = RAIN.CI');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'RAIN', 'REIN', 1, 'and REIN.CI = RAIN.CI');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'REIN', 'GEST', 1, 'and REIN.gestione = GEST.codice');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'GEST', 'REIN', 1, 'and REIN.gestione = GEST.codice');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE )
VALUES ( 'REIN', 'CECO_REIN', 1, 'and REIN.cdc = CECO_REIN.codice (+)');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'CECO_REIN', 'REIN', 1, 'and REIN.cdc = CECO.codice (+)');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'REIN', 'RAGI', 1, 'and REIN.CI = RAGI.CI');
INSERT INTO RELAZIONE_COND_OGGETTO ( OGGETTO, RIFERIMENTO, SEQUENZA, RELAZIONE ) 
VALUES ( 'RAGI', 'REIN', 1, 'and REIN.CI = RAGI.CI');

