INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'S', NULL, NULL, 'CONTABILITA_VOCE.RAPPORTO', 'Giorni Servizio a Rapp. orario', 'CFG'
, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'T', NULL, NULL, 'CONTABILITA_VOCE.RAPPORTO', 'Giorni Servizio a Rapp. orario Mese Precedente'
, 'CFG', NULL, NULL);
