delete from PAM_REF_CODES
 where RV_DOMAIN = 'CLASSI_RAPPORTO.CAT_FISCALE'
   and RV_LOW_VALUE in ( '15', '25' );
INSERT INTO PAM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE )
VALUES ( '15', NULL, 'A', 'CLASSI_RAPPORTO.CAT_FISCALE', 'Mod. 770 quadri SA, SB e SD no sosp Add. (dipendenti)', 'CFG'); 
INSERT INTO PAM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ( '25', NULL, 'A', 'CLASSI_RAPPORTO.CAT_FISCALE', 'Mod. 770 quadro SA , SB e SD no sosp Add. (assimilati)', 'CFG'); 

