INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_ASTE', 4, 'IMAS', 'A', NULL, NULL, 'imp.Assen', NULL, NULL, NULL, 'PECDIMAS', NULL
, NULL, NULL, NULL, NULL); 

