INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( 'GESCAL', '19', 'DEF_ISTITUTI_PREVIDENZIALI.ISTITUTO', 'Gestione per Case Lavoratori'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( 'INPDAI', '20', 'DEF_ISTITUTI_PREVIDENZIALI.ISTITUTO', 'Istituto Naz. di previdenza per i dirigenti di aziende industriali '); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( 'INAM', '21', 'DEF_ISTITUTI_PREVIDENZIALI.ISTITUTO', 'Istituto Nazionale Assistenza Malattia Lavoratori'); 