INSERT INTO PAM_REF_CODES 
( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 )
VALUES ( 'FH', NULL, NULL, 'PARENTELE.CARICO_FIS', 'Figlio Handicappato', 'CFG', NULL, NULL); 
INSERT INTO PAM_REF_CODES
( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 )
VALUES ( 'HD', NULL, NULL, 'PARENTELE.CARICO_FIS', 'Figlio Handicappato Doppio', 'CFG', NULL, NULL); 

start crp_pecccafa.sql