INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_COD_FISCALE', 'PECSDDRE', 6, 'Stampa Codice Fiscale', NULL, NULL, 1, 'U', 'N', NULL, 'P_X'
, NULL, NULL, NULL); 

