alter table eventi_infortunio add (SEDE_INAIL_RES        VARCHAR2(15)   NULL
                                  ,MOD_INVIO_SOMMA       VARCHAR2(2)    NULL);
						
/* Inserimento richiamo in contesto DSEIN */

delete from a_guide_o 
 where guida_o = 'P_CDEIN';
 
 /* Nuovo Ref-Codes campo Mod_invio_somma */ 

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CDEIN', 1, 'CAIN', 'C', NULL, NULL, 'Cause', NULL, NULL, NULL, 'PECDCAIN', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CDEIN', 2, 'QUIN', 'Q', NULL, NULL, 'Qua.inail', NULL, NULL, NULL, 'PECDQUIN', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CDEIN', 3, 'CAIN', 'A', NULL, NULL, 'Agenti', NULL, NULL, NULL, 'PECDAGIN', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CDEIN', 4, 'PAAN', 'P', NULL, NULL, 'Parti an.', NULL, NULL, NULL, 'PECDPAAN', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CDEIN', 5, 'ATIN', 'T', NULL, NULL, 'aTtivita', NULL, NULL, NULL, 'PECDATIN', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CDEIN', 6, 'CRAT', 'R', NULL, NULL, 'att.Reg.', NULL, NULL, NULL, 'PECDCRAT', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CDEIN', 7, 'SEIN', 'S', NULL, NULL, 'Sed.Inail', NULL, NULL, NULL, 'PECDSEIN', NULL
, NULL, NULL, NULL, NULL); 				
						
								  
/* Modifica Ref-Codes */ 

delete 
from pec_ref_codes 
where rv_domain = 'EVENTI_INFORTUNIO.VALIDITA'; 
 
 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'SI', NULL, '1', 'EVENTI_INFORTUNIO.VALIDITA', 'L''evento è valido', NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'NO', NULL, '2', 'EVENTI_INFORTUNIO.VALIDITA', 'L''evento NON è valido', NULL, NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'A', NULL, '3', 'EVENTI_INFORTUNIO.VALIDITA', 'Annullato per errore di digitazione'
, NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'I', NULL, '4', 'EVENTI_INFORTUNIO.VALIDITA', 'Passato di competenza INPS', NULL, NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'N', NULL, '5', 'EVENTI_INFORTUNIO.VALIDITA', 'Annullato dall''INAIL', NULL, NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'R', NULL, '6', 'EVENTI_INFORTUNIO.VALIDITA', 'Rinuncia dei giorni da parte dell''infortunato'
, NULL, NULL, NULL);								  

/* Setto la Sede di Default */

update eventi_infortunio evin
   set sede_inail_res = 
	   (select sein.codice
		  from sedi_inail           sein
		      ,rapporti_retributivi rare
			  ,assicurazioni_inail  asin
		 where rare.ci              = evin.ci
		   and rare.posizione_inail = asin.codice
		   and asin.sede_inail      = sein.codice)
 where nvl(sede_inail_res,' ') = ' ' 		   
;	

/* Inserimento nuovo ref_codes per invio somma inab. temporanea */

INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE ) VALUES ( 
'DL', NULL, 'DL', 'EVENTI_INFORTUNIO.MOD_INVIO_SOMMA', 'Al Datore di Lavoro', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE ) VALUES ( 
'LD', NULL, 'LD', 'EVENTI_INFORTUNIO.MOD_INVIO_SOMMA', 'Al Lavoratore presso il proprio Domicilio'
, 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE ) VALUES ( 
'LS', NULL, 'LS', 'EVENTI_INFORTUNIO.MOD_INVIO_SOMMA', 'Al Lavoratore presso la Sede dell''impresa'
, 'CFG'); 

