-- Attività 17536

delete from a_guide_o
where guida_o='P_RATGI';

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RATGI', 1, 'UNO', 'R', NULL, NULL, 'Rettifica', NULL, NULL, NULL, 'PGMAATGI', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RATGI', 2, 'PEGI', 'P', NULL, NULL, 'Periodi', NULL, NULL, NULL, 'PGMAPEGI', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RATGI', 3, 'CAAT', 'A', NULL, NULL, 'Attributi', NULL, NULL, NULL, 'PGMDATGI', NULL
, NULL, NULL, NULL, NULL); 

update a_voci_menu
set guida_o='P_RATGI'
where voce_menu='PGMRATGI';
