INSERT INTO pgm_ref_codes 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ('A', 'VARIABILI_ATTRIBUTO.TIPO','Alfanumerico','CFG' );
INSERT INTO pgm_ref_codes 
( RV_LOW_VALUE, RV_DOMAIN, RV_MEANING, RV_TYPE )
VALUES ('N', 'VARIABILI_ATTRIBUTO.TIPO','Numerico','CFG' );