insert into a_errori ( errore, descrizione )
values ('P01088','Codice Comune non Codificato');
insert into a_errori ( errore, descrizione )
values ('P01089','Codice Regione non Codificata');


insert into a_errori ( errore, descrizione ,proprieta)
values ('P05716','Il Codice Regione va indicato in Presenza di Add. Regionale o Comunale','B');
insert into a_errori ( errore, descrizione ,proprieta)
values ('P05717','L''addizionale va indicata in Presenza di Codice Regionale o Comunale','B');

insert into a_errori ( errore, descrizione ,proprieta)
values ('P05745','Non sono permesse piu'' di 2 registrazioni per Individuo in un Anno','B');
insert into a_errori ( errore, descrizione ,proprieta)
values ('P05746','Non e'' permessa piu'' di una reg. di ril. M per Individuo in un Anno','B');
insert into a_errori ( errore, descrizione ,proprieta)
values ('P05747','Non sono permesse piu'' reg. di ril. diversa da M per Ind. in un Anno','B');
insert into a_errori ( errore, descrizione ,proprieta)
values ('P05749','Non e'' permessa una reg. con ril. M in assenza di reg. di altro tipo','B');

delete from PEC_REF_CODES 
where RV_DOMAIN = 'DENUNCIA_CAAF.CODICE_REGIONE';

INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '1', '01', 'DENUNCIA_CAAF.CODICE_REGIONE', 'ABRUZZO');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '2', '02', 'DENUNCIA_CAAF.CODICE_REGIONE', 'BASILICATA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '3', '03', 'DENUNCIA_CAAF.CODICE_REGIONE', 'BOLZANO');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '4', '04', 'DENUNCIA_CAAF.CODICE_REGIONE', 'CALABRIA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '5', '05', 'DENUNCIA_CAAF.CODICE_REGIONE', 'CAMPANIA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '6', '06', 'DENUNCIA_CAAF.CODICE_REGIONE', 'EMILIA ROMAGNA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '7', '07', 'DENUNCIA_CAAF.CODICE_REGIONE', 'FRIULI VENEZIA GIULIA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '8', '08', 'DENUNCIA_CAAF.CODICE_REGIONE', 'LAZIO');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '9', '09', 'DENUNCIA_CAAF.CODICE_REGIONE', 'LIGURIA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '10', '10', 'DENUNCIA_CAAF.CODICE_REGIONE', 'LOMBARDIA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '11', '11', 'DENUNCIA_CAAF.CODICE_REGIONE', 'MARCHE');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '12', '12', 'DENUNCIA_CAAF.CODICE_REGIONE', 'MOLISE');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '13', '13', 'DENUNCIA_CAAF.CODICE_REGIONE', 'PIEMONTE');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '14', '14', 'DENUNCIA_CAAF.CODICE_REGIONE', 'PUGLIA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '15', '15', 'DENUNCIA_CAAF.CODICE_REGIONE', 'SARDEGNA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '16', '16', 'DENUNCIA_CAAF.CODICE_REGIONE', 'SICILIA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '17', '17', 'DENUNCIA_CAAF.CODICE_REGIONE', 'TOSCANA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '18', '18', 'DENUNCIA_CAAF.CODICE_REGIONE', 'TRENTO');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '19', '19', 'DENUNCIA_CAAF.CODICE_REGIONE', 'UMBRIA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '20', '20', 'DENUNCIA_CAAF.CODICE_REGIONE', 'VALLE D''AOSTA');
INSERT INTO PEC_REF_CODES
( RV_LOW_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING )
VALUES ( '21', '21', 'DENUNCIA_CAAF.CODICE_REGIONE', 'VENETO');
