delete A_GUIDE_O where GUIDA_O in ('P_CSTVB','P_CSMVB');

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSMVB', 1, 'PREN', 'P', NULL, NULL, 'Prenot.', NULL, NULL, NULL, 'ACAEPRPA', '*', NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSMVB', 2, 'RIRE', 'M', NULL, NULL, 'Mese', NULL, NULL, NULL, 'PECRMERE', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSMVB', 3, 'GEST', 'S', NULL, NULL, 'geStioni', NULL, NULL, NULL, 'PGMEGEST', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSMVB', 4, 'CLRA', 'R', NULL, NULL, 'Rapporti', NULL, NULL, NULL, 'PAMDCLRA', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSMVB', 5, 'GRRA', 'P', NULL, NULL, 'gruPpi', NULL, NULL, NULL, 'PAMDGRRA', NULL, NULL, NULL, NULL, NULL); 

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSTVB', 1, 'PREN', 'P', NULL, NULL, 'Prenot.', NULL, NULL, NULL, 'ACAEPRPA', '*', NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSTVB', 2, 'RIRE', 'M', NULL, NULL, 'Mese', NULL, NULL, NULL, 'PECRMERE', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSTVB', 3, 'GEST', 'S', NULL, NULL, 'geStioni', NULL, NULL, NULL, 'PGMEGEST', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSTVB', 4, 'CLRA', 'R', NULL, NULL, 'Rapporti', NULL, NULL, NULL, 'PAMDCLRA', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
values ( 'P_CSTVB', 5, 'GRRA', 'P', NULL, NULL, 'gruPpi', NULL, NULL, NULL, 'PAMDGRRA', NULL, NULL, NULL, NULL, NULL);

UPDATE A_VOCI_MENU SET GUIDA_O = 'P_CSTVB'
WHERE  VOCE_MENU='PECCSTVB';

UPDATE A_VOCI_MENU SET GUIDA_O = 'P_CSMVB'
WHERE  VOCE_MENU='PECCSMVB';

DELETE A_SELEZIONI
WHERE VOCE_MENU='PECCSTVB';

DELETE A_SELEZIONI
WHERE VOCE_MENU='PECCSMVB';

insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'NUM_CARATTERI', 'PECCSMVB', 0, 'Numero caratteri per substring', NULL, NULL, 4, 'C', 'S', '120', NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'SE_SUBSTR', 'PECCSMVB', 0, 'Abilita substring', NULL, NULL, 2, 'C', 'S', 'SI', NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'SE_UPPER', 'PECCSMVB', 0, 'Abilita upper', NULL, NULL, 2, 'C', 'S', 'SI', NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'TXTFILE', 'PECCSMVB', 0, 'Nome TXT da produrre', NULL, NULL, 80, 'C', 'S', 'PECCSMVB.txt', NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_ANNO', 'PECCSMVB', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, 'RIRE', 1, 1); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_MENSILITA', 'PECCSMVB', 2, '    Cod.Mensilita''', NULL, NULL, 4, 'U', 'N', NULL, NULL, 'RIRE', 1, 2); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_ACCREDITI', 'PECCSMVB', 3, 'Solo Accrediti', NULL, NULL, 1, 'U', 'N', 'X', 'P_X', NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_BANCHE_ESTERE', 'PECCSMVB', 4, 'Banche Estere', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_IBAN', 'PECCSMVB', 5, 'Coordinate IBAN', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_FASCIA', 'PECCSMVB', 6, 'Fascia', NULL, NULL, 2, 'U', 'N', '%', NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_GESTIONE', 'PECCSMVB', 7, 'Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_RAPPORTO', 'PECCSMVB', 8, 'Rapporto', NULL, NULL, 4, 'U', 'N', '%', NULL, 'CLRA', 1, 1); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_GRUPPO', 'PECCSMVB', 9, 'Gruppo', NULL, NULL, 12, 'U', 'N', '%', NULL, 'GRRA', 1, 1); 

insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'NUM_CARATTERI', 'PECCSTVB', 0, 'Caratteri per substring', NULL, NULL, 4, 'C', 'S', '120', NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'SE_SUBSTR', 'PECCSTVB', 0, 'Abilita substring', NULL, NULL, 2, 'C', 'S', 'SI', NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'SE_UPPER', 'PECCSTVB', 0, 'Abilita upper', NULL, NULL, 2, 'C', 'S', 'SI', NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'TXTFILE', 'PECCSTVB', 0, 'Nome TXT da produrre', NULL, NULL, 80, 'C', 'S', 'PECCSTVB.txt', NULL, NULL, NULL, NULL);
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_ANNO', 'PECCSTVB', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, 'RIRE', 1, 1); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_MENSILITA', 'PECCSTVB', 2, '    Cod.Mensilita''', NULL, NULL, 4, 'U', 'N', NULL, NULL, 'RIRE', 1, 2); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_ACCREDITI', 'PECCSTVB', 3, 'Solo Accrediti', NULL, NULL, 1, 'U', 'N', 'X', 'P_ACCREDITI_CSTVB', NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_BANCHE_ESTERE', 'PECCSTVB', 4, 'Banche Estere', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_DATA_ESECUZIONE', 'PECCSTVB', 5, 'Data di Esecuzione', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_IBAN', 'PECCSTVB', 6, 'Coordinate IBAN', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_FASCIA', 'PECCSTVB', 7, 'Fascia di Gestione', NULL, NULL, 2, 'U', 'N', NULL, NULL, NULL, NULL, 3); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_RAPPORTO', 'PECCSTVB', 8, 'Rapporto', NULL, NULL, 4, 'U', 'N', '%', NULL, 'CLRA', 1, 1); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_GESTIONE', 'PECCSTVB', 9, 'Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
insert into a_selezioni ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
values ( 'P_GRUPPO', 'PECCSTVB', 10, 'Gruppo', NULL, NULL, 12, 'U', 'N', '%', NULL, 'GRRA', 1, 1); 
