start crp_peccepre.sql

insert into a_errori ( errore, descrizione )
values ('P05874','Colonna definita in modo errato per estrazione ');

delete A_PASSI_PROC where voce_menu='PECSEPRE';

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRE', 1, 'Estrazioni Parametriche di Retribuzione', NULL, NULL, 'Q', 'PECCEPRE'
, NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRE', 2, 'Caricamento Tabella Calcolo Valori', NULL, NULL, 'Q', 'PECCCAVA', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRE', 3, 'Estrazioni Parametriche di Retribuzione', NULL, NULL, 'R', 'PECSEPRE'
, NULL, 'PECSEPRE', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRE', 4, 'Delete da Tabella Calcolo Valori', NULL, NULL, 'Q', 'PECDCAVA', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRE', 10, 'Estrazioni Parametriche per Totali', NULL, NULL, 'R', 'PECSEPTO'
, NULL, 'PECSEPTO', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRE', 11, 'Delete da Tabella Calcolo Valori', NULL, NULL, 'Q', 'PECDCAVA', NULL
, NULL, 'N'); 

delete A_PASSI_PROC where voce_menu='PECSEPRP';

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRP', 1, 'Estraz. Param. Retribuzione Periodiche', NULL, NULL, 'Q', 'PECCEPRE'
, NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRP', 2, 'Caricamento Tabella Calcolo Valori', NULL, NULL, 'Q', 'PECCCAVA', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRP', 3, 'Estraz. Param. Retribuzione Periodiche', NULL, NULL, 'R', 'PECSEPRE'
, NULL, 'PECSEPRE', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRP', 4, 'Calcellazione tabella Calcolo Valori', NULL, NULL, 'Q', 'PECDCAVA'
, NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRP', 10, 'Estrazioni Parametriche per Totali', NULL, NULL, 'R', 'PECSEPTO'
, NULL, 'PECSEPTO', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSEPRP', 11, 'Delete da Tabella Calcolo Valori', NULL, NULL, 'Q', 'PECDCAVA', NULL
, NULL, 'N'); 

