DELETE A_GUIDE_O WHERE GUIDA_O='P_SRIRI';

INSERT INTO A_GUIDE_O 
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
VALUES ( 'P_SRIRI', 1, 'PREN', 'P', NULL, NULL, 'Prenotaz.', NULL, NULL, NULL, 'ACAEPRPA', '*', NULL, NULL, NULL, NULL); 

INSERT INTO A_GUIDE_O 
( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 )
VALUES ( 'P_SRIRI', 2, 'RAIN', 'I', NULL, NULL, 'Individuo', NULL, NULL, NULL, 'P00RANAG', NULL, NULL, NULL, NULL, NULL); 


DELETE A_VOCI_MENU WHERE VOCE_MENU='PMTSRIRI';

INSERT INTO A_VOCI_MENU 
( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,PROPRIETA )
VALUES ( 'PMTSRIRI', 'P00', 'SRIRI', NULL, NULL, 'Stampa Richieste di Rimborso', NULL, NULL, 'F', 'D', 'ACAPARPR', NULL, 1, 'P_SRIRI', NULL); 

DELETE A_SELEZIONI WHERE VOCE_MENU='PMTSRIRI';

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
VALUES ( 'P_CI', 'PMTSRIRI', 1, 'Cod.Ind.', NULL, NULL, 8, 'N', 'N', NULL, NULL, 'RAIN', 0, 1); 

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
VALUES ( 'P_RICHIESTA', 'PMTSRIRI', 2, 'Richiesta', NULL, NULL, 1, 'N', 'S', NULL, 'PMTSRIRI_RICHIESTA', NULL, NULL, NULL); 

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
VALUES ( 'P_DATA_INIZIO', 'PMTSRIRI', 3, 'Data Inizio Trasferta', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
VALUES ( 'P_DATA_FINE', 'PMTSRIRI', 4, 'Data Fine Trasferta', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
VALUES ( 'P_DATA_INI_AGG', 'PMTSRIRI', 5, 'Data Inizio Aggiornamento', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK )
VALUES ( 'P_DATA_FIN_AGG', 'PMTSRIRI', 6, 'Data Fine Aggiornamento', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 


DELETE A_DOMINI_SELEZIONI WHERE DOMINIO='PMTSRIRI_RICHIESTA';

INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2 ) 
VALUES ( 'PMTSRIRI_RICHIESTA', '1', NULL, 'Richiesta caricata dal dipendente', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2 ) 
VALUES ( 'PMTSRIRI_RICHIESTA', '2', NULL, 'Richiesta valutata dall''ufficio', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1,DESCRIZIONE_AL2 ) 
VALUES ( 'PMTSRIRI_RICHIESTA', '3', NULL, 'Tutte le Richieste', NULL, NULL); 
