alter table ente add (INVIO_CEDOLINO          varchar2(1) DEFAULT 'P'
                    , PUBBLICAZIONE_CEDOLINO  NUMBER(1));

INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'A', NULL, NULL, 'ENTE.INVIO_CEDOLINO', 'Allegato alla Mail', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'N', NULL, NULL, 'ENTE.INVIO_CEDOLINO', 'Notifica Pubblicazione', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'P', NULL, NULL, 'ENTE.INVIO_CEDOLINO', 'Postalizzazione', 'CFG', NULL, NULL);

start crp_PECSMORM.sql
start crp_CHK_MAIL.sql
