ALTER TABLE ANAGRAFICI MODIFY(E_MAIL VARCHAR2(2000));
ALTER TABLE GESTIONI MODIFY(E_MAIL VARCHAR2(2000));
ALTER TABLE ENTE MODIFY(E_MAIL VARCHAR2(2000));
ALTER TABLE RAPPORTI_INDIVIDUALI MODIFY(E_MAIL VARCHAR2(2000));
ALTER TABLE COMPONENTI MODIFY(E_MAIL VARCHAR2(2000));

start crp_pecsmorm.sql
start crp_pecsmgla.sql
start crp_pecsmdpm.sql


