ALTER TABLE ARCHIVIO_DOCUMENTI_GIURIDICI ADD (DATO_A4 VARCHAR2(30));
ALTER TABLE ARCHIVIO_DOCUMENTI_GIURIDICI ADD (DATO_N4 NUMBER(15,5));


--la vista viene ricreata anche se invariata per farle acquisire campi nuovi

start crv_dogi.sql


ALTER TABLE SOTTOCODICI_DOCUMENTO ADD (NOTA_N4 VARCHAR2(15));
ALTER TABLE SOTTOCODICI_DOCUMENTO ADD (NOTA_N4_AL1 VARCHAR2(15));
ALTER TABLE SOTTOCODICI_DOCUMENTO ADD (NOTA_N4_AL2 VARCHAR2(15));
ALTER TABLE SOTTOCODICI_DOCUMENTO ADD (NOTA_A4 VARCHAR2(15));
ALTER TABLE SOTTOCODICI_DOCUMENTO ADD (NOTA_A4_AL1 VARCHAR2(15));
ALTER TABLE SOTTOCODICI_DOCUMENTO ADD (NOTA_A4_AL2 VARCHAR2(15));



