delete from a_guide_o
where guida_o='P_NOVO';

insert into a_guide_o (GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1, TITOLO_ESTESO_AL2)
values ('P_NOVO', 1, 'VOCO', 'V', '', '', 'Voci', '', '', 'P_VOCO', '', '', '', '', '', '');

insert into a_guide_o (GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1, TITOLO_ESTESO_AL2)
values ('P_NOVO', 2, 'CONT', 'C', '', '', 'Contratti', '', '', '', 'PGMDCONT', '', '', '', '', '');

insert into a_guide_o (GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1, TITOLO_ESTESO_AL2)
values ('P_NOVO', 3, 'QUGI', 'Q', '', '', 'Qualifica', '', '', '', 'PGMDQUAL', '', '', '', '', '');

insert into a_guide_o (GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1, TITOLO_ESTESO_AL2)
values ('P_NOVO', 4, 'RUOL', 'R', '', '', 'Ruoli', '', '', '', 'PGMDRUOL', '', '', '', '', '');

insert into a_guide_o (GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1, TITOLO_ESTESO_AL2)
values ('P_NOVO', 5, 'FIGU', 'F', '', '', 'Figure', '', '', '', 'PGMDFIGU', '', '', '', '', '');

insert into a_guide_o (GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1, TITOLO_ESTESO_AL2)
values ('P_NOVO', 6, 'TIRA', 'T', '', '', 'Tipi rap.', '', '', '', 'PGMDTIRA', '', '', '', '', '');

insert into a_guide_o (GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1, TITOLO_ESTESO_AL2)
values ('P_NOVO', 7, 'POSI', 'P', '', '', 'Posizioni', '', '', '', 'PGMDPOSI', '', '', '', '', '');
