-- Inserimento testata DESVC

INSERT INTO ESTRAZIONE_VALORI_CONTABILI 
( ESTRAZIONE, COLONNA, DAL, SEQUENZA, DESCRIZIONE, NOTE )
select 
'SMT_TAB8B', '13',  to_date('01012006','ddmmyyyy'), 10, 'Cod. S820','Compenso per Turni di Guardia Notturni'
from dual
where exists (select 'x' 
                from  ESTRAZIONE_VALORI_CONTABILI 
               where  estrazione = 'SMT_TAB8B' 
                 and  colonna = '01'
                 and descrizione like '%202%')
and   not exists (select 'x' 
                    from ESTRAZIONE_VALORI_CONTABILI 
                   where estrazione = 'SMT_TAB8B' 
                     and colonna    = '13') ;



start crp_pecsmt13.sql

INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL1', NULL, NULL, 'SMT_TAB8B', 'Colonna 1', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL2', NULL, NULL, 'SMT_TAB8B', 'Colonna 2', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL3', NULL, NULL, 'SMT_TAB8B', 'Colonna 3', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL4', NULL, NULL, 'SMT_TAB8B', 'Colonna 4', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL5', NULL, NULL, 'SMT_TAB8B', 'Colonna 5', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL6', NULL, NULL, 'SMT_TAB8B', 'Colonna 6', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL7', NULL, NULL, 'SMT_TAB8B', 'Colonna 7', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL8', NULL, NULL, 'SMT_TAB8B', 'Colonna 8', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL9', NULL, NULL, 'SMT_TAB8B', 'Colonna 9', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL10', NULL, NULL, 'SMT_TAB8B', 'Colonna 10', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL11', NULL, NULL, 'SMT_TAB8B', 'Colonna 11', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL12', NULL, NULL, 'SMT_TAB8B', 'Colonna 12', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('COL13', NULL, NULL, 'SMT_TAB8B', 'Colonna 13', 'CFG', NULL, NULL); 


