DELETE PGM_REF_CODES WHERE RV_DOMAIN='EVENTI_GIURIDICI.CONTO_ANNUALE';

INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('0', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Assenze non gestite', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('1', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Colonna 1', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('2', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Colonna 2', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('3', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Colonna 3', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('4', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Colonna 4', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('5', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Colonna 5', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('6', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Colonna 6', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('7', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Colonna 7', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('99', NULL, NULL, 'EVENTI_GIURIDICI.CONTO_ANNUALE', 'Cessazione', NULL, NULL, NULL); 

