INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGMAAPEA', 1, 'Aggiornamento Automatico Assenze', NULL, NULL, 'Q', 'PGMAAPEA', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGMAAPEA', 91, 'Errore in Elaborazione', NULL, NULL, 'R', 'ACARAPPR', NULL, 'PECELASE'
, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGMAAPEA', 92, 'Cancellazione Errori', NULL, NULL, 'Q', 'ACACANRP', NULL, NULL, NULL); 

start crp_pgmaapea.sql