ALTER TABLE RIMBORSI_INFORTUNIO
MODIFY(NUMERO_PRATICA NUMBER(10));

INSERT INTO A_ERRORI 
( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, PROPRIETA ) 
VALUES ( 'P00608', 'La data inizio rimborso non può essere inferiore alla data infortunio', NULL, NULL, NULL); 
INSERT INTO A_ERRORI
( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, PROPRIETA )
VALUES ( 'P00607', 'La data inizio prosecuz. non può essere inferiore alla  data infortunio', NULL, NULL, NULL);

INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE )
VALUES ( 'ACCONTO', NULL, NULL, 'EVENTI_INFORTUNIO.CAUSALE_RIMBORSO', 'Acconto', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE )
VALUES ( 'CONGUAGLIO', NULL, NULL, 'EVENTI_INFORTUNIO.CAUSALE_RIMBORSO', 'Conguaglio', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE )
VALUES ( 'RICADUTA', NULL, NULL, 'EVENTI_INFORTUNIO.CAUSALE_RIMBORSO', 'Ricaduta', 'CFG'); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE )
VALUES ( 'SALDO', NULL, NULL, 'EVENTI_INFORTUNIO.CAUSALE_RIMBORSO', 'Saldo', 'CFG'); 

