ALTER TABLE RICHIESTE_RIMBORSO ADD (sede_del VARCHAR2(4));
ALTER TABLE RICHIESTE_RIMBORSO ADD (numero_del NUMBER(7));
ALTER TABLE RICHIESTE_RIMBORSO ADD (anno_del NUMBER(4));

ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (sede_del VARCHAR2(4));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (numero_del NUMBER(7));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (anno_del NUMBER(4));

ALTER TABLE RICHIESTE_RIMBORSO ADD (RISORSA_INTERVENTO VARCHAR2(7));
ALTER TABLE RICHIESTE_RIMBORSO ADD (CAPITOLO VARCHAR2(14));
ALTER TABLE RICHIESTE_RIMBORSO ADD (ARTICOLO VARCHAR2(14));
ALTER TABLE RICHIESTE_RIMBORSO ADD (CONTO VARCHAR2(2));
ALTER TABLE RICHIESTE_RIMBORSO ADD (IMPEGNO NUMBER(5));
ALTER TABLE RICHIESTE_RIMBORSO ADD (ANNO_IMPEGNO NUMBER(4));
ALTER TABLE RICHIESTE_RIMBORSO ADD (SUB_IMPEGNO NUMBER(5));
ALTER TABLE RICHIESTE_RIMBORSO ADD (ANNO_SUB_IMPEGNO NUMBER(4));
ALTER TABLE RICHIESTE_RIMBORSO ADD (CODICE_SIOPE NUMBER(4));

ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (RISORSA_INTERVENTO VARCHAR2(7));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (CAPITOLO VARCHAR2(14));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (ARTICOLO VARCHAR2(14));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (CONTO VARCHAR2(2));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (IMPEGNO NUMBER(5));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (ANNO_IMPEGNO NUMBER(4));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (SUB_IMPEGNO NUMBER(5));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (ANNO_SUB_IMPEGNO NUMBER(4));
ALTER TABLE RIGHE_RICHIESTA_RIMBORSO ADD (CODICE_SIOPE NUMBER(4));

DELETE A_VOCI_MENU WHERE VOCE_MENU='PMTCCOUF';

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,PROPRIETA ) VALUES ('PMTCCOUF', 'P00', 'CCOUF', NULL, NULL, 'Caricamento Controllo Ufficio', NULL, NULL, 'F', 'F', 'PMTCCOUF', NULL, 1, 'P_CCOUF', NULL);

DELETE A_GUIDE_O WHERE GUIDA_O='P_CCOUF'; 

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 ) VALUES ('P_CCOUF', 1, 'ACER', 'A', NULL, NULL, 'Acconti', NULL, NULL, NULL, 'PMTEACER', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 ) VALUES ('P_CCOUF', 2, 'DELI', 'D', NULL, NULL, 'Delibere', NULL, NULL, NULL, 'P00EDELI', NULL, NULL, NULL, NULL, NULL); 


-- start crp_gp4mt.sql ( inclusa nel file A20121 )
