INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'12', NULL, NULL, 'ASTENSIONI.DISOCCUPAZIONE_INPS', 'Congedo Matrimoniale', 'CFG'
, NULL, NULL);

-- Modifica per A21464.1
start crv_wpegi.sql

start crp_PECCDS22.sql
start crp_PECCSR18.sql


