DELETE A_VOCI_MENU WHERE VOCE_MENU='PMTCRIST';

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,PROPRIETA ) VALUES ('PMTCRIST', 'P00', 'CRIST', NULL, NULL, 'Caricamento Richieste di Storno', NULL, NULL, 'F', 'F', 'PMTCRIST', NULL, 1, 'P_CRIST', NULL); 

DELETE A_GUIDE_O WHERE GUIDA_O='P_CRIST';

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 ) VALUES ('P_CRIST', 1, 'ACER', 'A', NULL, NULL, 'Acconti', NULL, NULL, NULL, 'PMTEACER', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,TITOLO_ESTESO_AL2 ) VALUES ('P_CRIST', 2, 'DELI', 'D', NULL, NULL, 'Delibere', NULL, NULL, NULL, 'P00EDELI', NULL, NULL, NULL, NULL, NULL); 

