delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECCCC07');                                                                                                                                                                                                      
delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECCCC07'));                                                                                                                                                     
delete from a_voci_menu where voce_menu = 'PECCCC07';                                                                                                                                                                                                                                                       
delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECCCC07');                                                                                                                                                                  
delete from a_passi_proc where voce_menu = 'PECCCC07';                                                                                                                                                                                                                                                      
delete from a_selezioni where voce_menu = 'PECCCC07';                                                                                                                                                                                                                                                       
delete from a_menu where voce_menu = 'PECCCC07' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                             
insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECCCC07','P00','CCC07','Conguaglio Cassa / Competenza','F','D','ACAPARPR','',1,'A_PARA');                                                                                           
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCCC07','1','Conguaglio Cassa / Competenza','Q','PECCCC07','','','');                                                                                                                                   
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCCC07','91','Stampa Segnalazioni Anomalie','R','ACARAPPR','','PECCCC07','N');                                                                                                                          
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCCC07','92','Cancellazione Segnalazioni','Q','ACACANRP','','','N');                                                                                                                                    
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO_CONG','PECCCC07','1','Anno Conguaglio effettuato:','4','N','S','','','','','');                                                            
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MESE_CONG','PECCCC07','2','Mese Conguaglio effettuato:','2','N','S','','','','','');                                                            
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MENSILITA_CONG','PECCCC07','3','Mens.Conguaglio effettuato:','4','U','S','','','','','');                                                       
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO_ELAB','PECCCC07','4','Anno da elaborare:','4','N','S','','','','','');                                                                     
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MESE_ELAB','PECCCC07','5','Mese da elaborare:','2','N','S','','','','','');                                                                     
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MENSILITA_ELAB','PECCCC07','6','Mens. da elaborare:','4','U','S','','','','','');                                                               
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_RAPPORTO','PECCCC07','7','Classe rapporto:','4','U','S','%','','CLRA','1','1');                                                                 
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GESTIONE','PECCCC07','8','Gestione:','8','U','S','%','','GEST','1','1');                                                                        
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_CONTRATTO','PECCCC07','9','Contratto:','4','U','S','%','','CONT','1','1');                                                                      
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_QUALIFICA','PECCCC07','10','Qualifica:','8','U','S','%','','QUAL','5','2');                                                                     
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_LIVELLO','PECCCC07','11','Livello:','4','U','S','%','','','','');                                                                               
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_VARIABILI','PECCCC07','12','Tratta anche voci variabili:','1','U','N','X','P_X','','','');                                                      
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000506','1013897','PECCCC07','60','');                                                                                                                                                              
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000506','1013897','PECCCC07','60','');                                                                                                                                                                
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000506','1013897','PECCCC07','60','');                                                                                                                                                              
insert into a_catalogo_stampe (stampa,titolo,tipo_proprieta,tipo_visura,classe,stampa_bloccata,stampa_protetta,sequenziale) values ('PECCCC07','SEGNALAZIONI CONGUAGLIO CASSA/COMPETENZA','U','U','A_C','N','N','S');                                                                                       
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,guida_v,voce_menu,voce_rif,proprieta) values ('A_PARA','1','PREN','P','Prenot...','','ACAEPRPA','*','X');                                                                                                                                      
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_X','X','','Conferma della condizione proposta');                                                                                                                                                                     

start crp_pecccc07.sql                                                                                                                                                           

