alter table DEPOSITO_PERIODI_PRESENZA modify ATTIVITA VARCHAR2(8);
alter table DEPOSITO_PERIODI_PRESENZA modify SEQ_ATTIVITA NUMBER(6);
alter table DEPOSITO_PERIODI_PRESENZA modify TIPO_RAPPORTO VARCHAR2(8);


