delete from a_selezioni where voce_menu = 'PECSONRE';                                                                                                                                                                                                                                                       

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO','PECSONRE','1','Elaborazione   : Anno','4','N','N','','','RIRE','1','1');                                                                 
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MENSILITA','PECSONRE','2','                Cod.Mensilita`','4','U','N','','','RIRE','1','2');                                                   
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_TITOLO','PECSONRE','3','                 Elaborato','30','U','N','','','ESON','1','1');                                                         
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_FILTRO_1','PECSONRE','4','Raggruppamento : 1)','15','U','S','%','','','','');                                                                   
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_FILTRO_2','PECSONRE','5','                 2)','15','U','S','%','','','','');                                                                   
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_FILTRO_3','PECSONRE','6','                 3)','15','U','S','%','','','','');                                                                   
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_FILTRO_4','PECSONRE','7','                 4)','15','U','S','%','','','','');                                                                   
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_TOTALI','PECSONRE','8','Stampa solo Totali','1','U','N','','P_X','','','');                                                                     
