ALTER TABLE ASTENSIONI ADD (LUNGA_ASSENZA  VARCHAR2(2)   DEFAULT 'NO'     NOT NULL);

INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('NO', NULL, NULL, 'ASTENSIONI.LUNGA_ASSENZA', 'Breve Assenza', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ('SI', NULL, NULL, 'ASTENSIONI.LUNGA_ASSENZA', 'Lunga Assenza', 'CFG', NULL, NULL); 

