INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'26', NULL, NULL, 'ESTRAZIONE_NOTE_CEDOLINI.SUB', 'X= Voci di Base aggregate al cambio di qualifica'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'27', NULL, NULL, 'ESTRAZIONE_NOTE_CEDOLINI.SUB', 'Indica il Livello di Aggregazione su Voci di Base e Rapportate (1,2,3)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'28', NULL, NULL, 'ESTRAZIONE_NOTE_CEDOLINI.SUB', 'X = Stampa le Voci Automatiche con dettaglio per riferimento'
, NULL, NULL, NULL);

start crp_pecsmor6.sql
