DELETE A_GUIDE_V WHERE GUIDA_V='P_ELPR';

INSERT INTO A_GUIDE_V ( GUIDA_V, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, VOCE_MENU, VOCE_RIF, PROPRIETA ) VALUES ('P_ELPR', 1, NULL, 'I', NULL, NULL, 'rich. Individuale', NULL, NULL, 'PECRELPI', NULL, NULL); 
INSERT INTO A_GUIDE_V ( GUIDA_V, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,TITOLO_AL1, TITOLO_AL2, VOCE_MENU, VOCE_RIF, PROPRIETA ) VALUES ('P_ELPR', 2, NULL, 'C', NULL, NULL, 'rich. Collettiva', NULL, NULL, 'PECRELRC', NULL, NULL); 
