start crp_peccbarp.sql
start crp_peccmocp3.sql

delete from A_DOMINI_SELEZIONI where dominio = 'P_ELAB';

INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_ELAB', 'A', NULL, 'Assegni Familiari'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_ELAB', 'B', NULL, 'Basi Voce'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_ELAB', 'C', NULL, 'Collettiva'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_ELAB', 'I', NULL, 'Individuale'); 
INSERT INTO A_DOMINI_SELEZIONI 
( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE ) 
VALUES ( 'P_ELAB', 'T', NULL, 'Totale'); 
