INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) VALUES ('P00248', 'Tipo Spesa già presente per la giornata', NULL, NULL, NULL); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) VALUES ('P00247', 'Durata della giornata inferiore al minimale orario', NULL, NULL, NULL); 
