start crp_peccmore_autofam.sql

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECDCODA');                                                                                                                                                                                                      
delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECDCODA'));                                                                                                                                                     
delete from a_voci_menu where voce_menu = 'PECDCODA';                                                                                                                                                                                                                                                       
delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECDCODA');                                                                                                                                                                  
delete from a_passi_proc where voce_menu = 'PECDCODA';                                                                                                                                                                                                                                                      
delete from a_selezioni where voce_menu = 'PECDCODA';                                                                                                                                                                                                                                                       
delete from a_menu where voce_menu = 'PECDCODA' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                             
insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECDCODA','P00','DCODA','Disattiva Conguaglio Detraz. Arretrate','F','D','ACAPARPR','',1,'A_PARA');                                                                                  
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECDCODA','1','Disattiva Cong. Detrazioni Arretrate','Q','PECDCODA','','','');                                                                                                                            
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECDCODA','91','Stampa Segnalazioni Anomalie','R','ACARAPPR','','PECDCODA','N');                                                                                                                          
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECDCODA','92','Cancellazione Segnalazioni','Q','ACACANRP','','','N');                                                                                                                                    
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_RAPPORTO','PECDCODA','1','Classe rapporto:','4','U','S','%','','CLRA','1','1');                                                                 
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GESTIONE','PECDCODA','2','Gestione:','8','U','S','%','','GEST','1','1');                                                                        
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_CONTRATTO','PECDCODA','3','Contratto:','4','U','S','%','','CONT','1','1');                                                                      
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000548','1013903','PECDCODA','1','');                                                                                                                                                               
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000548','1013903','PECDCODA','1','');                                                                                                                                                                 
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000548','1013903','PECDCODA','1','');                                                                                                                                                               
insert into a_catalogo_stampe (stampa,titolo,tipo_proprieta,tipo_visura,classe,stampa_bloccata,stampa_protetta,sequenziale) values ('PECDCODA','SEGNALAZIONI CONGUAGLIO CASSA/COMPETENZA','U','U','A_C','N','N','S');                                                                                       
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,guida_v,voce_menu,voce_rif,proprieta) values ('A_PARA','1','PREN','P','Prenot...','','ACAEPRPA','*','X');                                                                                                                                      


start crp_pecdcoda.sql