delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECSDC07');                                                                                                                                                                                                      
delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECSDC07'));                                                                                                                                                     
delete from a_voci_menu where voce_menu = 'PECSDC07';                                                                                                                                                                                                                                                       
delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECSDC07');                                                                                                                                                                  
delete from a_passi_proc where voce_menu = 'PECSDC07';                                                                                                                                                                                                                                                      
delete from a_selezioni where voce_menu = 'PECSDC07';                                                                                                                                                                                                                                                       
delete from a_menu where voce_menu = 'PECSDC07' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                             
insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECSDC07','P00','SDC07','Stampa differenze contributi su cumulo','F','D','ACAPARPR','',1,'A_PARA');                                                                                  
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECSDC07','1','Stampa differenze contributi su cumulo','Q','PECSDC07','','','');                                                                                                                          
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECSDC07','2','Stampa squadrature','R','PECSAPST','','PECSAPST','N');                                                                                                                                     
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECSDC07','91','Stampa Segnalazioni Anomalie','R','ACARAPPR','','PECSDC07','N');                                                                                                                          
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECSDC07','92','Cancellazione Segnalazioni','Q','ACACANRP','','','N');                                                                                                                                    
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO_LIQ','PECSDC07','1','Da anno di liquidazione:','4','N','N','','','','','');                                                                
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DETTAGLIO','PECSDC07','2','Stampa Dettaglio Liquidazione:','1','U','N','','P_X','','','');                                                      
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000506','1013899','PECSDC07','61','');                                                                                                                                                              
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000506','1013899','PECSDC07','61','');                                                                                                                                                                
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000506','1013899','PECSDC07','61','');                                                                                                                                                              
insert into a_catalogo_stampe (stampa,titolo,tipo_proprieta,tipo_visura,classe,stampa_bloccata,stampa_protetta,sequenziale) values ('PECSAPST','Stampa Elenco','U','U','A_C','N','N','S');                                                                                                                  
insert into a_catalogo_stampe (stampa,titolo,tipo_proprieta,tipo_visura,classe,stampa_bloccata,stampa_protetta,sequenziale) values ('PECSDC07','SEGNALAZIONI DIFFERENZE CONTRIBUTI SU CUMULO','U','U','A_C','N','N','S');                                                                                   
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,guida_v,voce_menu,voce_rif,proprieta) values ('A_PARA','1','PREN','P','Prenot...','','ACAEPRPA','*','X');                                                                                                                                      
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_X','X','','Conferma della condizione proposta');                                                                                                                                                                     

start crt_tcir.sql
start crt_tccn.sql
start crp_pecsdc07.sql