DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'PPALPRAS_ORD', 'P_PPALPRAS_ORD');

insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) 
values ('P_PPALPRAS_ORD','AL','','per Cognome e Nome');
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) 
values ('P_PPALPRAS_ORD','BA','','per Badge');
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) 
values ('P_PPALPRAS_ORD','CA','','per Cartellino');
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) 
values ('P_PPALPRAS_ORD','MA','','per Matricola');

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'PPALPRAS_SEL', 'P_PPALPRAS_SEL' );

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'AS', NULL, 'Assistenza', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'AT', NULL, 'Attivita` o Disciplina', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'CC', NULL, 'Centro di Costo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'CF', NULL, 'Classifivazione Funzionale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'CL', NULL, 'Contratto di Lavoro', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'CR', NULL, 'Classe di Rapporto', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'FG', NULL, 'Figura Giuridica', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'FP', NULL, 'Fattore Produttivo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'GG', NULL, 'Giorni Settimanali', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'GS', NULL, 'Gestione', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'OL', NULL, 'Ore Lavorative', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'OM', NULL, 'HH:MM Giornalieri', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'PG', NULL, 'Posizione Giuridica', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'QR', NULL, 'Qualifica Retributiva', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'RR', NULL, 'Ruolo Retributivo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'SA', NULL, 'Settore A', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'SB', NULL, 'Settore B', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'SC', NULL, 'Settore C', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'SD', NULL, 'Sede', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'SG', NULL, 'Settore di Gestione', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'ST', NULL, 'Settore di Assegnazione', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PPALPRAS_SEL', 'TR', NULL, 'Tipo di Rapporto', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'PMTSRIRI_RICHIESTA', 'P_PMTSRIRI_RICHIESTA');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PMTSRIRI_RICHIESTA', '1', NULL, 'Richiesta caricata dal dipendente', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PMTSRIRI_RICHIESTA', '2', NULL, 'Richiesta valutata dall''ufficio', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PMTSRIRI_RICHIESTA', '3', NULL, 'Tutte le Richieste', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'D_INTERNA', 'P_D_INTERNA');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_INTERNA', 'C', NULL, 'Complessiva', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_INTERNA', 'P', NULL, 'Per Postalizzazione', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_INTERNA', 'T', NULL, 'Per Invio Telematico', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_INTERNA', 'X', NULL, 'Ad uso interno', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'TIPO_LVOEC', 'P_TIPO_LVOEC' );

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_TIPO_LVOEC', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_TIPO_LVOEC', 'C', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_TIPO_LVOEC', 'F', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_TIPO_LVOEC', 'Q', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_TIPO_LVOEC', 'T', NULL, NULL, NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'D_LVAEM','P_D_LVAEM');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_LVAEM', 'D', NULL, 'Stampa Dettaglio Individuale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_LVAEM', 'Q', NULL, 'Stampa Quadrature', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_LVAEM', 'T', NULL, 'Solo Totali', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'D_LVADM','P_D_LVADM');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_LVADM', 'D', NULL, 'Stampa Dettaglio Individuale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_LVADM', 'Q', NULL, 'Stampa Quadrature e Anomalie', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_LVADM', 'T', NULL, 'Solo Totali', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'D_TIPO','P_D_TIPO' );

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_TIPO', 'A', NULL, 'Dettaglio Annuale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_TIPO', 'D', NULL, 'Dettaglio Individuale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_TIPO', 'I', NULL, 'Solo Totali Individuali', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_TIPO', 'T', NULL, 'Solo Totali Generali', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'D_TERZA_PAGINA', 'P_D_TERZA_PAGINA');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_TERZA_PAGINA', 'P', NULL, 'Stampa a parte', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_D_TERZA_PAGINA', 'S', NULL, 'Stampa di seguito', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'CREIN_TIPO_ELAB', 'P_CREIN_TIPO_ELAB');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CREIN_TIPO_ELAB', 'I', NULL, 'Non altera gli Inseriti', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CREIN_TIPO_ELAB', 'P', NULL, 'Parziale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CREIN_TIPO_ELAB', 'S', NULL, 'Singolo Individuo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CREIN_TIPO_ELAB', 'T', NULL, 'Totale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CREIN_TIPO_ELAB', 'V', NULL, 'Non altera i Variati', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'CREIN_TIPO', 'P_CREIN_TIPO');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CREIN_TIPO', 'C', NULL, 'Consuntivo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CREIN_TIPO', 'P', NULL, 'Preventivo', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'CALAP_1',  'P_CALAP_1');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CALAP_1', '1', NULL, 'Imp. al netto e alq. media', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CALAP_1', '2', NULL, 'Imp. al lordo e alq. media', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CALAP_1', '3', NULL, 'Calcolo alq. media', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CALAP_1', '4', NULL, 'Imp. 2^ AP al netto e alq. media', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'PDOSDOEF_TIPO', 'P_PDOSDOEF_TIPO');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PDOSDOEF_TIPO', '1', NULL, 'Elaborazione Totale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PDOSDOEF_TIPO', '2', NULL, 'Profili con Assegnazioni', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PDOSDOEF_TIPO', '3', NULL, 'Profili privi di Assegnazioni', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PDOSDOEF_TIPO', '4', NULL, 'Profili con sole Assegnazioni di Ruolo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PDOSDOEF_TIPO', '5', NULL, 'Profili con sole Assegnazioni non Ruolo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PDOSDOEF_TIPO', '6', NULL, 'Tutte le Assegnazioni di Ruolo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PDOSDOEF_TIPO', '7', NULL, 'Tutte le Assegnazioni non di Ruolo', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_PDOSDOEF_TIPO', '9', NULL, 'Profili con Assegnazioni di Ruolo e non', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'CLASSE_L_VOEC', 'P_CLASSE_LVOEC');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'A', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'B', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'C', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'I', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'P', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'Q', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'R', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'T', NULL, NULL, NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_CLASSE_LVOEC', 'V', NULL, NULL, NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'COMPARTO', 'P_COMPARTO');

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_COMPARTO', '%', NULL, 'Tutti', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_COMPARTO', 'ALTRO', NULL, 'Altro Personale', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_COMPARTO', 'EL', NULL, 'Enti Locali', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_COMPARTO', 'ELS', NULL, 'Enti Locali Personale Scuola', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_COMPARTO', 'SSN', NULL, 'Servizio Sanitario Nazionale', NULL, NULL); 

DELETE FROM A_DOMINI_SELEZIONI WHERE DOMINIO IN ( 'D_SDEDI', 'P_SDEDI' );

INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_SDEDI', 'DS22', NULL, 'Modello DS22', NULL, NULL); 
INSERT INTO A_DOMINI_SELEZIONI ( DOMINIO, VALORE_LOW, VALORE_HIGH, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2 ) 
VALUES ( 'P_SDEDI', 'SR18', NULL, 'Modello SR18', NULL, NULL);

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PPALPRAS');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_SEL_1', 'PPALPRAS', 1, '1^ Raggruppamento', NULL, NULL, 2, 'U', 'S', NULL, 'P_PPALPRAS_SEL', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_VAL_1', 'PPALPRAS', 2, 'Cod. per Filtro sul 1^ Raggr.', NULL, NULL, 15, 'U', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_SEL_2', 'PPALPRAS', 3, '2^ Raggruppamento', NULL, NULL, 2, 'U', 'N', NULL, 'P_PPALPRAS_SEL', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_VAL_2', 'PPALPRAS', 4, 'Cod. per Filtro sul 2^ Raggr.', NULL, NULL, 15, 'U', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_SEL_3', 'PPALPRAS', 5, '3^ Raggruppamento', NULL, NULL, 2, 'U', 'N', NULL, 'P_PPALPRAS_SEL', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_VAL_3', 'PPALPRAS', 6, 'Cod. per Filtro sul 3^ Raggr.', NULL, NULL, 15, 'U', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_SEL_4', 'PPALPRAS', 7, '4^ Raggruppamento', NULL, NULL, 2, 'U', 'N', NULL, 'P_PPALPRAS_SEL', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_VAL_4', 'PPALPRAS', 8, 'Cod. per Filtro sul 4^ Raggr.', NULL, NULL, 15, 'U', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_SE_NOM', 'PPALPRAS', 9, 'Se Situazione Nominativa', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ORD', 'PPALPRAS', 10, 'Ordinamento Situaz. Nominativa', NULL, NULL, 2, 'U', 'N', NULL, 'P_PPALPRAS_ORD', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA', 'PPALPRAS', 11, 'Data Rif. se diversa da Appl.', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PMTSRIRI');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_CI', 'PMTSRIRI', 1, 'Cod.Ind.', NULL, NULL, 8, 'N', 'N', NULL, NULL, 'RAIN', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_DISTINTA', 'PMTSRIRI', 7, 'Data Distinta', NULL, NULL, 10, 'D', 'N', NULL, NULL, 'RIRI', 0, 2); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_FINE', 'PMTSRIRI', 4, 'Data Fine Trasferta', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_FIN_AGG', 'PMTSRIRI', 6, 'Data Fine Aggiornamento', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_INIZIO', 'PMTSRIRI', 3, 'Data Inizio Trasferta', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_INI_AGG', 'PMTSRIRI', 5, 'Data Inizio Aggiornamento', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_NR_DISTINTA', 'PMTSRIRI', 8, 'Numero Distinta', NULL, NULL, 8, 'N', 'N', NULL, NULL, 'RIRI', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_RICHIESTA', 'PMTSRIRI', 2, 'Richiesta', NULL, NULL, 1, 'N', 'S', NULL, 'P_PMTSRIRI_RICHIESTA', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT9');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTT9', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT9', 4, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT9', 2, 'Gestione:', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT9', 3, 'Totali Generali:', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT8');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTT8', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT8', 6, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_A', 'PECSMTT8', 3, 'A', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_DA', 'PECSMTT8', 2, 'Da', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT8', 4, '              Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT8', 5, '              Totali Generali', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT7');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTT7', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT7', 4, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT7', 2, '              Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT7', 3, '              Totali Generali', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT6');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTT6', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT6', 6, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_A', 'PECSMTT6', 3, '               A', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_DA', 'PECSMTT6', 2, '               Da', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT6', 4, '              Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT6', 5, '              Totali Generali', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT5');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTT5', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT5', 6, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_A', 'PECSMTT5', 3, '              A', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_DA', 'PECSMTT5', 2, '              Da', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT5', 4, '              Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT5', 5, '              Totale Generale', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT4');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNI', 'PECSMTT4', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT4', 4, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT4', 2, 'Gestione:', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT4', 3, 'Totali Generali', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL);

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT3');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTT3', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT3', 4, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT3', 2, '              Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT3', 3, '              Totale Generale', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT2');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTT2', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT2', 4, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT2', 2, '              Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT2', 3, '              Totale Generale', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTT1');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTT1', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTT1', 6, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_A', 'PECSMTT1', 3, '              A', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_DA', 'PECSMTT1', 2, '              Da', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTT1', 4, '              Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMTT1', 5, '              Totale Generale', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTN1');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'D_TIPO', 'PECSMTN1', 3, 'Tipo Elaborazione', NULL, NULL, 1, 'U', 'N', 'T', 'P_TIPO_SMT', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTN1', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTN1', 4, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMTN1', 2, '              Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMTLA');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMTLA', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMTLA', 3, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PECSMTLA', 2, '              Tipo', NULL, NULL, 1, 'U', 'S', 'T', 'P_TIPO_SMTLA', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMT13');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMT13', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ARROTONDA', 'PECSMT13', 6, 'Arrotonda', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMT13', 7, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_A', 'PECSMT13', 3, 'A', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_DA', 'PECSMT13', 2, 'Da', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMT13', 4, 'Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMT13', 5, 'Totali Generali', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMT12');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMT12', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ARROTONDA', 'PECSMT12', 6, 'Arrotonda', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMT12', 7, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_A', 'PECSMT12', 3, 'A', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_DA', 'PECSMT12', 2, 'Da', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GEST', 'PECSMT12', 4, 'Gestione', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMT12', 5, 'Totali Generali', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMT11');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMT11', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_COMPARTO', 'PECSMT11', 6, 'Comparto', NULL, NULL, 10, 'U', 'N', '%', 'P_COMPARTO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_A', 'PECSMT11', 3, '    A', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DATA_DA', 'PECSMT11', 2, '    Da', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECSMT11', 4, 'Gestione:', NULL, NULL, 4, 'U', 'S', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOT', 'PECSMT11', 5, 'Totali Generali:', NULL, NULL, 1, 'U', 'N', NULL, 'P_SMTT', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSCER6');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_PRG_CEDOLINO', 'PECSCER6', 0, 'Progressivo Temporaneo', NULL, NULL, 8, 'N', 'N', '1', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO_ELA', 'PECSCER6', 1, 'Elaborazione   : Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, 'RIRE', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_MENSILITA_ELA', 'PECSCER6', 2, '                Cod.Mensilita`', NULL, NULL, 4, 'U', 'N', NULL, NULL, 'RIRE', 1, 2); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_RICHIESTA', 'PECSCER6', 3, '                 Tipo', NULL, NULL, 1, 'U', 'S', 'T', 'P_CERE_TIPO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_1', 'PECSCER6', 4, 'Raggruppamento : 1)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_2', 'PECSCER6', 5, '                 2)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_3', 'PECSCER6', 6, '                 3)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_4', 'PECSCER6', 7, '                 4)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_CI', 'PECSCER6', 8, 'Individuale    : Codice', NULL, NULL, 8, 'N', 'N', NULL, NULL, 'RAIN', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GR_LING', 'PECSCER6', 9, 'Gr.Linguistico richiesto', NULL, NULL, 1, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_NUM_STAMPA', 'PECSCER6', 10, 'Numero Stampa :', NULL, NULL, 8, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO_DESFORMAT', 'PECSCER6', 11, 'Tipo stampa', NULL, NULL, 4, 'U', 'S', 'PDF', 'P_SCER6', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FRONTE_RETRO', 'PECSCER6', 12, 'Stampa in Fronte/Retro', NULL, NULL, 2, 'U', 'N', NULL, 'P_SI_NO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_MODELLO_STAMPA', 'PECSCER6', 13, 'Modello Stampa', NULL, NULL, 8, 'U', 'N', NULL, NULL, 'STMS', NULL, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_INTERNA', 'PECSCER6', 14, 'Modalità di Stampa', NULL, NULL, 1, 'U', 'S', 'X', 'P_D_INTERNA', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMCU6');
DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECSMCU7');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECSMCU6', 1, 'Elaborazione:Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PECSMCU6', 2, 'Tipo', NULL, NULL, 1, 'U', 'S', 'T', 'P_SM101', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_CI', 'PECSMCU6', 3, 'Individuale :Codice', NULL, NULL, 8, 'N', 'N', NULL, NULL, 'RAIN', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DAL', 'PECSMCU6', 4, 'Cessazione:Dal', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_AL', 'PECSMCU6', 5, 'Al', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ESTRAZIONE_I', 'PECSMCU6', 6, 'Estrazione Individui:', NULL, NULL, 1, 'U', 'N', '1', 'P_ESTR_I', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_1', 'PECSMCU6', 7, 'Collettiva:Raggruppam. 1)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_2', 'PECSMCU6', 8, ' 2)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_3', 'PECSMCU6', 9, ' 3)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_4', 'PECSMCU6', 10, ' 4)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOTALI', 'PECSMCU6', 11, 'Totali Generali:', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO_DESFORMAT', 'PECSMCU6', 12, 'Tipo Stampa', NULL, NULL, 4, 'U', 'S', NULL, 'P_SMCU6', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TERZA_PAGINA', 'PECSMCU6', 13, 'Stampa Terza Pagina', NULL, NULL, 1, 'U', 'S', NULL, 'P_D_TERZA_PAGINA', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ORDINAMENTO', 'PECSMCU6', 14, 'Ordinamento come modello CUD', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ETICHETTE', 'PECSMCU6', 15, 'Stampa Etichette', NULL, NULL, 1, 'U', 'N', NULL, 'P_SECU3', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DICITURA', 'PECSMCU6', 16, 'Originale/Copia:', NULL, NULL, 1, 'U', 'N', NULL, 'P_DICI', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DOMICILIO', 'PECSMCU6', 17, 'Domicilio', NULL, NULL, 1, 'U', 'N', 'X', 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_STAMPA_ENTE', 'PECSMCU6', 18, 'Stampa indirizzo per cessati', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_PREVIDENZIALE', 'PECSMCU6', 19, 'Non stampa dati Previdenziali', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DMA_ASS', 'PECSMCU6', 20, 'Suddivisione DMA per Ass.', NULL, NULL, 1, 'U', 'N', 'X', 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_NOTE_1', 'PECSMCU6', 21, 'Note fisse : 1 Riga', NULL, NULL, 70, 'C', 'N', 'prova di note 1', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_NOTE_2', 'PECSMCU6', 22, '2 Riga', NULL, NULL, 70, 'C', 'N', 'prova di note 2', NULL, NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECLVOEC');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_CLASSE', 'PECLVOEC', 2, 'Classe', NULL, NULL, 1, 'U', 'S', '%', 'P_CLASSE_LVOEC', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_CODICE_VOCE', 'PECLVOEC', 1, 'Codice Voce', NULL, NULL, 10, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ORDINE', 'PECLVOEC', 4, 'Ordinamento', NULL, NULL, 1, 'U', 'S', 'S', 'P_ORD_VOCI', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PECLVOEC', 3, 'Tipo', NULL, NULL, 1, 'U', 'S', '%', 'P_TIPO_LVOEC', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECLVAEM');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECLVAEM', 1, 'Elaborazione Anno: ...........', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO_DENUNCIA', 'PECLVAEM', 2, 'Anno Denuncia: ...............', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DIFFERENZA', 'PECLVAEM', 5, 'Differenza....................', NULL, NULL, 2, 'N', 'N', '5', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECLVAEM', 3, 'Gestione: ....................', NULL, NULL, 8, 'U', 'N', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ORDINAMENTO', 'PECLVAEM', 6, 'Ordinamento: .................', NULL, NULL, 1, 'U', 'N', 'C', 'P_LNDMI', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PECLVAEM', 4, 'Tipo Elaborazione:............', NULL, NULL, 1, 'U', 'N', NULL, 'P_D_LVAEM', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECLVADM');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECLVADM', 1, 'Elaborazione Anno: ...........', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DIFFERENZA', 'PECLVADM', 4, 'Differenza....................', NULL, NULL, 2, 'N', 'N', '5', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECLVADM', 2, 'Gestione: ....................', NULL, NULL, 8, 'U', 'N', '%', NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PECLVADM', 3, 'Tipo Elaborazione:............', NULL, NULL, 1, 'U', 'N', NULL, 'P_D_LVADM', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECLISDP');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECLISDP', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PECLISDP', 2, '              Gestione', NULL, NULL, 4, 'U', 'N', NULL, NULL, 'GEST', 1, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PECLISDP', 3, '              Tipo', NULL, NULL, 1, 'U', 'S', 'D', 'P_D_TIPO', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECCUD06');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_AL', 'PECCUD06', 5, '  Al', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECCUD06', 1, 'Elaborazione:  Anno', NULL, NULL, 4, 'N', 'N', '2005', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_CI', 'PECCUD06', 3, 'Individuale :  Codice', NULL, NULL, 8, 'N', 'N', NULL, NULL, 'RAIN', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DAL', 'PECCUD06', 4, 'Cessazione  :  Dal', NULL, NULL, 10, 'D', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DICITURA', 'PECCUD06', 12, 'Originale/Copia:', NULL, NULL, 1, 'U', 'N', NULL, 'P_DICI', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_DOMICILIO', 'PECCUD06', 13, 'Domicilio', NULL, NULL, 1, 'U', 'N', 'X', 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ESTRAZIONE_I', 'PECCUD06', 6, 'Estrazione Individui:', NULL, NULL, 1, 'U', 'N', NULL, 'P_ESTR_I', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_1', 'PECCUD06', 7, 'Collettiva  :  Raggruppam. 1)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_2', 'PECCUD06', 8, ' 2)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_3', 'PECCUD06', 9, ' 3)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FILTRO_4', 'PECCUD06', 10, ' 4)', NULL, NULL, 15, 'U', 'S', '%', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_NOTE_1', 'PECCUD06', 17, 'Note fisse : 1 Riga', NULL, NULL, 70, 'C', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_NOTE_2', 'PECCUD06', 18, '2 Riga', NULL, NULL, 70, 'C', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_PREVIDENZIALE', 'PECCUD06', 15, 'Non stampa dati Previdenziali', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_RIBASSATE', 'PECCUD06', 19, 'Stampa note ribassate', NULL, NULL, 2, 'U', 'S', 'NO', 'P_SI_NO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_STAMPA_ENTE', 'PECCUD06', 14, 'Stampa indirizzo per cessati', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TERZA_PAGINA', 'PECCUD06', 16, 'Stampa Terza Pagina', NULL, NULL, 1, 'U', 'S', NULL, 'P_D_TERZA_PAGINA', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PECCUD06', 2, '  Tipo', NULL, NULL, 1, 'U', 'S', 'T', 'P_SM101', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO_DESFORMAT', 'PECCUD06', 0, 'Tipo Stampa', NULL, NULL, 4, 'U', 'S', 'PDF', NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TOTALI', 'PECCUD06', 11, 'Totali Generali:', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECCREIN');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECCREIN', 1, 'Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_CI', 'PECCREIN', 4, 'Cod.Ind.', NULL, NULL, 8, 'C', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PECCREIN', 2, 'Tipo di calcolo', NULL, NULL, 1, 'U', 'N', 'C', 'P_CREIN_TIPO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO_ELAB', 'PECCREIN', 3, 'Tipo di elaborazione', NULL, NULL, 1, 'U', 'N', 'P', 'P_CREIN_TIPO_ELAB', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PECCALAP');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ANNO', 'PECCALAP', 1, 'Elaborazione: Anno', NULL, NULL, 4, 'N', 'N', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO_ELAB', 'PECCALAP', 2, 'Tipo Elaborazione', NULL, NULL, 1, 'N', 'S', '3', 'P_CALAP_1', NULL, NULL, NULL); 

DELETE FROM A_SELEZIONI WHERE VOCE_MENU IN ('PDOSDOEF');

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_APPR_LIVELLO', 'PDOSDOEF', 15, 'Liv. di Appr. per Assegnazione', NULL, NULL, 1, 'N', 'N', NULL, 'P_SUDD_1_4', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ASSEGNAZIONE', 'PDOSDOEF', 14, 'Codice della Assegnazione', NULL, NULL, 15, 'U', 'S', '%', NULL, 'VS', 0, 2); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ASSENZE', 'PDOSDOEF', 6, 'Assenze', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ATTIVITA', 'PDOSDOEF', 13, 'Codice della Attivita`', NULL, NULL, 4, 'U', 'S', '%', NULL, 'ATTI', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_D_F', 'PDOSDOEF', 3, 'Situazione Giuridica', NULL, NULL, 1, 'U', 'N', 'D', 'P_DF', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_FIGURA', 'PDOSDOEF', 12, 'Codice della Figura', NULL, NULL, 8, 'U', 'S', '%', NULL, 'FIGI', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_GESTIONE', 'PDOSDOEF', 2, 'Gestione', NULL, NULL, 4, 'U', 'N', '%', NULL, 'GEST', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_INCARICHI', 'PDOSDOEF', 7, 'Incarichi', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_NOMINATIVA', 'PDOSDOEF', 4, 'Nominativa', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ORDINAMENTO', 'PDOSDOEF', 10, 'Tipo di Ordinamento', NULL, NULL, 2, 'U', 'S', 'F', 'P_AF_FA_F', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_ORE', 'PDOSDOEF', 11, 'Ore Lavorate', NULL, NULL, 1, 'U', 'N', 'O', 'P_ORE', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_REVISIONE', 'PDOSDOEF', 1, 'Revisione', NULL, NULL, 8, 'N', 'N', NULL, NULL, 'REDO', 0, 1); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_SCOSTAMENTI', 'PDOSDOEF', 5, 'Scostamenti', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_SOSTITUTI', 'PDOSDOEF', 8, 'Sostituti', NULL, NULL, 1, 'U', 'N', NULL, 'P_X', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK )
VALUES ( 'P_TIPO', 'PDOSDOEF', 9, 'Tipo', NULL, NULL, 1, 'N', 'N', '1', 'P_PDOSDOEF_TIPO', NULL, NULL, NULL); 

delete from A_SELEZIONI where voce_menu = 'PECSDEDI';

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK ) 
VALUES ( 'P_CI', 'PECSDEDI', 1, 'Codice Individuale............', NULL, NULL, 8, 'N', 'S', NULL, NULL, 'RAIN', 1, 1); 

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK ) 
VALUES ('P_MODELLO', 'PECSDEDI', 2, 'Modello Stampa................', NULL, NULL, 4, 'U', 'S', NULL, 'P_SDEDI', NULL, NULL, NULL); 

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK ) 
VALUES ('P_TELEFONO', 'PECSDEDI', 3, 'Numero di Telefono............', NULL, NULL, 16, 'U', 'N', NULL, NULL, NULL, NULL, NULL);

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,NUMERO_FK ) 
VALUES ('P_FIRMATARIO', 'PECSDEDI', 4, 'Firmatario....................', NULL, NULL, 8, 'N', 'N', NULL, NULL, 'RAIN', 2, 1); 


