ALTER TABLE DEPOSITO_VARIABILI_ECONOMICHE
ADD (MESE_LIQUIDAZIONE NUMBER(2));

UPDATE DEPOSITO_VARIABILI_ECONOMICHE DEVE
SET    MESE_LIQUIDAZIONE = MESE
WHERE  ANNO_LIQUIDAZIONE IS NOT NULL
AND    MENSILITA_LIQUIDAZIONE IS NOT NULL
AND    MESE IS NOT NULL;

UPDATE DEPOSITO_VARIABILI_ECONOMICHE DEVE
SET    MESE_LIQUIDAZIONE = (SELECT MIN(MESE)
                            FROM   MENSILITA
                            WHERE  TIPO IN('S','N','A')
                            AND    MENSILITA = DEVE.MENSILITA_LIQUIDAZIONE
                            )
WHERE  ANNO_LIQUIDAZIONE IS NOT NULL
AND    MENSILITA_LIQUIDAZIONE IS NOT NULL
AND    MESE IS NULL;


start crp_peccmoco.sql