INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
PROPRIETA ) VALUES ( 
'P00610', 'Definizione Struttura Cedolino errata o mancante', NULL, NULL, NULL);

start crp_PECSMORM.sql
