
delete from a_selezioni where voce_menu = 'PECCCAAF';                                                                                                                                                                                                                                                       

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO','PECCCAAF','1','Elaborazione  : Anno','4','N','N','','','','','');                                                                        
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MENSILITA','PECCCAAF','2',' Mensilita`','4','U','N','','','','','');                                                                            
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DATA_RIC','PECCCAAF','3','Periodo di Ricezione:Da','10','D','N','','','','','');                                                                
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DATA_RIC_A','PECCCAAF','4',' :A','10','D','N','','','','','');                                                                                  
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ALBO','PECCCAAF','5','Numero Albo CAAF','16','U','N','','','','','');                                                                           
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GESTIONE','PECCCAAF','6','Gestione','4','U','S','%','','GEST','1','1');                                                                         
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_RAPPORTO','PECCCAAF','7','Rapporto','4','U','S','%','','CLRA','1','1');                                                                         
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GRUPPO','PECCCAAF','8','Gruppo','12','U','S','%','','GRRA','1','1');                                                                            
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_INSERISCI','PECCCAAF','9','Accoda Registrazioni','2','U','S','NO','P_CAAF_ACCODA','','','');                                                    
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_VARIABILI','PECCCAAF','10','Trattamento Variabili','1','U','N','','P_X','','','');                                                              
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_SECONDA_RATA','PECCCAAF','11','Trattamento Seconda Rata','1','U','N','','P_X','','','');                                                        
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_RATE','PECCCAAF','12','Trattamento Versam.Rateali:','1','U','N','','P_X','','','');                                                             
