delete from a_prenotazioni where voce_menu = 'PGMSWLOG';

delete from a_voci_menu where voce_menu = 'PGMSWLOG';

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,
PROPRIETA ) VALUES ( 
'PCWSWLOG', 'P00', 'SWLOG', NULL, NULL, 'Log Stampa Word', NULL, NULL, 'F', 'D', NULL
, NULL, 1, NULL, NULL);

delete from a_voci_menu where voce_menu = 'PGMSWLOG';

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PCWSWLOG', 1, 'Log Stampa Word', NULL, NULL, 'R', 'PECSAPST', NULL, 'PECSAPST', 'N');

