INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'0', NULL, NULL, 'ASTENSIONI.MAT_DETFAM', 'Non matura Detrazioni Familiari', 'CFG'
, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'1', NULL, NULL, 'ASTENSIONI.MAT_DETFAM', 'Matura Detrazioni Familiari', 'CFG', NULL
, NULL); 