INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 1, 'I', 'T', '<V:gest.descrizione,39,40>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 2, 'I', 'T', '<V:gest.indirizzo,39,40>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 3, 'I', 'T', '<V:gest.comune,39,40>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 4, 'I', 'T', '<V:gest.codice_fiscale,39,40>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 5, 'I', 'T', '  '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 6, 'I', 'T', '<V:gest.codice,1,4><V:pere.ruolo,7,4><V:sedi.codice,13,6><V:sett.codice,23,6><V:rain.ci_st,49,11><P:Pag.,73><V:sys.num_pag,73,5>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 7, 'I', 'T', ' '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 8, 'I', 'T', '<V:anag.data_nas,1,8><V:anag.codice_fiscale,10,16><V:rare.matricola,27,8><V:anag.cognome_nome,39,40>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 9, 'I', 'T', ' <V:anag.presso,39,40>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 10, 'I', 'T', '<V:rain.rapporto,1,4><V:rain.dal,7,8><V:pegi.dal,17,8><V:pegi.al,27,8> '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 11, 'I', 'T', '  '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 12, 'I', 'T', '<V:qual.descrizione,1,14><V:pere.tipo_rapporto,15,4><V:pere.posizione,20,4><V:qugi.livello,25,4><V:pere.ore_coco_td,29,6><V:rare.statistico1,39,40>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 13, 'I', 'T', '<V:figi.descrizione,1,34><V:sedi.descrizione,39,40>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 14, 'I', 'T', '<V:sys.esnc0,12,8><V:anag.partita_iva,39,16>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 15, 'I', 'T', '<C:sel_inec.anz_voce,1,8><C:sel_inec.anz_numero,11,2><C:sel_inec.anz_data,16,10><C:sel_inec.qual_descrizione,29,18>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 16, 'C', 'T', '<C:sel_moco.sequenza,1,4><C:sel_moco.descrizione,6,37><C:sel_moco.tar_st,43,11><C:sel_moco.qta_st,54,8><C:sel_moco.imp_st,62,17>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 17, 'C', 'T', NULL); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 58, 'P', 'T', ' '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 59, 'P', 'T', ' '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 60, 'P', 'P', '<V:mens.periodo_comp,1,31>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 60, 'P', 'U', '<V:mens.periodo_comp,1,29><V:moco.arr_pre,32,7><V:moco.arr_att,38,7><V:moco.totale_comp,45,10><V:moco.totale_rit,54,10><V:moco.netto,63,13>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 61, 'P', 'T', '<V:sys.pagina,66,6><V:sys.num_pag_dip,74,1><V:sys.separatore_pag,75,1><V:sys.tot_pag_dip,76,1>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 62, 'P', 'T', '<V:rare_descrizione_banca,1,65>'); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 63, 'P', 'T', ' '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 64, 'P', 'T', ' '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 64, 'P', 'U', '<V:sys.data_elab,1,16><V:sys.prg_cedolino,29,4> '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 65, 'P', 'T', ' '); 
INSERT INTO STRUTTURA_MODELLI_STAMPA ( CODICE, SEQUENZA, TIPO_RIGA, FLAG_STAMPA,
RIGA ) VALUES ( 
'STD_CEDO', 66, 'P', 'T', ' ');

INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
PROPRIETA ) VALUES ( 
'P00613', 'Si sono verificati errori nella creazione del Modello duplicato', NULL
, NULL, NULL); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
PROPRIETA ) VALUES ( 
'P00612', 'I Modelli con prefisso STD_ non sono ammessi', NULL, NULL, NULL); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
PROPRIETA ) VALUES ( 
'P00611', 'Modello già esistente', NULL, NULL, NULL);

