INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'C', '2', NULL, 'MODELLI_STAMPA.TIPORIGA', 'Corpo del Cedolino', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'I', '1', NULL, 'MODELLI_STAMPA.TIPORIGA', 'Intestazione del Cedolino', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'N', '3', NULL, 'MODELLI_STAMPA.TIPORIGA', 'Note del Cedolino', 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'P', '4', NULL, 'MODELLI_STAMPA.TIPORIGA', 'Piede del Cedolino', 'CFG', NULL, NULL); 

INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'N', '3', NULL, 'MODELLI_STAMPA.FLAGSTAMPA', 'Stampa sulla Pagina delle Note', 'CFG'
, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'P', '1', NULL, 'MODELLI_STAMPA.FLAGSTAMPA', 'Stampa sulla Prima Pagina dei Movimenti'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'T', '2', NULL, 'MODELLI_STAMPA.FLAGSTAMPA', 'Stampa su Tutte le Pagine', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'U', '4', NULL, 'MODELLI_STAMPA.FLAGSTAMPA', 'Stampa sull Ultima Pagina dei Movimenti'
, 'CFG', NULL, NULL);

