start crp_cursore_certificato.sql
start crp_pgmscert.sql

INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'NO', NULL, NULL, 'CERTIFICATI.NOTE_IND', 'Negazione', 'CFG', NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'SU', NULL, NULL, 'CERTIFICATI.NOTE_IND', 'Stampa Unificando Periodi', 'CFG', NULL
, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'SI', NULL, NULL, 'CERTIFICATI.NOTE_IND', 'Conferma', 'CFG', NULL, NULL); 