INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'25', NULL, NULL, 'ESTRAZIONE_NOTE_CEDOLINI.SUB', 'Non stampa i campi relativi all''Inail'
, 'CFG', NULL, NULL); 

