-- Nuovi ref-codes per cursore CUR_DELI
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.anno_del', '<C:', '4', 'MODELLI_STAMPA.DEFINIZIONE', 'Anno di Delibera (ADERE)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.causale', '<C:', '30', 'MODELLI_STAMPA.DEFINIZIONE', 'Causale della Delibera (ADERE)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.descrizione', '<C:', '38', 'MODELLI_STAMPA.DEFINIZIONE', 'Descrizione della Voce (EMOCO)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.imp', '<C:', '12', 'MODELLI_STAMPA.DEFINIZIONE', 'Importo della Voce (EMOCO)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.numero_del', '<C:', '7', 'MODELLI_STAMPA.DEFINIZIONE', 'Numero di Delibera (ADERE)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.qta', '<C:', '12', 'MODELLI_STAMPA.DEFINIZIONE', 'Quantita della Voce (EMOCO)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.riferimento', '<C:', '10', 'MODELLI_STAMPA.DEFINIZIONE', 'Riferimento della Voce (EMOCO)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.sede_del', '<C:', '4', 'MODELLI_STAMPA.DEFINIZIONE', 'Sede di Delibera (ADERE)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.sequenza', '<C:', '4', 'MODELLI_STAMPA.DEFINIZIONE', 'Sequenza della Voce (EMOCO)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.tar', '<C:', '12', 'MODELLI_STAMPA.DEFINIZIONE', 'Tariffa della Voce (EMOCO)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'sel_deli.voce', '<C:', '10', 'MODELLI_STAMPA.DEFINIZIONE', 'Codice della Voce (EMOCO)'
, 'CFG', NULL, NULL);

start crp_PECSMOR6.sql