start crp_gp4gm.sql

start crp_gp4_unor.sql

start crp_gp4_stam.sql

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_PESE', 15, 'SETT', 'R', NULL, NULL, 'Rip.funz.', NULL, NULL, NULL, 'PGMDRIFU', NULL
, NULL, NULL, NULL, NULL); 
