start crp_gp4_stam.sql

delete from a_guide_o where guida_o = 'P_RIFU';
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RIFU', 1, 'RIFU', 'E', NULL, NULL, 'Elenco', NULL, NULL, NULL, 'PGMERIFU', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RIFU', 2, 'SETT', 'S', NULL, NULL, 'Sudd.set.', NULL, NULL, 'P_SETT', NULL, NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RIFU', 3, 'SEDE', 'D', NULL, NULL, 'seDi', NULL, NULL, 'P_SEDE', NULL, NULL, NULL
, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RIFU', 4, 'CLFU', 'F', NULL, NULL, 'cl.Funz.', NULL, NULL, NULL, 'PGMDCLFU', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RIFU', 5, 'CECO', 'C', NULL, NULL, 'C.d.c', NULL, NULL, NULL, 'PGMDCECO', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RIFU', 6, 'PEGI', 'I', NULL, NULL, 'Inquadr.', NULL, NULL, NULL, 'PGMRPEGI', NULL
, NULL, NULL, NULL, NULL); 

delete from A_GUIDE_V where GUIDA_V = 'P_SETT';
INSERT INTO A_GUIDE_V ( GUIDA_V, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, VOCE_MENU, VOCE_RIF, PROPRIETA ) VALUES ( 
'P_SETT', 1, NULL, 'E', NULL, NULL, 'Elenco', NULL, NULL, 'PGMESETT', NULL, NULL); 
INSERT INTO A_GUIDE_V ( GUIDA_V, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, VOCE_MENU, VOCE_RIF, PROPRIETA ) VALUES ( 
'P_SETT', 2, NULL, 'D', NULL, NULL, 'Definizione', NULL, NULL, 'PGMDSETT', NULL, NULL); 

delete from A_GUIDE_V where GUIDA_V = 'P_SEDE';
INSERT INTO A_GUIDE_V ( GUIDA_V, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, VOCE_MENU, VOCE_RIF, PROPRIETA ) VALUES ( 
'P_SEDE', 1, NULL, 'E', NULL, NULL, 'Elenco', NULL, NULL, 'PGMESEDE', NULL, NULL); 
INSERT INTO A_GUIDE_V ( GUIDA_V, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, VOCE_MENU, VOCE_RIF, PROPRIETA ) VALUES ( 
'P_SEDE', 2, NULL, 'D', NULL, NULL, 'Definizione', NULL, NULL, 'PGMDSEDE', NULL, NULL); 