
delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PGMLSOGI');                                                                                                                                                                                                      

delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PGMLSOGI'));                                                                                                                                                     

delete from a_voci_menu where voce_menu = 'PGMLSOGI';                                                                                                                                                                                                                                                       

delete from a_passi_proc where voce_menu = 'PGMLSOGI';                                                                                                                                                                                                                                                      

delete from a_selezioni where voce_menu = 'PGMLSOGI';                                                                                                                                                                                                                                                       

delete from a_menu where voce_menu = 'PGMLSOGI' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                             

delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PGMLSOGI');                                                                                                                                                                  

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PGMLSOGI','P00','LSOGI','Lista Sostituzioni Giuridiche','F','D','ACAPARPR','',1,'P_LSOGI');                                                                                          

insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PGMLSOGI','1','Lista Sostituzioni Giuridiche','R','PGMLSOGI','','PGMLSOGI','N');                                                                                                                          

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_TIPO','PGMLSOGI','1','Tipo di Rapporto Giuridico','1','U','S','A','P_TIPO_SOGI','','','');                                                      
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_DAL','PGMLSOGI','2','Dal','10','D','N','','','','','');                                                                                         
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_AL','PGMLSOGI','3','Al','10','D','N','','','','','');                                                                                           
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_CI','PGMLSOGI','4','Cod.Ind.','8','N','N','','','RAIN','1','1');                                                                                
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ASSENZA','PGMLSOGI','5','Codice Assenza','4','U','N','','','ASTE','1','1');                                                                     
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ORDINAMENTO','PGMLSOGI','6','Ordinamento','1','U','N','C','P_ORD_SOGI','','','');                                                               
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_SOSTITUZIONI','PGMLSOGI','7','Sostituzioni','1','U','N','T','P_SOST_SOGI','','','');                                                            

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000195','1013763','PGMLSOGI','12','');                                                                                                                                                              
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000195','1013763','PGMLSOGI','12','');                                                                                                                                                                
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000195','1013763','PGMLSOGI','12','');                                                                                                                                                              

insert into a_catalogo_stampe (stampa,titolo,tipo_proprieta,tipo_visura,classe,stampa_bloccata,stampa_protetta,sequenziale) values ('PGMLSOGI','Lista Sostituzioni Giuridiche','U','U','PDF','N','N','S');                                                                                                  

insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_LSOGI','1','PREN','P','Prenot.','ACAEPRPA','*');                                                                                                                                                                
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_LSOGI','2','RAIN','I','Individuo','P00RANAG','');                                                                                                                                                               
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_LSOGI','3','ASTE','A','Astens.','PGMEASTE','');  

insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_ORD_SOGI','C','','Ordinamento per Cod.Ind.');                                                                                                                                                                        
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_ORD_SOGI','D','','Ordinamento Data Assenza');                                                                                                                                                                        
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_SOST_SOGI','C','','Completamente Sostituibili');                                                                                                                                                                     
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_SOST_SOGI','N','','Non Sostituibili');                                                                                                                                                                               
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_SOST_SOGI','P','','Parzialmente Sostituibili');                                                                                                                                                                      
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_SOST_SOGI','T','','Tutti');                                                                                                                                                                                          
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_TIPO_SOGI','A','','Astensioni');                                                                                                                                                                                     
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_TIPO_SOGI','I','','Incarichi');                                                                                                                                                                                      
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_TIPO_SOGI','S','','Sostituzioni');                                                                                                                                                                                   
