UPDATE A_VOCI_MENU SET TITOLO = 'Lista Addizionali da CAAF'
WHERE VOCE_MENU='PECLVACA';

UPDATE A_PASSI_PROC SET TITOLO = 'Lista Addizionali da CAAF'
WHERE  VOCE_MENU='PECLVACA';

UPDATE A_CATALOGO_STAMPE SET TITOLO = 'Lista Addizionali da CAAF'
WHERE  STAMPA='PECLVACA';