INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_CARCC', 1, 'PREN', 'P', NULL, NULL, 'Prenot...', NULL, NULL, NULL, 'ACAEPRPA', '*'
, NULL, NULL, NULL, NULL); 

UPDATE A_VOCI_MENU SET GUIDA_O = 'P_CARCC'
WHERE VOCE_MENU = 'PECCARCC';

start crp_peccimcc.sql
start crp_peccarcc.sql