delete from PEC_REF_CODES
where  RV_DOMAIN = 'CONDIZIONI_FAMILIARI.TABELLA';

INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'1', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 1', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'10', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 10', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'11', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 11', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'12', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 12', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'2', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 2', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'3', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 3', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'4', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 4', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'5', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 5', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'6', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 6', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'7', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 7', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'8', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 8', 'CFG', NULL
, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'9', NULL, NULL, 'CONDIZIONI_FAMILIARI.TABELLA', 'Importo tabella 9', 'CFG', NULL
, NULL); 
COMMIT;