start crv_scaf.sql

start crv_coea.sql

delete from a_menu where voce_menu in ('PECEASFA', 'PECDSCAF');
delete from a_menu where voce_menu in ('PECEASFA', 'PECDSCAF') AND APPLICAZIONE = 'GP4';

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,
PROPRIETA ) VALUES ( 
'PECDSCAF', 'P00', 'DSCAF', NULL, NULL, 'Scaglioni Assegni Familiari', NULL, NULL
, 'F', 'F', 'PECDSCAF', NULL, 1, NULL, NULL); 

INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA,
STAMPANTE ) VALUES ( 
'GP4', '*', 1000351, 1013727, 'PECDSCAF', 71, NULL); 
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA,
STAMPANTE ) VALUES ( 
'GP4', 'AMM', 1000351, 1013727, 'PECDSCAF', 71, NULL); 

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,
PROPRIETA ) VALUES ( 
'PECEASFA', 'P00', 'EASFA', NULL, NULL, 'Elenco Assegni Familiari', NULL, NULL, 'F'
, 'F', 'PECEASFA', NULL, 1, NULL, NULL); 

INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA,
STAMPANTE ) VALUES ( 
'GP4', '*', 1000351, 1013725, 'PECEASFA', 91, NULL); 

INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA,
STAMPANTE ) VALUES ( 
'GP4', 'AMM', 1000351, 1013725, 'PECEASFA', 91, NULL); 