delete from A_PASSI_PROC where voce_menu = 'PECCCAAF';
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECCCAAF', 1, 'Caricamento somme C.A.A.F. in variabili', NULL, NULL, 'Q', 'CHK_SCAD'
, NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECCCAAF', 2, 'Caricamento somme C.A.A.F. in variabili', NULL, NULL, 'Q', 'PECCCAAF'
, NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECCCAAF', 91, 'Segnalazioni in Elaborazione', NULL, NULL, 'R', 'ACARAPPR', NULL
, 'PECCCAAF', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECCCAAF', 92, 'Stampa prospetto versamenti rateali', NULL, NULL, 'R', 'PECSCAAF'
, NULL, 'PECSCAAF', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECCCAAF', 93, 'Cancellazione Segnalazioni', NULL, NULL, 'Q', 'ACACANRP', NULL, NULL
, 'N'); 

INSERT INTO SCADENZE_DENUNCE ( CODICE, DATA_SCADENZA, DATA_FORZATURA, UTENTE,
DATA_AGG ) VALUES ( 
'730',  TO_Date( '11/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 'MONICA'
,  TO_Date( '02/08/2005 01:48:17 PM', 'MM/DD/YYYY HH:MI:SS AM')); 

start crp_chk_scad.sql
start crp_pecccaaf.sql