delete from a_selezioni
where voce_menu = 'PECSMOR6';

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_FRONTE_RETRO', 'PECSMOR6', 2, 'Stampa in Fronte/Retro', NULL, NULL, 2, 'U', 'N'
, NULL, 'P_SI_NO', NULL, NULL, NULL); 
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_TIPO_DESFORMAT', 'PECSMOR6', 1, 'Tipo stampa', NULL, NULL, 4, 'U', 'S', 'A_A', 'P_SCER6'
, NULL, NULL, NULL); 

delete from a_voci_menu
where voce_menu = 'PECSMOR6';

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,
PROPRIETA ) VALUES ( 
'PECSMOR6', 'P00', 'SMOR6', NULL, NULL, 'Stampa Retribuzioni Elaborate', NULL, NULL
, 'F', 'D', 'ACAPARPR', NULL, 1, NULL, NULL);


