start crp_pgpcvoci.sql

DELETE FROM A_PASSI_PROC WHERE VOCE_MENU='PGP4VOCI';

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGP4VOCI', 1, 'Creazione file Voci Emolumenti', NULL, NULL, 'Q', 'PGPCVOCI', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGP4VOCI', 2, 'Creazione file Voci Emolumenti', NULL, NULL, 'R', 'SI4V3WAS', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGP4VOCI', 3, 'Lista Voci emolumenti esportate', NULL, NULL, 'R', 'PGPLVOCI', NULL
, 'PGPLVOCI', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGP4VOCI', 4, 'Lista Voci emolumenti esportate', NULL, NULL, 'Q', 'ACACANAS', NULL
, NULL, 'N'); 
COMMIT;
