start crp_pgpcqual.sql

DELETE FROM A_PASSI_PROC WHERE VOCE_MENU='PGP4QUAL';

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGP4QUAL', 1, 'Creazione file Qualifiche Ente', NULL, NULL, 'Q', 'PGPCQUAL', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGP4QUAL', 2, 'Creazione file Qualifiche Ente', NULL, NULL, 'R', 'SI4V3WAS', NULL
, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGP4QUAL', 3, 'Lista qualifiche ente esportate', NULL, NULL, 'R', 'PGPLQUAL', NULL
, 'PGPLQUAL', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PGP4QUAL', 4, 'Lista qualifiche ente esportate', NULL, NULL, 'Q', 'ACACANAS', NULL
, NULL, 'N'); 
COMMIT;
