update a_catalogo_stampe 
   set titolo = 'SCHEDA INDIVIDUALE INFORTUNI'
 where stampa = 'PECSINFO';

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_FINCATO', 'PECSINFO', 4, 'Stampa su foglio pre-fincato', NULL, NULL, 1, 'U', 'N'
, NULL, 'P_X', NULL, NULL, NULL); 

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS,
NUMERO_FK ) VALUES ( 
'P_NUMERO', 'PECSINFO', 3, 'Numero Progressivo Infortunio', NULL, NULL, 8, 'N', 'N'
, NULL, NULL, NULL, NULL, NULL); 

