start crf_RARS_TMA.sql
start CRP_CODICE_FISCALE.sql
start crp_gp4do.sql
start crp_pecargla.sql
start crp_PECCADPM.sql
start crp_PECCAEDP.sql
start crp_PECCARDO.sql
start crp_peccarst.sql
start crp_PECCATFR.SQL
start crp_peccbarp.sql
start crp_peccmocp_ritenuta.sql
start crp_peccmore11.sql
start crp_peccmore2.sql
start crp_peccmore4.sql
start crp_peccmore5.sql
start crp_peccmore6.sql
start crp_peccmore7.sql
start crp_peccmore8.sql
start crp_peccmore_ritenuta.sql
start crp_peccmore_tariffa.sql
start crp_pecco1md.sql
start crp_peccpere2.sql
start crp_PECCRCDP.sql
start crp_PECCREIN.sql
start crp_peccrtfr.sql
start crp_pecdonao.sql
start crp_PECLISDO.sql
start crp_PECSMFA1.sql
start crp_pecsmgla.sql
start crp_pgmitelo.sql