delete from a_voci_menu where voce_menu = 'PECAADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECAADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECAADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECAADMA' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECAADMA');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

delete from a_guide_o where voce_menu = 'PECAADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECAADMA');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECAADMA'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECAADMA','P00','AADMA','Aggiornamento Archivio DMA I.N.P.D.A.P.','F','F','PECAADMA','',1,'P_DECP');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1013754','1013756','PECAADMA','2','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1013754','1013756','PECAADMA','2','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1013754','1013756','PECAADMA','2','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_DECP','1','GEST','G','Gestioni','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_DECP','2','RIRE','M','Mese','PECRMERE','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_guide_v (guida_v,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_GEST','1','','','Definizione','PGMDGEST','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
insert into a_guide_v (guida_v,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_GEST','2','','','Elenco','PGMEGEST','PGMDGEST');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

