start crp_peccadma.sql

start crp_denunce_inpdap.sql

start sia_periodo_crp.sql


delete from a_voci_menu where voce_menu = 'PECECFDM';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECECFDM';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECECFDM';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECECFDM' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECECFDM');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

delete from a_guide_o where voce_menu = 'PECECFDM';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECECFDM');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECECFDM'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECECFDM','P00','ECFDM','Denuncia DMA I.N.P.D.A.P.','N','M','','',1,'');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1000553','1013754','PECECFDM','22','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1000553','1013754','PECECFDM','22','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1000553','1013754','PECECFDM','22','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    


delete from a_voci_menu where voce_menu = 'PECCADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_passi_proc where voce_menu = 'PECCADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_selezioni where voce_menu = 'PECCADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

delete from a_menu where voce_menu = 'PECCADMA' and ruolo in ('*','AMM','PEC');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

delete from a_catalogo_stampe where stampa in (select stampa from a_passi_proc where substr(stampa,1,1) = 'P' and voce_menu = 'PECCADMA');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

delete from a_guide_o where voce_menu = 'PECCADMA';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

delete from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECCADMA');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

delete from a_guide_v where guida_v in (select guida_v from a_guide_o where guida_o in (select guida_o from a_voci_menu where voce_menu = 'PECCADMA'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_voci_menu (voce_menu,ambiente,acronimo,titolo,tipo_voce,tipo,modulo,stringa,importanza,guida_o) values ('PECCADMA','P00','CADMA','Caricamento Archivio DMA','F','D','ACAPARPR','',1,'P_CCADMA');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCADMA','1','Caricamento Archivio DMA','Q','PECCADMA','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCADMA','91','Errori di Elaborazione','R','ACARAPPR','','PECCADMA','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCADMA','92','Cancellazione errori','Q','ACACANRP','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCADMA','93','Lista Segnalazioni Denuncia DMA','R','PECLSDMA','','PECLSDMA','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
insert into a_passi_proc (voce_menu,passo,titolo,tipo,modulo,stringa,stampa,gruppo_ling) values ('PECCADMA','94','Cancellazione errori','Q','ACACANAS','','','N');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ANNO','PECCADMA','1','Elaborazione: Anno','4','N','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_CI','PECCADMA','7','Cod.Ind.','8','N','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GESTIONE','PECCADMA','3','Gestione','8','U','N','%','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_GRUPPO','PECCADMA','4','Gruppo','12','U','N','%','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_MESE','PECCADMA','2','                      Mese','2','N','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_PREVIDENZA','PECCADMA','5','Previdenza','6','U','N','CP%','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_SFASATO','PECCADMA','8','Anno Previdenziale da Novembre','1','U','N','','','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_TIPO','PECCADMA','6','Tipo Elaborazione','1','U','S','','P_CADMA','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_CASSA','PECCADMA','9','Archiviazione Econ. Per Cassa','1','U','N','','P_X','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
insert into a_selezioni (parametro,voce_menu,sequenza,descrizione,lunghezza,formato,obbligo,valore_default,dominio,alias,gruppo_alias,numero_fk) values ('P_ULTIMA_CESS','PECCADMA','10','Solo ultima cessazione','1','U','N','','P_X','','','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','*','1013754','1013755','PECCADMA','1','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','PEC','1013754','1013755','PECCADMA','1','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_menu (applicazione,ruolo,padre,figlio,voce_menu,sequenza,stampante) values ('GP4','AMM','1013754','1013755','PECCADMA','1','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CADMA','I','','Non altera Inseriti manualmente');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CADMA','P','','Parziale(non altera variazioni manuali)');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CADMA','S','','Singolo Individuo');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CADMA','T','','Totale');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
insert into a_domini_selezioni (dominio,valore_low,valore_high,descrizione) values ('P_CADMA','V','','Non altera Variati manualmente');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_CCADMA','1','PREN','P','Pren.','ACAEPRPA','*');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_CCADMA','2','RAIN','I','Individuo','P00RANAG','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_CCADMA','3','GEST','G','Gestioni','PGMEGEST','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_CCADMA','4','CLRA','R','Rapporti','PAMDCLRA','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
insert into a_guide_o (guida_o,sequenza,alias,lettera,titolo,voce_menu,voce_rif) values ('P_CCADMA','5','GRRA','U','grUppi','PAMDGRRA','');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

INSERT INTO A_CATALOGO_STAMPE ( STAMPA, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO_PROPRIETA, TIPO_VISURA,
CLASSE, STAMPA_BLOCCATA, STAMPA_PROTETTA, SEQUENZIALE ) VALUES ( 
'PECCADMA', 'SEGNALAZIONI ARCHIVIAZIONE DMA', NULL, NULL, 'U', 'U', 'A_C', 'N', 'N'
, 'S'); 




