delete from PEC_REF_CODES 
where rv_domain = 'CONTABILITA_VOCE.SOMME'
and rv_low_value in ('5','6');

INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'5', NULL, NULL, 'CONTABILITA_VOCE.SOMME', 'Somme Fiscali 5 (altre somme e valori)'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'6', NULL, NULL, 'CONTABILITA_VOCE.SOMME', 'Somme Fiscali 6 (Erogazioni Liberali)'
, 'CFG', NULL, NULL); 
