INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'O', NULL, 'O', 'ESTRAZIONE_CONTRIBUTI.NUMERO', 'Numero Dipendenti Rapportati a ore'
, 'CFG', NULL, NULL); 

