INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'IPN_INAIL', NULL, NULL, 'VOCI_ECONOMICHE.SPECIFICA', 'Imponibile per Autoliquidazione INAIL'
, 'CFG', NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'RET_CO_ORA', NULL, NULL, 'VOCI_ECONOMICHE.SPECIFICA', 'Voce calcolo tariffa oraria per autoliquidazione'
, 'CFG', NULL, NULL); 
