INSERT INTO A_CATALOGO_STAMPE ( STAMPA, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO_PROPRIETA, TIPO_VISURA,
CLASSE, STAMPA_BLOCCATA, STAMPA_PROTETTA, SEQUENZIALE ) VALUES ( 
'PECSTDMA', 'TOTALI DENUNCIA DMA', NULL, NULL, 'U', 'U', 'A_A', 'N', 'N', 'S'); 

delete 
  from a_passi_proc
 where voce_menu = 'PECSMDMA'
;

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSMDMA', 1, 'Elaborazione Supporto Magnetico DMA', NULL, NULL, 'Q', 'PECSMDMA'
, NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSMDMA', 2, 'Elaborazione Supporto Magnetico DMA', NULL, NULL, 'Q', 'PECCFDMA'
, NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSMDMA', 3, 'Elaborazione Supporto Magnetico DMA', NULL, NULL, 'R', 'SI4V3WAS'
, NULL, NULL, 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSMDMA', 4, 'Elaborazione Supporto Magnetico DMA', NULL, NULL, 'R', 'PECSTDMA'
, NULL, 'PECSTDMA', 'N'); 
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA,
STAMPA, GRUPPO_LING ) VALUES ( 
'PECSMDMA', 5, 'Elaborazione Supporto Magnetico DMA', NULL, NULL, 'Q', 'ACACANAS'
, NULL, NULL, 'N');