INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_RECE', 1, 'RECE', 'G', NULL, NULL, 'raGgrupp.', NULL, NULL, NULL, 'PECERECE', NULL
, NULL, NULL, NULL, NULL); 

DELETE A_VOCI_MENU WHERE VOCE_MENU='PECSREIN';

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,
PROPRIETA ) VALUES ( 
'PECSREIN', 'P00', 'SREIN', NULL, NULL, 'Stampa Retribuzioni INAIL Individuali', NULL
, NULL, 'F', 'D', 'ACAPARPR', 'LIS_AUTOLIQUIDAZIONE', 1, 'P_RECE', NULL); 


DELETE A_VOCI_MENU WHERE VOCE_MENU='PECSQUIN';

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O,
PROPRIETA ) VALUES ( 
'PECSQUIN', 'P00', 'SQUIN', NULL, NULL, 'Quadratura Retribuzioni INAIL', NULL, NULL
, 'F', 'D', 'ACAPARPR', 'QUADRATURA_INAIL', 1, 'P_RECE', NULL); 

