start crv_gp4gm_1.sql

start crv_visa.sql

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_ESTAM', 1, 'RIFU', 'R', NULL, NULL, 'Rip.funz.', NULL, NULL, NULL, 'PGMDRIFU', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_ESTAM', 2, 'ASCO', 'C', NULL, NULL, 'Contabile', NULL, NULL, NULL, 'PECRASCO', NULL
, NULL, NULL, NULL, NULL); 
INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO,
TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1,
TITOLO_ESTESO_AL2 ) VALUES ( 
'P_ESTAM', 3, 'PEGI', 'I', NULL, NULL, 'Inquadr.', NULL, NULL, NULL, 'PGMRPEGI', NULL
, NULL, NULL, NULL, NULL); 


UPDATE A_VOCI_MENU 
SET    GUIDA_O='P_ESTAM'
WHERE VOCE_MENU='PGMESTAM';



