alter table ente add (rilevazione_presenze varchar2(1) default 'C' 
      constraint RILEVAZIONE_PRESENZE_CC check (RILEVAZIONE_PRESENZE in ('C','M','N')));


update ENTE set RILEVAZIONE_PRESENZE='C';

alter table ENTE modify RILEVAZIONE_PRESENZE not null;

INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'C', NULL, NULL, 'ENTE.RILEVAZIONE_PRESENZE', 'Codice Individuale', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'M', NULL, NULL, 'ENTE.RILEVAZIONE_PRESENZE', 'Matricola', NULL, NULL, NULL); 
INSERT INTO PGM_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'N', NULL, NULL, 'ENTE.RILEVAZIONE_PRESENZE', 'Numero Individuale', NULL, NULL, NULL); 
