INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'3', NULL, NULL, 'TRATTAMENTI_PREVIDENZIALI.TIPO_TRATTAMENTO', 'TFS con limite di contribuzione',
NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'4', NULL, NULL, 'TRATTAMENTI_PREVIDENZIALI.TIPO_TRATTAMENTO', 'TFR con limite di contribuzione',
NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'5', NULL, NULL, 'TRATTAMENTI_PREVIDENZIALI.TIPO_TRATTAMENTO', 'Fondo Pensione',
NULL, NULL, NULL); 
INSERT INTO PEC_REF_CODES ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING,
RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2 ) VALUES ( 
'6', NULL, NULL, 'TRATTAMENTI_PREVIDENZIALI.TIPO_TRATTAMENTO', 'Fondo Pensione con limite di contribuzione',
NULL, NULL, NULL); 

COMMIT;
