-- contiene anche 9964 e 9965
delete from caselle_fiscali
where anno = 2004
and sequenza in ( 63, 69 );

INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, TIPO_CASELLA, CASELLA_DETT ) 
VALUES ( 2004, 'C', 63, 'Casella 63', NULL, NULL, 'D', '69'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, TIPO_CASELLA, CASELLA_DETT ) 
VALUES ( 2004, 'C', 69, 'Casella 69', NULL, NULL, 'D', '105'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, TIPO_CASELLA, CASELLA_DETT ) 
VALUES ( 2004, 'S', 63, 'Casella 63', NULL, NULL, 'D', '69'); 
INSERT INTO CASELLE_FISCALI ( ANNO, TIPO_DICHIARAZIONE, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2, TIPO_CASELLA, CASELLA_DETT ) 
VALUES ( 2004, 'S', 69, 'Casella 69', NULL, NULL, 'D', '105'); 

start crp_cursore_fiscale.sql
start crp_peccnocu.sql
start crp_peccarfi.sql
start crp_pecsmcud.sql