start \si4\Gp4\Gipv4\ins\crp_peccpere3.sql
start \si4\Gp4\Gipv4\ins\crp_peccpere2.sql
start \si4\Gp4\Gipv4\ins\crp_peccpere.sql
start \si4\Gp4\Gipv4\ins\crp_gp4_caco.sql
start \si4\Gp4\Gipv4\ins\crp_gp4_defi.sql
start \si4\Gp4\Gipv4\ins\crp_gp4_ente.sql
start \si4\Gp4\Gipv4\ins\crp_gp4_inex.sql
start \si4\Gp4\Gipv4\ins\crp_gp4_rare.sql
start \si4\Gp4\Gipv4\ins\crf_peccmore.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore_autofam.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore_ritenuta.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore_tariffa.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore_onaosi.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore_veneto.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore12.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore11.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore10.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore9.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore8.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore7.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore6.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore5.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore4.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore3.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore2.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore1.sql
start \si4\Gp4\Gipv4\ins\crp_peccmore.sql
exec utilitypackage.compile_all;


