INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00200', 'Indennita Diaria di Missione Nulla', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00200' );
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00201', 'Valore minimo 0', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00201' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA )
SELECT  'P00202', 'Valore minimo 1', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00202' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00203', 'Minimo Ore maggiore di Massimo Ore', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00203' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00204', 'Valori ammessi da 0.01 a 100', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00204' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00205', 'Esiste un record con ore che si intersecano a quelle caricate', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00205' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00206', 'Valori ammessi da 1 a 59', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00206' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00207', 'Causale Spesa gia a Forfait', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00207' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00208', 'Valori negativi non ammessi', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00208' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00209', 'Non sono state trovate spese da sostituire con forfait.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00209' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00210', 'Manca l''opportuno Tipo Spesa!', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00210' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00211', 'Trovati piu'' di un Tipo Spesa!', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00211' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00212', 'Impossibile valorizzare il forfait: non trovata la tariffa.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00212' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00213', 'Impossibile valorizzare il forfait: trovate piu'' di una tariffa.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00213' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00214', 'Il progressivo puo'' assumere solo valori < 5000', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00214' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00215', 'Durata della trasferta inferiore al minimale orario', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00215' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00216', 'Impossibile valorizzare il forfait: non gestita la tariffa.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00216' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00217', 'Il progressivo puo'' assumere solo valori < 4000', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00217' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00218', 'Non spetta la Diaria.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00218' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00219', 'Impossibile valorizzare la diaria: non gestita la tariffa.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00219' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA )
SELECT  'P00220', 'Impossibile valorizzare la diaria: non trovata la tariffa.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00220' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00221', 'Impossibile valorizzare la diaria: trovate piu'' di una tariffa.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00221' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00222', 'Impossibile valorizzare la diaria: non trovata la percentuale di diaria.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00222' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00223', 'Impossibile valorizzare la diaria: trovate piu'' percentuali di diaria.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00223' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00224', 'Data Documento nulla !', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00224' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00225', 'Importo maggiore dell'' importo massimale.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00225' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00226', 'La trasferta e'' durata meno di 24 ore.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00226' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00227', 'ATTENZIONE! Quantita diversa dal nr di giorni di durata della trasferta.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00227' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00228', 'ATTENZIONE! Quantita diversa dal nr di ore di durata della trasferta.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00228' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00229', 'Diaria nel comune dell'' Ente non prevista.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00229' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00230', 'Diaria nel comune di residenza non prevista.', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00230' ); 
INSERT INTO A_ERRORI ( ERRORE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,PROPRIETA ) 
SELECT  'P00231', 'Impossibile effettuare l''inserimento, uno dei flag e'' attivato', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS ( SELECT 'X' FROM A_ERRORI  WHERE ERRORE = 'P00231' ); 
COMMIT;