SET TERMOUT OFF 

REM ============================================================
REM    Extract TABLE :   PMT_REF_CODES
REM ============================================================

WHENEVER SQLERROR EXIT

ALTER TABLE pmt_ref_codes DISABLE ALL TRIGGERS;

DELETE FROM pmt_ref_codes;

WHENEVER SQLERROR CONTINUE

INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '1', NULL, NULL, 'STATI_RICHIESTA_RIMBORSO.STATO_RICHIESTA', 'Richiesta Caricata', 'CFG', NULL, NULL);
INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '2', NULL, NULL, 'STATI_RICHIESTA_RIMBORSO.STATO_RICHIESTA', 'Richiesta Controllata', 'CFG', NULL, NULL);
INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '3', NULL, NULL, 'STATI_RICHIESTA_RIMBORSO.STATO_RICHIESTA', 'Richiesta Sospesa', 'CFG', NULL, NULL);
INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '4', NULL, NULL, 'STATI_RICHIESTA_RIMBORSO.STATO_RICHIESTA', 'Richiesta Respinta', 'CFG', NULL, NULL);
INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '5', NULL, NULL, 'STATI_RICHIESTA_RIMBORSO.STATO_RICHIESTA', 'Richiesta di Storno', 'CFG', NULL, NULL);
INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '6', NULL, NULL, 'STATI_RICHIESTA_RIMBORSO.STATO_RICHIESTA', 'Richiesta Autorizzata', 'CFG', NULL, NULL);
INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '7', NULL, NULL, 'STATI_RICHIESTA_RIMBORSO.STATO_RICHIESTA', 'Richiesta passata in Economico', 'CFG', NULL, NULL);
INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '+', NULL, NULL, 'PARAMETRI_MISSIONI.SEGNO_ACCONTO_IN_EC', 'Valori Positivi', 'CFG', NULL, NULL);
INSERT INTO pmt_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2)
VALUES ( '-', NULL, NULL, 'PARAMETRI_MISSIONI.SEGNO_ACCONTO_IN_EC', 'Valori Negativi', 'CFG', NULL, NULL);


WHENEVER SQLERROR EXIT

ALTER TABLE pmt_ref_codes ENABLE ALL TRIGGERS;
