-- i file sono startati in ignore in quanto si richiamano tra loro 
-- e renderebbero invalida la versione del DB

start crp_GP4AA.sql
start crp_gp4_alei.sql
start crp_gp4_alin.sql
start crp_GP4_ANAG.sql
start crp_gp4_asin.sql
start crp_GP4_ASTE.sql
start crp_gp4_ATGI.sql
start crp_gp4_ATTI.sql
start crp_GP4_CACO.sql
start crp_GP4_CAFA.sql
start crp_GP4_cale.sql
start crp_gp4_CECO.sql
start crp_gp4_CLFU.sql
start crp_gp4_COAT.sql
start crp_GP4_COMP.sql
start crp_GP4_COMU.sql
start crp_gp4_CONT.sql
start crp_GP4_COST.sql
start crp_GP4_DEFI.sql
start crp_gp4_deli.sql
start crp_GP4_DOOR.sql
start crp_GP4_ENTE.sql
start crp_gp4_esin.sql
start crp_gp4_EVGI.sql
start crp_gp4_EVIN.sql
start crp_gp4_EVRA.sql
start crp_GP4_FIGI.sql
start crp_GP4_GEAM.sql
start crp_GP4_GEST.sql
start crp_gp4_imvo.sql
start crp_GP4_INEX.sql
start crp_gp4_PEDO.sql
start crp_GP4_PEGI.sql
start crp_gp4_POFU.sql
start crp_gp4_poii.sql
start crp_GP4_POSI.sql
start crp_gp4_prfi.sql
start crp_gp4_PRPR.sql
start crp_gp4_qual.sql
start crp_GP4_QUGI.sql
start crp_GP4_RAIN.sql
start crp_GP4_RARE.sql
start crp_GP4_RARS.sql
start crp_gp4_rdre.sql
start crp_GP4_REDO.sql
start crp_GP4_REST.sql
start crp_gp4_reuo.sql
start crp_GP4_RIDO.sql
start crp_gp4_rigd.sql
start crp_gp4_RUOL.sql
start crp_GP4_SDAM.sql
start crp_GP4_SEPR.SQL
start crp_gp4_SOGI.sql
start crp_GP4_STAM.sql
start crp_GP4_SUST.sql
start crp_GP4_TIIN.sql
start crp_gp4_TIRA.sql
start crp_gp4_vori.sql

start crp_gp4_PDOCMODO.sql
start crp_GP4_PDODMODO.sql
