DECLARE
D_cliente  varchar2(8);
V_comando  varchar2(32000);
BEGIN
  BEGIN
    SELECT substr(note,instr(note, 'Cliente=')+8,100)
      INTO D_cliente
      from ad4_enti
     where note  like '%Cliente%'
       and ente   = '&1 '
     ;
  EXCEPTION WHEN NO_DATA_FOUND THEN
     D_cliente := 'XXXX';
  END;
  IF D_cliente = 'ER09' THEN -- Reggio
-- dbms_output.put_line('Reggio');
     V_comando := ' CREATE OR REPLACE PACKAGE GP4_BADGE IS '
                ||'type badgetype is record ( '
                ||'ci 		rapporti_individuali.ci%type, '
                ||'nome		rapporti_individuali.nome%type, '
                ||'cognome	rapporti_individuali.cognome%type, '
                ||'stringa_badge	varchar2(200), '
                ||'dal		rapporti_individuali.dal%type, '
                ||'rapporto	rapporti_individuali.rapporto%type , '
                ||'gestione	periodi_giuridici.gestione%type, '
                ||'gruppo 	rapporti_individuali.gruppo%type , '
                ||'fascia	gestioni.fascia%type, '
                ||'ruolo	posizioni.ruolo%type, '
                ||'no_badge	varchar2(200) '
                ||'); '
                ||'type badgecurtyp is REF CURSOR return badgetype; '
                ||'procedure open_badge( pci in number, pnome in varchar2, pcognome in varchar2 '
                ||', pdal in date, pal in date, prapporto in varchar2, pgestione in varchar2 '
                ||',pgruppo in varchar2,pfascia in varchar2, pruolo in varchar2, pbadge in out badgecurtyp); '
                ||'end GP4_BADGE; ';
     si4.sql_execute(V_comando);
     V_comando := 'CREATE OR REPLACE PACKAGE BODY GP4_BADGE IS '
                ||'procedure open_badge( pci in number, pnome in varchar2, pcognome in varchar2 '
                ||', pdal in date, pal in date, prapporto in varchar2, pgestione in varchar2 '
                ||',pgruppo in varchar2,pfascia in varchar2, pruolo in varchar2, pbadge in out badgecurtyp) is '
                ||'begin '
                ||'  open pbadge for '
                ||'select rain.ci ,rain.nome,rain.cognome,get_stringa_badge(rain.ci),rain.dal,rain.rapporto '
                ||', pegi.gestione, rain.gruppo , gest.fascia, posi.ruolo, get_no_badge(rain.ci) '
                ||'from rapporti_individuali rain, periodi_giuridici pegi , gestioni gest, posizioni posi '
                ||'where rain.ci = pegi.ci '
                ||'and pegi.dal is not null and '
                ||'nvl(pegi.al,to_date(''3333333'',''j'')) > sysdate '
                ||'and pegi.rilevanza = ''S'' '
                ||'and gest.codice = pegi.gestione '
                ||'and pegi.posizione = posi.codice '
                ||'AND rain.ci = nvl(pci,rain.ci) '
                ||'and rain.nome = nvl(pnome,rain.nome) '
                ||'and rain.cognome = nvl(pcognome,rain.cognome) '
                ||'and rain.dal between nvl(pdal,rain.dal) and nvl(pal,to_date(''3333333'',''j'')) '
                ||'and rain.rapporto = nvl(prapporto,rain.rapporto) '
                ||'and pegi.gestione = nvl(pgestione,pegi.gestione) '
                ||'and nvl(rain.gruppo,''%'') = nvl(pgruppo,nvl(rain.gruppo,''%'')) '
                ||'and nvl(gest.fascia,''%'') = nvl(pfascia,nvl(gest.fascia,''%'')) '
                ||'and posi.ruolo = nvl(pruolo,posi.ruolo) '
                ||'union '
                ||'select rain.ci ,rain.nome,rain.cognome,get_stringa_badge(rain.ci),rain.dal,rain.rapporto '
                ||',null gestione, rain.gruppo , null fascia, null ruolo, get_no_badge(rain.ci) '
                ||'from rapporti_individuali rain, periodi_giuridici pegi '
                ||'where rain.ci = pegi.ci '
                ||'and pegi.dal is not null '
                ||'and nvl(pegi.al,to_date(''3333333'',''j'')) >= sysdate '
                ||'and pegi.rilevanza = ''P'' '
                ||'AND rain.ci = nvl(pci,rain.ci) '
                ||'and rain.nome = nvl(pnome,rain.nome) '
                ||'and rain.cognome = nvl(pcognome,rain.cognome) '
                ||'and rain.dal between nvl(pdal,rain.dal) and nvl(pal,to_date(''3333333'',''j'')) '
                ||'and rain.rapporto = nvl(prapporto,rain.rapporto) '
                ||'and pgestione is null '
                ||'and nvl(rain.gruppo,''%'') = nvl(pgruppo,nvl(rain.gruppo,''%'')) '
                ||'and pfascia is null '
                ||'and pruolo is null '
                ||'and not exists(select ''x'' from periodi_giuridici  '
                ||'where  ci = pegi.ci and dal >= pegi.dal and rilevanza = ''S'') '
                ||'  order by 1; '
                ||'end; '
                ||'end GP4_BADGE;';
     si4.sql_execute(V_comando);
  ELSE
-- dbms_output.put_line('Altro');
     V_comando := 'CREATE OR REPLACE PACKAGE GP4_BADGE IS '
                ||'type badgetype is record ( '
                ||'ci 		rapporti_individuali.ci%type, '
                ||'nome		rapporti_individuali.nome%type, '
                ||'cognome	rapporti_individuali.cognome%type, '
                ||'stringa_badge varchar2(200), '
                ||'dal		rapporti_individuali.dal%type, '
                ||'rapporto	rapporti_individuali.rapporto%type , '
                ||'gestione	periodi_giuridici.gestione%type, '
                ||'gruppo 	rapporti_individuali.gruppo%type , '
                ||'fascia	gestioni.fascia%type, '
                ||'ruolo	posizioni.ruolo%type, '
                ||'no_badge	varchar2(200) '
                ||'); '
                ||'type badgecurtyp is REF CURSOR return badgetype; '
                ||'procedure open_badge( pci in number, pnome in varchar2, pcognome in varchar2 '
                ||', pdal in date, pal in date, prapporto in varchar2, pgestione in varchar2,pgruppo in varchar2 '
                ||',pfascia in varchar2, pruolo in varchar2, pbadge in out badgecurtyp); '
                ||'end GP4_BADGE; ';
     si4.sql_execute(V_comando);
     V_comando := 'CREATE OR REPLACE PACKAGE BODY GP4_BADGE IS '
                ||'procedure open_badge( pci in number, pnome in varchar2, pcognome in varchar2 '
                ||', pdal in date, pal in date, prapporto in varchar2, pgestione in varchar2,pgruppo in varchar2 '
                ||',pfascia in varchar2, pruolo in varchar2, pbadge in out badgecurtyp) is '
                ||'begin '
                ||'  open pbadge for '
                ||'select  rain.ci , rain.nome, rain.cognome '
                ||'       ,get_stringa_badge(rain.ci), asba.dal '
                ||'       ,rain.rapporto, pegi.gestione ,rain.gruppo ,posi.ruolo ,gest.fascia '
                ||'       ,get_no_badge(asba.asba_id) '
                ||'from rapporti_individuali rain, assegnazioni_badge asba, periodi_giuridici pegi '
                ||', gestioni gest, posizioni posi '
                ||'where rain.ci = asba.ci '
                ||'and asba.dal is not null '
                ||'and pegi.ci = asba.ci '
                ||'and pegi.rilevanza = ''S'' '
                ||'and sysdate between pegi.dal and nvl(pegi.al,sysdate)  '
                ||'and pegi.dal >= asba.dal '
                ||'and gest.codice = pegi.gestione '
                ||'and pegi.posizione = posi.codice ' 
                ||'AND rain.ci = nvl(pci,rain.ci) '
                ||'and rain.nome = nvl(pnome,rain.nome) '
                ||'and rain.cognome = nvl(pcognome,rain.cognome) '
                ||'and asba.dal between nvl(pdal,asba.dal) and nvl(pal,sysdate) '
                ||'and rain.rapporto = nvl(prapporto,rain.rapporto) '
                ||'and pegi.gestione = nvl(pgestione,pegi.gestione) '
                ||'and nvl(rain.gruppo,''%'') = nvl(pgruppo,nvl(rain.gruppo,''%'')) '
                ||'and nvl(gest.fascia,''%'') = nvl(pfascia,nvl(gest.fascia,''%'')) '
                ||'and posi.ruolo = nvl(pruolo,posi.ruolo) '
                ||'union '
                ||'select rain.ci ,rain.nome,rain.cognome,get_stringa_badge(rain.ci),asba.dal,rain.rapporto '
                ||',null gestione, rain.gruppo , null fascia, null ruolo, get_no_badge(rain.ci) '
                ||'from rapporti_individuali rain, assegnazioni_badge asba '
                ||'where rain.ci = asba.ci '
                ||'and asba.dal is not null '
                ||'and nvl(asba.al,to_date(''3333333'',''j'')) >= sysdate '
                ||'AND rain.ci = nvl(pci,rain.ci) '
                ||'and rain.nome = nvl(pnome,rain.nome) '
                ||'and rain.cognome = nvl(pcognome,rain.cognome) '
                ||'and asba.dal between nvl(pdal,asba.dal) and nvl(pal,to_date(''3333333'',''j'')) '
                ||'and rain.rapporto = nvl(prapporto,rain.rapporto) '
                ||'and pgestione is null '
                ||'and nvl(rain.gruppo,''%'') = nvl(pgruppo,nvl(rain.gruppo,''%'')) '
                ||'and pfascia is null '
                ||'and pruolo is null '
                ||'and not exists(select ''x'' from periodi_giuridici pegi  '
                ||'where asba.ci = pegi.ci and asba.dal <= pegi.dal and rilevanza = ''S'') '
                ||'  order by 1 ; '
                ||'end; '
                ||'end GP4_BADGE;';
     si4.sql_execute(V_comando);
  END IF;
END;
/
