REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM SEQUENCE
REM      EVPA_SQ


REM
REM Progressivo evento di presenza / assenza e classi di presenza / assenza
REM
PROMPT 
PROMPT Creating Sequence EVPA_SQ
CREATE SEQUENCE evpa_sq
 INCREMENT BY 1
 START WITH 1
 MINVALUE 1
 MAXVALUE 9999999999
 NOCYCLE 
 CACHE 2
 NOORDER 
;

REM
REM  End of command file
REM
