REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-DEC-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DEPOSITO_VARIABILI_INCENTIVO
REM INDEX
REM      DVIP_IK

REM
REM     DVIP - DEposito Variabili Incentivo per passaggio all" Economico
REM
PROMPT 
PROMPT Creating Table DEPOSITO_VARIABILI_INCENTIVO
CREATE TABLE deposito_variabili_incentivo(
 anno                            NUMBER(4,0)      NOT NULL,
 mese                            NUMBER(2,0)      NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 fondo                           VARCHAR(2)       NOT NULL,
 parte                           VARCHAR(4)       NOT NULL,
 progetto                        VARCHAR(8)       NOT NULL,
 scp                             VARCHAR(4)       NOT NULL,
 tipo                            VARCHAR(1)       NOT NULL,
 importo                         NUMBER(12,2)     NOT NULL,
 anno_bil                        NUMBER(4,0)      NULL,
 risorsa_intervento              VARCHAR(7)       NULL,
 capitolo                        VARCHAR(14)      NULL,
 articolo                        VARCHAR(14)      NULL,
 impegno                         NUMBER(5)        NULL,
 sede_del                        VARCHAR(4)       NULL,
 anno_del                        NUMBER(4,0)      NULL,
 numero_del                      NUMBER(7,0)      NULL,
 c_anno                          NUMBER(4,0)      NOT NULL,
 c_mese                          NUMBER(2,0)      NOT NULL,
 flag_voce                       VARCHAR(1)       NOT NULL,
 anno_impegno                    NUMBER(4)        NULL,
 sub_impegno                     NUMBER(5)        NULL,
 anno_sub_impegno                NUMBER(4)        NULL,
 codice_siope		         NUMBER(4)        NULL
)
;

COMMENT ON TABLE deposito_variabili_incentivo
    IS 'DVIP - DEposito Variabili Incentivo per passaggio all" Economico';


REM
REM 
REM
PROMPT
PROMPT Creating Index DVIP_IK on Table DEPOSITO_VARIABILI_INCENTIVO
CREATE INDEX DVIP_IK ON DEPOSITO_VARIABILI_INCENTIVO
(
      progetto ,
      scp )
PCTFREE  10
;

REM
REM  End of command file
REM
