CREATE TABLE PROGETTI
(PROGETTO              VARCHAR2(8)   NOT NULL
,DESCRIZIONE           VARCHAR2(30)  NOT NULL
,VOCE                  VARCHAR2(10)  NOT NULL
,SUB                   VARCHAR2(2)   NOT NULL
)
/
CREATE UNIQUE INDEX PROG_PK ON PROGETTI (PROGETTO)
/
