REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  19-JAN-94
REM
REM For application system GIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      IMPUTAZIONI_CENTRO_COSTO
REM INDEX
REM      IMCC_IK

REM
REM     IMCC - Movimenti Imputazione alla Contabilita` per Centro di Costo
REM
PROMPT 
PROMPT Creating Table IMPUTAZIONI_CENTRO_COSTO
CREATE TABLE imputazioni_centro_costo(
 anno                            NUMBER(4)        NOT NULL,
 periodo                         NUMBER(2)        NOT NULL,
 cc                              VARCHAR(8)       NOT NULL,
 fp                              VARCHAR(8)       NOT NULL,
 quantita                        NUMBER(12,2)     NULL,
 valore                          NUMBER(16,2)     NULL,
 causale                         VARCHAR(3)       NULL,
 dat_mov                         NUMBER(7,0)      NULL,
 dat_doc                         NUMBER(7,0)      NULL,
 rif_doc                         VARCHAR(8)       NULL,
 note                            VARCHAR(40)      NULL,
 dat_da                          NUMBER(7,0)      NULL,
 dat_a                           NUMBER(7,0)      NULL,
 dato_n1                         NUMBER(8)        NULL,
 dato_a1                         VARCHAR2(100)    NULL
);

COMMENT ON TABLE imputazioni_centro_costo
    IS 'IMCC - Movimenti Imputazione alla Contabilita` per Centro di Costo';


REM
REM 
REM
PROMPT
PROMPT Creating Index IMCC_IK on Table IMPUTAZIONI_CENTRO_COSTO
CREATE INDEX IMCC_IK ON IMPUTAZIONI_CENTRO_COSTO
(
      anno ,
      periodo ,
      cc ,
      fp )
PCTFREE  10
;

REM
REM  End of command file
REM
