REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      SOSPENSIONI_PROGRESSIONE
REM INDEX
REM      SOPR_PK

REM
REM     SOPR - Data di sospensione delle progressioni economiche
REM
PROMPT 
PROMPT Creating Table SOSPENSIONI_PROGRESSIONE
CREATE TABLE sospensioni_progressione(
 contratto                       VARCHAR(4)       NOT NULL,
 gestione                        VARCHAR(8)       NOT NULL,
 ruolo                           VARCHAR(4)       NOT NULL,
 livello                         VARCHAR(4)       NOT NULL,
 qualifica                       VARCHAR(8)       NOT NULL,
 dal                             DATE             NULL
)
;

COMMENT ON TABLE sospensioni_progressione
    IS 'SOPR - Data di sospensione delle progressioni economiche';


REM
REM 
REM
PROMPT
PROMPT Creating Index SOPR_PK on Table SOSPENSIONI_PROGRESSIONE
CREATE UNIQUE INDEX SOPR_PK ON SOSPENSIONI_PROGRESSIONE
(
      contratto ,
      gestione ,
      ruolo ,
      livello ,
      qualifica )
PCTFREE  10
;

REM
REM  End of command file
REM
