REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONE_RIGHE_MODULO
REM INDEX
REM      ESRM_PK
REM      ESRM_VOCO_FK

REM
REM     ESRM - Voci contabili da raccogliere nei Moduli Raccolta Variabili
REM
PROMPT 
PROMPT Creating Table ESTRAZIONE_RIGHE_MODULO
CREATE TABLE estrazione_righe_modulo(
 modulo                          VARCHAR(4)       NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 voce                            VARCHAR(10)      NULL,
 sub                             VARCHAR(2)       NULL,
 note                            VARCHAR(240)     NULL
)
;

COMMENT ON TABLE estrazione_righe_modulo
    IS 'ESRM - Voci contabili da raccogliere nei Moduli Raccolta Variabili';


REM
REM 
REM
PROMPT
PROMPT Creating Index ESRM_PK on Table ESTRAZIONE_RIGHE_MODULO
CREATE UNIQUE INDEX ESRM_PK ON ESTRAZIONE_RIGHE_MODULO
(
      modulo ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESRM_VOCO_FK on Table ESTRAZIONE_RIGHE_MODULO
CREATE INDEX ESRM_VOCO_FK ON ESTRAZIONE_RIGHE_MODULO
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
