REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RACCOLTA_VARIABILI
REM INDEX
REM      RAVA_PK
REM      RAVA_RAIN_FK

REM
REM     RAVA - Valori dei Moduli di Raccolta Variabili caricati
REM
PROMPT 
PROMPT Creating Table RACCOLTA_VARIABILI
CREATE TABLE raccolta_variabili(
 modulo                          VARCHAR(4)       NOT NULL,
 cc                              VARCHAR(30)      NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 riferimento                     DATE             NOT NULL,
 dato1                           NUMBER(15,5)     NULL,
 arr1                            VARCHAR(1)       NULL,
 dato2                           NUMBER(15,5)     NULL,
 arr2                            VARCHAR(1)       NULL,
 dato3                           NUMBER(15,5)     NULL,
 arr3                            VARCHAR(1)       NULL,
 dato4                           NUMBER(15,5)     NULL,
 arr4                            VARCHAR(1)       NULL,
 voce                            VARCHAR(10)      NULL,
 sub                             VARCHAR(2)       NULL,
 tipo                            VARCHAR(1)       NULL,
 dato                            NUMBER(15,5)     NULL,
 arr                             VARCHAR(1)       NULL,
 progressivo                     NUMBER(6)        NULL,
 competenza                      DATE             NULL
)
;

COMMENT ON TABLE raccolta_variabili
    IS 'RAVA - Valori dei Moduli di Raccolta Variabili caricati';


REM
REM 
REM
PROMPT
PROMPT Creating Index RAVA_PK on Table RACCOLTA_VARIABILI
CREATE UNIQUE INDEX RAVA_PK ON RACCOLTA_VARIABILI
(
      modulo ,
      cc ,
      ci ,
      riferimento )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RAVA_RAIN_FK on Table RACCOLTA_VARIABILI
CREATE INDEX RAVA_RAIN_FK ON RACCOLTA_VARIABILI
(
      ci )
PCTFREE  10
;

REM
REM  End of command file
REM
