CREATE TABLE RIGHE_QUALIFICHE_STATISTICHE ( 
  STATISTICA         VARCHAR2 (6)  NOT NULL, 
  CODICE             VARCHAR2 (6)  NOT NULL, 
  SEQUENZA           NUMBER (3), 
  QUALIFICA          NUMBER (6), 
  TIPO_RAPPORTO      VARCHAR2 (4), 
  FIGURA             NUMBER (6), 
  DI_RUOLO           VARCHAR2 (1), 
  TEMPO_DETERMINATO  VARCHAR2 (2), 
  PART_TIME          VARCHAR2 (2), 
  RAPPORTO_GG        VARCHAR2 (2),
  formazione_lavoro       varchar2(2) null,
  RUOLO                  VARCHAR2(4),
  ATTIVITA               VARCHAR2(4),
  PROFILO_PROFESSIONALE  VARCHAR2(4),
  POSIZIONE_FUNZIONALE   VARCHAR2(4),
  CI                     NUMBER(8)
)
; 


CREATE INDEX RQST_IK ON 
  RIGHE_QUALIFICHE_STATISTICHE(CODICE, STATISTICA) 
 ;

CREATE INDEX RQST_FIGU_FK
 ON RIGHE_QUALIFICHE_STATISTICHE(CODICE, STATISTICA, FIGURA);
CREATE INDEX RQST_QUAL_FK
 ON RIGHE_QUALIFICHE_STATISTICHE(CODICE, STATISTICA, QUALIFICA);