REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      FORMULE_CERTIFICATO
REM INDEX
REM      FOCE_CERT_FK
REM      FOCE_PK

REM
REM     FOCE - Formule verbali preformattate da includere nei certificati
REM
PROMPT 
PROMPT Creating Table FORMULE_CERTIFICATO
CREATE TABLE formule_certificato(
 codice                          VARCHAR(4)       NOT NULL,
 tipo                            VARCHAR(4)       NULL,
 descrizione                     VARCHAR(75)      NULL,
 descrizione_al1                 VARCHAR(75)      NULL,
 descrizione_al2                 VARCHAR(75)      NULL
)
;

COMMENT ON TABLE formule_certificato
    IS 'FOCE - Formule verbali preformattate da includere nei certificati';


REM
REM 
REM
PROMPT
PROMPT Creating Index FOCE_CERT_FK on Table FORMULE_CERTIFICATO
CREATE INDEX FOCE_CERT_FK ON FORMULE_CERTIFICATO
(
      tipo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index FOCE_PK on Table FORMULE_CERTIFICATO
CREATE UNIQUE INDEX FOCE_PK ON FORMULE_CERTIFICATO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
