REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      POSTI_ORGANICO
REM INDEX
REM      POOR_PK

REM
REM     POOR - Identificazione del Posto in Organico
REM
PROMPT 
PROMPT Creating Table POSTI_ORGANICO
CREATE TABLE posti_organico(
 sede                            VARCHAR(4)       NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 numero                          NUMBER(7,0)      NOT NULL,
 posto                           NUMBER(4,0)      NOT NULL
)
;

COMMENT ON TABLE posti_organico
    IS 'POOR - Identificazione del Posto in Organico';


REM
REM 
REM
PROMPT
PROMPT Creating Index POOR_PK on Table POSTI_ORGANICO
CREATE UNIQUE INDEX POOR_PK ON POSTI_ORGANICO
(
      sede ,
      anno ,
      numero ,
      posto )
PCTFREE  10
;

REM
REM  End of command file
REM
