REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIFERIMENTO_RETRIBUZIONE
REM INDEX
REM      RIRE_PK

REM
REM     RIRE - Periodo di riferimento per la retribuzione mensile
REM
PROMPT 
PROMPT Creating Table RIFERIMENTO_RETRIBUZIONE
CREATE TABLE riferimento_retribuzione(
 rire_id                         VARCHAR(4)       NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 mese                            NUMBER(2,0)      NOT NULL,
 mensilita                       VARCHAR(3)       NOT NULL,
 ini_ela                         DATE             NOT NULL,
 fin_ela                         DATE             NOT NULL,
 conguaglio                      VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE riferimento_retribuzione
    IS 'RIRE - Periodo di riferimento per la retribuzione mensile';


REM
REM 
REM
PROMPT
PROMPT Creating Index RIRE_PK on Table RIFERIMENTO_RETRIBUZIONE
CREATE UNIQUE INDEX RIRE_PK ON RIFERIMENTO_RETRIBUZIONE
(
      rire_id )
PCTFREE  10
;

REM
REM  End of command file
REM
