REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system GIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      BILANCIO
REM INDEX
REM      BILA_IK

REM
REM     BILA - Estremi di identificazione degli impegni di spesa in bilancio
REM
PROMPT 
PROMPT Creating Table BILANCIO
CREATE TABLE bilancio(
 divisione                       VARCHAR(4)       NOT NULL,
 esercizio                       NUMBER(4,0)      NOT NULL,
 e_s                             VARCHAR(1)       NOT NULL,
 risorsa_intervento              VARCHAR(7)       NOT NULL,
 capitolo                        VARCHAR(6)       NOT NULL,
 articolo                        VARCHAR(14)      NOT NULL,
 gestione                        NUMBER(4,0)      NOT NULL,
 sede_del                        VARCHAR(4)       NULL,
 anno_del                        NUMBER(4,0)      NULL,
 numero_del                      NUMBER(7,0)      NULL,
 impegno                         NUMBER(6,0)      NULL,
 sub                             NUMBER(6)        NULL,
 funzionale                      VARCHAR(8)       NULL,
 soggetto                        NUMBER(9,0)      NULL
)
;

COMMENT ON TABLE bilancio
    IS 'BILA - Estremi di identificazione degli impegni di spesa in bilancio';


REM
REM 
REM
PROMPT
PROMPT Creating Index BILA_IK on Table BILANCIO
CREATE INDEX BILA_IK ON BILANCIO
(
      divisione ,
      esercizio ,
      e_s ,
      capitolo ,
      articolo ,
      gestione ,
      sede_del ,
      anno_del ,
      numero_del )
PCTFREE  10
;

REM
REM  End of command file
REM
