REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ASSEGNAZIONI_CONTABILI
REM INDEX
REM      ASCO_PK
REM      ASCO_RIFU_FK
REM      ASCO_SEDE_FK
REM      ASCO_SETT_FK

REM
REM     ASCO - Assegnazioni contabili diverse dalla assegnazione giuridica
REM
PROMPT 
PROMPT Creating Table ASSEGNAZIONI_CONTABILI
CREATE TABLE assegnazioni_contabili(
 ci                              NUMBER(8,0)      NOT NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 settore                         NUMBER(6,0)      NOT NULL,
 sede                            NUMBER(6,0)      NOT NULL,
 quota                           NUMBER(5,2)      NOT NULL,
 intero                          NUMBER(5,2)      NOT NULL,
 note                            VARCHAR(4000)    NULL,
 utente                          VARCHAR(8)       NULL,
 data_agg                        DATE             NULL
)
;

COMMENT ON TABLE assegnazioni_contabili
    IS 'ASCO - Assegnazioni contabili diverse dalla assegnazione giuridica';


REM
REM 
REM
PROMPT
PROMPT Creating Index ASCO_PK on Table ASSEGNAZIONI_CONTABILI
CREATE UNIQUE INDEX ASCO_PK ON ASSEGNAZIONI_CONTABILI
(
      ci ,
      dal ,
      settore ,
      sede )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ASCO_RIFU_FK on Table ASSEGNAZIONI_CONTABILI
CREATE INDEX ASCO_RIFU_FK ON ASSEGNAZIONI_CONTABILI
(
      settore ,
      sede )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ASCO_SEDE_FK on Table ASSEGNAZIONI_CONTABILI
CREATE INDEX ASCO_SEDE_FK ON ASSEGNAZIONI_CONTABILI
(
      sede )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ASCO_SETT_FK on Table ASSEGNAZIONI_CONTABILI
CREATE INDEX ASCO_SETT_FK ON ASSEGNAZIONI_CONTABILI
(
      settore )
PCTFREE  10
;


REM
REM  End of command file
REM
