REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      EQUIPE_STORICHE
REM INDEX
REM      EQST_EQIP_FK
REM      EQST_PK

REM
REM     EQST - Riferimento al periodo storico di definizione dell"equipe
REM
PROMPT 
PROMPT Creating Table EQUIPE_STORICHE
CREATE TABLE equipe_storiche(
 equipe                          VARCHAR(4)       NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sede                            NUMBER(6,0)      NULL
)
;

COMMENT ON TABLE equipe_storiche
    IS 'EQST - Riferimento al periodo storico di definizione dell"equipe';


REM
REM 
REM
PROMPT
PROMPT Creating Index EQST_EQIP_FK on Table EQUIPE_STORICHE
CREATE INDEX EQST_EQIP_FK ON EQUIPE_STORICHE
(
      equipe )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EQST_PK on Table EQUIPE_STORICHE
CREATE UNIQUE INDEX EQST_PK ON EQUIPE_STORICHE
(
      equipe ,
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
