REM  Objects being generated in this file are:-
REM TABLE
REM      TOTALI_DMA_Z1
REM INDEX
REM      TOZ1_PK ON 

REM
REM      TOZ1 - Totali Z1 Denuncia DMA
REM
PROMPT 
PROMPT Creating Table TOTALI_DMA_Z1

CREATE TABLE TOTALI_DMA_Z1
( ANNO                  NUMBER(4)	NOT NULL	
, MESE                  NUMBER(2)	NOT NULL
, CF_DIC                VARCHAR2(16)	NOT NULL
, CF_APP                VARCHAR2(16)	NOT NULL
, CF_VERS               VARCHAR2(16)    NOT NULL
, CASSA                 VARCHAR2(1)	NOT NULL
, TIPO_ALIQUOTA         NUMBER(1)	NOT NULL
, RIFERIMENTO           NUMBER(6)	NOT NULL
, NR_FILE               NUMBER(2)	NOT NULL
, IPN_PENS              NUMBER(14,2)
, CONTR_PENS            NUMBER(14,2)
, IPN_PENS_CN           NUMBER(14,2)
, CONTR_PENS_CN         NUMBER(14,2)
, IPN_PENS_SUD          NUMBER(14,2)
, CONTR_PENS_SUD        NUMBER(14,2)
, IPN_PENS_CN_407       NUMBER(14,2)
, CONTR_PENS_CN_407     NUMBER(14,2)
, IPN_PENS_SUD_407      NUMBER(14,2)
, CONTR_PENS_SUD_407    NUMBER(14,2)
, IPN_L135              NUMBER(14,2)
, CONTR_L135            NUMBER(14,2)
, IPN_SU_ECCEDENZA      NUMBER(14,2)
, CONTR_SU_ECCEDENZA    NUMBER(14,2)
, IPN_L166              NUMBER(14,2)
, CONTR_L166            NUMBER(14,2)
, IPN_TFS               NUMBER(14,2)
, CONTR_TFS             NUMBER(14,2)
, IPN_TFR               NUMBER(14,2)
, CONTR_TFR             NUMBER(14,2)
, ULT_IPN_TFR           NUMBER(14,2)
, CONTR_ULT_TFR         NUMBER(14,2)
, IPN_CASSA_CREDITO     NUMBER(14,2)
, CONTR_CASSA_CREDITO   NUMBER(14,2)
, IPN_ENPDEDP           NUMBER(14,2)
, CONTR_ENPDEDP         NUMBER(14,2)
, RISCATTO_PENS         NUMBER(14,2)
, RICONGIUNZIONE        NUMBER(14,2)
, RISCATTO_TFS          NUMBER(14,2)
, MUTUO                 NUMBER(14,2)
, PRESTITO              NUMBER(14,2)
, RISCATTO_TFR          NUMBER(14,2)
, SANZIONI              NUMBER(14,2)
, CONTR_SOSPESO         NUMBER(14,2)
, CONTR_CONGUAGLIO      NUMBER(14,2)
, UTENTE                VARCHAR2 (8) 
, TIPO_AGG              VARCHAR2 (1)
, DATA_AGG              DATE
);

COMMENT ON TABLE TOTALI_DMA_Z1
    IS 'TOZ1 - Totali per Record Z1 Denuncia DMA';

REM 
REM
PROMPT
PROMPT Creating Index TOZ1_PK on Table TOTALI_DMA_Z1
CREATE UNIQUE INDEX TOZ1_PK ON 
  TOTALI_DMA_Z1( ANNO, MESE, CF_DIC, CF_APP, CF_VERS, CASSA, TIPO_ALIQUOTA, RIFERIMENTO, NR_FILE)
; 

