REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VALORI_PROGRESSIONE_VOCE
REM INDEX
REM      VPVO_PK

REM
REM     VPVO - Importi delle voci tabellari a progressione
REM
PROMPT 
PROMPT Creating Table VALORI_PROGRESSIONE_VOCE
CREATE TABLE valori_progressione_voce(
 voce                            VARCHAR(10)      NOT NULL,
 contratto                       VARCHAR(4)       NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 livello                         VARCHAR(4)       NOT NULL,
 tipo_rapporto                   VARCHAR(4)       NOT NULL,
 periodo                         NUMBER(2,0)      NOT NULL,
 per_pro                         NUMBER(7,4)      NULL,
 imp_fis                         NUMBER(15,5)     NULL
)
;

COMMENT ON TABLE valori_progressione_voce
    IS 'VPVO - Importi delle voci tabellari a progressione';


REM
REM 
REM
PROMPT
PROMPT Creating Index VPVO_PK on Table VALORI_PROGRESSIONE_VOCE
CREATE UNIQUE INDEX VPVO_PK ON VALORI_PROGRESSIONE_VOCE
(
      voce ,
      contratto ,
      dal ,
      livello ,
      tipo_rapporto ,
      periodo )
PCTFREE  10
;

REM
REM  End of command file
REM
