SET SCAN OFF

REM TABLE
REM      SOSTITUZIONI_GIURIDICHE 
REM INDEX
REM      SOGI_PK
REM      SOGI_IK1
REM      SOGI_IK2
REM      SOGI_IK3
REM      SOGI_IK4
REM      SOGI_PEGI_FK

CREATE TABLE SOSTITUZIONI_GIURIDICHE 
( SOGI_ID                 NUMBER (10)   NOT NULL, 
  TITOLARE                NUMBER (8)    NOT NULL, 
  DAL_ASTENSIONE          DATE          NOT NULL, 
  RILEVANZA_ASTENSIONE    VARCHAR2 (1), 
  ORE_SOSTITUIBILI        NUMBER (5,2)  NOT NULL, 
  SOSTITUTO               NUMBER (8)    NOT NULL, 
  DAL                     DATE          NOT NULL, 
  AL                      DATE, 
  RILEVANZA_SOSTITUZIONE  VARCHAR2 (1), 
  ORE_SOSTITUZIONE        NUMBER (5,2)  NOT NULL,
  UTENTE		  vARCHAR2(8),
  DATA_AGG                DATE,
  NOTE                    VARCHAR2(4000)
);

CREATE UNIQUE INDEX SOGI_PK ON SOSTITUZIONI_GIURIDICHE 
(SOGI_ID);

CREATE INDEX SOGI_IK1 ON SOSTITUZIONI_GIURIDICHE 
(TITOLARE);

CREATE INDEX SOGI_IK2 ON SOSTITUZIONI_GIURIDICHE 
(SOSTITUTO, DAL);

CREATE INDEX SOGI_IK3 ON SOSTITUZIONI_GIURIDICHE 
(RILEVANZA_ASTENSIONE);

CREATE INDEX SOGI_IK4 ON SOSTITUZIONI_GIURIDICHE 
(SOSTITUTO, TITOLARE);

CREATE INDEX SOGI_PEGI_FK ON SOSTITUZIONI_GIURIDICHE 
(TITOLARE, DAL_ASTENSIONE);
