REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TRASFORMAZIONE_POSTI
REM INDEX
REM      TRPO_PK
REM      TRPO_POOR_IN_FK

REM
REM     TRPO - Identificazione della provenienza di un posto in organico
REM
PROMPT 
PROMPT Creating Table TRASFORMAZIONE_POSTI
CREATE TABLE trasformazione_posti(
 da_sede                         VARCHAR(4)       NOT NULL,
 da_anno                         NUMBER(4,0)      NOT NULL,
 da_numero                       NUMBER(7,0)      NOT NULL,
 da_posto                        NUMBER(4,0)      NOT NULL,
 in_sede                         VARCHAR(4)       NOT NULL,
 in_anno                         NUMBER(4,0)      NOT NULL,
 in_numero                       NUMBER(7,0)      NOT NULL,
 in_posto                        NUMBER(4,0)      NOT NULL
)
;

COMMENT ON TABLE trasformazione_posti
    IS 'TRPO - Identificazione della provenienza di un posto in organico';


REM
REM 
REM
PROMPT
PROMPT Creating Index TRPO_PK on Table TRASFORMAZIONE_POSTI
CREATE UNIQUE INDEX TRPO_PK ON TRASFORMAZIONE_POSTI
(
      da_sede ,
      da_anno ,
      da_numero ,
      da_posto ,
      in_sede ,
      in_anno ,
      in_numero ,
      in_posto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TRPO_POOR_IN_FK on Table TRASFORMAZIONE_POSTI
CREATE INDEX TRPO_POOR_IN_FK ON TRASFORMAZIONE_POSTI
(
      in_sede ,
      in_anno ,
      in_numero ,
      in_posto )
PCTFREE  10
;

REM
REM  End of command file
REM
