REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      SETTORI
REM INDEX
REM      SETT_GEST_FK
REM      SETT_IK
REM      SETT_PK
REM      SETT_SEDE_FK
REM      SETT_SETT_A_FK
REM      SETT_SETT_B_FK
REM      SETT_SETT_C_FK
REM      SETT_SETT_G_FK
REM      SETT_UK

REM
REM     SETT - Suddivisione settoriale nell"ambito delle gestioni dell"ente
REM
PROMPT 
PROMPT Creating Table SETTORI
CREATE TABLE settori(
 codice                          VARCHAR(15)      NOT NULL,
 descrizione                     VARCHAR(30)      NOT NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 numero                          NUMBER(8)      NOT NULL,
 sequenza                        NUMBER(6)      NULL,
 suddivisione                    NUMBER(1,0)      NOT NULL,
 gestione                        VARCHAR(8)       NOT NULL,
 settore_g                       NUMBER(8)      NULL,
 settore_a                       NUMBER(8)      NULL,
 settore_b                       NUMBER(8)      NULL,
 settore_c                       NUMBER(8)      NULL,
 assegnabile                     VARCHAR(2)       NOT NULL,
 sede                            NUMBER(8)      NULL,
 cod_reg                         VARCHAR(6)       NULL
)
;

COMMENT ON TABLE settori
    IS 'SETT - Suddivisione settoriale nell"ambito delle gestioni dell"ente';


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_GEST_FK on Table SETTORI
CREATE INDEX SETT_GEST_FK ON SETTORI
(
      gestione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_IK on Table SETTORI
CREATE INDEX SETT_IK ON SETTORI
(
      suddivisione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_PK on Table SETTORI
CREATE UNIQUE INDEX SETT_PK ON SETTORI
(
      numero )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_SEDE_FK on Table SETTORI
CREATE INDEX SETT_SEDE_FK ON SETTORI
(
      sede )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_SETT_A_FK on Table SETTORI
CREATE INDEX SETT_SETT_A_FK ON SETTORI
(
      settore_a )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_SETT_B_FK on Table SETTORI
CREATE INDEX SETT_SETT_B_FK ON SETTORI
(
      settore_b )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_SETT_C_FK on Table SETTORI
CREATE INDEX SETT_SETT_C_FK ON SETTORI
(
      settore_c )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_SETT_G_FK on Table SETTORI
CREATE INDEX SETT_SETT_G_FK ON SETTORI
(
      settore_g )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index SETT_UK on Table SETTORI
CREATE UNIQUE INDEX SETT_UK ON SETTORI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
