CREATE TABLE TOTALI_RETRIBUZIONI_INAIL ( 
  ANNO             NUMBER (4)    NOT NULL, 
  GESTIONE         VARCHAR2 (8)  NOT NULL, 
  RUOLO            VARCHAR2 (4), 
  POSIZIONE_INAIL  VARCHAR2 (4)  NOT NULL, 
  ESENZIONE        VARCHAR2 (4), 
  CAPITOLO         VARCHAR2 (14), 
  ARTICOLO         VARCHAR2 (14), 
  CONTO            VARCHAR2 (2), 
  FUNZIONALE       VARCHAR2 (8), 
  CDC              VARCHAR2 (8), 
  TIPO_IPN         VARCHAR2 (1)  NOT NULL, 
  IMPONIBILE       NUMBER, 
  PREMIO           NUMBER, 
  NUM_RECORD       NUMBER, 
  TOT_IMPONIBILE   NUMBER, 
  TOT_PREMIO       NUMBER)
  ; 


COMMENT ON TABLE TOTALI_RETRIBUZIONI_INAIL IS 'snapshot table for snapshot TOTALI_RETRIBUZIONI_INAIL';
