REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  09-FEB-94
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      IPOTESI_SPESA_INCENTIVO
REM INDEX
REM      ISIP_EIIP_FK
REM      ISIP_GRIP_FK
REM      ISIP_IK
REM      ISIP_PRIP_FK
REM      ISIP_QUAL_FK
REM      ISIP_RUOL_FK
REM      ISIP_SEDE_FK
REM      ISIP_SETT_FK
REM      ISIP_VEIP_FK

REM
REM     ISIP - Ipotesi di Spesa di Incentivazione della Produttivita`
REM
PROMPT 
PROMPT Creating Table IPOTESI_SPESA_INCENTIVO
CREATE TABLE ipotesi_spesa_incentivo(
 versione                        VARCHAR(4)       NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 note                            VARCHAR(240)     NULL,
 gruppo                          VARCHAR(2)       NOT NULL,
 settore                         NUMBER(6,0)      NOT NULL,
 sede                            NUMBER(6,0)      NOT NULL,
 equipe                          VARCHAR(4)       NOT NULL,
 progetto                        VARCHAR(8)       NOT NULL,
 ruolo                           VARCHAR(4)       NOT NULL,
 qualifica                       NUMBER(6,0)      NOT NULL,
 tipo_rapporto                   VARCHAR(4)       NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NOT NULL,
 tetto                           NUMBER(12,2)     NOT NULL,
 ore                             NUMBER(5,2)      NULL,
 importo                         NUMBER(12,2)     NULL
)
;

COMMENT ON TABLE ipotesi_spesa_incentivo
    IS 'ISIP - Ipotesi di Spesa di Incentivazione della Produttivita`';


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_EIIP_FK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_EIIP_FK ON IPOTESI_SPESA_INCENTIVO
(
      equipe )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_GRIP_FK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_GRIP_FK ON IPOTESI_SPESA_INCENTIVO
(
      gruppo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_IK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_IK ON IPOTESI_SPESA_INCENTIVO
(
      versione ,
      ci )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_PRIP_FK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_PRIP_FK ON IPOTESI_SPESA_INCENTIVO
(
      progetto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_QUAL_FK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_QUAL_FK ON IPOTESI_SPESA_INCENTIVO
(
      qualifica )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_RUOL_FK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_RUOL_FK ON IPOTESI_SPESA_INCENTIVO
(
      ruolo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_SEDE_FK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_SEDE_FK ON IPOTESI_SPESA_INCENTIVO
(
      sede )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_SETT_FK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_SETT_FK ON IPOTESI_SPESA_INCENTIVO
(
      settore )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISIP_VEIP_FK on Table IPOTESI_SPESA_INCENTIVO
CREATE INDEX ISIP_VEIP_FK ON IPOTESI_SPESA_INCENTIVO
(
      versione )
PCTFREE  10
;

REM
REM  End of command file
REM
