REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  06-DEC-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VALORI_PRESENZA
REM INDEX
REM      VAPA_PK
REM      VAPA_VOCO_FK

REM
REM     VAPA - Importi individuali delle causali a Valore
REM
PROMPT 
PROMPT Creating Table VALORI_PRESENZA
CREATE TABLE valori_presenza(
 evento                          NUMBER(10,0)     NOT NULL,
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL,
 operazione                      VARCHAR(1)       NOT NULL,
 tar                             NUMBER(15,5)     NULL,
 qta                             NUMBER(12,2)     NULL,
 imp                             NUMBER(12,2)     NULL,
 utente                          VARCHAR(8)       NULL,
 data_agg                        DATE             NULL
)
STORAGE    (INITIAL          3K)
;

COMMENT ON TABLE valori_presenza
    IS 'VAPA - Importi individuali delle causali a Valore';


REM
REM 
REM
PROMPT
PROMPT Creating Index VAPA_PK on Table VALORI_PRESENZA
CREATE INDEX VAPA_PK ON VALORI_PRESENZA
(
      evento ,
      voce ,
      sub )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VAPA_VOCO_FK on Table VALORI_PRESENZA
CREATE INDEX VAPA_VOCO_FK ON VALORI_PRESENZA
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
