CREATE TABLE ATTRIBUTI_GIURIDICI ( 
  ATGI_ID     NUMBER (10)   NOT NULL, 
  CI          NUMBER (8)    NOT NULL, 
  RILEVANZA   VARCHAR2 (1)  NOT NULL, 
  DAL         DATE          NOT NULL, 
  COAT_ID     NUMBER (10)   NOT NULL, 
  NOTE        VARCHAR2 (2000), 
  SEDE_DEL    VARCHAR2 (4), 
  ANNO_DEL    NUMBER (4), 
  NUMERO_DEL  NUMBER (8), 
  UTENTE      VARCHAR2 (8), 
  DATA_AGG    DATE)
; 


CREATE INDEX ATGI_COAT_FK ON 
  ATTRIBUTI_GIURIDICI(COAT_ID) 
; 

CREATE INDEX ATGI_PEGI_FK ON 
  ATTRIBUTI_GIURIDICI(CI, RILEVANZA, DAL) 
; 

CREATE UNIQUE INDEX ATGI_PK ON 
  ATTRIBUTI_GIURIDICI(ATGI_ID) 
; 



COMMENT ON TABLE ATTRIBUTI_GIURIDICI IS 'Attribuzioni aggiuntive al periodo giuridico';
