REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      IMPUTAZIONI_CONT_ECONOMICA
REM INDEX
REM      IMCE_IK

REM
REM    IMCE - Archivio di transito movimenti contabilita' economica in Bilancio
REM
PROMPT 
PROMPT Creating Table IMPUTAZIONI_CONT_ECONOMICA
CREATE TABLE imputazioni_cont_economica(
 data                            DATE             NOT NULL,
 azienda                         VARCHAR2(4)      NOT NULL,
 esercizio                       NUMBER (4,0)     NOT NULL,
 ruolo                           VARCHAR2(4)      NULL,
 contratto                       VARCHAR2(4)      NULL,
 funzionale                      VARCHAR2(8)      NULL,
 cdc                             VARCHAR2(8)      NULL,
 di_ruolo                        VARCHAR2(2)      NULL,
 conto                           VARCHAR2(14)     NOT NULL,
 d_a                             VARCHAR2(1)      NOT NULL,
 costo                           VARCHAR2(1)      NOT NULL,
 importo                         NUMBER (12,2)    NOT NULL,
 causale                         VARCHAR2(60)     NULL,
 mese                            number(2)        NOT NULL,
 mensilita                       VARCHAR2(4)      NOT NULL,
 inizio_competenza               DATE             NULL,
 fine_competenza                 DATE             NULL
)
;

COMMENT ON TABLE imputazioni_cont_economica
    IS 'IMCE - Archivio di transito movimenti contabilita'' economica in Bilancio';


REM
REM 
REM
REM 
REM

PROMPT
PROMPT Creating Index IMCE_IK on Table IMPUTAZIONI_CONT_ECONOMICA
CREATE INDEX IMCE_IK ON IMPUTAZIONI_CONT_ECONOMICA
(
      data,azienda )
PCTFREE  10
;

REM
REM  End of command file
REM
