REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-Apr-93 12:04
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VALORI_BASE_VOCE_BP
REM INDEX
REM      VBVP_CONT_FK
REM      VBVP_GEST_FK
REM      VBVP_PK

REM
REM    VBVP - Importi delle voci tabellari base per Bilancio di Previsione
REM
PROMPT 
PROMPT Creating Table VALORI_BASE_VOCE_BP
CREATE TABLE valori_base_voce_bp(
 voce                            VARCHAR (10)     NOT NULL,
 contratto                       VARCHAR (4)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 gestione                        VARCHAR (8)      NOT NULL,
 ruolo                           VARCHAR (4)      NOT NULL,
 livello                         VARCHAR (4)      NOT NULL,
 qualifica                       VARCHAR (8)      NOT NULL,
 tipo_rapporto                   VARCHAR (4)      NOT NULL,
 valore                          NUMBER (15,5)    NOT NULL
)
PCTFREE  10
PCTUSED  40
INITRANS 1
MAXTRANS 255
;

COMMENT ON TABLE valori_base_voce_bp
    IS 'VBVP - Importi delle voci tabellari base per Bilancio di Previsione';


REM
REM 
REM
REM 
REM

PROMPT
PROMPT Creating Index VBVP_CONT_FK on Table VALORI_BASE_VOCE_BP
CREATE INDEX VBVP_CONT_FK ON VALORI_BASE_VOCE_BP
(
      contratto )
PCTFREE  50
INITRANS 2
MAXTRANS 255
;


REM
REM 
REM
REM 
REM

PROMPT
PROMPT Creating Index VBVP_GEST_FK on Table VALORI_BASE_VOCE_BP
CREATE INDEX VBVP_GEST_FK ON VALORI_BASE_VOCE_BP
(
      gestione )
PCTFREE  50
INITRANS 2
MAXTRANS 255
;


REM
REM 
REM
REM 
REM

PROMPT
PROMPT Creating Index VBVP_PK on Table VALORI_BASE_VOCE_BP
CREATE UNIQUE INDEX VBVP_PK ON VALORI_BASE_VOCE_BP
(
      voce ,
      contratto ,
      dal ,
      gestione ,
      ruolo ,
      livello ,
      qualifica ,
      tipo_rapporto )
PCTFREE  50
INITRANS 2
MAXTRANS 255
;

REM
REM  End of command file
REM
