-- creazione della tabella cause_infortunio

CREATE TABLE CAUSE_INFORTUNIO ( 
  CAUSA        VARCHAR2 (6)  NOT NULL, 
  DESCRIZIONE  VARCHAR2 (120)  NOT NULL, 
  SEQUENZA     NUMBER(4), 
  SE_AGENTE    VARCHAR2 (2)  NOT NULL, 
  SE_SUB       VARCHAR2 (2)  NOT NULL, 
  SE_PARTE     VARCHAR2 (2)  NOT NULL, 
  STATISTICO   VARCHAR2 (6));

CREATE INDEX CAIN_PK ON CAUSE_INFORTUNIO 
(CAUSA )
;
