REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALENDARI
REM INDEX
REM      CALE_PK

REM
REM     CALE - Calendario delle giornate festive e feriali
REM
PROMPT 
PROMPT Creating Table CALENDARI
CREATE TABLE calendari(
 calendario                      VARCHAR(4)       NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 mese                            NUMBER(2,0)      NOT NULL,
 giorni                          VARCHAR(31)      NOT NULL
)
;

COMMENT ON TABLE calendari
    IS 'CALE - Calendario delle giornate festive e feriali';


REM
REM 
REM
PROMPT
PROMPT Creating Index CALE_PK on Table CALENDARI
CREATE UNIQUE INDEX CALE_PK ON CALENDARI
(
      calendario ,
      anno ,
      mese )
PCTFREE  10
;

REM
REM  End of command file
REM
