REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  01-DEC-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CLASSI_EVENTO
REM INDEX
REM      CLEV_PK

REM
REM     CLEV - Classi Evento di Presenza/Assenza
REM
PROMPT 
PROMPT Creating Table CLASSI_EVENTO
CREATE TABLE classi_evento(
 codice                          VARCHAR(8)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 qualificazione                  VARCHAR(1)       NOT NULL,
 tipo                            VARCHAR(1)       NOT NULL,
 gestione                        VARCHAR(1)       NOT NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL
)
;

COMMENT ON TABLE classi_evento
    IS 'CLEV - Classi Evento di Presenza/Assenza';


REM
REM 
REM
PROMPT
PROMPT Creating Index CLEV_PK on Table CLASSI_EVENTO
CREATE UNIQUE INDEX CLEV_PK ON CLASSI_EVENTO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
