REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RACCOLTA_MODULI
REM INDEX
REM      RAMO_PK

REM
REM     RAMO - Moduli di Raccolta Variabili caricati
REM
PROMPT 
PROMPT Creating Table RACCOLTA_MODULI
CREATE TABLE raccolta_moduli(
 modulo                          VARCHAR(4)       NOT NULL,
 cc                              VARCHAR(30)      NOT NULL,
 risorsa_intervento              VARCHAR(7)       NULL,
 capitolo                        VARCHAR(14)      NULL,
 articolo                        VARCHAR(14)      NULL,
 impegno                         NUMBER(5)        NULL,
 conto                           VARCHAR(2)       NULL,
 sede_del                        VARCHAR(4)       NULL,
 anno_del                        NUMBER(4)        NULL,
 numero_del                      NUMBER(7)        NULL,
 anno_impegno                    NUMBER(4)        NULL,
 sub_impegno                     NUMBER(5)        NULL,
 anno_sub_impegno                NUMBER(4)        NULL,
 codice_siope                    NUMBER(4)        NULL
)
;

COMMENT ON TABLE raccolta_moduli
    IS 'RAMO - Moduli di Raccolta Variabili caricati';


REM
REM 
REM
PROMPT
PROMPT Creating Index RAMO_PK on Table RACCOLTA_MODULI
CREATE UNIQUE INDEX RAMO_PK ON RACCOLTA_MODULI
(
      modulo ,
      cc )
PCTFREE  10
;

REM
REM  End of command file
REM
