PROMPT Creating Table KEY_ERROR_LOG
CREATE TABLE KEY_ERROR_LOG ( 
  ERROR_DATE      DATE, 
  ERROR_TEXT      VARCHAR2(2000), 
  ERROR_USER      VARCHAR2(8), 
  ERROR_USERTEXT  VARCHAR2(2000), 
  ERROR_TYPE      VARCHAR2(1), 
  ERROR_SESSION   NUMBER) 
/
PROMPT 
PROMPT Creating Table REGISTRO
CREATE TABLE REGISTRO ( 
  CHIAVE    VARCHAR2(512)  NOT NULL, 
  STRINGA   VARCHAR2(100)  NOT NULL, 
  COMMENTO  VARCHAR2(2000), 
  VALORE    VARCHAR2(2000), 
  CONSTRAINT REGISTRO_PK
  PRIMARY KEY ( CHIAVE, STRINGA ) )
/
PROMPT 
PROMPT Creating Table KEY_CONSTRAINT_ERROR
CREATE TABLE KEY_CONSTRAINT_ERROR ( 
  NOME         VARCHAR2(30)  NOT NULL, 
  TIPO_ERRORE  VARCHAR2(2)   NOT NULL, 
  ERRORE       VARCHAR2(6)   NOT NULL) 
/ 
CREATE UNIQUE INDEX KCER_PK ON 
  KEY_CONSTRAINT_ERROR(NOME, TIPO_ERRORE) 
/ 
PROMPT 
PROMPT Creating Table KEY_CONSTRAINT_TYPE
CREATE TABLE KEY_CONSTRAINT_TYPE ( 
  DB_ERROR     VARCHAR2(10)  NOT NULL, 
  TIPO_ERRORE  VARCHAR2(2)   NOT NULL) 
/
CREATE UNIQUE INDEX KCTY_PK ON 
  KEY_CONSTRAINT_TYPE(DB_ERROR) 
/
