CREATE TABLE ALIQUOTE_ESENZIONE_INAIL ( 
  ESENZIONE  VARCHAR2 (4)  NOT NULL, 
  ANNO       NUMBER (4)    NOT NULL, 
  ALIQUOTA   NUMBER (5,2)  NOT NULL, 
  UTENTE     VARCHAR2 (8), 
  DATA_AGG   DATE); 


PROMPT Creating Index AESI_PK on Table ALIQUOTE_ESENZIONE_INAIL
CREATE UNIQUE INDEX AESI_PK ON ALIQUOTE_ESENZIONE_INAIL
(ESENZIONE,ANNO )
;

CREATE INDEX AESI_ESIN_FK ON 
  ALIQUOTE_ESENZIONE_INAIL(ESENZIONE) 
; 

