REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      FIGURE
REM INDEX
REM      FIGU_PK

REM
REM     FIGU - Figure professionali o mansioni specifiche
REM
PROMPT 
PROMPT Creating Table FIGURE
CREATE TABLE figure(
 numero                          NUMBER(6,0)      NOT NULL,
 descrizione                     VARCHAR(120)     NULL,
 descrizione_al1                 VARCHAR(120)     NULL,
 descrizione_al2                 VARCHAR(120)     NULL,
 sequenza                        NUMBER(6,0)      NULL,
 fattore                         VARCHAR(6)       NULL,
 fattore_td                      VARCHAR(6)       NULL,
 des_abb			          VARCHAR2(20)    NULL
)
;

COMMENT ON TABLE figure
    IS 'FIGU - Figure professionali o mansioni specifiche';


REM
REM 
REM
PROMPT
PROMPT Creating Index FIGU_PK on Table FIGURE
CREATE UNIQUE INDEX FIGU_PK ON FIGURE
(
      numero )
PCTFREE  10
;

REM
REM  End of command file
REM
