CREATE TABLE CATEGORIE_ATTRIBUTI ( 
  CATEGORIA    VARCHAR2 (4)  NOT NULL, 
  DESCRIZIONE  VARCHAR2 (60)  NOT NULL, 
  NOTE         VARCHAR2 (2000), 
  SEQUENZA     NUMBER (6))
  ; 


CREATE UNIQUE INDEX CATEGORIE_ATTRIBUTI_PK ON 
  CATEGORIE_ATTRIBUTI(CATEGORIA) 
; 