REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  27-Mai-93 09:28
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      MOVIMENTI_BILANCIO_PREVISIONE
REM INDEX
REM      MOBP_IK

REM
REM    MOBP - Movimenti sintetici di Bilancio di Previsione
REM
PROMPT 
PROMPT Creating Table MOVIMENTI_BILANCIO_PREVISIONE
CREATE TABLE movimenti_bilancio_previsione(
 anno                            NUMBER (4,0)     NOT NULL,
 mese                            NUMBER (2,0)     NOT NULL,
 mensilita                       VARCHAR (3)      NOT NULL,
 divisione                       VARCHAR (4)      NULL,
 sezione                         VARCHAR (4)      NULL,
 gestione                        VARCHAR (8)      NULL,
 settore                         NUMBER (6,0)     NULL,
 sede                            NUMBER (6,0)     NULL,
 funzionale                      VARCHAR (8)      NULL,
 cdc                             VARCHAR (8)      NULL,
 ruolo                           VARCHAR (4)      NULL,
 di_ruolo                        VARCHAR(1)       NULL,
 livello                         VARCHAR (4)      NULL,
 contratto                       VARCHAR (4)      NULL,
 qualifica                       NUMBER (6,0)     NULL,
 tipo_rapporto                   VARCHAR (4)      NULL,
 ore                             NUMBER (5,2)     NULL,
 trattamento                     VARCHAR (4)      NULL,
 figura                          NUMBER (6,0)     NULL,
 attivita                        VARCHAR (4)      NULL,
 bilancio                        VARCHAR (2)      NULL,
 budget                          VARCHAR (4)      NULL,
 anno_rif                        NUMBER (4,0)     NULL,
 arr                             VARCHAR(1)       NULL,
 sede_del                        VARCHAR (4)      NULL,
 anno_del                        NUMBER (4,0)     NULL,
 numero_del                      NUMBER (7,0)     NULL,
 risorsa_intervento              VARCHAR(7)       NULL,
 capitolo                        VARCHAR(14)      NULL,
 articolo                        VARCHAR(14)      NULL,
 impegno                         NUMBER(5)        NULL,
 conto                           VARCHAR(2)       NULL,
 importo                         NUMBER (14,2)    NULL,
 imponibile                      NUMBER (17,5)    NULL,
 quantita                        NUMBER (12,2)    NULL,
 nr_voci                         NUMBER (5,0)     NULL,
 anno_impegno                    NUMBER(4)        NULL,
 sub_impegno                     NUMBER(5)        NULL,
 anno_sub_impegno                NUMBER(4)        NULL,
 codice_siope		         NUMBER(4)        NULL
)
PCTFREE  10
PCTUSED  40
INITRANS 1
MAXTRANS 255
;

COMMENT ON TABLE movimenti_bilancio_previsione
    IS 'MOBP - Movimenti sintetici di Bilancio di Previsione';


REM
REM 
REM
REM 
REM

PROMPT
PROMPT Creating Index MOBP_IK on Table MOVIMENTI_BILANCIO_PREVISIONE
CREATE INDEX MOBP_IK ON MOVIMENTI_BILANCIO_PREVISIONE
(
      anno ,
      mese ,
      mensilita )
PCTFREE  10
;

REM
REM  End of command file
REM
