REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONE_ELENCHI
REM INDEX
REM      ESEL_PK
REM      ESEL_VOCO_FK

REM
REM     ESEL - Parametri di estrazione degli Elenchi di dettaglio voci
REM
PROMPT 
PROMPT Creating Table ESTRAZIONE_ELENCHI
CREATE TABLE estrazione_elenchi(
 sequenza                        NUMBER(3,0)      NOT NULL,
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL,
 tariffa                         VARCHAR(2)       NOT NULL,
 quantita                        VARCHAR(2)       NOT NULL,
 importo                         VARCHAR(2)       NOT NULL,
 arr_mese                        VARCHAR(2)       NOT NULL,
 qta_pro                         VARCHAR(2)       NOT NULL,
 imp_pro                         VARCHAR(2)       NOT NULL,
 arr_pro                         VARCHAR(2)       NOT NULL,
 attiva                          VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE estrazione_elenchi
    IS 'ESEL - Parametri di estrazione degli Elenchi di dettaglio voci';


REM
REM 
REM
PROMPT
PROMPT Creating Index ESEL_PK on Table ESTRAZIONE_ELENCHI
CREATE UNIQUE INDEX ESEL_PK ON ESTRAZIONE_ELENCHI
(
      sequenza ,
      voce ,
      sub )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESEL_VOCO_FK on Table ESTRAZIONE_ELENCHI
CREATE INDEX ESEL_VOCO_FK ON ESTRAZIONE_ELENCHI
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
