REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  28-MAR-94
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DEPOSITO_EVENTI_PRESENZA

REM
REM     DEPA - Deposito Eventi giuridici di Assenza
REM
PROMPT 
PROMPT Creating Table DEPOSITO_EVENTI_PRESENZA
CREATE TABLE deposito_eventi_presenza(
 rilevanza                       VARCHAR(1)       NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 assenza                         VARCHAR(8)       NOT NULL,
 data                            DATE             NOT NULL,
 operazione                      VARCHAR(1)       NOT NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 errore                          NUMBER(2)        NULL,
 sede                            VARCHAR(4)       NULL,
 anno                            NUMBER(4)        NULL,
 numero                          NUMBER(7)        NULL,
 utente                          VARCHAR(8)       NULL,
 data_agg                        DATE             NULL
)
;

COMMENT ON TABLE deposito_eventi_presenza
    IS 'DEPA - Deposito Eventi giuridici di Assenza';

REM
REM  End of command file
REM
