REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  17-JUN-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DENUNCIA_O1_INPS
REM INDEX
REM      D1IS_GEST_FK
REM      D1IS_IK
REM      D1IS_RARE_FK

REM
REM     D1IS - Archivio Denuncia I.N.P.S. O1/M
REM
PROMPT 
PROMPT Creating Table DENUNCIA_O1_INPS
CREATE TABLE denuncia_o1_inps(
 anno                            NUMBER(4,0)      NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 gestione                        VARCHAR(8)       NOT NULL,
 provincia                       VARCHAR(3)       NULL,
 codice                          VARCHAR(10)      NULL,
 qualifica                       VARCHAR(1)       NULL,
 assicurazioni                   VARCHAR(1)       NULL,
 importo_cc                      NUMBER(12,2)     NULL,
 importo_ac                      NUMBER(12,2)     NULL,
 settimane                       NUMBER(2,0)      NULL,
 giorni                          NUMBER(3,0)      NULL,
 mesi                            VARCHAR(12)      NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 contratto                       VARCHAR(4)       NULL,
 livello                         VARCHAR(4)       NULL,
 data_cessazione                 DATE             NULL,
 tipo_rapporto                   VARCHAR(4)       NULL,
 trasf_rapporto                  VARCHAR(2)       NULL,
 sett_utili                      NUMBER(2,0)      NULL,
 importo_ap                      NUMBER(12,2)     NULL,
 nucleo_af                       NUMBER(2,0)      NULL,
 importo_af                      NUMBER(12,2)     NULL,
 rd_148                          VARCHAR(2)       NULL,
 tipo_c1                         VARCHAR(3)       NULL,
 dal_c1                          DATE             NULL,
 al_c1                           DATE             NULL,
 importo_c1                      NUMBER(12,2)     NULL,
 sett_c1                         NUMBER(2,0)      NULL,
 gg_r_c1                         NUMBER(3,0)      NULL,
 gg_u_c1                         NUMBER(3,0)      NULL,
 importo_pen_c1                  NUMBER(12,2)     NULL,
 gg_nr_c1                        NUMBER(3,0)      NULL,
 tipo_c2                         VARCHAR(3)       NULL,
 dal_c2                          DATE             NULL,
 al_c2                           DATE             NULL,
 importo_c2                      NUMBER(12,2)     NULL,
 sett_c2                         NUMBER(2,0)      NULL,
 gg_r_c2                         NUMBER(3,0)      NULL,
 gg_u_c2                         NUMBER(3,0)      NULL,
 importo_pen_c2                  NUMBER(12,2)     NULL,
 gg_nr_c2                        NUMBER(3,0)      NULL,
 tipo_c3                         VARCHAR(3)       NULL,
 dal_c3                          DATE             NULL,
 al_c3                           DATE             NULL,
 importo_c3                      NUMBER(12,2)     NULL,
 sett_c3                         NUMBER(2,0)      NULL,
 gg_r_c3                         NUMBER(3,0)      NULL,
 gg_u_c3                         NUMBER(3,0)      NULL,
 importo_pen_c3                  NUMBER(12,2)     NULL,
 gg_nr_c3                        NUMBER(3,0)      NULL,
 tipo_c4                         VARCHAR(3)       NULL,
 dal_c4                          DATE             NULL,
 al_c4                           DATE             NULL,
 importo_c4                      NUMBER(12,2)     NULL,
 sett_c4                         NUMBER(2,0)      NULL,
 gg_r_c4                         NUMBER(3,0)      NULL,
 gg_u_c4                         NUMBER(3,0)      NULL,
 importo_pen_c4                  NUMBER(12,2)     NULL,
 gg_nr_c4                        NUMBER(3,0)      NULL,
 sett_d                          NUMBER(2,0)      NULL,
 importo_rid_d                   NUMBER(12,2)     NULL,
 importo_cig_d                   NUMBER(12,2)     NULL,
 sett1_mal_d                     NUMBER(2,0)      NULL,
 sett2_mal_d                     NUMBER(2,0)      NULL,
 sett1_mat_d                     NUMBER(2,0)      NULL,
 sett2_mat_d                     NUMBER(2,0)      NULL,
 sett1_m88_d                     NUMBER(2,0)      NULL,
 sett2_m88_d                     NUMBER(2,0)      NULL,
 sett1_cig_d                     NUMBER(2,0)      NULL,
 sett2_cig_d                     NUMBER(2,0)      NULL,
 sett2_dds_d                     NUMBER(2,0)      NULL,
 utente                          VARCHAR(8)       NULL,
 tipo_agg                        VARCHAR(1)       NULL,
 data_agg                        DATE             NULL,
 tabella_af                      VARCHAR(3)       NULL,
 classe_af                       VARCHAR(3)       NULL,
 istituto                        VARCHAR(6)       NULL,
 tempo_pieno                     VARCHAR(2)       NULL,
 tempo_determinato               VARCHAR(2)       NULL,
 sett1_m53_d                     NUMBER(2)        NULL,
 sett2_m53_d                     NUMBER(2)        NULL,
 sett1_dl151_d                   NUMBER(2)        NULL,
 sett2_dl151_d                   NUMBER(2)        NULL
)
;

COMMENT ON TABLE denuncia_o1_inps
    IS 'D1IS - Archivio Denuncia I.N.P.S. O1/M';


REM
REM 
REM
PROMPT
PROMPT Creating Index D1IS_GEST_FK on Table DENUNCIA_O1_INPS
CREATE INDEX D1IS_GEST_FK ON DENUNCIA_O1_INPS
(
      gestione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index D1IS_IK on Table DENUNCIA_O1_INPS
CREATE INDEX D1IS_IK ON DENUNCIA_O1_INPS
(
      anno ,
      ci )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index D1IS_RARE_FK on Table DENUNCIA_O1_INPS
CREATE INDEX D1IS_RARE_FK ON DENUNCIA_O1_INPS
(
      ci )
PCTFREE  10
;

REM
REM  End of command file
REM
