REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      FORMULA_CAUSALI
REM INDEX
REM      FOCA_PK

REM
REM     FOCA - Formula di calcolo del valore da attribuire alle causali
REM
PROMPT 
PROMPT Creating Table FORMULA_CAUSALI
CREATE TABLE formula_causali(
 codice                          VARCHAR(8)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL
)
;

COMMENT ON TABLE formula_causali
    IS 'FOCA - Formula di calcolo del valore da attribuire alle causali';


REM
REM 
REM
PROMPT
PROMPT Creating Index FOCA_PK on Table FORMULA_CAUSALI
CREATE UNIQUE INDEX FOCA_PK ON FORMULA_CAUSALI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
