REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      EVENTI_GIURIDICI
REM INDEX
REM      EVGI_PK
REM      EVGI_POSI_FK

REM
REM     EVGI - Eventi e motivazioni che identificano periodi e documenti giurid
REM - ici
REM
PROMPT 
PROMPT Creating Table EVENTI_GIURIDICI
CREATE TABLE eventi_giuridici(
 codice                          VARCHAR(6)       NOT NULL,
 descrizione                     VARCHAR(120)     NULL,
 descrizione_al1                 VARCHAR(120)     NULL,
 descrizione_al2                 VARCHAR(120)     NULL,
 sequenza                        NUMBER(3,0)      NULL,
 delibera                        VARCHAR(2)       NOT NULL,
 certificabile                   VARCHAR(2)       NOT NULL,
 presso                          VARCHAR(2)       NOT NULL,
 stato_servizio                  VARCHAR(2)       NOT NULL,
 rilevanza                       VARCHAR(1)       NOT NULL,
 posizione                       VARCHAR(4)       NULL,
 unico                           VARCHAR(2)       NOT NULL,
 conto_annuale                   NUMBER(2,0)      NULL,
 cert_sett                       VARCHAR(2)       default 'NO' NOT NULL,
 onaosi                          NUMBER(2)        NULL,
 inps                            VARCHAR2(3)      NULL
)
;

COMMENT ON TABLE eventi_giuridici
    IS 'EVGI - Eventi e motivazioni che identificano periodi e documenti giuridici';


REM
REM 
REM
PROMPT
PROMPT Creating Index EVGI_PK on Table EVENTI_GIURIDICI
CREATE UNIQUE INDEX EVGI_PK ON EVENTI_GIURIDICI
(
      codice )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVGI_POSI_FK on Table EVENTI_GIURIDICI
CREATE INDEX EVGI_POSI_FK ON EVENTI_GIURIDICI
(
      posizione )
PCTFREE  10
;

REM
REM  End of command file
REM
