REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CODICI_BILANCIO
REM INDEX
REM      COBI_CLBU_FK
REM      COBI_ISCR_FK
REM      COBI_PK

REM
REM     COBI - Codici di ripartizione economica della spesa in bilancio
REM
PROMPT 
PROMPT Creating Table CODICI_BILANCIO
CREATE TABLE codici_bilancio(
 codice                          VARCHAR(2)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 tipo                            VARCHAR(1)       NOT NULL,
 costo                           VARCHAR(1)       NULL,
 budget                          VARCHAR(4)       NULL,
 istituto                        VARCHAR(5)       NULL,
 allegato                        VARCHAR(1)       NULL,
 bilancio_lordo                  VARCHAR(2)       NULL, 
 IMPUTAZIONE_MENSILE  		 VARCHAR2(2)      DEFAULT 'SI' null,
 IMPUTAZIONE_DELIBERA            varchar2(2)      null,
 NOTE                            VARCHAR2(4000)   NULL,
 NOTE_AL1                        VARCHAR2(4000)   NULL,
 NOTE_AL2                        VARCHAR2(4000)   NULL
)
;

COMMENT ON TABLE codici_bilancio
    IS 'COBI - Codici di ripartizione economica della spesa in bilancio';


REM
REM 
REM
PROMPT
PROMPT Creating Index COBI_CLBU_FK on Table CODICI_BILANCIO
CREATE INDEX COBI_CLBU_FK ON CODICI_BILANCIO
(
      budget )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index COBI_ISCR_FK on Table CODICI_BILANCIO
CREATE INDEX COBI_ISCR_FK ON CODICI_BILANCIO
(
      istituto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index COBI_PK on Table CODICI_BILANCIO
CREATE UNIQUE INDEX COBI_PK ON CODICI_BILANCIO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
