CREATE TABLE STAMPANTI_BADGE
(
  STAMPANTE    VARCHAR2(100),
  DESCRIZIONE  VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX STAMPANTI_BADGE_PK ON STAMPANTI_BADGE
(STAMPANTE)
LOGGING
NOPARALLEL;