REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      APPOGGIO_CERTIFICATI     

REM
REM     ACER - Tavola di appoggio per l'elaborazione dei certificati di  
REM            servizio.               
REM
PROMPT 
PROMPT Creating Table APPOGGIO_CERTIFICATI
CREATE TABLE appoggio_certificati (
 prenotazione                    NUMBER(6,0)      NOT NULL,
 progressivo                     NUMBER(4,0)      NOT NULL,
 ci                              NUMBER(8,0)      NULL,
 decorrenza                      DATE             NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 rientri                         number(2)        NULL,
 lung_riga                       number(2)        NOT NULL,
 testo                           LONG             NULL 
)
;

COMMENT ON TABLE appoggio_certificati
    IS 'ACER - Tavola di appoggio per certificati di servizio';  

REM
REM  End of command file
REM
