REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  16-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      MOTIVI_EVENTO
REM INDEX
REM      MOEV_PK

REM
REM     Created from Entity MOTIVO EVENTO by P00 on 10-NOV-93
REM
PROMPT 
PROMPT Creating Table MOTIVI_EVENTO
CREATE TABLE motivi_evento(
 codice                          VARCHAR(8)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 istat                           NUMBER(6)        NULL
)
;

COMMENT ON TABLE motivi_evento
    IS 'Created from Entity MOTIVO EVENTO by P00 on 10-NOV-93';


REM
REM 
REM
PROMPT
PROMPT Creating Index MOEV_PK on Table MOTIVI_EVENTO
CREATE UNIQUE INDEX MOEV_PK ON MOTIVI_EVENTO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
