REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-NOV-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VALIDITA_QUALIFICA_MINISTERO
REM INDEX
REM      VQMI_PK

REM
REM     VQMI - Periodi di validita Qualifiche Ministero
REM
PROMPT 
PROMPT Creating Table VALIDITA_QUALIFICA_MINISTERO
CREATE TABLE validita_qualifica_ministero(
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 note                            VARCHAR(240)     NULL
)
;

COMMENT ON TABLE validita_qualifica_ministero
    IS 'VQMI - Periodi di validita Qualifiche Ministeriali';


REM
REM 
REM
PROMPT
PROMPT Creating Index VQMI_PK on Table VALIDITA_QUALIFICA_MINISTERO
CREATE UNIQUE INDEX VQMI_PK ON VALIDITA_QUALIFICA_MINISTERO
(
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
