REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TESTI_FORMULA
REM INDEX
REM      TEFO_GRLI_FK
REM      TEFO_PK

REM
REM     TEFO - Righe di testo preformattato delle formule da includere nei cert
REM - ificati
REM
PROMPT 
PROMPT Creating Table TESTI_FORMULA
CREATE TABLE testi_formula(
 formula                         VARCHAR(4)       NOT NULL,
 gruppo_ling                     VARCHAR(4)       NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 testo                           VARCHAR(75)      NULL
)
;

COMMENT ON TABLE testi_formula
    IS 'TEFO - Righe di testo preformattato delle formule da includere nei certificati';


REM
REM 
REM
PROMPT
PROMPT Creating Index TEFO_GRLI_FK on Table TESTI_FORMULA
CREATE INDEX TEFO_GRLI_FK ON TESTI_FORMULA
(
      gruppo_ling )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TEFO_PK on Table TESTI_FORMULA
CREATE UNIQUE INDEX TEFO_PK ON TESTI_FORMULA
(
      formula ,
      gruppo_ling ,
      sequenza )
PCTFREE  10
;

REM
REM  End of command file
REM
