REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONI_VOCE
REM INDEX
REM      ESVO_CONT_FK
REM      ESVO_GEST_FK
REM      ESVO_PK
REM      ESVO_TRPR_FK

REM
REM     ESVO - Condizioni di estrazione automatica delle voci contabili
REM
PROMPT 
PROMPT Creating Table ESTRAZIONI_VOCE
CREATE TABLE estrazioni_voce(
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL,
 gestione                        VARCHAR(8)       NOT NULL,
 contratto                       VARCHAR(4)       NOT NULL,
 condizione                      VARCHAR(4)       NOT NULL,
 trattamento                     VARCHAR(4)       NOT NULL,
 sequenza                        NUMBER(3,0)      NULL,
 richiesta                       VARCHAR(1)       NOT NULL
)
;

COMMENT ON TABLE estrazioni_voce
    IS 'ESVO - Condizioni di estrazione automatica delle voci contabili';


REM
REM 
REM
PROMPT
PROMPT Creating Index ESVO_CONT_FK on Table ESTRAZIONI_VOCE
CREATE INDEX ESVO_CONT_FK ON ESTRAZIONI_VOCE
(
      contratto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESVO_GEST_FK on Table ESTRAZIONI_VOCE
CREATE INDEX ESVO_GEST_FK ON ESTRAZIONI_VOCE
(
      gestione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESVO_PK on Table ESTRAZIONI_VOCE
CREATE UNIQUE INDEX ESVO_PK ON ESTRAZIONI_VOCE
(
      voce ,
      sub ,
      gestione ,
      contratto ,
      condizione ,
      trattamento )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESVO_TRPR_FK on Table ESTRAZIONI_VOCE
CREATE INDEX ESVO_TRPR_FK ON ESTRAZIONI_VOCE
(
      trattamento )
PCTFREE  10
;

REM
REM  End of command file
REM
