REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ASSEGNAZIONI_INCENTIVO
REM INDEX
REM      ASIP_PK
REM      ASIP_RAGI_FK

REM
REM     ASIP - Assegnazioni individuali a progetti di incentivo
REM
PROMPT 
PROMPT Creating Table ASSEGNAZIONI_INCENTIVO
CREATE TABLE assegnazioni_incentivo(
 progetto                        VARCHAR(8)       NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 ore_ind                         NUMBER(5,2)      NULL,
 importo                         NUMBER(12,2)       NULL,
 perc_ragg                       NUMBER(5,2)      NULL,
 note                            VARCHAR(240)     NULL,
 utente                          VARCHAR(8)       NULL,
 data_agg                        DATE             NULL
)
;

COMMENT ON TABLE assegnazioni_incentivo
    IS 'ASIP - Assegnazioni individuali a progetti di incentivo';


REM
REM 
REM
PROMPT
PROMPT Creating Index ASIP_PK on Table ASSEGNAZIONI_INCENTIVO
CREATE INDEX ASIP_PK ON ASSEGNAZIONI_INCENTIVO
(
      progetto ,
      ci ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ASIP_RAGI_FK on Table ASSEGNAZIONI_INCENTIVO
CREATE INDEX ASIP_RAGI_FK ON ASSEGNAZIONI_INCENTIVO
(
      ci )
PCTFREE  10
;

REM
REM  End of command file
REM
