REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      QUALIFICHE_INCENTIVO
REM INDEX
REM      QUIP_GRIP_FK
REM      QUIP_PK

REM
REM     QUIP - Attributi di incentivazione delle qualifiche retributive
REM
PROMPT 
PROMPT Creating Table QUALIFICHE_INCENTIVO
CREATE TABLE qualifiche_incentivo(
 numero                          NUMBER(6,0)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 gruppo                          VARCHAR(2)       NOT NULL,
 max_plus                        NUMBER(5,2)      NULL,
 max_plus_td                     NUMBER(5,2)      NULL,
 tetto_base                      NUMBER(12,2)     NULL,
 tetto_base_td                   NUMBER(12,2)     NULL
)
;

COMMENT ON TABLE qualifiche_incentivo
    IS 'QUIP - Attributi di incentivazione delle qualifiche retributive';


REM
REM 
REM
PROMPT
PROMPT Creating Index QUIP_GRIP_FK on Table QUALIFICHE_INCENTIVO
CREATE INDEX QUIP_GRIP_FK ON QUALIFICHE_INCENTIVO
(
      gruppo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index QUIP_PK on Table QUALIFICHE_INCENTIVO
CREATE INDEX QUIP_PK ON QUALIFICHE_INCENTIVO
(
      numero ,
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
