REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VOCI_INAIL
REM INDEX
REM      VOIN_PK
REM      VOIN_VOCO_FK

REM
REM     VOIN - Voci retributive abbinate alle posizioni assicurative INAIL
REM
PROMPT 
PROMPT Creating Table VOCI_INAIL
CREATE TABLE voci_inail(
 codice                          VARCHAR(4)       NOT NULL,
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE voci_inail
    IS 'VOIN - Voci retributive abbinate alle posizioni assicurative INAIL';


REM
REM 
REM
PROMPT
PROMPT Creating Index VOIN_PK on Table VOCI_INAIL
CREATE UNIQUE INDEX VOIN_PK ON VOCI_INAIL
(
      codice ,
      voce ,
      sub )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VOIN_VOCO_FK on Table VOCI_INAIL
CREATE INDEX VOIN_VOCO_FK ON VOCI_INAIL
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
