REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  06-SEP-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      MOVIMENTI_INCENTIVO
REM INDEX
REM      MOIP_GRIP_FK
REM      MOIP_IK
REM      MOIP_MESE_FK
REM      MOIP_RAGI_FK
REM      MOIP_RUOL_FK

REM
REM     MOIP - Registrazioni contabili dei movimenti di incentivo individuali p
REM - er periodi di competenza.
REM
PROMPT 
PROMPT Creating Table MOVIMENTI_INCENTIVO
CREATE TABLE movimenti_incentivo(
 progetto                        VARCHAR(8)       NOT NULL,
 scp                             VARCHAR(4)       NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 periodo                         DATE             NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 mese                            NUMBER(2,0)      NOT NULL,
 equipe                          VARCHAR(4)       NULL,
 gruppo                          VARCHAR(2)       NULL,
 dal                             DATE             NULL,
 ruolo                           VARCHAR(4)       NULL,
 qualifica                       NUMBER(6,0)      NULL,
 tipo_rapporto                   VARCHAR(4)       NULL,
 sede                            NUMBER(6,0)      NULL,
 settore                         NUMBER(6,0)      NULL,
 giorni                          NUMBER(2,0)      NULL,
 calcolo                         VARCHAR(1)       NULL,
 ore                             NUMBER(5,2)      NULL,
 importo                         NUMBER(12,2)     NULL,
 liquidato                       NUMBER(12,2)     NULL,
 saldo                           NUMBER(12,2)     NULL,
 da_liquidare                    NUMBER(12,2)     NULL,
 ruolo_impegno                   VARCHAR(4)       NULL,
 sequenza_impegno                NUMBER(3,0)      NULL,
 anno_cdc                        NUMBER(4,0)      NULL,
 trim_cdc                        NUMBER(2,0)      NULL,
 perc_ragg                       NUMBER(5,2)      NULL
)
;

COMMENT ON TABLE movimenti_incentivo
    IS 'MOIP - Registrazioni contabili dei movimenti di incentivo individuali per periodi di competenza.';


REM
REM 
REM
PROMPT
PROMPT Creating Index MOIP_GRIP_FK on Table MOVIMENTI_INCENTIVO
CREATE INDEX MOIP_GRIP_FK ON MOVIMENTI_INCENTIVO
(
      gruppo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index MOIP_IK on Table MOVIMENTI_INCENTIVO
CREATE INDEX MOIP_IK ON MOVIMENTI_INCENTIVO
(
      progetto ,
      scp ,
      periodo ,
      ci )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index MOIP_MESE_FK on Table MOVIMENTI_INCENTIVO
CREATE INDEX MOIP_MESE_FK ON MOVIMENTI_INCENTIVO
(
      anno ,
      mese )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index MOIP_RAGI_FK on Table MOVIMENTI_INCENTIVO
CREATE INDEX MOIP_RAGI_FK ON MOVIMENTI_INCENTIVO
(
      ci )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index MOIP_RUOL_FK on Table MOVIMENTI_INCENTIVO
CREATE INDEX MOIP_RUOL_FK ON MOVIMENTI_INCENTIVO
(
      ruolo )
PCTFREE  10
;

REM
REM  End of command file
REM
