CREATE TABLE CONTRIBUTI_INAIL
 ( 
  ANNO       NUMBER (4)       NOT NULL, 
  CI         NUMBER (8)       NOT NULL, 
  VOCE       VARCHAR2 (10)    NOT NULL, 
  SUB        VARCHAR2 (2)     NOT NULL, 
  MESE       NUMBER (2)               , 
  POSIZIONE  VARCHAR2 (4)     NOT NULL, 
  RUOLO      VARCHAR2 (4)             , 
  IPN        NUMBER
)
  STORAGE ( 
   INITIAL 3000 K
   NEXT 1000 K
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 12 )
;
CREATE INDEX COIN_IK ON 
  CONTRIBUTI_INAIL(ANNO, POSIZIONE, RUOLO) 
  STORAGE(INITIAL 1000 K NEXT 1000 K PCTINCREASE 50 ) 
; 
