REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PAM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CLASSI_RAPPORTO
REM INDEX
REM      CLRA_PK

REM
REM     CLRA - Classi di rapporto individuale con l"ente
REM
PROMPT 
PROMPT Creating Table CLASSI_RAPPORTO
CREATE TABLE classi_rapporto(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 retributivo                     VARCHAR(2)       NOT NULL,
 presenza                        VARCHAR(2)       NOT NULL,
 giuridico                       VARCHAR(2)       NOT NULL,
 concorso                        VARCHAR(2)       NOT NULL,
 cat_fiscale                     VARCHAR(2)       NULL,
 cat_inail                       VARCHAR(2)       NULL,
 vortale                         VARCHAR(2)       DEFAULT 'SI' NOT NULL,
 dotazione                       varchar2(2)      DEFAULT 'SI' NOT NULL,
 tipo_compenso                   VARCHAR(15)       NULL,
 tipo_compenso_AL1                   VARCHAR(15)       NULL,
 tipo_compenso_AL2                   VARCHAR(15)       NULL
)
;

COMMENT ON TABLE classi_rapporto
    IS 'CLRA - Classi di rapporto individuale con l"ente';


REM
REM 
REM
PROMPT
PROMPT Creating Index CLRA_PK on Table CLASSI_RAPPORTO
CREATE UNIQUE INDEX CLRA_PK ON CLASSI_RAPPORTO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
