REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TIPI_CALENDARIO
REM INDEX
REM      TICA_PK

REM
REM     TICA - Tipi di calendario applicabili sulle sedi di lavoro
REM
PROMPT 
PROMPT Creating Table TIPI_CALENDARIO
CREATE TABLE tipi_calendario(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL
)
;

COMMENT ON TABLE tipi_calendario
    IS 'TICA - Tipi di calendario applicabili sulle sedi di lavoro';


REM
REM 
REM
PROMPT
PROMPT Creating Index TICA_PK on Table TIPI_CALENDARIO
CREATE UNIQUE INDEX TICA_PK ON TIPI_CALENDARIO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
