REM
SET SCAN OFF

REM TABLE
REM     SMT_INDIVIDUI
REM INDEX
REM     SMIN_PK

REM
REM     SMIN - SMT Individui 
REM
PROMPT 
PROMPT Creating Table SMT_INDIVIDUI
CREATE TABLE SMT_INDIVIDUI
( ANNO	            NUMBER(4)   NOT NULL
, CI	            NUMBER(8)   NOT NULL
, GESTIONE	    VARCHAR2(8) NOT NULL
, SESSO	            VARCHAR2(1)
, ETA	            NUMBER(3)
, ANZIANITA	    NUMBER(3)
, ANZIANITA_MM	    NUMBER(3)
, ANZIANITA_GG	    NUMBER(4)
, ANZIANITA_PREC    NUMBER(3)
, ANZIANITA_PREC_MM NUMBER(3)
, ANZIANITA_PREC_GG NUMBER(4)
, INT_COMANDATO	    VARCHAR2(2)
, INT_FUORI_RUOLO   VARCHAR2(2)
, EST_COMANDATO	    VARCHAR2(2)
, EST_FUORI_RUOLO   VARCHAR2(2)
, UTENTE	    VARCHAR2(8)
, TIPO_AGG	    VARCHAR2(1)
, DATA_AGG	    DATE
)
;

COMMENT ON TABLE SMT_INDIVIDUI
    IS 'SMIN - SMT Individui ';

REM
REM 
REM
PROMPT
PROMPT Creating Index DECP_RARE_FK on Table DENUNCIA_CP
CREATE UNIQUE INDEX SMIN_PK ON 
  SMT_INDIVIDUI(ANNO, GESTIONE, CI) 
PCTFREE  10
;

REM
REM  End of command file
REM