REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RELAZIONE_RIFE_OGGETTO
REM INDEX
REM      RERO_PK
REM      RERO_REOG_RIF_FK

REM
REM     RERO - Relazione tra gli oggetti delle Estrazioni Parametriche
REM
PROMPT 
PROMPT Creating Table RELAZIONE_RIFE_OGGETTO
CREATE TABLE relazione_rife_oggetto(
 oggetto                         VARCHAR(10)      NOT NULL,
 riferimento                     VARCHAR(10)      NOT NULL
)
;

COMMENT ON TABLE relazione_rife_oggetto
    IS 'RERO - Relazione tra gli oggetti delle Estrazioni Parametriche';


REM
REM 
REM
PROMPT
PROMPT Creating Index RERO_PK on Table RELAZIONE_RIFE_OGGETTO
CREATE UNIQUE INDEX RERO_PK ON RELAZIONE_RIFE_OGGETTO
(
      oggetto ,
      riferimento )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RERO_REOG_RIF_FK on Table RELAZIONE_RIFE_OGGETTO
CREATE INDEX RERO_REOG_RIF_FK ON RELAZIONE_RIFE_OGGETTO
(
      riferimento )
PCTFREE  10
;

REM
REM  End of command file
REM
