REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RELAZIONE_ATTR_ESTRAZIONE
REM INDEX
REM      REAE_PK
REM      REAE_REAT_FK

REM
REM     REAE - Attributi richiesti dalle Estrazioni Parametriche
REM
PROMPT 
PROMPT Creating Table RELAZIONE_ATTR_ESTRAZIONE
CREATE TABLE relazione_attr_estrazione(
 estrazione                      VARCHAR(20)      NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 attributo                       VARCHAR(20)      NOT NULL,
 alias                           VARCHAR(20)      NOT NULL,
 descrizione                     VARCHAR(60)      NULL,
 descrizione_al1                 VARCHAR(60)      NULL,
 descrizione_al2                 VARCHAR(60)      NULL
)
;

COMMENT ON TABLE relazione_attr_estrazione
    IS 'REAE - Attributi richiesti dalle Estrazioni Parametriche';


REM
REM 
REM
PROMPT
PROMPT Creating Index REAE_PK on Table RELAZIONE_ATTR_ESTRAZIONE
CREATE UNIQUE INDEX REAE_PK ON RELAZIONE_ATTR_ESTRAZIONE
(
      estrazione ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index REAE_REAT_FK on Table RELAZIONE_ATTR_ESTRAZIONE
CREATE INDEX REAE_REAT_FK ON RELAZIONE_ATTR_ESTRAZIONE
(
      attributo )
PCTFREE  10
;

REM
REM  End of command file
REM
