REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ISTITUTI_CREDITO
REM INDEX
REM      ISCR_PK
REM      ISCR_SOGG_FK

REM
REM     ISCR - Istituti di credito e identificativi di soggetti fiscali
REM
PROMPT 
PROMPT Creating Table ISTITUTI_CREDITO
CREATE TABLE istituti_credito(
  CODICE           VARCHAR2(5)                   NOT NULL,
  DESCRIZIONE      VARCHAR2(30)                      NULL,
  DESCRIZIONE_AL1  VARCHAR2(30)                      NULL,
  DESCRIZIONE_AL2  VARCHAR2(30)                      NULL,
  SOGGETTO         NUMBER(9)                         NULL,
  CODICE_ABI       VARCHAR2(5)                       NULL,
  CODICE_CAB       VARCHAR2(5)                       NULL,
  NUM_QUIETANZA    NUMBER(2)                         NULL,
  PRONTA_CASSA     VARCHAR2(2)      DEFAULT 'NO' NOT NULL,
  NOTE             VARCHAR2(4000)                    NULL,
  NOTE_AL1         VARCHAR2(4000)                    NULL,
  NOTE_AL2         VARCHAR2(4000)                    NULL
)
;

COMMENT ON TABLE istituti_credito
    IS 'ISCR - Istituti di credito e identificativi di soggetti fiscali';


REM
REM 
REM
PROMPT
PROMPT Creating Index ISCR_PK on Table ISTITUTI_CREDITO
CREATE UNIQUE INDEX ISCR_PK ON ISTITUTI_CREDITO
(
      codice )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ISCR_SOGG_FK on Table ISTITUTI_CREDITO
CREATE INDEX ISCR_SOGG_FK ON ISTITUTI_CREDITO
(
      soggetto )
PCTFREE  10
;

REM
REM  End of command file
REM
