REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  04-AUG-94
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLO_POSTI
REM INDEX
REM      CAPON_IK

REM
REM     CAPO - Tabella di servizio per prospetti di Pianta Organica
REM
PROMPT 
PROMPT Creating Table CALCOLO_POSTI
CREATE TABLE calcolo_posti(
 capo_prenotazione               NUMBER(6,0)      NOT NULL,
 capo_rilevanza                  NUMBER(2,0)      NOT NULL,
 capo_lingue                     VARCHAR(3)       NULL,
 rior_data                       DATE             NOT NULL,
 popi_sede_posto                 VARCHAR(4)       NULL,
 popi_anno_posto                 NUMBER(4,0)      NULL,
 popi_numero_posto               NUMBER(7,0)      NULL,
 popi_posto                      NUMBER(5,0)      NULL,
 popi_gruppo                     VARCHAR(12)      NULL,
 popi_dal                        DATE             NULL,
 popi_ricopribile                VARCHAR(1)       NULL,
 popi_pianta                     NUMBER(6,0)      NULL,
 setp_sequenza                   NUMBER(6,0)      NULL,
 setp_codice                     VARCHAR(15)      NULL,
 popi_settore                    NUMBER(6,0)      NULL,
 sett_sequenza                   NUMBER(6,0)      NULL,
 sett_codice                     VARCHAR(15)      NULL,
 sett_suddivisione               NUMBER(1,0)      NULL,
 sett_settore_g                  NUMBER(6,0)      NULL,
 setg_sequenza                   NUMBER(6,0)      NULL,
 setg_codice                     VARCHAR(15)      NULL,
 sett_settore_a                  NUMBER(6,0)      NULL,
 seta_sequenza                   NUMBER(6,0)      NULL,
 seta_codice                     VARCHAR(15)      NULL,
 sett_settore_b                  NUMBER(6,0)      NULL,
 setb_sequenza                   NUMBER(6,0)      NULL,
 setb_codice                     VARCHAR(15)      NULL,
 sett_settore_c                  NUMBER(6,0)      NULL,
 setc_sequenza                   NUMBER(6,0)      NULL,
 setc_codice                     VARCHAR(15)      NULL,
 sett_gestione                   VARCHAR(4)       NULL,
 gest_prospetto_po               VARCHAR(1)       NULL,
 gest_sintetico_po               VARCHAR(1)       NULL,
 popi_figura                     NUMBER(6,0)      NULL,
 figi_dal                        DATE             NULL,
 figu_sequenza                   NUMBER(6,0)      NULL,
 figi_codice                     VARCHAR(8)       NULL,
 figi_qualifica                  NUMBER(6,0)      NULL,
 qugi_dal                        DATE             NULL,
 qual_sequenza                   NUMBER(6,0)      NULL,
 qugi_codice                     VARCHAR(8)       NULL,
 qugi_contratto                  VARCHAR(4)       NULL,
 cost_dal                        DATE             NULL,
 cont_sequenza                   NUMBER(3,0)      NULL,
 cost_ore_lavoro                 NUMBER(5,2)      NULL,
 qugi_livello                    VARCHAR(4)       NULL,
 figi_profilo                    VARCHAR(4)       NULL,
 prpr_sequenza                   NUMBER(3,0)      NULL,
 prpr_suddivisione_po            VARCHAR(1)       NULL,
 figi_posizione                  VARCHAR(4)       NULL,
 pofu_sequenza                   NUMBER(3,0)      NULL,
 qugi_ruolo                      VARCHAR(4)       NULL,
 ruol_sequenza                   NUMBER(3,0)      NULL,
 popi_attivita                   VARCHAR(4)       NULL,
 atti_sequenza                   NUMBER(6,0)      NULL,
 pegi_posizione                  VARCHAR(4)       NULL,
 posi_sequenza                   NUMBER(3,0)      NULL,
 pegi_tipo_rapporto              VARCHAR(4)       NULL,
 capo_previsti                   NUMBER(5,0)      NULL,
 capo_ore_previsti               NUMBER(5,2)      NULL,
 capo_in_pianta                  NUMBER(5,0)      NULL,
 capo_in_deroga                  NUMBER(5,0)      NULL,
 capo_in_sovrannumero            NUMBER(5,0)      NULL,
 capo_in_rilascio                NUMBER(5,0)      NULL,
 capo_in_acquisizione            NUMBER(5,0)      NULL,
 capo_in_istituzione             NUMBER(5,0)      NULL,
 capo_assegnazioni_ruolo_l1      NUMBER(5,0)      NULL,
 capo_ore_assegnazioni_ruolo_l1  NUMBER(5,2)      NULL,
 capo_assegnazioni_ruolo_l2      NUMBER(5,0)      NULL,
 capo_ore_assegnazioni_ruolo_l2  NUMBER(5,2)      NULL,
 capo_assegnazioni_ruolo_l3      NUMBER(5,0)      NULL,
 capo_ore_assegnazioni_ruolo_l3  NUMBER(5,2)      NULL,
 capo_assegnazioni_ruolo         NUMBER(5,0)      NULL,
 capo_ore_assegnazioni_ruolo     NUMBER(5,2)      NULL,
 capo_assegnazioni               NUMBER(5,0)      NULL,
 capo_ore_assegnazioni           NUMBER(5,2)      NULL,
 capo_assenze_incarico           NUMBER(5,0)      NULL,
 capo_assenze_assenza            NUMBER(5,0)      NULL,
 capo_disponibili                NUMBER(5,0)      NULL,
 capo_ore_disponibili            NUMBER(5,2)      NULL,
 capo_coperti_ruolo_1            NUMBER(5,0)      NULL,
 capo_ore_coperti_ruolo_1        NUMBER(5,2)      NULL,
 capo_coperti_ruolo_2            NUMBER(5,0)      NULL,
 capo_ore_coperti_ruolo_2        NUMBER(5,2)      NULL,
 capo_coperti_ruolo_3            NUMBER(5,0)      NULL,
 capo_ore_coperti_ruolo_3        NUMBER(5,2)      NULL,
 capo_coperti_ruolo              NUMBER(5,0)      NULL,
 capo_ore_coperti_ruolo          NUMBER(5,2)      NULL,
 capo_coperti_no_ruolo           NUMBER(5,0)      NULL,
 capo_ore_coperti_no_ruolo       NUMBER(5,2)      NULL,
 capo_vacanti                    NUMBER(5,0)      NULL,
 capo_ore_vacanti                NUMBER(5,2)      NULL,
 capo_vacanti_coperti            NUMBER(5,0)      NULL,
 capo_ore_vacanti_coperti        NUMBER(5,2)      NULL,
 capo_vacanti_non_coperti        NUMBER(5,0)      NULL,
 capo_ore_vacanti_non_coperti    NUMBER(5,2)      NULL,
 capo_vacanti_non_ricopribili    NUMBER(5,0)      NULL,
 popi_delibera_01                VARCHAR(13)      NULL,
 popi_delibera_02                VARCHAR(13)      NULL,
 popi_delibera_03                VARCHAR(13)      NULL,
 popi_delibera_04                VARCHAR(13)      NULL,
 popi_delibera_05                VARCHAR(13)      NULL,
 popi_delibera_06                VARCHAR(13)      NULL,
 popi_delibera_07                VARCHAR(13)      NULL,
 popi_delibera_08                VARCHAR(13)      NULL,
 popi_delibera_09                VARCHAR(13)      NULL,
 popi_delibera_10                VARCHAR(13)      NULL,
 popi_delibera_11                VARCHAR(13)      NULL,
 popi_delibera_12                VARCHAR(13)      NULL
)
;

COMMENT ON TABLE calcolo_posti
    IS 'CAPO - Tabella di servizio per prospetti di Pianta Organica';


REM
REM 
REM
PROMPT
PROMPT Creating Index CAPON_IK on Table CALCOLO_POSTI
CREATE INDEX CAPON_IK ON CALCOLO_POSTI
(
      capo_prenotazione )
PCTFREE  10
;

REM
REM  End of command file
REM
