REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DEPOSITO_PERIODI_PRESENZA
REM INDEX
REM      DPPA_PK

REM
REM     DPPA - Tabella di Lavoro per Stampe Periodi effettivi di Presenza.
REM
PROMPT 
PROMPT Creating Table DEPOSITO_PERIODI_PRESENZA
CREATE TABLE deposito_periodi_presenza(
 prenotazione                    NUMBER(6,0)      NOT NULL,
 data                            DATE             NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 ufficio                         VARCHAR(20)      NULL,
 badge                           NUMBER(5)        NULL,
 sede                            NUMBER(6,0)      NULL,
 cod_sede                        VARCHAR(8)       NULL,
 seq_sede                        NUMBER(3,0)      NULL,
 cartellino                      VARCHAR(6)       NULL,
 gestione                        VARCHAR(8)       NULL,
 matricola                       NUMBER(8,0)      NULL,
 gg_set                          NUMBER(1)        NULL,
 min_gg                          NUMBER(4)        NULL,
 ore_min_gg                      NUMBER(2)        NULL,
 minuti_min_gg                   NUMBER(2)        NULL,
 cdc                             VARCHAR(8)       NULL,
 fattore_produttivo              VARCHAR(6)       NULL,
 assistenza                      VARCHAR(6)       NULL,
 automatismo                     VARCHAR(1)       NULL,
 rilevanza                       VARCHAR(1)       NULL,
 inizio                          DATE             NULL,
 segmento                        VARCHAR(1)       NULL,
 evento                          VARCHAR(6)       NULL,
 seq_evento                      NUMBER(3,0)      NULL,
 posizione                       VARCHAR(4)       NULL,
 seq_posizione                   NUMBER(3,0)      NULL,
 ruolo                           VARCHAR(4)       NULL,
 seq_ruolo                       NUMBER(3,0)      NULL,
 figura                          NUMBER(6,0)      NULL,
 cod_figura                      VARCHAR(8)       NULL,
 seq_figura                      NUMBER(6,0)      NULL,
 attivita                        VARCHAR(8)       NULL,
 seq_attivita                    NUMBER(6,0)      NULL,
 contratto                       VARCHAR(4)       NULL,
 seq_contratto                   NUMBER(3,0)      NULL,
 qualifica                       NUMBER(6,0)      NULL,
 cod_qualifica                   VARCHAR(8)       NULL,
 seq_qualifica                   NUMBER(6,0)      NULL,
 tipo_rapporto                   VARCHAR(8)       NULL,
 ore                             NUMBER(5,2)      NULL,
 settore                         NUMBER(6,0)      NULL,
 cod_settore                     VARCHAR(15)      NULL,
 seq_settore                     NUMBER(6,0)      NULL,
 funzionale                      VARCHAR(8)       NULL,
 seq_funzionale                  NUMBER(3,0)      NULL,
 classe_rapporto                 VARCHAR(4)       NULL,
 seq_classe_rapporto             NUMBER(3,0)      NULL
)
;

COMMENT ON TABLE deposito_periodi_presenza
    IS 'DPPA - Tabella di Lavoro per Stampe Periodi effettivi di Presenza.';


REM
REM 
REM
PROMPT
PROMPT Creating Index DPPA_PK on Table DEPOSITO_PERIODI_PRESENZA
CREATE INDEX DPPA_PK ON DEPOSITO_PERIODI_PRESENZA
(
      prenotazione ,
      ci ,
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
