CREATE TABLE PARTI_ANATOMICHE ( 
  PARTE        VARCHAR2 (6)  NOT NULL, 
  DESCRIZIONE  VARCHAR2 (120)  NOT NULL, 
  SEQUENZA     NUMBER(4), 
  STATISTICO   VARCHAR2 (6));

CREATE INDEX paan_PK ON PARTI_ANATOMICHE
(parte )
;