REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TARIFFE_VOCE
REM INDEX
REM      TAVO_PK
REM      TAVO_VOCO_FK

REM
REM     TAVO - Caratteristiche storiche delle tariffe di voci retributive
REM
PROMPT 
PROMPT Creating Table TARIFFE_VOCE
CREATE TABLE tariffe_voce(
 voce                            VARCHAR(10)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 tipo_moltiplica                 VARCHAR(2)       NOT NULL,
 moltiplica                      NUMBER(15,5)     NULL,
 tipo_divide                     VARCHAR(2)       NOT NULL,
 divide                          NUMBER(15,5)     NULL,
 decimali                        NUMBER(1,0)      NULL,
 arrotonda                       NUMBER(12,2)     NULL,
 val_voce_qta                    VARCHAR(1)       NULL,
 cod_voce_qta                    VARCHAR(10)      NULL,
 sub_voce_qta                    VARCHAR(2)       NULL,
 quantita                        NUMBER(12,2)     NULL,
 tipo_moltiplica_qta             VARCHAR(2)       NOT NULL,
 moltiplica_qta                  NUMBER(14,4)     NULL,
 tipo_divide_qta                 VARCHAR(2)       NOT NULL,
 divide_qta                      NUMBER(14,4)     NULL,
 decimali_qta                    NUMBER(1,0)      NULL,
 astensione                      VARCHAR2(4)      NULL
)
;

COMMENT ON TABLE tariffe_voce
    IS 'TAVO - Caratteristiche storiche delle tariffe di voci retributive';


REM
REM 
REM
PROMPT
PROMPT Creating Index TAVO_PK on Table TARIFFE_VOCE
CREATE UNIQUE INDEX TAVO_PK ON TARIFFE_VOCE
(
      voce ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TAVO_VOCO_FK on Table TARIFFE_VOCE
CREATE INDEX TAVO_VOCO_FK ON TARIFFE_VOCE
(
      cod_voce_qta ,
      sub_voce_qta )
PCTFREE  10
;

REM
REM  End of command file
REM
