REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CARRIERE
REM INDEX
REM      CARR_PK

REM
REM     CARR - Carriere professionali
REM
PROMPT 
PROMPT Creating Table CARRIERE
CREATE TABLE carriere(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL
)
;

COMMENT ON TABLE carriere
    IS 'CARR - Carriere professionali';


REM
REM 
REM
PROMPT
PROMPT Creating Index CARR_PK on Table CARRIERE
CREATE UNIQUE INDEX CARR_PK ON CARRIERE
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
