CREATE TABLE RIPARTIZIONE_GRUPPI_DOTAZIONE ( 
  RIGD_ID       NUMBER (10)   NOT NULL, 
  GRUPPO        VARCHAR2 (10), 
  DAL           DATE          NOT NULL, 
  AL            DATE, 
  NUMERO_I      NUMBER (8), 
  NUMERO_ORE_I  NUMBER (9,2), 
  NUMERO_D      NUMBER (8), 
  NUMERO_ORE_D  NUMBER (9,2), 
  NUMERO_L      NUMBER (8), 
  NUMERO_ORE_L  NUMBER (9,2));

CREATE UNIQUE INDEX RIGD_PK ON RIPARTIZIONE_GRUPPI_DOTAZIONE
(RIGD_ID);