REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system GIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DELIBERE
REM INDEX
REM      DELI_PK

REM
REM     DELI - Protocollo dei provvedimenti deliberativi emessi
REM
PROMPT 
PROMPT Creating Table DELIBERE
CREATE TABLE delibere(
 sede                            VARCHAR(4)       NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 numero                          NUMBER(7,0)      NOT NULL,
 data                            DATE             NOT NULL,
 oggetto                         VARCHAR(240)     NULL,
 descrizione                     VARCHAR(50)      NULL,
 esecutivita                     VARCHAR(1)       NOT NULL,
 tipo_ese                        VARCHAR(30)      NOT NULL,
 numero_ese                      VARCHAR(12)      NULL,
 data_ese                        DATE             NULL,
 note                            VARCHAR(4000)    NULL
)
;

COMMENT ON TABLE delibere
    IS 'DELI - Protocollo dei provvedimenti deliberativi emessi';


REM
REM 
REM
PROMPT
PROMPT Creating Index DELI_PK on Table DELIBERE
CREATE UNIQUE INDEX DELI_PK ON DELIBERE
(
      sede ,
      anno ,
      numero )
PCTFREE  10
;

REM
REM  End of command file
REM
