REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  11-AUG-94
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLO_LIQUIDAZIONE_MALATTIE
REM INDEX
REM      CALM_IK
REM      CALM_IK2

REM
REM     
REM
PROMPT 
PROMPT Creating Table CALCOLO_LIQUIDAZIONE_MALATTIE
CREATE TABLE calcolo_liquidazione_malattie(
 calm_prenotazione               NUMBER(6,0)      NOT NULL,
 ripa_mese                       NUMBER(2,0)      NOT NULL,
 mens_descrizione                VARCHAR(30)      NULL,
 ripa_anno                       NUMBER(4,0)      NOT NULL,
 rain_ci                         NUMBER(8,0)      NOT NULL,
 rain_cognome                    VARCHAR(36)      NOT NULL,
 rain_nome                       VARCHAR(36)      NOT NULL,
 anag_indirizzo                  VARCHAR(40)      NULL,
 anag_provincia                  NUMBER(3,0)      NULL,
 anag_comune                     NUMBER(3,0)      NULL,
 comu_descrizione                VARCHAR(40)      NULL,
 comu_sigla_provincia            VARCHAR(5)       NULL,
 anag_presso                     VARCHAR(40)      NULL,
 gest_codice                     VARCHAR(4)       NULL,
 gest_nome                       VARCHAR(40)      NULL,
 clpa_evento                     NUMBER(10,0)     NULL,
 clpa_classe                     VARCHAR(8)       NULL,
 clpa_dal                        DATE             NULL,
 clpa_al                         DATE             NULL,
 clpa_riferimento                DATE             NULL,
 calm_dal_retribuzione           DATE             NULL,
 calm_al_retribuzione            DATE             NULL,
 calm_data_01                    DATE             NULL,
 calm_data_02                    DATE             NULL,
 calm_importo_03                 NUMBER(14,2)     NULL,
 calm_gg_03                      NUMBER(2,0)      NULL,
 calm_importo_04                 NUMBER(14,2)     NULL,
 calm_gg_04                      NUMBER(2,0)      NULL,
 calm_importo_05                 NUMBER(14,2)     NULL,
 calm_gg_06                      NUMBER(2,0)      NULL,
 calm_importo_07                 NUMBER(14,2)     NULL,
 calm_gg_07                      NUMBER(2,0)      NULL,
 calm_dato1_08                   NUMBER(14,2)     NULL,
 calm_dato2_08                   NUMBER(14,2)     NULL,
 calm_dato1_12                   NUMBER(14,2)     NULL,
 calm_dal_08                     DATE             NULL,
 calm_al_08                      DATE             NULL,
 calm_importo_08                 NUMBER(14,2)     NULL,
 calm_dato1_09                   NUMBER(14,2)     NULL,
 calm_dato2_09                   NUMBER(14,2)     NULL,
 calm_dal_09                     DATE             NULL,
 calm_al_09                      DATE             NULL,
 calm_importo_09                 NUMBER(14,2)     NULL,
 calm_dato1_10                   NUMBER(14,2)     NULL,
 calm_dato2_10                   NUMBER(14,2)     NULL,
 calm_dal_10                     DATE             NULL,
 calm_al_10                      DATE             NULL,
 calm_importo_10                 NUMBER(14,2)     NULL,
 calm_dato1_11                   NUMBER(14,2)     NULL,
 calm_dato2_11                   NUMBER(14,2)     NULL,
 calm_dal_11                     DATE             NULL,
 calm_al_11                      DATE             NULL,
 calm_importo_11                 NUMBER(14,2)     NULL,
 calm_dato1_13                   NUMBER(14,2)     NULL,
 calm_dato2_13                   NUMBER(14,2)     NULL,
 calm_dal_13                     DATE             NULL,
 calm_al_13                      DATE             NULL,
 calm_importo_13                 NUMBER(14,2)     NULL,
 calm_dato1_14                   NUMBER(14,2)     NULL,
 calm_dato2_14                   NUMBER(14,2)     NULL,
 calm_dal_14                     DATE             NULL,
 calm_al_14                      DATE             NULL,
 calm_importo_14                 NUMBER(14,2)     NULL,
 calm_dato1_15                   NUMBER(14,2)     NULL,
 calm_dato2_15                   NUMBER(14,2)     NULL,
 calm_dal_15                     DATE             NULL,
 calm_al_15                      DATE             NULL,
 calm_importo_15                 NUMBER(14,2)     NULL
)
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CALM_IK on Table CALCOLO_LIQUIDAZIONE_MALATTIE
CREATE INDEX CALM_IK ON CALCOLO_LIQUIDAZIONE_MALATTIE
(
      calm_prenotazione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CALM_IK2 on Table CALCOLO_LIQUIDAZIONE_MALATTIE
CREATE INDEX CALM_IK2 ON CALCOLO_LIQUIDAZIONE_MALATTIE
(
      rain_ci )
PCTFREE  10
;

REM
REM  End of command file
REM
