CREATE TABLE CODICI_ATTRIBUTO ( 
  COAT_ID      NUMBER (10)   NOT NULL, 
  CATEGORIA    VARCHAR2 (4)  NOT NULL, 
  ATTRIBUTO    VARCHAR2 (15)  NOT NULL, 
  DAL          DATE          NOT NULL, 
  AL           DATE, 
  DESCRIZIONE  VARCHAR2 (120)  NOT NULL, 
  SEDE_DEL     VARCHAR2 (4), 
  ANNO_DEL     NUMBER (4), 
  NUMERO_DEL   NUMBER (8), 
  SEQUENZA     NUMBER (6), 
  CONTINUATO   VARCHAR2(2)       DEFAULT 'NO' NOT NULL,
  NOTE         VARCHAR2 (2000), 
  UTENTE       VARCHAR2 (8), 
  DATA_AGG     DATE,
  MAX_NR       NUMBER
) ; 



CREATE INDEX COAT_CAAT_FK ON 
  CODICI_ATTRIBUTO(CATEGORIA) 
; 

CREATE UNIQUE INDEX COAT_PK ON 
  CODICI_ATTRIBUTO(COAT_ID) 
; 


CREATE UNIQUE INDEX COAT_IK ON 
  CODICI_ATTRIBUTO(CATEGORIA,ATTRIBUTO,DAL) 
; 


COMMENT ON TABLE CODICI_ATTRIBUTO IS 'Codifiche degli attributi giuridici';
