REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN ON

REM  Objects being generated in this file are:-
REM TABLE
REM      RAPPORTI_DIVERSI
REM INDEX
REM      RADI_IK     

REM
REM     RADI - Identificazione dei rapporti di erede, precedente datore di 
REM            lavoro e precedenti rapporti con lo stesso ente 
REM
PROMPT 
PROMPT Creating Table RAPPORTI_DIVERSI
CREATE TABLE rapporti_diversi(
 ci                              NUMBER(8,0)      NOT NULL,
 ci_erede                        NUMBER(8,0)      NOT NULL,
 quota_erede                     NUMBER(5,2)      NULL,
 tipo_erede                      VARCHAR(1)       NULL,
 rilevanza                       VARCHAR(1)       NOT NULL,
 anno                            NUMBER (4)       NOT NULL
)
;

COMMENT ON TABLE rapporti_diversi    IS 'RARE - Identificazione dei rapporti con caratteristiche retributive';


REM
REM 
REM

REM
REM Non unico escludento CI diversi di stesso NI e CI di GESTIONI diverse
REM
PROMPT
PROMPT Creating Index RADI_PK on Table RAPPORTI_DIVERSI
CREATE UNIQUE INDEX RADI_PK ON RAPPORTI_DIVERSI
(ci ,
 anno ,
 ci_erede
 )
PCTFREE  10
;

REM
REM  End of command file
REM
