REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  30-MAY-94
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DENUNCIA_INPDAP
REM INDEX
REM      DEDP_GEST_FK
REM      DEDP_PK
REM      DEDP_RARE_FK

REM
REM     DEDP - Archivio Denuncia Inpdap
REM
PROMPT 
PROMPT Creating Table DENUNCIA_INPDAP
CREATE TABLE denuncia_inpdap(
 anno                            NUMBER(4)        NOT NULL,
 previdenza                      VARCHAR(6)       NOT NULL,
 assicurazioni                   VARCHAR(6)       NOT NULL,
 ci                              NUMBER(8)        NOT NULL,
 gestione                        VARCHAR(8)       NULL,
 codice                          VARCHAR(10)      NULL,
 posizione                       VARCHAR(8)       NULL,
 rilevanza                       VARCHAR(1)       NOT NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 tipo_impiego                    VARCHAR(2)       NULL,
 tipo_servizio                   varchar(2)       NULL,
 gg_utili                        number(3)        NULL,
 data_cessazione                 DATE             NULL,
 comp_fisse                      NUMBER(12,2)     NULL,
 comp_accessorie                 number(12,2)     NULL,
 iis_conglobata                  number(12,2)     NULL,
 comp_inadel                     number(12,2)     NULL,
 comp_tfr                        NUMBER(12,2)     NULL,
 ipn_tfr                         NUMBER(12,2)     NULL,
 premio_prod                     number(12,2)     NULL,
 riferimento                     NUMBER(4,0)      NULL,
 competenza                      number(4,0)      NULL,
 utente                          VARCHAR(8)       NULL,
 tipo_agg                        VARCHAR(1)       NULL,
 data_agg                        DATE             NULL,
 maggiorazioni                   VARCHAR(12)      NULL,
 causa_cessazione                VARCHAR(2)       NULL,
 data_decorrenza                 date             NULL,
 gg_tfr                          number(3)        NULL,
 ind_non_a                       number(12,2)     NULL,
 l_165                           number(12,2)     NULL,  
 l_388                           VARCHAR2(1)      NULL,
 comp_18                         number(12,2)     NULL,  
 tredicesima	               number(12,2)     NULL,
 gg_mag_1	                     number(3)        NULL,
 gg_mag_2	                     number(3)        NULL,
 gg_mag_3	                     number(3)        NULL,
 gg_mag_4	                     number(3)        NULL,
 data_opz_tfr	               date             NULL,
 cf_amm_fisse	               varchar2(16)     NULL,
 cf_amm_acc	                     varchar2(16)     NULL,
 comparto                        VARCHAR2(2)      NULL,
 sottocomparto                   VARCHAR2(2)      NULL,
 qualifica                       VARCHAR2(6)      NULL,
 rap_orario			         NUMBER(13,10)    NULL,
 PERC_L300                       NUMBER(5,2)      NULL,
 rit_inpdap                      number(12,2)     NULL,
 rit_tfs                         NUMBER(12,2)     NULL,
 contr_tfr                       NUMBER(12,2)     NULL
 )
;

COMMENT ON TABLE denuncia_inpdap
    IS 'DEDP - Archivio Denuncia Inpdap';


REM
REM 
REM
PROMPT
PROMPT Creating Index DEDP_GEST_FK on Table DENUNCIA_INPDAP
CREATE INDEX DEDP_GEST_FK ON DENUNCIA_INPDAP
(
      gestione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index DEDP_PK on Table DENUNCIA_INPDAP
CREATE INDEX DEDP_PK ON DENUNCIA_INPDAP
(
      anno ,
      previdenza ,
      ci ,
      gestione ,
      rilevanza ,
      dal ,
      competenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index DEDP_RARE_FK on Table DENUNCIA_INPDAP
CREATE INDEX DEDP_RARE_FK ON DENUNCIA_INPDAP
(
      ci )
PCTFREE  10
;

REM
REM  End of command file
REM
