REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CONTABILITA_VOCE
REM INDEX
REM      COVO_CLBU_FK
REM      COVO_COBI_FK
REM      COVO_DELI_FK
REM      COVO_ISCR_FK
REM      COVO_PK

REM
REM     COVO - Caretteristiche storiche di contabilizzazione della voce
REM
PROMPT 
PROMPT Creating Table CONTABILITA_VOCE
CREATE TABLE contabilita_voce(
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 descrizione                     VARCHAR(30)      NOT NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 des_abb                         VARCHAR(10)       NULL,
 des_abb_al1                     VARCHAR(10)       NULL,
 des_abb_al2                     VARCHAR(10)       NULL,
 note                            VARCHAR(240)     NULL,
 fiscale                         VARCHAR(1)       NOT NULL,
 somme                           VARCHAR(2)       NULL,
 rapporto                        VARCHAR(1)       NULL,
 stampa_tar                      VARCHAR(1)       NOT NULL,
 stampa_qta                      VARCHAR(1)       NOT NULL,
 stampa_imp                      VARCHAR(1)       NOT NULL,
 starie_tar                      VARCHAR(1)       NOT NULL,
 starie_qta                      VARCHAR(1)       NOT NULL,
 starie_imp                      VARCHAR(1)       NOT NULL,
 bilancio                        VARCHAR(2)       NULL,
 budget                          VARCHAR(4)       NULL,
 sede_del                        VARCHAR(4)       NULL,
 anno_del                        NUMBER(4,0)      NULL,
 numero_del                      NUMBER(7,0)      NULL,
 capitolo                        VARCHAR(14)      NULL,
 articolo                        VARCHAR(14)      NULL,
 conto                           VARCHAR(2)       NULL,
 istituto                        VARCHAR(5)       NULL,
 COD_VOCE_CONTR_SEP              VARCHAR(10)      NULL,
 SUB_VOCE_CONTR_SEP              VARCHAR(2)       NULL,
 stampa_fr                       VARCHAR(1)       default 'F' NOT NULL,
 impegno                         NUMBER(5)        NULL,
 risorsa_intervento              VARCHAR(7)       NULL,
 anno_impegno                    NUMBER(4)        NULL,
 sub_impegno                     NUMBER(5)        NULL,
 anno_sub_impegno                NUMBER(4)        NULL,
 codice_siope		         NUMBER(4)        NULL
)
;

COMMENT ON TABLE contabilita_voce
    IS 'COVO - Caretteristiche storiche di contabilizzazione della voce';


REM
REM 
REM
PROMPT
PROMPT Creating Index COVO_CLBU_FK on Table CONTABILITA_VOCE
CREATE INDEX COVO_CLBU_FK ON CONTABILITA_VOCE
(
      budget )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index COVO_COBI_FK on Table CONTABILITA_VOCE
CREATE INDEX COVO_COBI_FK ON CONTABILITA_VOCE
(
      bilancio )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index COVO_DELI_FK on Table CONTABILITA_VOCE
CREATE INDEX COVO_DELI_FK ON CONTABILITA_VOCE
(
      sede_del ,
      anno_del ,
      numero_del )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index COVO_ISCR_FK on Table CONTABILITA_VOCE
CREATE INDEX COVO_ISCR_FK ON CONTABILITA_VOCE
(
      istituto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index COVO_PK on Table CONTABILITA_VOCE
CREATE UNIQUE INDEX COVO_PK ON CONTABILITA_VOCE
(
      voce ,
      sub ,
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
