REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RELAZIONE_CHIAVI
REM INDEX
REM      RECH_PK

REM
REM     RECH - Chiavi di ordinamento previste dalle Estrazioni Parametriche
REM
PROMPT 
PROMPT Creating Table RELAZIONE_CHIAVI
CREATE TABLE relazione_chiavi(
 chiave                          VARCHAR(20)      NOT NULL,
 descrizione                     VARCHAR(60)      NULL,
 descrizione_al1                 VARCHAR(60)      NULL,
 descrizione_al2                 VARCHAR(60)      NULL,
 nome                            VARCHAR(20)      NULL,
 nome_al1                        VARCHAR(20)      NULL,
 nome_al2                        VARCHAR(20)      NULL
)
;

COMMENT ON TABLE relazione_chiavi
    IS 'RECH - Chiavi di ordinamento previste dalle Estrazioni Parametriche';


REM
REM 
REM
PROMPT
PROMPT Creating Index RECH_PK on Table RELAZIONE_CHIAVI
CREATE UNIQUE INDEX RECH_PK ON RELAZIONE_CHIAVI
(
      chiave )
PCTFREE  10
;

REM
REM  End of command file
REM
