REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-JUL-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONE_GESTIONI
REM INDEX
REM      ESGE_GEST_FK
REM      ESGE_PK

REM
REM     ESGE - Selezioni di estrazione degli elaborati di Gestione
REM
PROMPT 
PROMPT Creating Table ESTRAZIONE_GESTIONI
CREATE TABLE estrazione_gestioni(
 estrazione                      VARCHAR(20)      NOT NULL,
 gestione                        VARCHAR(4)       NOT NULL,
 settore                         VARCHAR(15)      NOT NULL
)
;

COMMENT ON TABLE estrazione_gestioni
    IS 'ESGE - Selezioni di estrazione degli elaborati di Gestione';


REM
REM 
REM
PROMPT
PROMPT Creating Index ESGE_GEST_FK on Table ESTRAZIONE_GESTIONI
CREATE INDEX ESGE_GEST_FK ON ESTRAZIONE_GESTIONI
(
      gestione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESGE_PK on Table ESTRAZIONE_GESTIONI
CREATE UNIQUE INDEX ESGE_PK ON ESTRAZIONE_GESTIONI
(
      estrazione ,
      gestione ,
      settore )
PCTFREE  10
;

REM
REM  End of command file
REM
