REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  13-SEP-95
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DENUNCIA_CAAF
REM INDEX
REM      CAAF_PK
REM      CAAF_RAIN_FK
REM      CAAF_RARE_FK

REM
REM     CAAF - Archivio Dati Centri Assistenza Fiscale
REM
PROMPT 
PROMPT Creating Table DENUNCIA_CAAF
CREATE TABLE denuncia_caaf(
 anno                            NUMBER(4,0)      NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 ci_caaf                         NUMBER(8,0)      NOT NULL,
 irpef_db                        NUMBER(12,2)         NULL,
 irpef_cr                        NUMBER(12,2)         NULL,
 ilor_db                         NUMBER(12,2)         NULL,
 ilor_cr                         NUMBER(12,2)         NULL,
 cssn_db                         NUMBER(12,2)         NULL,
 cssn_cr                         NUMBER(12,2)         NULL,
 irpef_1r                        NUMBER(12,2)         NULL,
 irpef_2r                        NUMBER(12,2)         NULL,
 cssn_1r                         NUMBER(12,2)         NULL,
 cssn_2r                         NUMBER(12,2)         NULL,
 flag_versamento                 NUMBER(1,0)          NULL,
 rettifica                       VARCHAR(1)       NOT NULL,
 somme_deb                       NUMBER(12,2)         NULL,
 somme_cr                        NUMBER(12,2)         NULL,
 irpef_int                       NUMBER(12,2)         NULL,
 irpef_sop                       NUMBER(12,2)         NULL,
 ssn_int                         NUMBER(12,2)         NULL,
 ssn_sop                         NUMBER(12,2)         NULL,
 irpef_nr                        NUMBER(12,2)         NULL,
 cssn_nr                         NUMBER(12,2)         NULL,
 utente                          VARCHAR(8)           NULL,
 data_agg                        DATE                 NULL,
 irpef_1r_int                    NUMBER(12,2)         NULL,
 irpef_1r_sop                    NUMBER(12,2)         NULL,
 ssn_1r_int                      NUMBER(12,2)         NULL,
 ssn_1r_sop                      NUMBER(12,2)         NULL,
 irpef_2r_int                    NUMBER(12,2)         NULL,
 irpef_2r_sop                    NUMBER(12,2)         NULL,
 ssn_2r_int                      NUMBER(12,2)         NULL,
 ssn_2r_sop                      NUMBER(12,2)         NULL,
 tipo                            NUMBER(1)        NOT NULL,
 conguaglio_1r                   VARCHAR(1)           NULL,
 conguaglio_2r                   VARCHAR(1)           NULL,
 euro_netto                      NUMBER(12,2)         NULL,
 euro_altro                      NUMBER(12,2)         NULL,
 euro_1r                         NUMBER(12,2)         NULL,
 euro_2r                         NUMBER(12,2)         NULL,
 irpef_acconto_ap                NUMBER(12,2)         NULL,
 euro_1r_int                     NUMBER(12,2)         NULL,
 euro_1r_sop                     NUMBER(12,2)         NULL,
 euro_2r_int                     NUMBER(12,2)         NULL,
 euro_2r_sop                     NUMBER(12,2)         NULL,
 irpef_acconto_ap_int            NUMBER(12,2)         NULL,
 irpef_acconto_ap_sop            NUMBER(12,2)         NULL,
 nr_rate                         NUMBER(10,0)         NULL,
 int_rate_irpef                  NUMBER(12,2)         NULL,
 int_rate_ssn                    NUMBER(12,2)         NULL,
 irpef_acconto_ap_con            NUMBER(12,2)         NULL,
 int_rate_irpef_1r               NUMBER(12,2)         NULL,
 int_rate_irpef_ap               NUMBER(12,2)         NULL,
 int_rate_irpef_ap_con           NUMBER(12,2)         NULL,
 int_rate_reg_dic                NUMBER(12,2)         NULL,
 int_rate_reg_con                NUMBER(12,2)         NULL,
 cod_reg_dic_db                  NUMBER(3,0)          NULL,
 add_reg_dic_db                  NUMBER(12,2)         NULL,
 cod_reg_con_db                  NUMBER(3,0)          NULL,
 add_reg_con_db                  NUMBER(12,2)         NULL,
 cod_reg_dic_cr                  NUMBER(3,0)          NULL,
 add_reg_dic_cr                  NUMBER(12,2)         NULL,
 cod_reg_con_cr                  NUMBER(3,0)          NULL,
 add_reg_con_cr                  NUMBER(12,2)         NULL,
 data_ricezione                  DATE                 NULL,
 int_rate_com_dic                NUMBER(12,2)         NULL,
 int_rate_com_con                NUMBER(12,2)         NULL,
 cod_com_dic_db                  VARCHAR(4)           NULL,
 add_com_dic_db                  NUMBER(12,2)         NULL,
 cod_com_con_db                  VARCHAR(4)           NULL,
 add_com_con_db                  NUMBER(12,2)         NULL,
 cod_com_dic_cr                  VARCHAR(4)           NULL,
 add_com_dic_cr                  NUMBER(12,2)         NULL,
 cod_com_con_cr                  VARCHAR(4)           NULL,
 add_com_con_cr                  NUMBER(12,2)         NULL,
 note                            VARCHAR(240)         NULL,
 irpef_1r_con                    NUMBER(12,2)         NULL,
 irpef_2r_con                    NUMBER(12,2)         NULL,
 int_rate_irpef_1r_con           NUMBER(12,2)         NULL,
 IRPEF_DB_CON                    NUMBER(12,2)         NULL,
 IRPEF_CR_CON                    NUMBER(12,2)         NULL,
 INT_RATE_IRPEF_CON              NUMBER(12,2)         NULL,
 COD_COM_ACC_DIC_DB              VARCHAR2(4)          NULL,
 ACC_ADD_COM_DIC_DB              NUMBER(12,2)         NULL,
 INT_RATE_ACC_COM_DIC            NUMBER(12,2)         NULL,
 COD_COM_ACC_CON_DB              VARCHAR2(4)          NULL,
 ACC_ADD_COM_CON_DB              NUMBER(12,2)         NULL,
 INT_RATE_ACC_COM_CON            NUMBER(12,2)         NULL
)
;

COMMENT ON TABLE denuncia_caaf
    IS 'CAAF - Archivio Dati Centri Assistenza Fiscale';


REM
REM 
REM
PROMPT
PROMPT Creating Index CAAF_PK on Table DENUNCIA_CAAF
CREATE UNIQUE INDEX CAAF_PK ON DENUNCIA_CAAF
(
      anno ,
      ci ,
      rettifica )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CAAF_RAIN_FK on Table DENUNCIA_CAAF
CREATE INDEX CAAF_RAIN_FK ON DENUNCIA_CAAF
(
      ci_caaf )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CAAF_RARE_FK on Table DENUNCIA_CAAF
CREATE INDEX CAAF_RARE_FK ON DENUNCIA_CAAF
(
      ci )
PCTFREE  10
;

REM
REM  End of command file
REM
