CREATE TABLE PROSECUZIONI_INFORTUNIO
(
  PROGRESSIVO  NUMBER(8),
  DAL          DATE,
  AL           DATE,
  GIORNI       NUMBER(3)
);


CREATE UNIQUE INDEX PINF_PK ON PROSECUZIONI_INFORTUNIO
(PROGRESSIVO, DAL);