REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      IMPONIBILI_VOCE
REM INDEX
REM      IMVO_PK

REM
REM     IMVO - Caratteristiche di imponibilita` della voce economica
REM
PROMPT 
PROMPT Creating Table IMPONIBILI_VOCE
CREATE TABLE imponibili_voce(
 voce                            VARCHAR(10)      NOT NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 moltiplica                      NUMBER(15,5)     NULL,
 divide                          NUMBER(15,5)     NULL,
 per_ipn                         NUMBER(5,2)      NULL,
 arr_ipn                         NUMBER(12,2)     NULL,
 max_ipn                         NUMBER(15,5)     NULL,
 min_ipn                         NUMBER(15,5)     NULL,
 min_gg                          NUMBER(15,5)     NULL,
 min_gg_pt                       NUMBER(15,5)     NULL,
 min_gg_1                        NUMBER(15,5)     NULL,
 min_gg_1_pt                     NUMBER(15,5)     NULL,
 min_gg_2                        NUMBER(15,5)     NULL,
 min_gg_2_pt                     NUMBER(15,5)     NULL,
 min_gg_3                        NUMBER(15,5)     NULL,
 min_gg_3_pt                     NUMBER(15,5)     NULL,
 note                            VARCHAR(240)     NULL,
 cassa_competenza                VARCHAR(2)       DEFAULT 'NO'
)
;

COMMENT ON TABLE imponibili_voce
    IS 'IMVO - Caratteristiche di imponibilita` della voce economica';


REM
REM 
REM
PROMPT
PROMPT Creating Index IMVO_PK on Table IMPONIBILI_VOCE
CREATE UNIQUE INDEX IMVO_PK ON IMPONIBILI_VOCE
(
      voce ,
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
