REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  30-MAY-94
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VERSAMENTI_CONTRIBUTIVI
REM INDEX
REM      DEDP_GEST_FK
REM      DEDP_PK
REM      DEDP_RARE_FK

REM
REM     VECO - Versamenti Contributivi
REM
PROMPT 
PROMPT Creating Table VERSAMENTI_CONTRIBUTIVI
CREATE TABLE VERSAMENTI_CONTRIBUTIVI 
( ANNO       	   NUMBER (4)     NOT NULL
, MESE        	   NUMBER (2)     NOT NULL
, MENSILITA        VARCHAR2 (4)   NOT NULL
, CI  		   NUMBER(8)      NOT NULL
, ISTITUTO         VARCHAR2(10)
, RUOLO            VARCHAR2(4) 
, ANNO_RIF         NUMBER (4)
, LORDO            NUMBER (12,2) 
, IMPONIBILE       NUMBER (12,2) 
, CONTRIBUTO       NUMBER (12,2)
, RITENUTA         NUMBER (12,2)
, TITOLO           VARCHAR2(240)
)
;


COMMENT ON TABLE versamenti_contributivi
    IS 'VECO - Versamenti Contributivi';


REM
REM 
REM
PROMPT
PROMPT Creating Index VECO_PK on Table VERSAMENTI_CONTRIBUTIVI
 
CREATE INDEX VECO_PK ON VERSAMENTI_CONTRIBUTIVI
(anno
,mese
,mensilita
,istituto)
PCTFREE  10
;


REM
REM  End of command file
REM


