REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RACCOLTA_RIGHE_MODULO
REM INDEX
REM      RARM_PK
REM      RARM_VOCO_FK

REM
REM     RARM - Personalizzazione dei Moduli di Raccolta Variabili caricati
REM
PROMPT 
PROMPT Creating Table RACCOLTA_RIGHE_MODULO
CREATE TABLE raccolta_righe_modulo(
 modulo                          VARCHAR(4)       NOT NULL,
 cc                              VARCHAR(30)      NOT NULL,
 sequenza                        NUMBER(1,0)      NOT NULL,
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE raccolta_righe_modulo
    IS 'RARM - Personalizzazione dei Moduli di Raccolta Variabili caricati';


REM
REM 
REM
PROMPT
PROMPT Creating Index RARM_PK on Table RACCOLTA_RIGHE_MODULO
CREATE UNIQUE INDEX RARM_PK ON RACCOLTA_RIGHE_MODULO
(
      modulo ,
      cc ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RARM_VOCO_FK on Table RACCOLTA_RIGHE_MODULO
CREATE INDEX RARM_VOCO_FK ON RACCOLTA_RIGHE_MODULO
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
