REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      EQUIPE
REM INDEX
REM      EQIP_PK

REM
REM     EQIP - Dizionario delle Equipes
REM
PROMPT 
PROMPT Creating Table EQUIPE
CREATE TABLE equipe(
 codice                          VARCHAR(4)       NOT NULL,
 definizione                     VARCHAR(30)      NULL,
 definizione_al1                 VARCHAR(30)      NULL,
 definizione_al2                 VARCHAR(30)      NULL
)
;

COMMENT ON TABLE equipe
    IS 'EQIP - Dizionario delle Equipes';


REM
REM 
REM
PROMPT
PROMPT Creating Index EQIP_PK on Table EQUIPE
CREATE UNIQUE INDEX EQIP_PK ON EQUIPE
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
