REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  11-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      GIUSTIFICATIVI
REM INDEX
REM      GIUS_PK

REM
REM     Created from Entity GIUSTIFICATIVO by P00 on 10-NOV-93
REM
PROMPT 
PROMPT Creating Table GIUSTIFICATIVI
CREATE TABLE giustificativi(
 codice                          VARCHAR(8)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL
)
;

COMMENT ON TABLE giustificativi
    IS 'Created from Entity GIUSTIFICATIVO by P00 on 10-NOV-93';


REM
REM 
REM
PROMPT
PROMPT Creating Index GIUS_PK on Table GIUSTIFICATIVI
CREATE UNIQUE INDEX GIUS_PK ON GIUSTIFICATIVI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
