REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  15-DEC-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIGHE_PROSPETTO_PRESENZA
REM INDEX
REM      RPPA_IK1
REM      RPPA_PK

REM
REM     RPPA - Dettaglio colonne dei prospetti di caricamento e di stampa
REM
PROMPT 
PROMPT Creating Table RIGHE_PROSPETTO_PRESENZA
CREATE TABLE righe_prospetto_presenza(
 prospetto                       VARCHAR(8)       NOT NULL,
 sequenza                        NUMBER(2,0)      NOT NULL,
 tipo                            VARCHAR(2)       NOT NULL,
 colonna                         VARCHAR(8)       NULL,
 stampa                          VARCHAR(1)       NULL
)
;

COMMENT ON TABLE righe_prospetto_presenza
    IS 'RPPA - Dettaglio colonne dei prospetti di caricamento e di stampa';


REM
REM 
REM
PROMPT
PROMPT Creating Index RPPA_IK1 on Table RIGHE_PROSPETTO_PRESENZA
CREATE INDEX RPPA_IK1 ON RIGHE_PROSPETTO_PRESENZA
(
      colonna )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RPPA_PK on Table RIGHE_PROSPETTO_PRESENZA
CREATE UNIQUE INDEX RPPA_PK ON RIGHE_PROSPETTO_PRESENZA
(
      prospetto ,
      sequenza )
PCTFREE  10
;

REM
REM  End of command file
REM
