REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system GIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      SOGGETTI
REM INDEX
REM      SOGG_PK

REM
REM     SOGG - Soggetti che anno rapporto fiscale con l"ente
REM
PROMPT 
PROMPT Creating Table SOGGETTI
CREATE TABLE soggetti(
 soggetto                        NUMBER(9,0)      NOT NULL,
 denominazione                   VARCHAR(40)      NULL,
 denominazione_al1               VARCHAR(40)      NULL,
 denominazione_al2               VARCHAR(40)      NULL,
 codice_fiscale                  VARCHAR(16)      NULL,
 divisione                       VARCHAR2(8)      NULL
)
;

COMMENT ON TABLE soggetti
    IS 'SOGG - Soggetti che anno rapporto fiscale con l"ente';


REM
REM 
REM
PROMPT
PROMPT Creating Index SOGG_PK on Table SOGGETTI
CREATE UNIQUE INDEX SOGG_PK ON SOGGETTI
(
      soggetto )
PCTFREE  10
;

REM
REM  End of command file
REM
