CREATE TABLE QUALIFICHE_INAIL ( 
  FIGURA           VARCHAR2 (8), 
  QUALIFICA        VARCHAR2 (8), 
  ATTIVITA         VARCHAR2 (4), 
  QUALIFICA_INAIL  VARCHAR2 (4)  NOT NULL)
; 


CREATE UNIQUE INDEX QUIN_PK ON 
  QUALIFICHE_INAIL( figura, qualifica, attivita) 
; 