REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JAN-94
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      EQUIPE_IPOTESI_INCENTIVO
REM INDEX
REM      EIIP_PK

REM
REM     EIIP - Definizione delle equipes per ambiente ipotesi di spesa
REM
PROMPT 
PROMPT Creating Table EQUIPE_IPOTESI_INCENTIVO
CREATE TABLE equipe_ipotesi_incentivo(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL
)
;

COMMENT ON TABLE equipe_ipotesi_incentivo
    IS 'EIIP - Definizione delle equipes per ambiente ipotesi di spesa';


REM
REM 
REM
PROMPT
PROMPT Creating Index EIIP_PK on Table EQUIPE_IPOTESI_INCENTIVO
CREATE UNIQUE INDEX EIIP_PK ON EQUIPE_IPOTESI_INCENTIVO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
