REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CONDIZIONI_FISCALI
REM INDEX
REM      COFI_PK

REM
REM     COFI - Condizioni di situazione familiare per detrazioni fiscali
REM
PROMPT 
PROMPT Creating Table CONDIZIONI_FISCALI
CREATE TABLE condizioni_fiscali(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL
)
;

COMMENT ON TABLE condizioni_fiscali
    IS 'COFI - Condizioni di situazione familiare per detrazioni fiscali';


REM
REM 
REM
PROMPT
PROMPT Creating Index COFI_PK on Table CONDIZIONI_FISCALI
CREATE UNIQUE INDEX COFI_PK ON CONDIZIONI_FISCALI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
