REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PEC version 1
REM

REM  Objects being generated in this file are:-
REM TABLE
REM      ADDIZIONALE_IRPEF_COMUNALE
REM INDEX
REM      AICO_PK
REM      AICO_IK

REM
REM    AICO - Addizionale IRPEF Comunale 
REM
PROMPT 
PROMPT Creating Table  ADDIZIONALE_IRPEF_COMUNALE
CREATE TABLE addizionale_irpef_comunale(
 cod_provincia                   NUMBER(3)    NOT NULL,
 cod_comune                      NUMBER(3)    NOT NULL,
 dal                             DATE         NOT NULL,
 al                              DATE                 ,
 esenzione                       NUMBER(15,5)     NULL,
 scaglione                       NUMBER(15,5) NOT NULL,
 aliquota                        NUMBER(8,5)      NULL,
 imposta                         NUMBER(15,5)     NULL

)
;

COMMENT ON TABLE addizionale_irpef_comunale
    IS 'AICO - Addizionale IRPEF Comunale';

REM
REM 
REM
PROMPT
PROMPT Creating Unique Index AICO_PK on Table ADDIZIONALE_IRPEF_COMUNALE
CREATE UNIQUE INDEX AICO_PK ON ADDIZIONALE_IRPEF_COMUNALE
(
      cod_provincia ,
      cod_comune ,
      dal ,
      scaglione)
;

REM
REM 
REM
PROMPT
PROMPT Creating Index AICO_IK on Table ADDIZIONALE_IRPEF_COMUNALE
CREATE INDEX AICO_IK ON ADDIZIONALE_IRPEF_COMUNALE
(
      cod_provincia ,
      cod_comune )
;


REM
REM  End of command file
REM
