REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      POSTI_PIANTA
REM INDEX
REM      POPI_ATTI_FK
REM      POPI_DELI_FK
REM      POPI_FIGU_FK
REM      POPI_GRDI_FK
REM      POPI_PK
REM      POPI_SETT_ASS_FK
REM      POPI_SETT_PIA_FK

REM
REM     POPI - Caratteristiche storiche del Posto in Pianta Organica
REM
PROMPT 
PROMPT Creating Table POSTI_PIANTA
CREATE TABLE posti_pianta(
 pianta                          NUMBER(6,0)      NOT NULL,
 settore                         NUMBER(6,0)      NOT NULL,
 figura                          NUMBER(6,0)      NOT NULL,
 attivita                        VARCHAR(4)       NULL,
 sede_posto                      VARCHAR(4)       NOT NULL,
 anno_posto                      NUMBER(4,0)      NOT NULL,
 numero_posto                    NUMBER(7,0)      NOT NULL,
 posto                           NUMBER(4,0)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 ore                             NUMBER(5,2)      NULL,
 situazione                      VARCHAR(1)       NOT NULL,
 sede_prov                       VARCHAR(4)       NULL,
 anno_prov                       NUMBER(4,0)      NULL,
 numero_prov                     NUMBER(7,0)      NULL,
 disponibilita                   VARCHAR(1)       NOT NULL,
 gruppo                          VARCHAR(12)      NULL,
 stato                           VARCHAR(1)       NOT NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL
)
;

COMMENT ON TABLE posti_pianta
    IS 'POPI - Caratteristiche storiche del Posto in Pianta Organica';


REM
REM 
REM
PROMPT
PROMPT Creating Index POPI_ATTI_FK on Table POSTI_PIANTA
CREATE INDEX POPI_ATTI_FK ON POSTI_PIANTA
(
      attivita )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index POPI_DELI_FK on Table POSTI_PIANTA
CREATE INDEX POPI_DELI_FK ON POSTI_PIANTA
(
      sede_prov ,
      anno_prov ,
      numero_prov )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index POPI_FIGU_FK on Table POSTI_PIANTA
CREATE INDEX POPI_FIGU_FK ON POSTI_PIANTA
(
      figura )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index POPI_GRDI_FK on Table POSTI_PIANTA
CREATE INDEX POPI_GRDI_FK ON POSTI_PIANTA
(
      gruppo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index POPI_PK on Table POSTI_PIANTA
CREATE UNIQUE INDEX POPI_PK ON POSTI_PIANTA
(
      sede_posto ,
      anno_posto ,
      numero_posto ,
      posto ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index POPI_SETT_ASS_FK on Table POSTI_PIANTA
CREATE INDEX POPI_SETT_ASS_FK ON POSTI_PIANTA
(
      settore )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index POPI_SETT_PIA_FK on Table POSTI_PIANTA
CREATE INDEX POPI_SETT_PIA_FK ON POSTI_PIANTA
(
      pianta )
PCTFREE  10
;

REM
REM  End of command file
REM
