REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RELAZIONE_COND_OGGETTO
REM INDEX
REM      RECO_PK

REM
REM     RECO - Condizioni di relazione tra oggetti previsti dalle Estrazioni Pa
REM - rametriche
REM
PROMPT 
PROMPT Creating Table RELAZIONE_COND_OGGETTO
CREATE TABLE relazione_cond_oggetto(
 oggetto                         VARCHAR(10)      NOT NULL,
 riferimento                     VARCHAR(10)      NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 relazione                       VARCHAR(60)      NOT NULL
)
;

COMMENT ON TABLE relazione_cond_oggetto
    IS 'RECO - Condizioni di relazione tra oggetti previsti dalle Estrazioni Parametriche';


REM
REM 
REM
PROMPT
PROMPT Creating Index RECO_PK on Table RELAZIONE_COND_OGGETTO
CREATE UNIQUE INDEX RECO_PK ON RELAZIONE_COND_OGGETTO
(
      oggetto ,
      riferimento ,
      sequenza )
PCTFREE  10
;

REM
REM  End of command file
REM
