REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CONTRATTI
REM INDEX
REM      CONT_PK

REM
REM     CONT - Contratti di lavoro gestiti nella retribuzione
REM
PROMPT 
PROMPT Creating Table CONTRATTI
CREATE TABLE contratti(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NOT NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL
)
;

COMMENT ON TABLE contratti
    IS 'CONT - Contratti di lavoro gestiti nella retribuzione';


REM
REM 
REM
PROMPT
PROMPT Creating Index CONT_PK on Table CONTRATTI
CREATE UNIQUE INDEX CONT_PK ON CONTRATTI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
