REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      INFORMAZIONI_EXTRACONTABILI
REM INDEX
REM      INEX_ANNO_IK
REM      INEX_PK

REM
REM     INEX - Informazioni contabili particolari o di rilevanza annuale
REM
PROMPT 
PROMPT Creating Table INFORMAZIONI_EXTRACONTABILI
CREATE TABLE informazioni_extracontabili(
 ci                              NUMBER(8,0)      NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 ipn_1ap                         NUMBER(12,2)     NULL,
 ipn_2ap                         NUMBER(12,2)     NULL,
 alq_ap                          NUMBER(4,2)      NULL,
 ipn_fam_1ap                     NUMBER(12,2)     NULL,
 ipn_fam_2ap                     NUMBER(12,2)     NULL,
 perc_irpef_ord                  NUMBER(4,2)      NULL,
 perc_irpef_sep                  NUMBER(4,2)      NULL,
 base_cong                       VARCHAR(1)       NULL,
 effe_cong                       VARCHAR(1)       NULL,
 det_con                         NUMBER(12,2)     NULL,
 det_fig                         NUMBER(12,2)     NULL,
 det_alt                         NUMBER(12,2)     NULL,
 det_spe                         NUMBER(12,2)     NULL,
 det_ult                         NUMBER(12,2)     NULL,
 ant_liq_ap                      NUMBER(12,2)     NOT NULL,
 ant_acc_ap                      NUMBER(12,2)     NOT NULL,
 ipt_liq_ap                      NUMBER(12,2)     NOT NULL,
 fdo_tfr_ap                      NUMBER(12,2)     NULL,
 gg_anz_c                        NUMBER(5,0)      NULL,
 ditta1                          VARCHAR(30)      NULL,
 ipn_1                           NUMBER(12,2)     NULL,
 ipn_no_ssn_1                    NUMBER(12,2)     NULL,
 ipn_ass_1                       NUMBER(12,2)     NULL,
 ipt_1                           NUMBER(12,2)     NULL,
 add_reg_1                       NUMBER(12,2)     NULL,
 add_pro_1                       NUMBER(12,2)     NULL,
 add_com_1                       NUMBER(12,2)     NULL,
 ditta2                          VARCHAR(30)      NULL,
 ipn_2                           NUMBER(12,2)     NULL,
 ipn_no_ssn_2                    NUMBER(12,2)     NULL,
 ipn_ass_2                       NUMBER(12,2)     NULL,
 ipt_2                           NUMBER(12,2)     NULL,
 add_reg_2                       NUMBER(12,2)     NULL,
 add_pro_2                       NUMBER(12,2)     NULL,
 add_com_2                       NUMBER(12,2)     NULL,
 ditta3                          VARCHAR(30)      NULL,
 ipn_3                           NUMBER(12,2)     NULL,
 ipn_no_ssn_3                    NUMBER(12,2)     NULL,
 ipn_ass_3                       NUMBER(12,2)     NULL,
 ipt_3                           NUMBER(12,2)     NULL,
 add_reg_3                       NUMBER(12,2)     NULL,
 add_pro_3                       NUMBER(12,2)     NULL,
 add_com_3                       NUMBER(12,2)     NULL,
 ipn_liq_ap                      NUMBER(12,2)     NULL,
 titolo_ap                       VARCHAR(1)       NULL,
 min_anno_ap                     NUMBER(4,0)      NULL,
 nr_anni_ap                      NUMBER(2,0)      NULL,
 perc_irpef_liq                  NUMBER(4,2)      NULL,
 titolo_tfr                      VARCHAR(2)       NULL,
 titolo_as                       VARCHAR(2)       NULL,
 rid_tfr                         NUMBER(12,2)     NULL,
 rid_rid_tfr                     NUMBER(12,2)     NULL,
 fdo_tfr_2000                    number(12,2)     NULL,
 riv_tfr_ap                      number(12,2)     NULL,
 ant_acc_2000                    number(12,2)     NULL,
 gg_anz_t_2000                   number(5,0)      NULL,
 gg_anz_i_2000                   number(5,0)      NULL,
 gg_anz_r_2000                   number(7,2)      NULL,
 cond_add			 number(1)        NULL,
 maggiore_ritenuta               varchar(1)       NULL,
 det_liq_ap                      number(12,2)     NULL,
 ipn_ded                         NUMBER(12,2)     NULL,
 ipn_ded_magg                    NUMBER(12,2)     NULL,
 ipn_onaosi_magg                 NUMBER(12,2)     NULL,
 aut_ass_fam                     varchar2(2)      NOT NULL,
 aut_ded_fam                     varchar2(2)      NOT NULL,
 perc_car_fam                    NUMBER(2)        NULL,
 ipn_fam_1                       NUMBER(12,2)     NULL,
 ipn_fam_2                       NUMBER(12,2)     NULL,
 ipn_fam_3                       NUMBER(12,2)     NULL,
 ipn_fam_4                       NUMBER(12,2)     NULL,
 ipn_fam_5                       NUMBER(12,2)     NULL,
 ipn_fam_6                       NUMBER(12,2)     NULL,
 ipn_fam_7                       NUMBER(12,2)     NULL,
 ipn_fam_8                       NUMBER(12,2)     NULL,
 ipn_fam_9                       NUMBER(12,2)     NULL,
 ipn_fam_10                      NUMBER(12,2)     NULL,
 ipn_fam_11                      NUMBER(12,2)     NULL,
 ipn_fam_12                      NUMBER(12,2)     NULL,
 rinuncia_esenzione_add_com      VARCHAR2(2)      NULL
)
;

COMMENT ON TABLE informazioni_extracontabili
    IS 'INEX - Informazioni contabili particolari o di rilevanza annuale';


REM
REM 
REM
PROMPT
PROMPT Creating Index INEX_ANNO_IK on Table INFORMAZIONI_EXTRACONTABILI
CREATE INDEX INEX_ANNO_IK ON INFORMAZIONI_EXTRACONTABILI
(
      anno )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index INEX_PK on Table INFORMAZIONI_EXTRACONTABILI
CREATE UNIQUE INDEX INEX_PK ON INFORMAZIONI_EXTRACONTABILI
(
      ci ,
      anno )
PCTFREE  10
;

REM
REM  End of command file
REM
