REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  05-AUG-94
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLO_NOMINATIVO_DOTAZIONE
REM INDEX
REM      DNPE_IK
REM      DNPE_IK2

REM
REM     
REM
PROMPT 
PROMPT Creating Table CALCOLO_NOMINATIVO_DOTAZIONE
CREATE TABLE calcolo_nominativo_dotazione(
 dnpe_prenotazione               NUMBER(6,0)      NOT NULL,
 dnpe_rilevanza                  NUMBER(2,0)      NULL,
 pegi_evento                     VARCHAR(4)       NULL,
 pegi_sede_del                   VARCHAR(4)       NULL,
 pegi_anno_del                   NUMBER(4)        NULL,
 pegi_numero_del                 NUMBER(7)        NULL,
 pegi_settore                    NUMBER(6,0)      NULL,
 sett_settore_g                  NUMBER(6,0)      NULL,
 sett_settore_a                  NUMBER(6,0)      NULL,
 sett_settore_b                  NUMBER(6,0)      NULL,
 sett_settore_c                  NUMBER(6,0)      NULL,
 sett_codice                     VARCHAR(15)      NULL,
 sett_suddivisione               NUMBER(1,0)      NULL,
 sett_gestione                   VARCHAR(4)       NULL,
 setg_codice                     VARCHAR(15)      NULL,
 seta_codice                     VARCHAR(15)      NULL,
 setb_codice                     VARCHAR(15)      NULL,
 setc_codice                     VARCHAR(15)      NULL,
 pegi_sede                       NUMBER(6,0)      NULL,
 sedi_codice                     VARCHAR(8)       NULL,
 pegi_figura                     NUMBER(6,0)      NULL,
 figi_codice                     VARCHAR(8)       NULL,
 pegi_qualifica                  NUMBER(6,0)      NULL,
 qugi_codice                     VARCHAR(8)       NULL,
 qugi_contratto                  VARCHAR(4)       NULL,
 qugi_livello                    VARCHAR(4)       NULL,
 qugi_ruolo                      VARCHAR(4)       NULL,
 figi_posizione                  VARCHAR(4)       NULL,
 figi_profilo                    VARCHAR(4)       NULL,
 pegi_attivita                   VARCHAR(4)       NULL,
 pegi_posizione                  VARCHAR(4)       NULL,
 pegi_tipo_rapporto              VARCHAR(4)       NULL,
 pegi_ore                        NUMBER(5,2)      NULL,
 pegi_ci                         NUMBER(8)        NULL,
 pegi_rilevanza                  VARCHAR(1)       NULL,
 pegi_assenza                    VARCHAR(4)       NULL,
 pegi_dal                        DATE             NULL,
 pegi_al                         DATE             NULL,
 pegi_rilevanza_presenza         VARCHAR(1)       NULL,
 pegi_dal_presenza               DATE             NULL,
 popi_sede_posto                 VARCHAR(4)       NULL,
 popi_anno_posto                 NUMBER(4)        NULL,
 popi_numero_posto               NUMBER(8)        NULL,
 popi_posto                      NUMBER(5)        NULL,
 popi_disponibilita              VARCHAR(1)       NULL,
 popi_gruppo                     VARCHAR(12)      NULL,
 rain_cognome                    VARCHAR(36)      NULL,
 rain_nome                       VARCHAR(36)      NULL,
 dnpe_mm_eta                     NUMBER(2,0)      NULL,
 dnpe_aa_eta                     NUMBER(2,0)      NULL,
 dnpe_gg_anz                     NUMBER(2,0)      NULL,
 dnpe_mm_anz                     NUMBER(2,0)      NULL,
 dnpe_aa_anz                     NUMBER(2,0)      NULL
)
;


REM
REM 
REM
PROMPT
PROMPT Creating Index DNPE_IK on Table CALCOLO_NOMINATIVO_DOTAZIONE
CREATE INDEX DNPE_IK ON CALCOLO_NOMINATIVO_DOTAZIONE
(
      dnpe_prenotazione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index DNPE_IK2 on Table CALCOLO_NOMINATIVO_DOTAZIONE
CREATE INDEX DNPE_IK2 ON CALCOLO_NOMINATIVO_DOTAZIONE
(
      pegi_ci )
PCTFREE  10
;

REM
REM  End of command file
REM
