REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  30-Mar-93 08:18
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIGHE_RIPARTIZIONE_LINGUISTICA
REM INDEX
REM      RRLI_PK
REM      RRLI_POFU_FK
REM      RRLI_RILI_FK

REM
REM    RRLI - Righe di composizione della Ripartizione Linguistica
REM
PROMPT 
PROMPT Creating Table RIGHE_RIPARTIZIONE_LINGUISTICA
CREATE TABLE righe_ripartizione_linguistica(
 ripartizione                    VARCHAR (8)      NOT NULL,
 settore                         NUMBER (6,0)     NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 sequenza                        NUMBER (3,0)     NOT NULL,
 profilo                         VARCHAR (4)      NOT NULL,
 posizione                       VARCHAR (4)      NOT NULL
)
;

COMMENT ON TABLE righe_ripartizione_linguistica
    IS 'RRLI - Righe di composizione della Ripartizione Linguistica';

COMMENT ON COLUMN righe_ripartizione_linguistica.ripartizione
    IS 'Codice di ripartizione del personale';

COMMENT ON COLUMN righe_ripartizione_linguistica.settore
    IS 'Numero identificativo della suddivisione';

COMMENT ON COLUMN righe_ripartizione_linguistica.dal
    IS 'Data di inizio validita` della ripartizione';

COMMENT ON COLUMN righe_ripartizione_linguistica.sequenza
    IS 'Sequenza di composizione della ripartizione';

COMMENT ON COLUMN righe_ripartizione_linguistica.profilo
    IS 'Codice del Profilo Professionale';

COMMENT ON COLUMN righe_ripartizione_linguistica.posizione
    IS 'Codice della Posizione Funzionale';


REM
REM 
REM
REM GENERATED CANDIDATE INDEX
REM

PROMPT
PROMPT Creating Index RRLI_PK on Table RIGHE_RIPARTIZIONE_LINGUISTICA
CREATE UNIQUE INDEX RRLI_PK ON RIGHE_RIPARTIZIONE_LINGUISTICA
(
      ripartizione ,
      settore ,
      dal ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
REM GENERATED CANDIDATE INDEX
REM

PROMPT
PROMPT Creating Index RRLI_POFU_FK on Table RIGHE_RIPARTIZIONE_LINGUISTICA
CREATE INDEX RRLI_POFU_FK ON RIGHE_RIPARTIZIONE_LINGUISTICA
(
      profilo ,
      posizione )
PCTFREE  10
;


REM
REM 
REM
REM GENERATED CANDIDATE INDEX
REM

PROMPT
PROMPT Creating Index RRLI_RILI_FK on Table RIGHE_RIPARTIZIONE_LINGUISTICA
CREATE INDEX RRLI_RILI_FK ON RIGHE_RIPARTIZIONE_LINGUISTICA
(
      ripartizione ,
      settore ,
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
