REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-MAY-97
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DENUNCIA_INAIL
REM INDEX
REM      DEIN_PK
REM      DEIN_IK

REM
REM     DEIN - Denuncia INAIL 
REM
PROMPT 
PROMPT Creating DENUNCIA_INAIL
CREATE TABLE denuncia_inail (
 dein_id                         NUMBER(10)     NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 gestione                        VARCHAR(8)       NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 pos_inail                       VARCHAR(12)          NULL,
 tipo_variazione                 VARCHAR(1)           NULL,
 data_variazione                 DATE                 NULL,
 dal                             DATE                 NULL,
 al                              DATE                 NULL,
 qua_inps                        VARCHAR(1)           NULL,
 part_time                       VARCHAR(2)           NULL,
 tempo_determinato               VARCHAR(2)           NULL,
 qua_fiscale                     VARCHAR(2)           NULL,
 qua_inail                       VARCHAR(2)           NULL,
 cap                             VARCHAR(5)           NULL,
 codice_catasto                  VARCHAR(4)           NULL,
 UTENTE                          VARCHAR2(8)          NULL,
 TIPO_AGG                        VARCHAR2(1)          NULL,
 DATA_AGG                        DATE
)
;

COMMENT ON TABLE denuncia_inail
    IS 'DEIN - Denuncia INAIL: tabella di lavoro per variazioni';

REM
REM 
REM
PROMPT
PROMPT Creating Unique Index DEIN_PK on Table DENUNCIA_INAIL
CREATE UNIQUE INDEX DEIN_PK ON DENUNCIA_INAIL
( dein_id )
;

REM
REM 
REM
PROMPT
PROMPT Creating Index DEIN_IK on Table DENUNCIA_INAIL
CREATE INDEX DEIN_IK ON DENUNCIA_INAIL
(
      anno ,
      pos_inail ,
      gestione )
PCTFREE  10
;

REM
REM  End of command file
REM
