REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RELAZIONE_ATTR_CHIAVE
REM INDEX
REM      REAC_PK
REM      REAC_REAT_FK

REM
REM     REAC - Abbinamento tra chiavi e attributi previsti dalle Estrazioni Par
REM - ametriche
REM
PROMPT 
PROMPT Creating Table RELAZIONE_ATTR_CHIAVE
CREATE TABLE relazione_attr_chiave(
 chiave                          VARCHAR(20)      NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 attributo                       VARCHAR(20)      NOT NULL,
 descrizione                     VARCHAR(60)      NULL,
 descrizione_al1                 VARCHAR(60)      NULL,
 descrizione_al2                 VARCHAR(60)      NULL,
 alias                           VARCHAR(20)      NOT NULL
)
;

COMMENT ON TABLE relazione_attr_chiave
    IS 'REAC - Abbinamento tra chiavi e attributi previsti dalle Estrazioni Parametriche';


REM
REM 
REM
PROMPT
PROMPT Creating Index REAC_PK on Table RELAZIONE_ATTR_CHIAVE
CREATE UNIQUE INDEX REAC_PK ON RELAZIONE_ATTR_CHIAVE
(
      chiave ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index REAC_REAT_FK on Table RELAZIONE_ATTR_CHIAVE
CREATE INDEX REAC_REAT_FK ON RELAZIONE_ATTR_CHIAVE
(
      attributo )
PCTFREE  10
;

REM
REM  End of command file
REM
