REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  30-MAY-94
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DENUNCIA_IMPORTI_INADEL
REM INDEX
REM      DIID_DEID_FK

REM
REM     DIID - Archivio Importi Denuncia I.N.A.D.E.L.
REM
PROMPT 
PROMPT Creating Table DENUNCIA_IMPORTI_INADEL
CREATE TABLE denuncia_importi_inadel(
 anno                            NUMBER(4,0)      NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 riferimento                     NUMBER(4,0)      NULL,
 codice                          VARCHAR(10)      NULL,
 importo                         NUMBER(12,2)     NULL,
 utente                          VARCHAR(8)       NULL,
 tipo_agg                        VARCHAR(1)       NULL,
 data_agg                        DATE             NULL,
 contributi                      NUMBER(12,2)     NULL
)
;

COMMENT ON TABLE denuncia_importi_inadel
    IS 'DIID - Archivio Importi Denuncia I.N.A.D.E.L.';


REM
REM 
REM
PROMPT
PROMPT Creating Index DIID_DEID_FK on Table DENUNCIA_IMPORTI_INADEL
CREATE INDEX DIID_DEID_FK ON DENUNCIA_IMPORTI_INADEL
(
      anno ,
      ci )
PCTFREE  10
;

REM
REM  End of command file
REM
