REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  01-DEC-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      INFORMAZIONI_ADD_FISCALI
REM INDEX
REM      INAF_PK

REM
REM     INAF - Informazioni Addizionali Fiscali
REM
PROMPT 
PROMPT Creating Table INFORMAZIONI_ADD_FISCALI
CREATE TABLE informazioni_add_fiscali(
 ci                              NUMBER(8)       NOT NULL,
 anno                            NUMBER(4)       NOT NULL,
 data_riferimento                DATE            NOT NULL,
 numero_figli                    NUMBER(2)       NULL,
 numero_disabili                 NUMBER(2)       NULL,
 tipo_carico                     NUMBER(1)       NULL,
 reddito_aggiuntivo              NUMBER(12,2)    NULL,
 utente                          VARCHAR2(8)     NULL,
 tipo_agg                        VARCHAR2(1)     NULL,
 data_agg                        DATE            NULL
)
;

COMMENT ON TABLE informazioni_add_fiscali
    IS 'INAF - Informazioni Addizionali Fiscali';


REM
REM 
REM
PROMPT
PROMPT Creating Index INAF_PK on Table INFORMAZIONI_ADD_FISCALI
CREATE UNIQUE INDEX INAF_PK ON INFORMAZIONI_ADD_FISCALI
(
      ci
    , anno
    , data_riferimento
)
PCTFREE  10
;

REM
REM  End of command file
REM
