REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CERTIFICATI
REM INDEX
REM      CERT_PK

REM
REM     CERT - Certificati di servizio elaborabili
REM
PROMPT 
PROMPT Creating Table CERTIFICATI
CREATE TABLE certificati(
 codice                          VARCHAR2(4)       NOT NULL,
 descrizione                     VARCHAR2(40)      NULL,
 descrizione_al1                 VARCHAR2(40)      NULL,
 descrizione_al2                 VARCHAR2(40)      NULL,
 note                            VARCHAR2(40)      NULL,
 note_al1                        VARCHAR2(40)      NULL,
 note_al2                        VARCHAR2(40)      NULL,
 decorrenza                      VARCHAR2(2)       NOT NULL,
 oggetto                         VARCHAR2(2)       NOT NULL,
 servizio                        VARCHAR2(2)       NOT NULL,
 note_ind                        VARCHAR2(2)       NOT NULL,
 ruolo                           VARCHAR2(2)       NOT NULL,
 attivita                        VARCHAR2(2)       NOT NULL,
 delibera                        VARCHAR2(2)       NOT NULL,
 esecutivita                     VARCHAR2(2)       NOT NULL,
 durata                          VARCHAR2(2)       NOT NULL,
 cessazione                      VARCHAR2(2)       NOT NULL,
 assenze                         VARCHAR2(2)       NOT NULL,
 economico                       VARCHAR2(2)       NOT NULL,
 f_int                           VARCHAR2(4)       NULL,
 f_pre                           VARCHAR2(4)       NULL,
 f_ser                           VARCHAR2(4)       NULL,
 f_dim                           VARCHAR2(4)       NULL,
 f_not                           VARCHAR2(4)       NULL,
 f_con                           VARCHAR2(4)       NULL,
 f_fir                           VARCHAR2(4)       NULL,
 SITUAZIONI_RATEALI              VARCHAR2(2)       default 'NO' NOT NULL,
 TEMPO_DETERMINATO               VARCHAR2(2)       default 'NO' NOT NULL,
 PART_TIME                       VARCHAR2(2)       default 'NO' NOT NULL,
 POS_ECONOMICA                   VARCHAR2(2)       default 'NO' NOT NULL,
 tipo_rapporto			   VARCHAR2(2)       NOT NULL,
 AUTOCERTIFICAZIONE              VARCHAR2(2)	   NOT NULL,
 U_PRESSO                        VARCHAR2(2)       NOT NULL
)
;

COMMENT ON TABLE certificati
    IS 'CERT - Certificati di servizio elaborabili';


REM
REM 
REM
PROMPT
PROMPT Creating Index CERT_PK on Table CERTIFICATI
CREATE UNIQUE INDEX CERT_PK ON CERTIFICATI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
