REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN ON

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLI_CONTABILI_DEP
REM INDEX
REM      CACD_IK
REM      CACD_IK2
REM      CACD_VOCO_FK

REM
REM     CACD - Calcolo transitorio dei movimenti contabili di retribuzione
REM
PROMPT 
PROMPT Creating Table CALCOLI_CONTABILI_DEP
CREATE TABLE calcoli_contabili_dep(
 ci                              NUMBER(8,0)      NOT NULL,
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL,
 riferimento                     DATE             NOT NULL,
 arr                             VARCHAR(1)       NULL,
 input                           VARCHAR(1)       NOT NULL,
 estrazione                      VARCHAR(2)       NOT NULL,
 data                            DATE             NULL,
 qualifica                       NUMBER(6,0)      NULL,
 tipo_rapporto                   VARCHAR(4)       NULL,
 ore                             NUMBER(5,2)      NULL,
 tar                             NUMBER(15,5)     NULL,
 qta                             NUMBER(15,5)     NULL,
 imp                             NUMBER(12,2)     NULL,
 sede_del                        VARCHAR(4)       NULL,
 anno_del                        NUMBER(4,0)      NULL,
 numero_del                      NUMBER(7,0)      NULL,
 risorsa_intervento              VARCHAR(7)       NULL,
 capitolo                        VARCHAR(14)      NULL,
 articolo                        VARCHAR(14)      NULL,
 impegno                         NUMBER(5)        NULL,
 conto                           VARCHAR(2)       NULL,
 ipn_c                           NUMBER(12,2)     NULL,
 ipn_s                           NUMBER(12,2)     NULL,
 ipn_p                           NUMBER(12,2)     NULL,
 ipn_l                           NUMBER(12,2)     NULL,
 ipn_e                           NUMBER(12,2)     NULL,
 ipn_t                           NUMBER(12,2)     NULL,
 ipn_eap                         NUMBER(12,2)     NULL,
 competenza                      DATE             NULL,
 ipn_a                           NUMBER(12,2)     NULL,
 ipn_ap                          NUMBER(12,2)     NULL,
 anno_impegno                    NUMBER(4)        NULL,
 sub_impegno                     NUMBER(5)        NULL,
 anno_sub_impegno                NUMBER(4)        NULL,
 codice_siope		         NUMBER(4)        NULL
)
;

COMMENT ON TABLE calcoli_contabili_dep
    IS 'CACO_DEP - Calcolo transitorio dei movimenti contabili di retribuzione';


REM
REM 
REM
PROMPT
PROMPT Creating Index CACD_IK on Table CALCOLI_CONTABILI_DEP
CREATE INDEX CACD_IK ON CALCOLI_CONTABILI_DEP
(
      ci )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CACD_IK2 on Table CALCOLI_CONTABILI_DEP
CREATE INDEX CACD_IK2 ON CALCOLI_CONTABILI_DEP
(
      estrazione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CACD_VOCO_FK on Table CALCOLI_CONTABILI_DEP
CREATE INDEX CACD_VOCO_FK ON CALCOLI_CONTABILI_DEP
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
