REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VOCI_CONTABILI_EVENTO
REM INDEX
REM      VCEV_FOCA_FK
REM      VCEV_PK
REM      VCEV_VOCO_FK

REM
REM     VCEV - Voci contabili per la valorizzazione dell" evento a causale
REM
PROMPT 
PROMPT Creating Table VOCI_CONTABILI_EVENTO
CREATE TABLE voci_contabili_evento(
 causale                         VARCHAR(8)       NOT NULL,
 assistenza                      VARCHAR(6)       NOT NULL,
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL,
 gestione                        VARCHAR(1)       NOT NULL,
 specie                          VARCHAR(1)       NULL,
 tipo                            VARCHAR(8)       NULL,
 formula                         VARCHAR(8)       NULL,
 moltiplica                      NUMBER(15,5)     NULL,
 divide                          NUMBER(15,5)     NULL,
 aliquota                        NUMBER(5,2)      NULL,
 decimali                        NUMBER(1,0)      NULL,
 prospetto                       VARCHAR(2)       NULL,
 part_time						 VARCHAR(2)		  NULL
)
;

COMMENT ON TABLE voci_contabili_evento
    IS 'VCEV - Voci contabili per la valorizzazione dell" evento a causale';


REM
REM 
REM
PROMPT
PROMPT Creating Index VCEV_FOCA_FK on Table VOCI_CONTABILI_EVENTO
CREATE INDEX VCEV_FOCA_FK ON VOCI_CONTABILI_EVENTO
(
      formula )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VCEV_PK on Table VOCI_CONTABILI_EVENTO
CREATE UNIQUE INDEX VCEV_PK ON VOCI_CONTABILI_EVENTO
(
      causale ,
      assistenza ,
      voce ,
      sub )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VCEV_VOCO_FK on Table VOCI_CONTABILI_EVENTO
CREATE INDEX VCEV_VOCO_FK ON VOCI_CONTABILI_EVENTO
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
