REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIFERIMENTO_ORGANICO
REM INDEX
REM      RIOR_PK

REM
REM     RIOR - Data di riferimento della situazione organica
REM
PROMPT 
PROMPT Creating Table RIFERIMENTO_ORGANICO
CREATE TABLE riferimento_organico(
 rior_id                         VARCHAR(4)       NOT NULL,
 data                            DATE             NOT NULL
)
;

COMMENT ON TABLE riferimento_organico
    IS 'RIOR - Data di riferimento della situazione organica';


REM
REM Identificatore unico di registrazione
REM
PROMPT
PROMPT Creating Index RIOR_PK on Table RIFERIMENTO_ORGANICO
CREATE UNIQUE INDEX RIOR_PK ON RIFERIMENTO_ORGANICO
(
      rior_id )
PCTFREE  10
;

REM
REM  End of command file
REM
