REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM     TIPI_RAPPORTO
REM INDEX
REM     TIRA_PK

REM
REM     TIRA - Tipi di Rapporto per Periodi Giuridici
REM
PROMPT 
PROMPT Creating Table TIPI_RAPPORTO
create table tipi_rapporto
(codice            varchar(4) NOT NULL,
 sequenza          number(4),
 descrizione       varchar(30),
 descrizione_al1   varchar(30),
 descrizione_al2   varchar(30),
 stampa_certificato varchar2(2) NOT NULL,
 conto_annuale     number(2),
 note              varchar2(4000)
)
;

COMMENT ON TABLE TIPI_RAPPORTO
    IS 'TIRA - Tipi di Rapporto per Periodi Giuridici';

REM
REM 
REM
PROMPT
PROMPT Creating Index TIRA_PK on Table TIPI_RAPPORTO
create unique index tira_pk
on tipi_rapporto (codice)
;


REM
REM  End of command file
REM



