REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ASTENSIONI
REM INDEX
REM      ASTE_EVGI_FK
REM      ASTE_PK

REM
REM     ASTE - Tipologie di astensione dal servizio
REM
PROMPT 
PROMPT Creating Table ASTENSIONI
CREATE TABLE astensioni(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(120)     NULL,
 descrizione_al1                 VARCHAR(120)     NULL,
 descrizione_al2                 VARCHAR(120)     NULL,
 sequenza                        NUMBER(3,0)      NULL,
 evento                          VARCHAR(6)       NOT NULL,
 conferma                        NUMBER(1,0)      NOT NULL,
 per_ret                         NUMBER(5,2)      NOT NULL,
 incide_gepe                     VARCHAR(2)       NOT NULL,
 incide_gipe                     VARCHAR(2)       NOT NULL,
 mat_anz                         NUMBER(1,0)      NOT NULL,
 mat_fer                         NUMBER(1,0)      NOT NULL,
 mat_inps                        NUMBER(1,0)      NOT NULL,
 mat_assfam                      NUMBER(1,0)      NOT NULL,
 conguaglio                      NUMBER(1,0)      NOT NULL,
 detrazioni                      NUMBER(1,0)      NOT NULL,
 automatismi                     NUMBER(1,0)      NOT NULL,
 sostituibile                    NUMBER(1,0)      NOT NULL,
 servizio                        NUMBER(1,0)      NOT NULL,
 rivalutazione_tfr               NUMBER(1,0)      NOT NULL,
 cat_fiscale                     varchar(2)       NULL,
 servizio_inpdap                 varchar(2)       NULL,
 GG_SOST_ANTE_ASSENZA            NUMBER (3), 
 GG_SOST_POST_ASSENZA            NUMBER (3),
 NOTE                            varchar2(240)    NULL,
 NOTE_AL1                        varchar2(240)    NULL,
 NOTE_AL2                        varchar2(240)    NULL,
 DISOCCUPAZIONE_INPS             number (2)       NULL,
 LUNGA_ASSENZA                   VARCHAR2(2)	  DEFAULT 'NO' NOT NULL,
 mat_detfam                      NUMBER(1)        NOT NULL
)
;

COMMENT ON TABLE astensioni
    IS 'ASTE - Tipologie di astensione dal servizio';


REM
REM 
REM
PROMPT
PROMPT Creating Index ASTE_EVGI_FK on Table ASTENSIONI
CREATE INDEX ASTE_EVGI_FK ON ASTENSIONI
(
      evento )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ASTE_PK on Table ASTENSIONI
CREATE UNIQUE INDEX ASTE_PK ON ASTENSIONI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
