REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  06-OCT-94
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      EVENTI_PRESENZA_CONSOLIDATI

REM
REM     
REM
PROMPT 
PROMPT Creating Table EVENTI_PRESENZA_CONSOLIDATI
CREATE TABLE eventi_presenza_consolidati(
 evento                          NUMBER(10,0)     NULL,
 ci                              NUMBER(8,0)      NULL,
 causale                         VARCHAR(8)       NULL,
 motivo                          VARCHAR(8)       NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 riferimento                     DATE             NULL,
 chiuso                          VARCHAR(2)       NULL,
 input                           VARCHAR(1)       NULL,
 classe                          NUMBER(10,0)     NULL,
 dalle                           NUMBER(4,0)      NULL,
 alle                            NUMBER(4,0)      NULL,
 valore                          NUMBER(12,2)     NULL,
 cdc                             VARCHAR(8)       NULL,
 sede                            NUMBER(6,0)      NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL,
 utente                          VARCHAR(8)       NULL,
 data_agg                        DATE             NULL
)
;

REM
REM  End of command file
REM
