CREATE TABLE ATTIVITA_INFORTUNIO ( 
  ATTIVITA     VARCHAR2 (6)  NOT NULL, 
  DESCRIZIONE  VARCHAR2 (120)  NOT NULL, 
  SEQUENZA     NUMBER(4), 
  STATISTICO   VARCHAR2 (6));

CREATE INDEX atin_PK ON ATTIVITA_INFORTUNIO 
(attivita )
;
