REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PAM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CONVOCAZIONI
REM INDEX
REM      CONV_CORR2_FK
REM      CONV_CORR_FK
REM      CONV_DELI_FK
REM      CONV_PK
REM      CONV_RAIN_PK

REM
REM     CONV - Estremi inerenti alla convocazione o a corrispondenza con l"indi
REM - viduo
REM
PROMPT 
PROMPT Creating Table CONVOCAZIONI
CREATE TABLE convocazioni(
 ci                              NUMBER(8,0)      NOT NULL,
 data                            DATE             NOT NULL,
 oggetto                         VARCHAR(30)      NULL,
 oggetto_al1                     VARCHAR(30)      NULL,
 oggetto_al2                     VARCHAR(30)      NULL,
 esito                           VARCHAR(1)       NOT NULL,
 note                            VARCHAR(4000)    NULL,
 registro_eff                    VARCHAR(4)       NULL,
 anno_eff                        NUMBER(4,0)      NULL,
 numero_eff                      NUMBER(7,0)      NULL,
 registro_rif                    VARCHAR(4)       NULL,
 anno_rif                        NUMBER(4,0)      NULL,
 numero_rif                      NUMBER(7,0)      NULL,
 sede_del                        VARCHAR(4)       NULL,
 anno_del                        NUMBER(4,0)      NULL,
 numero_del                      NUMBER(7,0)      NULL
)
;

COMMENT ON TABLE convocazioni
    IS 'CONV - Estremi inerenti alla convocazione o a corrispondenza con l"individuo';


REM
REM 
REM
PROMPT
PROMPT Creating Index CONV_CORR2_FK on Table CONVOCAZIONI
CREATE INDEX CONV_CORR2_FK ON CONVOCAZIONI
(
      registro_rif ,
      anno_rif ,
      numero_rif )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CONV_CORR_FK on Table CONVOCAZIONI
CREATE INDEX CONV_CORR_FK ON CONVOCAZIONI
(
      registro_eff ,
      anno_eff ,
      numero_eff )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CONV_DELI_FK on Table CONVOCAZIONI
CREATE INDEX CONV_DELI_FK ON CONVOCAZIONI
(
      sede_del ,
      anno_del ,
      numero_del )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CONV_PK on Table CONVOCAZIONI
CREATE UNIQUE INDEX CONV_PK ON CONVOCAZIONI
(
      ci ,
      data )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CONV_RAIN_PK on Table CONVOCAZIONI
CREATE INDEX CONV_RAIN_PK ON CONVOCAZIONI
(
      ci )
PCTFREE  10
;

REM
REM  End of command file
REM
