REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  16-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIPARTIZIONE_MOTIVI
REM INDEX
REM      RIMO_FK
REM      RIMO_MOEV_FK

REM
REM     
REM
PROMPT 
PROMPT Creating Table RIPARTIZIONE_MOTIVI
CREATE TABLE ripartizione_motivi(
 classe                          VARCHAR(8)       NOT NULL,
 motivo                          VARCHAR(8)       NOT NULL,
 istat                           NUMBER(6,0)      NULL
)
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIMO_FK on Table RIPARTIZIONE_MOTIVI
CREATE UNIQUE INDEX RIMO_FK ON RIPARTIZIONE_MOTIVI
(
      classe ,
      motivo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIMO_MOEV_FK on Table RIPARTIZIONE_MOTIVI
CREATE INDEX RIMO_MOEV_FK ON RIPARTIZIONE_MOTIVI
(
      motivo )
PCTFREE  10
;

REM
REM  End of command file
REM
