REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  23-Dec-92 15:48
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      IMPUTAZIONI_CONTABILI
REM INDEX
REM      IMCO_IK

REM
REM    IMCO - Archivio di transito movimenti contabili in Bilancio
REM
PROMPT 
PROMPT Creating Table IMPUTAZIONI_CONTABILI
CREATE TABLE imputazioni_contabili(
 data                            DATE             NOT NULL,
 divisione                       VARCHAR2(4)      NOT NULL,
 esercizio                       NUMBER (4,0)     NOT NULL,
 e_s                             VARCHAR2(1)      NOT NULL,
 risorsa_intervento              VARCHAR2(7)      NOT NULL,
 capitolo                        VARCHAR2(8)      NOT NULL,
 articolo                        VARCHAR2(14)     NOT NULL,
 gestione                        NUMBER (4,0)     NOT NULL,
 funzionale                      VARCHAR2(8)      NULL,
 sede_del                        VARCHAR2(4)      NULL,
 anno_del                        NUMBER (4,0)     NULL,
 numero_del                      NUMBER (7,0)     NULL,
 impegno                         NUMBER (6,0)     NULL,
 sub                             NUMBER (6,0)     NULL,
 soggetto                        NUMBER (9,0)     NOT NULL,
 costo                           VARCHAR2(1)      NOT NULL,
 importo                         NUMBER (12,2)    NOT NULL,
 causale                         VARCHAR2(60)     NULL,
 sezione                         VARCHAR2(4)      NULL,
 anno_impegno                    NUMBER(4)        NULL,
 anno_sub                        NUMBER(4)        NULL,
 num_quietanza                   NUMBER(2)        NULL,
 codice_siope		         NUMBER(4)        NULL,
 UTENTE                          VARCHAR2(8)      NULL,
 DATA_AGG                        DATE             NULL
)
;

COMMENT ON TABLE imputazioni_contabili
    IS 'IMCO - Archivio di transito movimenti contabili in Bilancio';


REM
REM 
REM
REM 
REM

PROMPT
PROMPT Creating Index IMCO_IK on Table IMPUTAZIONI_CONTABILI
CREATE INDEX IMCO_IK ON IMPUTAZIONI_CONTABILI
(
      data )
PCTFREE  10
;

REM
REM  End of command file
REM
