REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  13-SEP-94
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ATTRIBUZIONE_EQUIPE_INCENTIVO
REM INDEX
REM      AEIP_EQIP_FK
REM      AEIP_PK
REM      AEIP_RIFU_FK

REM
REM     AEIP - Attribuzione della Equipe di appartenenza
REM
PROMPT 
PROMPT Creating Table ATTRIBUZIONE_EQUIPE_INCENTIVO
CREATE TABLE attribuzione_equipe_incentivo(
 gruppo                          VARCHAR(2)       NOT NULL,
 settore                         NUMBER(6,0)      NOT NULL,
 sede                            NUMBER(6,0)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 equipe                          VARCHAR(4)       NOT NULL
)
;

COMMENT ON TABLE attribuzione_equipe_incentivo
    IS 'AEIP - Attribuzione della Equipe di appartenenza';


REM
REM 
REM
PROMPT
PROMPT Creating Index AEIP_EQIP_FK on Table ATTRIBUZIONE_EQUIPE_INCENTIVO
CREATE INDEX AEIP_EQIP_FK ON ATTRIBUZIONE_EQUIPE_INCENTIVO
(
      equipe )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index AEIP_PK on Table ATTRIBUZIONE_EQUIPE_INCENTIVO
CREATE UNIQUE INDEX AEIP_PK ON ATTRIBUZIONE_EQUIPE_INCENTIVO
(
      gruppo ,
      settore ,
      sede ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index AEIP_RIFU_FK on Table ATTRIBUZIONE_EQUIPE_INCENTIVO
CREATE INDEX AEIP_RIFU_FK ON ATTRIBUZIONE_EQUIPE_INCENTIVO
(
      settore ,
      sede )
PCTFREE  10
;

REM
REM  End of command file
REM
