REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN ON
REM  Objects being generated in this file are:-
REM TABLE
REM      archivio_documenti_giuridici
REM INDEX
REM      adog_COMU_FK
REM      adog_DELI_FK
REM      adog_PK
REM      adog_SODO_FK

REM
REM     adog - Documenti e altri titoli non di carriera dell"individuo
REM
PROMPT 
PROMPT Creating Table archivio_documenti_giuridici
CREATE TABLE archivio_documenti_giuridici(
 ci                              NUMBER(8,0)      NOT NULL,
 evento                          VARCHAR2(6)       NOT NULL,
 scd                             VARCHAR2(6)       NOT NULL,
 del                             DATE             NOT NULL,
 descrizione                     VARCHAR2(30)      NULL,
 descrizione_al1                 VARCHAR2(30)      NULL,
 descrizione_al2                 VARCHAR2(30)      NULL,
 sede_del                        VARCHAR2(4)       NULL,
 numero_del                      NUMBER(7,0)      NULL,
 anno_del                        NUMBER(4,0)      NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 rilascio                        DATE             NULL,
 numero                          VARCHAR2(12)      NULL,
 categoria                       VARCHAR2(12)      NULL,
 presso                          VARCHAR2(40)      NULL,
 provincia                       NUMBER(3,0)      NULL,
 comune                          NUMBER(3,0)      NULL,
 scadenza                        DATE             NULL,
 rinnovo                         DATE             NULL,
 utente                          VARCHAR2(8)       NULL,
 data_agg                        DATE             NULL,
 dato_n1                         NUMBER(15,5)     NULL,
 dato_n2                         NUMBER(15,5)     NULL,
 dato_n3                         NUMBER(15,5)     NULL,
 dato_n4                         NUMBER(15,5)     NULL,
 dato_a1                         VARCHAR2(30)      NULL,
 dato_a2                         VARCHAR2(30)      NULL,
 dato_a3                         VARCHAR2(30)      NULL,
 dato_a4                         VARCHAR2(30)      NULL,
 note                            VARCHAR2(4000)    NULL,
 note_al1                        VARCHAR2(4000)    NULL,
 note_al2                        VARCHAR2(4000)    NULL
)
STORAGE  (
  INITIAL   &1DIMx50
  NEXT   &1DIMx50
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  50
  )
;

COMMENT ON TABLE archivio_documenti_giuridici
    IS 'adog - Documenti e altri titoli non di carriera dell"individuo';


REM
REM 
REM
PROMPT
PROMPT Creating Index adog_COMU_FK on Table archivio_documenti_giuridici
CREATE INDEX adog_COMU_FK ON archivio_documenti_giuridici
(
      provincia ,
      comune )
PCTFREE  10
STORAGE  (
  INITIAL   &1DIMx25
  NEXT   &1DIMx25
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  50
  )
;


REM
REM 
REM
PROMPT
PROMPT Creating Index adog_DELI_FK on Table archivio_documenti_giuridici
CREATE INDEX adog_DELI_FK ON archivio_documenti_giuridici
(
      sede_del ,
      anno_del ,
      numero_del )
PCTFREE  10
STORAGE  (
  INITIAL   &1DIMx25
  NEXT   &1DIMx25
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  50
  )
;


REM
REM 
REM
PROMPT
PROMPT Creating Index adog_PK on Table archivio_documenti_giuridici
CREATE UNIQUE INDEX adog_PK ON archivio_documenti_giuridici
(
      ci ,
      del ,
      evento ,
      scd )
PCTFREE  10
STORAGE  (
  INITIAL   &1DIMx25
  NEXT   &1DIMx25
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  50
  )
;


REM
REM 
REM
PROMPT
PROMPT Creating Index adog_SODO_FK on Table archivio_documenti_giuridici
CREATE INDEX adog_SODO_FK ON archivio_documenti_giuridici
(
      evento ,
      scd )
PCTFREE  10
STORAGE  (
  INITIAL   &1DIMx25
  NEXT   &1DIMx25
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  50
  )
;

REM
REM  End of command file
REM
