REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CONTRATTI_STORICI
REM INDEX
REM      COST_PK

REM
REM     COST - Attributi storici dei contratti di lavoro gestiti
REM
PROMPT 
PROMPT Creating Table CONTRATTI_STORICI
CREATE TABLE contratti_storici(
 contratto                       VARCHAR(4)       NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 note                            VARCHAR(4000)    NULL,
 note_al1                        VARCHAR(4000)    NULL,
 note_al2                        VARCHAR(4000)    NULL,
 dpr                             VARCHAR(12)      NULL,
 con_inps                        VARCHAR(4)       NOT NULL,
 ore_lavoro                      NUMBER(5,2)      NOT NULL,
 gg_lavoro                       NUMBER(2,0)      NOT NULL,
 ore_gg                          NUMBER(5,2)      NOT NULL,
 div_orario                      NUMBER(5,2)      NOT NULL,
 ore_mensili                     NUMBER(5,2)      NOT NULL,
 gg_assenza                      VARCHAR(1)       NULL,
 gg_effettivi                    VARCHAR(1)       NULL,
 data_decorrenza                 date             NULL,
 mesi_deduzioni                  NUMBER(2)        NULL,
 nota_livello                    VARCHAR(15)      NULL,
 conto_annuale                   NUMBER(2)        NULL,
 supero_gg_lavoro                varchar2(2)      DEFAULT 'NO' NOT Null
)
;

COMMENT ON TABLE contratti_storici
    IS 'COST - Attributi storici dei contratti di lavoro gestiti';


REM
REM 
REM
PROMPT
PROMPT Creating Index COST_PK on Table CONTRATTI_STORICI
CREATE UNIQUE INDEX COST_PK ON CONTRATTI_STORICI
(
      contratto ,
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
