REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  30-MAY-94
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      NOTE_CUD
REM INDEX
REM      NOCU_PK
REM
REM      NOCU - Note CUD
REM
PROMPT 
PROMPT Creating Table NOTE_CUD

create table note_cud
 (ci         number(8)      not null,
  anno       number(4)      not null,
  codice     varchar(3)     not null,
  sequenza   number         not null,
  note       varchar(2000)  null,
  note_al1   varchar(2000)  null,
  note_al2   varchar(2000)  null,
  utente     varchar(8)     null,
  tipo_agg   varchar(1)     null,
  data_agg   date           null
 )
;

create UNIQUE index NOCU_PK on note_cud (ci,anno,codice,sequenza)
;

COMMENT ON TABLE note_cud
    IS 'NOCU - Note CUD';