REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CLASSI_DELIBERA
REM INDEX
REM      CLDE_PK

REM
REM     CLDE - Classificazioni tipologie di deliberazione variabili retributive
REM
PROMPT 
PROMPT Creating Table CLASSI_DELIBERA
CREATE TABLE classi_delibera(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 max_qta                         NUMBER(12,2)     NULL
)
;

COMMENT ON TABLE classi_delibera
    IS 'CLDE - Classificazioni tipologie di deliberazione variabili retributive';


REM
REM 
REM
PROMPT
PROMPT Creating Index CLDE_PK on Table CLASSI_DELIBERA
CREATE UNIQUE INDEX CLDE_PK ON CLASSI_DELIBERA
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
