REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  06-SEP-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      IMPEGNI_PROGETTO_INCENTIVO
REM INDEX
REM      IPIP_PK

REM
REM     IPIP - Impegni di spesa per finanziamento progetti di incentivo
REM
PROMPT 
PROMPT Creating Table IMPEGNI_PROGETTO_INCENTIVO
CREATE TABLE impegni_progetto_incentivo(
 progetto                        VARCHAR(8)       NOT NULL,
 scp                             VARCHAR(4)       NOT NULL,
 ruolo                           VARCHAR(4)       NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 anno_bil                        NUMBER(4,0)      NULL,
 risorsa_intervento              VARCHAR(7)       NULL,
 capitolo                        VARCHAR(14)      NULL,
 articolo                        VARCHAR(14)      NULL,
 impegno                         NUMBER(5)        NULL,
 importo                         NUMBER(19,5)     NOT NULL,
 sede_del                        VARCHAR(4)       NULL,
 anno_del                        NUMBER(4,0)      NULL,
 numero_del                      NUMBER(7,0)      NULL,
 note                            VARCHAR(240)     NULL,
 anno_impegno                    NUMBER(4)        NULL,
 sub_impegno                     NUMBER(5)        NULL,
 anno_sub_impegno                NUMBER(4)        NULL,
 codice_siope		         NUMBER(4)        NULL
)
;

COMMENT ON TABLE impegni_progetto_incentivo
    IS 'IPIP - Impegni di spesa per finanziamento progetti di incentivo';


REM
REM 
REM
PROMPT
PROMPT Creating Index IPIP_PK on Table IMPEGNI_PROGETTO_INCENTIVO
CREATE UNIQUE INDEX IPIP_PK ON IMPEGNI_PROGETTO_INCENTIVO
(
      progetto ,
      scp ,
      ruolo ,
      sequenza )
PCTFREE  10
;

REM
REM  End of command file
REM
