REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIPARTIZIONI_CONTABILI
REM INDEX
REM      RICO_FK
REM      RICO_IK
REM      RICO_PK

REM
REM     RICO - Imputazione contabile delle ripartizione economiche e funzionali
REM
PROMPT 
PROMPT Creating Table RIPARTIZIONI_CONTABILI
CREATE TABLE ripartizioni_contabili(
 gestione                        VARCHAR(8)       NOT NULL,
 ruolo                           VARCHAR(4)       NOT NULL,
 contratto                       VARCHAR2(4)      NOT NULL,
 di_ruolo                        VARCHAR(1)       NOT NULL,
 funzionale                      VARCHAR(8)       NOT NULL,
 bilancio                        VARCHAR(2)       NOT NULL,
 arr                             VARCHAR(1)       NOT NULL,
 chiave                          VARCHAR(24)      NOT NULL,
 input_bilancio                  VARCHAR(2)       NULL,
 input_segno                     VARCHAR(1)       NULL,
 risorsa_intervento              VARCHAR(7)       NULL,
 capitolo                        VARCHAR(14)      NULL,
 articolo                        VARCHAR(14)      NULL,
 impegno                         NUMBER(5)        NULL,
 conto                           VARCHAR(2)       NULL,
 divisione                       VARCHAR(4)       NULL,
 sezione                         VARCHAR(4)       NULL,
 istituto                        VARCHAR(5)       NULL,
 anno_impegno                    NUMBER(4)        NULL,
 sub_impegno                     NUMBER(5)        NULL,
 anno_sub_impegno                NUMBER(4)        NULL,
 codice_siope		         NUMBER(4)        NULL
)
;

COMMENT ON TABLE ripartizioni_contabili
    IS 'RICO - Imputazione contabile delle ripartizione economiche e funzionali';


REM
REM 
REM
PROMPT
PROMPT Creating Index RICO_FK on Table RIPARTIZIONI_CONTABILI
CREATE INDEX RICO_FK ON RIPARTIZIONI_CONTABILI
(
      bilancio )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RICO_IK on Table RIPARTIZIONI_CONTABILI
CREATE INDEX RICO_IK ON RIPARTIZIONI_CONTABILI
(
      chiave )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RICO_PK on Table RIPARTIZIONI_CONTABILI
CREATE UNIQUE INDEX RICO_PK ON RIPARTIZIONI_CONTABILI
(
      gestione ,
      ruolo ,
      contratto ,
      di_ruolo ,
      funzionale ,
      bilancio ,
      arr ,
      input_bilancio )
PCTFREE  10
;

REM
REM  End of command file
REM
