REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DELIBERE_RETRIBUTIVE
REM INDEX
REM      DERE_CLDE_FK
REM      DERE_IK
REM      DERE_MENS_FK

REM
REM     DERE - Estemi deliberativi dei provvedimenti retribuzione variabili
REM
PROMPT 
PROMPT Creating Table DELIBERE_RETRIBUTIVE
CREATE TABLE delibere_retributive(
 sede                            VARCHAR(4)       NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 numero                          NUMBER(7,0)      NOT NULL,
 tipo                            VARCHAR(4)       NOT NULL,
 riferimento                     DATE             NOT NULL,
 anno_elab                       NUMBER(4,0)      NOT NULL,
 mese                            NUMBER(2)        NULL,
 mensilita                       VARCHAR(3)       NULL,
 causale                         VARCHAR(30)      NULL,
 causale_al1                     VARCHAR(30)      NULL,
 causale_al2                     VARCHAR(30)      NULL,
 risorsa_intervento              VARCHAR(7)       NULL,
 capitolo                        VARCHAR(14)      NULL,
 articolo                        VARCHAR(14)      NULL,
 impegno                         NUMBER(5)        NULL,
 conto                           VARCHAR(2)       NULL,
 competenza                      DATE             NULL,
 arr                             VARCHAR2(1)      NULL,
 anno_impegno                    NUMBER(4)        NULL,
 sub_impegno                     NUMBER(5)        NULL,
 anno_sub_impegno                NUMBER(4)        NULL,
 codice_siope		         NUMBER(4)        NULL
)
;

COMMENT ON TABLE delibere_retributive
    IS 'DERE - Estemi deliberativi dei provvedimenti retribuzione variabili';


REM
REM 
REM
PROMPT
PROMPT Creating Index DERE_CLDE_FK on Table DELIBERE_RETRIBUTIVE
CREATE INDEX DERE_CLDE_FK ON DELIBERE_RETRIBUTIVE
(
      tipo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index DERE_IK on Table DELIBERE_RETRIBUTIVE
CREATE INDEX DERE_IK ON DELIBERE_RETRIBUTIVE
(
      sede ,
      anno ,
      numero ,
      tipo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index DERE_MENS_FK on Table DELIBERE_RETRIBUTIVE
CREATE INDEX DERE_MENS_FK ON DELIBERE_RETRIBUTIVE
(
      mese ,
      mensilita )
PCTFREE  10
;

REM
REM  End of command file
REM
