REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VALIDITA_ASSEGNI_FAMILIARI
REM INDEX
REM      VAAF_PK

REM
REM     VAAF - Periodi di validita` degli importi di assegno per nucleo familia
REM - re
REM
PROMPT 
PROMPT Creating Table VALIDITA_ASSEGNI_FAMILIARI
CREATE TABLE validita_assegni_familiari(
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 note                            VARCHAR(240)     NULL
)
;

COMMENT ON TABLE validita_assegni_familiari
    IS 'VAAF - Periodi di validita` degli importi di assegno per nucleo familiare';


REM
REM 
REM
PROMPT
PROMPT Creating Index VAAF_PK on Table VALIDITA_ASSEGNI_FAMILIARI
CREATE UNIQUE INDEX VAAF_PK ON VALIDITA_ASSEGNI_FAMILIARI
(
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
