REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  16-JUN-94
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TOTALIZZAZIONE_CAUSALI
REM INDEX
REM      TOCA_CAEV_FK
REM      TOCA_PK

REM
REM     TOCA - Totalizzazione causali nelle categorie di Presenza/Assenza
REM
PROMPT 
PROMPT Creating Table TOTALIZZAZIONE_CAUSALI
CREATE TABLE totalizzazione_causali(
 categoria                       VARCHAR(8)       NOT NULL,
 causale                         VARCHAR(8)       NOT NULL,
 motivo                          VARCHAR(8)       NOT NULL,
 segno                           VARCHAR(1)       NOT NULL,
 gestione                        VARCHAR(1)       NOT NULL,
 riferimento_mm                  NUMBER(2,0)      NULL,
 riferimento_gg                  NUMBER(2,0)      NULL
)
;

COMMENT ON TABLE totalizzazione_causali
    IS 'TOCA - Totalizzazione causali nelle categorie di Presenza/Assenza';


REM
REM 
REM
PROMPT
PROMPT Creating Index TOCA_CAEV_FK on Table TOTALIZZAZIONE_CAUSALI
CREATE INDEX TOCA_CAEV_FK ON TOTALIZZAZIONE_CAUSALI
(
      causale )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TOCA_PK on Table TOTALIZZAZIONE_CAUSALI
CREATE UNIQUE INDEX TOCA_PK ON TOTALIZZAZIONE_CAUSALI
(
      categoria ,
      causale ,
      motivo )
PCTFREE  10
;

REM
REM  End of command file
REM
