REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TRATTAMENTI_PREVIDENZIALI
REM INDEX
REM      TRPR_PK

REM
REM     TRPR - Trattamento previdenziale e contributivo da applicare
REM
PROMPT 
PROMPT Creating Table TRATTAMENTI_PREVIDENZIALI
CREATE TABLE trattamenti_previdenziali(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 contribuzione                   NUMBER(2,0)      NOT NULL,
 ruolo                           VARCHAR(2)       NULL,
 ser_max                         NUMBER(3,0)      NULL,
 ser_min                         NUMBER(3,0)      NULL,
 previdenza                      VARCHAR(6)       NULL,
 assistenza                      VARCHAR(6)       NULL,
  FINE_SERVIZIO 			   NUMBER(1)        NULL
)
;

COMMENT ON TABLE trattamenti_previdenziali
    IS 'TRPR - Trattamento previdenziale e contributivo da applicare';


REM
REM 
REM
PROMPT
PROMPT Creating Index TRPR_PK on Table TRATTAMENTI_PREVIDENZIALI
CREATE UNIQUE INDEX TRPR_PK ON TRATTAMENTI_PREVIDENZIALI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
