REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONE_VALORI_CONTABILI
REM INDEX
REM      ESVC_PK

REM
REM     ESVC - Colonne previste dai Report parametrici su valori contabili
REM
PROMPT 
PROMPT Creating Table ESTRAZIONE_VALORI_CONTABILI
CREATE TABLE estrazione_valori_contabili(
 estrazione                      VARCHAR(20)      NOT NULL,
 colonna                         VARCHAR(30)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 descrizione                     VARCHAR(60)      NULL,
 descrizione_al1                 VARCHAR(60)      NULL,
 descrizione_al2                 VARCHAR(60)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL,
 moltiplica                      NUMBER(15,5)     NULL,
 arrotonda                       NUMBER(12,2)     NULL,
 divide                          NUMBER(15,5)     NULL
)
;

COMMENT ON TABLE estrazione_valori_contabili
    IS 'ESVC - Colonne previste dai Report parametrici su valori contabili';


REM
REM 
REM
PROMPT
PROMPT Creating Index ESVC_PK on Table ESTRAZIONE_VALORI_CONTABILI
CREATE UNIQUE INDEX ESVC_PK ON ESTRAZIONE_VALORI_CONTABILI
(
      estrazione ,
      colonna ,
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
