REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  04-AUG-94
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLO_NOMINATIVO_DOTAZIONE
REM INDEX
REM      CNDON_IK
REM      CNDON_IK2
REM      CNDON_IK3

REM
REM     
REM
PROMPT 
PROMPT Creating Table CALCOLO_NOMINATIVO_DOTAZIONE
CREATE TABLE calcolo_nominativo_dotazione(
 cndo_prenotazione               NUMBER(6,0)      NOT NULL,
 cndo_rilevanza                  NUMBER(2)        NOT NULL,
 rior_data                       DATE             NOT NULL,
 popi_sede_posto                 VARCHAR(4)       NULL,
 popi_anno_posto                 NUMBER(4,0)      NULL,
 popi_numero_posto               NUMBER(7,0)      NULL,
 popi_posto                      NUMBER(5,0)      NULL,
 popi_gruppo                     VARCHAR(12)      NULL,
 popi_dal                        DATE             NULL,
 popi_ricopribile                VARCHAR(1)       NULL,
 popi_pianta                     NUMBER(6,0)      NULL,
 setp_sequenza                   NUMBER(6,0)      NULL,
 setp_codice                     VARCHAR(15)      NULL,
 popi_settore                    NUMBER(6,0)      NULL,
 sett_sequenza                   NUMBER(6,0)      NULL,
 sett_codice                     VARCHAR(15)      NULL,
 sett_suddivisione               NUMBER(1,0)      NULL,
 sett_settore_g                  NUMBER(6,0)      NULL,
 setg_sequenza                   NUMBER(6,0)      NULL,
 setg_codice                     VARCHAR(15)      NULL,
 sett_settore_a                  NUMBER(6,0)      NULL,
 seta_sequenza                   NUMBER(6,0)      NULL,
 seta_codice                     VARCHAR(15)      NULL,
 sett_settore_b                  NUMBER(6,0)      NULL,
 setb_sequenza                   NUMBER(6,0)      NULL,
 setb_codice                     VARCHAR(15)      NULL,
 sett_settore_c                  NUMBER(6,0)      NULL,
 setc_sequenza                   NUMBER(6,0)      NULL,
 setc_codice                     VARCHAR(15)      NULL,
 sett_gestione                   VARCHAR(4)       NULL,
 gest_prospetto_po               VARCHAR(1)       NULL,
 gest_sintetico_po               VARCHAR(1)       NULL,
 sett_sede                       NUMBER(6,0)      NULL,
 sedi_codice                     VARCHAR(8)       NULL,
 sedi_sequenza                   NUMBER(6,0)      NULL,
 popi_figura                     NUMBER(6,0)      NULL,
 figi_dal                        DATE             NULL,
 figu_sequenza                   NUMBER(6,0)      NULL,
 figi_codice                     VARCHAR(8)       NULL,
 figi_qualifica                  NUMBER(6,0)      NULL,
 qugi_dal                        DATE             NULL,
 qual_sequenza                   NUMBER(6,0)      NULL,
 qugi_codice                     VARCHAR(8)       NULL,
 qugi_contratto                  VARCHAR(4)       NULL,
 cost_dal                        DATE             NULL,
 cont_sequenza                   NUMBER(3,0)      NULL,
 cost_ore_lavoro                 NUMBER(5,2)      NULL,
 qugi_livello                    VARCHAR(4)       NULL,
 figi_profilo                    VARCHAR(4)       NULL,
 prpr_sequenza                   NUMBER(3,0)      NULL,
 prpr_suddivisione_po            VARCHAR(1)       NULL,
 figi_posizione                  VARCHAR(4)       NULL,
 pofu_sequenza                   NUMBER(3,0)      NULL,
 qugi_ruolo                      VARCHAR(4)       NULL,
 ruol_sequenza                   NUMBER(3,0)      NULL,
 popi_attivita                   VARCHAR(4)       NULL,
 atti_sequenza                   NUMBER(6,0)      NULL,
 pegi_posizione                  VARCHAR(4)       NULL,
 posi_sequenza                   NUMBER(3,0)      NULL,
 pegi_tipo_rapporto              VARCHAR(4)       NULL,
 pegi_ore                        NUMBER(5,2)      NULL,
 pegi_ci                         NUMBER(8,0)      NULL,
 pegi_sostituto                  NUMBER(8,0)      NULL,
 pegi_rilevanza                  VARCHAR(1)       NULL,
 pegi_assenza                    VARCHAR(4)       NULL,
 pegi_gruppo_ling                VARCHAR(1)       NULL,
 pegi_sede_del                   VARCHAR(4)       NULL,
 pegi_anno_del                   NUMBER(4,0)      NULL,
 pegi_numero_del                 NUMBER(7,0)      NULL,
 pegi_evento                     VARCHAR(6)       NULL,
 evgi_sequenza                   NUMBER(3,0)      NULL,
 cndo_mm_eta                     NUMBER(4,0)      NULL,
 cndo_aa_eta                     NUMBER(4,0)      NULL,
 cndo_gg_anz                     NUMBER(4,0)      NULL,
 cndo_mm_anz                     NUMBER(4,0)      NULL,
 cndo_aa_anz                     NUMBER(4,0)      NULL,
 cndo_dal                        DATE             NULL,
 cndo_al                         DATE             NULL,
 popi_sede_posto_inc             VARCHAR(4)       NULL,
 popi_anno_posto_inc             NUMBER(4,0)      NULL,
 popi_numero_posto_inc           NUMBER(7,0)      NULL,
 popi_posto_inc                  NUMBER(5,0)      NULL,
 cndo_assunto                    NUMBER(1)        NULL,
 cndo_cessato                    NUMBER(1)        NULL,
 cndo_acquisito                  NUMBER(1)        NULL,
 CNDO_RILASCIATO        NUMBER (1), 
 CNDO_TP                NUMBER (5), 
 CNDO_TD                NUMBER (5), 
 CNDO_RUOLO             NUMBER (5), 
 CNDO_INCARICATO        NUMBER (5), 
 CNDO_MANS_SUP          NUMBER (5), 
 CNDO_INC_TD            NUMBER (5), 
 CNDO_SUPPLENTE         NUMBER (5), 
 CNDO_INC_AQ            NUMBER (5), 
 CNDO_ASSENTE           NUMBER (5), 
 CNDO_ASPETTATIVA       NUMBER (5), 
 CNDO_UNIV              NUMBER (5), 
 CNDO_VAC_TIT           NUMBER (5), 
 CNDO_SOVR              NUMBER (5) ) 
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CNDON_IK on Table CALCOLO_NOMINATIVO_DOTAZIONE
CREATE INDEX CNDON_IK ON CALCOLO_NOMINATIVO_DOTAZIONE
(
      cndo_prenotazione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CNDON_IK3 on Table CALCOLO_NOMINATIVO_DOTAZIONE
CREATE INDEX CNDON_IK3 ON CALCOLO_NOMINATIVO_DOTAZIONE
(
      pegi_ci )
PCTFREE  10
;

REM
REM  End of command file
REM
