REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CASELLE_FISCALI
REM INDEX
REM      CAFI_PK

REM
REM     CAFI - Note delle Caselle Della denuncia Fiscale 
REM
PROMPT 
PROMPT Creating Table CASELLE_FISCALI
CREATE TABLE caselle_fiscali(
 anno                            NUMBER(4)        NOT NULL,
 tipo_dichiarazione              VARCHAR(1)       NOT NULL,
 sequenza                        NUMBER(4,0)      NOT NULL,
 descrizione                     VARCHAR(15)      NULL,
 descrizione_al1                 VARCHAR(15)      NULL,
 descrizione_al2                 VARCHAR(15)      NULL,
 tipo_casella                    VARCHAR(1)       NOT NULL,
 casella_dett                    VARCHAR(15)      NULL
)
;

COMMENT ON TABLE caselle_fiscali
    IS 'CAFI - Note da indicare nelle Caselle Della denuncia Fiscale 
';


REM
REM 
REM
PROMPT
PROMPT Creating Index CAFI_PK on Table CASELLE_FISCALI
CREATE UNIQUE INDEX CAFI_PK ON CASELLE_FISCALI
(     anno,
      tipo_dichiarazione,
      sequenza )
PCTFREE  10
;

REM
REM  End of command file
REM

