REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      GRUPPI_INCENTIVO
REM INDEX
REM      GRIP_PK

REM
REM     GRIP - Dizionario dei Gruppi di incentivazione
REM
PROMPT 
PROMPT Creating Table GRUPPI_INCENTIVO
CREATE TABLE gruppi_incentivo(
 codice                          VARCHAR(2)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 flag_voce                       VARCHAR(1)       NULL
)
;

COMMENT ON TABLE gruppi_incentivo
    IS 'GRIP - Dizionario dei Gruppi di incentivazione';


REM
REM 
REM
PROMPT
PROMPT Creating Index GRIP_PK on Table GRUPPI_INCENTIVO
CREATE UNIQUE INDEX GRIP_PK ON GRUPPI_INCENTIVO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
