REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VOCI_ECONOMICHE
REM INDEX
REM      VOEC_IK
REM      VOEC_MENS_FK
REM      VOEC_PK
REM      VOEC_UK
REM      VOEC_UK2
REM      VOEC_UK3

REM
REM     VOEC - Caratteristiche fondamentali delle voci economiche
REM
PROMPT 
PROMPT Creating Table VOCI_ECONOMICHE
CREATE TABLE voci_economiche(
 codice                          VARCHAR(10)      NOT NULL,
 oggetto                         VARCHAR(30)      NULL,
 oggetto_al1                     VARCHAR(30)      NULL,
 oggetto_al2                     VARCHAR(30)      NULL,
 sequenza                        NUMBER(4,0)      NOT NULL,
 classe                          VARCHAR(1)       NOT NULL,
 estrazione                      VARCHAR(1)       NULL,
 specie                          VARCHAR(1)       NULL,
 tipo                            VARCHAR(1)       NOT NULL,
 automatismo                     VARCHAR(10)      NULL,
 specifica                       VARCHAR(10)      NULL,
 numero                          VARCHAR(6)       NULL,
 memorizza                       VARCHAR(1)       NOT NULL,
 mese                            NUMBER(2,0)      NULL,
 mensilita                       VARCHAR(3)       NULL,
 note                            VARCHAR(240)     NULL,
 controllo_disponibilita         VARCHAR2(1)      NULL,
 livello_controllo               VARCHAR2(1)      NULL,
 origine                         VARCHAR2(5)      NULL,
 nome_flusso                     VARCHAR2(60)     NULL,
 esclusivo                       VARCHAR2(1)      NULL
)
;

COMMENT ON TABLE voci_economiche
    IS 'VOEC - Caratteristiche fondamentali delle voci economiche';


REM
REM 
REM
PROMPT
PROMPT Creating Index VOEC_IK on Table VOCI_ECONOMICHE
CREATE INDEX VOEC_IK ON VOCI_ECONOMICHE
(
      classe )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VOEC_MENS_FK on Table VOCI_ECONOMICHE
CREATE INDEX VOEC_MENS_FK ON VOCI_ECONOMICHE
(
      mese ,
      mensilita )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VOEC_PK on Table VOCI_ECONOMICHE
CREATE UNIQUE INDEX VOEC_PK ON VOCI_ECONOMICHE
(
      codice )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VOEC_UK on Table VOCI_ECONOMICHE
CREATE UNIQUE INDEX VOEC_UK ON VOCI_ECONOMICHE
(
      sequenza )
PCTFREE  10
;


REM
REM 
REM
REM PROMPT
REM PROMPT Creating Index VOEC_UK2 on Table VOCI_ECONOMICHE
REM CREATE UNIQUE INDEX VOEC_UK2 ON VOCI_ECONOMICHE
REM (
REM      numero )
REM PCTFREE  10
REM ;
REM     Indice inibito da Mauro il 2/7/99 per poter utilizzare il campo 
REM     nel Progetto Pensioni.

REM
REM 
REM
PROMPT
PROMPT Creating Index VOEC_UK3 on Table VOCI_ECONOMICHE
CREATE UNIQUE INDEX VOEC_UK3 ON VOCI_ECONOMICHE
(
      automatismo )
PCTFREE  10
;

REM
REM 
REM
PROMPT
PROMPT Creating Index VOEC_IK2 on Table VOCI_ECONOMICHE
CREATE INDEX VOEC_IK2 ON VOCI_ECONOMICHE
(
      specifica )
PCTFREE  10
;

REM
REM  End of command file
REM
