REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  25-JUN-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DENUNCIA_O3_INPS
REM INDEX
REM      D3IS_GEST_FK
REM      D3IS_PK

REM
REM     D3IS - Archivio Denuncia I.N.P.S. O3/M
REM
PROMPT 
PROMPT Creating Table DENUNCIA_O3_INPS
CREATE TABLE denuncia_o3_inps(
 anno                            NUMBER(4,0)      NOT NULL,
 gestione                        VARCHAR(8)       NOT NULL,
 nr_o1m                          NUMBER(5,0)      NULL,
 importo_b                       NUMBER(14,2)     NULL,
 importo_c                       NUMBER(14,2)     NULL,
 importo_af                      NUMBER(14,2)     NULL,
 nr_dip_af                       NUMBER(5,0)      NULL,
 nr_nucleo_af                    NUMBER(5,0)      NULL,
 importo_mal                     NUMBER(14,2)     NULL,
 nr_dir_mal                      NUMBER(5,0)      NULL,
 nr_ind_mal                      NUMBER(5,0)      NULL,
 gg_ind_mal                      NUMBER(6,0)      NULL,
 nr_eve_mal                      NUMBER(5,0)      NULL,
 importo_m88                     NUMBER(14,2)     NULL,
 nr_ind_m88                      NUMBER(5,0)      NULL,
 gg_ind_m88                      NUMBER(6,0)      NULL,
 nr_eve_m88                      NUMBER(5,0)      NULL,
 importo_mat                     NUMBER(14,2)     NULL,
 nr_ind_mat                      NUMBER(5,0)      NULL,
 gg_ind_mat                      NUMBER(6,0)      NULL,
 nr_eve_mat                      NUMBER(5,0)      NULL,
 importo_cig                     NUMBER(14,2)     NULL
)
;

COMMENT ON TABLE denuncia_o3_inps
    IS 'D3IS - Archivio Denuncia I.N.P.S. O3/M';


REM
REM 
REM
PROMPT
PROMPT Creating Index D3IS_GEST_FK on Table DENUNCIA_O3_INPS
CREATE INDEX D3IS_GEST_FK ON DENUNCIA_O3_INPS
(
      gestione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index D3IS_PK on Table DENUNCIA_O3_INPS
CREATE UNIQUE INDEX D3IS_PK ON DENUNCIA_O3_INPS
(
      anno ,
      gestione )
PCTFREE  10
;

REM
REM  End of command file
REM
