REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLI_RETRIBUTIVI

REM
REM     CARE - Calcolo transitorio dei periodi retributivi
REM
PROMPT 
PROMPT Creating Table CALCOLI_RETRIBUTIVI
CREATE TABLE calcoli_retributivi(
 ci                              NUMBER(8,0)      NOT NULL,
 anno                            NUMBER(4)        NOT NULL,
 mese                            NUMBER(2)        NOT NULL,
 g_dal                           NUMBER(2)        NULL,
 g_al                            NUMBER(2)        NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NOT NULL,
 servizio                        VARCHAR(1)       NOT NULL,
 gg_con                          NUMBER(3)        NOT NULL,
 gg_lav                          NUMBER(3)        NOT NULL,
 gg_pre                          NUMBER(3)        NOT NULL,
 gg_inp                          NUMBER(3)        NOT NULL,
 st_inp                          NUMBER(2)        NOT NULL,
 gg_af                           NUMBER(3)        NOT NULL,
 gg_fis                          NUMBER(3)        NOT NULL,
 assenza                         VARCHAR(4)       NULL,
 giorni                          NUMBER(3)        NOT NULL,
 ore_lavoro                      NUMBER(5,2)      NOT NULL,
 settore                         NUMBER(6,0)      NULL,
 sede                            NUMBER(6,0)      NULL,
 figura                          NUMBER(6,0)      NULL,
 attivita                        VARCHAR(4)       NULL,
 contratto                       VARCHAR(4)       NULL,
 gestione                        VARCHAR(8)       NULL,
 ruolo                           VARCHAR(4)       NULL,
 profilo                         VARCHAR(4)       NULL,
 posizione                       VARCHAR(4)       NULL,
 qualifica                       NUMBER(6,0)      NULL,
 tipo_rapporto                   VARCHAR(4)       NULL,
 ore                             NUMBER(5,2)      NULL,
 sede_del                        VARCHAR(4)       NULL,
 anno_del                        NUMBER(4)        NULL,
 numero_del                      NUMBER(7)        NULL,
 rap_mese                        NUMBER(9,6)      NULL,
 gg_det                          number(3)        NOT NULL,
 gg_365                          number(3)        NOT NULL,
 delibera                        VARCHAR(4)       NULL,
 gg_df                           NUMBER(3)        NOT NULL
)
;

COMMENT ON TABLE calcoli_retributivi
    IS 'CARE - Calcolo transitorio dei periodi retributivi';

REM
REM  End of command file
REM
