REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  01-DEC-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CAUSALI_EVENTO
REM INDEX
REM      CAEV_CLDE_FK
REM      CAEV_PK
REM      CAEV_VOCO_FK

REM
REM     CAEV - Causali Evento di Presenza/Assenza
REM
PROMPT 
PROMPT Creating Table CAUSALI_EVENTO
CREATE TABLE causali_evento(
 codice                          VARCHAR(8)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(6,0)      NOT NULL,
 des_abb                         VARCHAR(8)       NULL,
 des_abb_al1                     VARCHAR(8)       NULL,
 des_abb_al2                     VARCHAR(8)       NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL,
 qualificazione                  VARCHAR(1)       NOT NULL,
 gestione                        VARCHAR(1)       NOT NULL,
 specie                          VARCHAR(1)       NULL,
 arrotonda                       NUMBER(12,2)     NULL,
 assenza                         VARCHAR(4)       NULL,
 max_qta                         NUMBER(12,2)     NULL,
 riferimento                     VARCHAR(1)       NOT NULL,
 tipo                            VARCHAR(1)       NOT NULL,
 voce                            VARCHAR(10)      NULL,
 sub                             VARCHAR(2)       NULL,
 classe_delibera                 VARCHAR(4)       NULL,
 prospetto                       VARCHAR(2)       NULL,
 retribuzione_azienda			   NUMBER(5,2)	     NULL,
 conto_annuale                   NUMBER(2)        NULL
)
;

COMMENT ON TABLE causali_evento
    IS 'CAEV - Causali Evento di Presenza/Assenza';


REM
REM 
REM
PROMPT
PROMPT Creating Index CAEV_CLDE_FK on Table CAUSALI_EVENTO
CREATE INDEX CAEV_CLDE_FK ON CAUSALI_EVENTO
(
      classe_delibera )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CAEV_PK on Table CAUSALI_EVENTO
CREATE UNIQUE INDEX CAEV_PK ON CAUSALI_EVENTO
(
      codice )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CAEV_VOCO_FK on Table CAUSALI_EVENTO
CREATE INDEX CAEV_VOCO_FK ON CAUSALI_EVENTO
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
