REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      SCAGLIONI_DETRAZIONE_FISCALE
REM INDEX
REM      SCDF_PK

REM
REM     SCDF - Scaglioni fiscali di imponibile per calcolo ulteriore detrazione
REM
PROMPT 
PROMPT Creating Table SCAGLIONI_DETRAZIONE_FISCALE
CREATE TABLE scaglioni_detrazione_fiscale(
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 scaglione                       NUMBER(15,5)     NOT NULL,
 detrazione                      NUMBER(15,5)     NOT NULL,
 imposta                         NUMBER(15,5)     NULL,
 tipo                            VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE scaglioni_detrazione_fiscale
    IS 'SCDF - Scaglioni fiscali di imponibile per calcolo ulteriore detrazione';


REM
REM 
REM
PROMPT
PROMPT Creating Index SCDF_PK on Table SCAGLIONI_DETRAZIONE_FISCALE
CREATE UNIQUE INDEX SCDF_PK ON SCAGLIONI_DETRAZIONE_FISCALE
(
      dal ,
      scaglione ,
      tipo )
PCTFREE  10
;

REM
REM  End of command file
REM
