REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CLASSI_PRESENZA
REM INDEX
REM      CLPA_CECO_FK
REM      CLPA_CLEV_FK
REM      CLPA_IK1
REM      CLPA_PK
REM      CLPA_SEDE_FK

REM
REM     CLPA - Eventi individuali a Classe
REM
PROMPT 
PROMPT Creating Table CLASSI_PRESENZA
CREATE TABLE classi_presenza(
 evento                          NUMBER(10,0)     NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 classe                          VARCHAR(8)       NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 riferimento                     DATE             NOT NULL,
 sede                            NUMBER(6,0)      NULL,
 cdc                             VARCHAR(8)       NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL,
 utente                          VARCHAR(8)       NULL,
 data_agg                        DATE             NULL
)
;

COMMENT ON TABLE classi_presenza
    IS 'CLPA - Eventi individuali a Classe';


REM
REM 
REM
PROMPT
PROMPT Creating Index CLPA_CECO_FK on Table CLASSI_PRESENZA
CREATE INDEX CLPA_CECO_FK ON CLASSI_PRESENZA
(
      cdc )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CLPA_CLEV_FK on Table CLASSI_PRESENZA
CREATE INDEX CLPA_CLEV_FK ON CLASSI_PRESENZA
(
      classe )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CLPA_IK1 on Table CLASSI_PRESENZA
CREATE INDEX CLPA_IK1 ON CLASSI_PRESENZA
(
      ci ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CLPA_PK on Table CLASSI_PRESENZA
CREATE UNIQUE INDEX CLPA_PK ON CLASSI_PRESENZA
(
      evento )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CLPA_SEDE_FK on Table CLASSI_PRESENZA
CREATE INDEX CLPA_SEDE_FK ON CLASSI_PRESENZA
(
      sede )
PCTFREE  10
;

REM
REM  End of command file
REM
