REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VOCI_DELIBERATE
REM INDEX
REM      VODE_PK
REM      VODE_VOCO_FK

REM
REM     VODE - Voci retributive attivate da una classe di deliberazione
REM
PROMPT 
PROMPT Creating Table VOCI_DELIBERATE
CREATE TABLE voci_deliberate(
 delibera                        VARCHAR(4)       NOT NULL,
 sequenza                        NUMBER(1,0)      NOT NULL,
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE voci_deliberate
    IS 'VODE - Voci retributive attivate da una classe di deliberazione';


REM
REM 
REM
PROMPT
PROMPT Creating Index VODE_PK on Table VOCI_DELIBERATE
CREATE UNIQUE INDEX VODE_PK ON VOCI_DELIBERATE
(
      delibera ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VODE_VOCO_FK on Table VOCI_DELIBERATE
CREATE INDEX VODE_VOCO_FK ON VOCI_DELIBERATE
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
