REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONE_RIGHE_CONTABILI
REM INDEX
REM      ESRC_PK
REM      ESRC_VOCO_FK
REM      ESRC_ESTR_FK
REM      ESRC_IK

REM
REM     ESRC - Voci contabili dei Report parametrici su valori contabili
REM
PROMPT 
PROMPT Creating Table ESTRAZIONE_RIGHE_CONTABILI
CREATE TABLE estrazione_righe_contabili(
 estrazione                      VARCHAR(20)      NOT NULL,
 colonna                         VARCHAR(30)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 voce                            VARCHAR(10)      NULL,
 sub                             VARCHAR(2)       NULL,
 tipo                            VARCHAR(1)       NULL,
 anno                            VARCHAR(1)       NULL,
 segno1                          VARCHAR(1)       NULL,
 dato1                           NUMBER(15,5)     NULL,
 segno2                          VARCHAR(1)       NULL,
 dato2                           NUMBER(15,5)     NULL
)
;

COMMENT ON TABLE estrazione_righe_contabili
    IS 'ESRC - Voci contabili dei Report parametrici su valori contabili';


REM
REM 
REM
PROMPT
PROMPT Creating Index ESRC_PK on Table ESTRAZIONE_RIGHE_CONTABILI
CREATE UNIQUE INDEX ESRC_PK ON ESTRAZIONE_RIGHE_CONTABILI
(
      estrazione ,
      colonna ,
      dal ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESRC_VOCO_FK on Table ESTRAZIONE_RIGHE_CONTABILI
CREATE INDEX ESRC_VOCO_FK ON ESTRAZIONE_RIGHE_CONTABILI
(
      voce ,
      sub )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESRC_ESTR_FK on Table ESTRAZIONE_RIGHE_CONTABILI
CREATE INDEX ESRC_ESTR_FK ON ESTRAZIONE_RIGHE_CONTABILI
(
      estrazione )
PCTFREE  10
;

REM
REM 
REM
PROMPT
PROMPT Creating Index ESRC_IK on Table ESTRAZIONE_RIGHE_CONTABILI
CREATE INDEX ESRC_IK ON ESTRAZIONE_RIGHE_CONTABILI
(
      estrazione ,
      colonna    )
PCTFREE  10
;

REM
REM  End of command file
REM
