REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ASSEGNI_FAMILIARI
REM INDEX
REM      ASFA_PK

REM
REM     ASFA - Importi di assegno per nucleo familiare
REM
PROMPT 
PROMPT Creating Table ASSEGNI_FAMILIARI
CREATE TABLE assegni_familiari(
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 scaglione                       NUMBER(12,2)     NOT NULL,
 numero                          NUMBER(2,0)      NOT NULL,
 tabella                         VARCHAR(3)       NOT NULL,
 importo                         NUMBER(12,2)     NULL,
 importo2                        NUMBER(12,2)     NULL,
 integrativo                     NUMBER(12,2)     NULL,
 aumento                         NUMBER(12,2)     NULL,
 NUMERO_FASCIA                   NUMBER(3)        NOT NULL
)
;

COMMENT ON TABLE assegni_familiari
    IS 'ASFA - Importi di assegno per nucleo familiare';


REM
REM 
REM
PROMPT
PROMPT Creating Index ASFA_PK on Table ASSEGNI_FAMILIARI
CREATE INDEX ASFA_PK ON ASSEGNI_FAMILIARI
(DAL, TABELLA, NUMERO_FASCIA, NUMERO)
PCTFREE  10
;

REM
REM 
REM
PROMPT
PROMPT Creating Index ASFA_IK on Table ASSEGNI_FAMILIARI
CREATE INDEX ASFA_IK ON ASSEGNI_FAMILIARI
(DAL, NUMERO_FASCIA)
PCTFREE  10
;

REM
REM  End of command file
REM
