REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-JUL-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      QUALIFICHE_GESTIONI
REM INDEX
REM      QUGE_PK

REM
REM     QUGE - Qualifiche previste dalle Gestioni
REM
PROMPT 
PROMPT Creating Table QUALIFICHE_GESTIONI
CREATE TABLE qualifiche_gestioni(
 gestione                        VARCHAR(8)       NOT NULL,
 livello                         VARCHAR(4)       NOT NULL,
 contratto_formazione            VARCHAR(2)       NOT NULL,
 qualifica                       VARCHAR(4)       NULL
)
;

COMMENT ON TABLE qualifiche_gestioni
    IS 'QUGE - Qualifiche previste dalle Gestioni';


REM
REM 
REM
PROMPT
PROMPT Creating Index QUGE_PK on Table QUALIFICHE_GESTIONI
CREATE UNIQUE INDEX QUGE_PK ON QUALIFICHE_GESTIONI
(
      gestione ,
      livello ,
      contratto_formazione )
PCTFREE  10
;

REM
REM  End of command file
REM
