REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PAM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CONDIZIONI_NON_PROFESSIONALI
REM INDEX
REM      CONP_PK

REM
REM     CONP - Tipologie di condizione non professionale
REM
PROMPT 
PROMPT Creating Table CONDIZIONI_NON_PROFESSIONALI
CREATE TABLE condizioni_non_professionali(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 max_carico_fam                  NUMBER(2,0)      NULL,
 max_carico_fis                  NUMBER(2,0)      NULL,
 inabile                         VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE condizioni_non_professionali
    IS 'CONP - Tipologie di condizione non professionale';


REM
REM 
REM
PROMPT
PROMPT Creating Index CONP_PK on Table CONDIZIONI_NON_PROFESSIONALI
CREATE UNIQUE INDEX CONP_PK ON CONDIZIONI_NON_PROFESSIONALI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
