REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      BASI_VOCE_BP
REM INDEX
REM      BAVP_CONT_FK
REM      BAVP_PK
REM      BAVP_VOEC_BAS_FK
REM      BAVP_VOEC_ECC_FK

REM
REM     BAVP - Voci economiche tabellari per Bilancio di Previsione
REM
PROMPT 
PROMPT Creating Table BASI_VOCE_BP
CREATE TABLE basi_voce_bp(
 voce                            VARCHAR(10)      NOT NULL,
 classe                          VARCHAR(1)       NOT NULL,
 contratto                       VARCHAR(4)       NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 note                            VARCHAR(240)     NULL,
 flag_inqv                       VARCHAR(1)       NULL,
 voce_base                       VARCHAR(10)      NULL,
 voce_ecce                       VARCHAR(10)      NULL,
 beneficio_anzianita             VARCHAR(1)       NULL,
 mm_inizio                       NUMBER(4,0)      NULL,
 mm_periodo                      NUMBER(4,0)      NULL,
 max_percentuale                 NUMBER(5,2)      NULL,
 max_periodi                     NUMBER(2,0)      NULL,
 min_periodi                     NUMBER(2,0)      NULL,
 gg_periodo                      NUMBER(2,0)      NULL,
 moltiplica                      NUMBER(15,5)     NULL,
 divide                          NUMBER(15,5)     NULL,
 decimali                        NUMBER(1,0)      NULL
)
PCTFREE  10
PCTUSED  40
INITRANS 1
MAXTRANS 255
;

COMMENT ON TABLE basi_voce_bp
    IS 'BAVP - Voci economiche tabellari per Bilancio di Previsione';


REM
REM 
REM
PROMPT
PROMPT Creating Index BAVP_CONT_FK on Table BASI_VOCE_BP
CREATE INDEX BAVP_CONT_FK ON BASI_VOCE_BP
(
      contratto )
PCTFREE  50
INITRANS 2
MAXTRANS 255
;


REM
REM 
REM
PROMPT
PROMPT Creating Index BAVP_PK on Table BASI_VOCE_BP
CREATE UNIQUE INDEX BAVP_PK ON BASI_VOCE_BP
(
      voce ,
      contratto ,
      dal )
PCTFREE  50
INITRANS 2
MAXTRANS 255
;


REM
REM 
REM
PROMPT
PROMPT Creating Index BAVP_VOEC_BAS_FK on Table BASI_VOCE_BP
CREATE INDEX BAVP_VOEC_BAS_FK ON BASI_VOCE_BP
(
      voce_base )
PCTFREE  50
INITRANS 2
MAXTRANS 255
;


REM
REM 
REM
PROMPT
PROMPT Creating Index BAVP_VOEC_ECC_FK on Table BASI_VOCE_BP
CREATE INDEX BAVP_VOEC_ECC_FK ON BASI_VOCE_BP
(
      voce_ecce )
PCTFREE  50
INITRANS 2
MAXTRANS 255
;

REM
REM  End of command file
REM
