REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIPARTIZIONI_FUNZIONALI
REM INDEX
REM      RIFU_CECO_FK
REM      RIFU_CLFU_FK
REM      RIFU_PK
REM      RIFU_SEDE_FK

REM
REM     RIFU - Ripartizioni funzionali di spesa per suddivisione settoriale
REM
PROMPT 
PROMPT Creating Table RIPARTIZIONI_FUNZIONALI
CREATE TABLE ripartizioni_funzionali(
 settore                         NUMBER(6,0)      NOT NULL,
 sede                            NUMBER(6,0)      NOT NULL,
 funzionale                      VARCHAR(8)       NULL,
 cdc                             VARCHAR(8)       NULL
)
;

COMMENT ON TABLE ripartizioni_funzionali
    IS 'RIFU - Ripartizioni funzionali di spesa per suddivisione settoriale';


REM
REM 
REM
PROMPT
PROMPT Creating Index RIFU_CECO_FK on Table RIPARTIZIONI_FUNZIONALI
CREATE INDEX RIFU_CECO_FK ON RIPARTIZIONI_FUNZIONALI
(
      cdc )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIFU_CLFU_FK on Table RIPARTIZIONI_FUNZIONALI
CREATE INDEX RIFU_CLFU_FK ON RIPARTIZIONI_FUNZIONALI
(
      funzionale )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIFU_PK on Table RIPARTIZIONI_FUNZIONALI
CREATE UNIQUE INDEX RIFU_PK ON RIPARTIZIONI_FUNZIONALI
(
      settore ,
      sede )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIFU_SEDE_FK on Table RIPARTIZIONI_FUNZIONALI
CREATE INDEX RIFU_SEDE_FK ON RIPARTIZIONI_FUNZIONALI
(
      sede )
PCTFREE  10
;

REM
REM  End of command file
REM
