REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TRATTAMENTI_CONTABILI
REM INDEX
REM      TRCO_PK
REM      TRCO_POSI_FK
REM      TRCO_TRPR_FK

REM
REM     TRCO - Abbinamento del trattamento previdenziale su profilo e posizione
REM
PROMPT 
PROMPT Creating Table TRATTAMENTI_CONTABILI
CREATE TABLE trattamenti_contabili(
 profilo_professionale           VARCHAR(4)       NOT NULL,
 posizione                       VARCHAR(4)       NOT NULL,
 trattamento                     VARCHAR(4)       NOT NULL,
 TIPO_TRATTAMENTO                VARCHAR2(1)      DEFAULT '0'                   NOT NULL
)
;

COMMENT ON TABLE trattamenti_contabili
    IS 'TRCO - Abbinamento del trattamento previdenziale su profilo e posizione';


REM
REM 
REM
PROMPT
PROMPT Creating Index TRCO_PK on Table TRATTAMENTI_CONTABILI
CREATE UNIQUE INDEX TRCO_PK ON TRATTAMENTI_CONTABILI
(
      profilo_professionale ,
      posizione,
      TIPO_TRATTAMENTO )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TRCO_POSI_FK on Table TRATTAMENTI_CONTABILI
CREATE INDEX TRCO_POSI_FK ON TRATTAMENTI_CONTABILI
(
      posizione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TRCO_TRPR_FK on Table TRATTAMENTI_CONTABILI
CREATE INDEX TRCO_TRPR_FK ON TRATTAMENTI_CONTABILI
(
      trattamento )
PCTFREE  10
;

REM
REM  End of command file
REM
