REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      AGGIUNTIVI_FAMILIARI
REM INDEX
REM      AGFA_PK
REM      AGFA_VAAF_FK

REM
REM     AGFA - Valori aggiuntivi agli scaglioni di reddito per nucleo familiare
REM
PROMPT 
PROMPT Creating Table AGGIUNTIVI_FAMILIARI
CREATE TABLE aggiuntivi_familiari(
 codice                          VARCHAR(4)       NOT NULL,
 dal                             DATE             NOT NULL,
 aggiuntivo                      NUMBER(12,2)     NOT NULL
)
;

COMMENT ON TABLE aggiuntivi_familiari
    IS 'AGFA - Valori aggiuntivi agli scaglioni di reddito per nucleo familiare';


REM
REM 
REM
PROMPT
PROMPT Creating Index AGFA_PK on Table AGGIUNTIVI_FAMILIARI
CREATE UNIQUE INDEX AGFA_PK ON AGGIUNTIVI_FAMILIARI
(
      codice ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index AGFA_VAAF_FK on Table AGGIUNTIVI_FAMILIARI
CREATE INDEX AGFA_VAAF_FK ON AGGIUNTIVI_FAMILIARI
(
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
