-- Creazione tabella RELAZIONI_UO

CREATE TABLE RELAZIONI_UO
(
  REVISIONE            NUMBER(8),
  GESTIONE             VARCHAR2(8),
  PADRE                NUMBER(8),
  CODICE_PADRE         VARCHAR2(15),
  SUDDIVISIONE_PADRE   VARCHAR2(8),
  FIGLIO               NUMBER(8),
  CODICE_FIGLIO        VARCHAR2(15),
  SUDDIVISIONE_FIGLIO VARCHAR2(8),
  SEQUENZA_FIGLIO     NUMBER(6),
  SEQUENZA_PADRE      NUMBER(6),
  DESCRIZIONE_FIGLIO  VARCHAR2(120),
  DESCRIZIONE_PADRE   VARCHAR2(120),
  LIVELLO_FIGLIO      NUMBER(2),
  LIVELLO_PADRE       NUMBER(2)
)
STORAGE  (
  INITIAL   &1DIMx300
  NEXT   &1DIMx150
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  0
  )
;


CREATE INDEX REUO_AK1 ON RELAZIONI_UO
(REVISIONE, PADRE)
STORAGE  (
  INITIAL   &1DIMx100
  NEXT   &1DIMx50
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  0
  )
;


CREATE INDEX REUO_AK2 ON RELAZIONI_UO
(REVISIONE, CODICE_PADRE)
STORAGE  (
  INITIAL   &1DIMx100
  NEXT   &1DIMx50
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  0
  )
;


CREATE INDEX REUO_AK3 ON RELAZIONI_UO
(REVISIONE, FIGLIO)
STORAGE  (
  INITIAL   &1DIMx100
  NEXT   &1DIMx50
  MINEXTENTS  1
  MAXEXTENTS  121 
  PCTINCREASE  0
  )
;
