REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ASSICURAZIONI_INAIL
REM INDEX
REM      ASIN_PK

REM
REM     ASIN - Posizioni assicurative INAIL
REM
PROMPT 
PROMPT Creating Table ASSICURAZIONI_INAIL
CREATE TABLE assicurazioni_inail(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 posizione                       VARCHAR(12)      NOT NULL,
 sede_inail                      varchar(15)
)
;

COMMENT ON TABLE assicurazioni_inail
    IS 'ASIN - Posizioni assicurative INAIL';


REM
REM 
REM
PROMPT
PROMPT Creating Index ASIN_PK on Table ASSICURAZIONI_INAIL
CREATE UNIQUE INDEX ASIN_PK ON ASSICURAZIONI_INAIL
(
      codice )
PCTFREE  10
;

CREATE UNIQUE INDEX ASIN_UK ON ASSICURAZIONI_INAIL
(POSIZIONE)
;
REM
REM  End of command file
REM
