REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PAM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      STATI_CIVILI
REM INDEX
REM      STCI_PK

REM
REM     STCI - Tipi di stato civile anagrafico
REM
PROMPT 
PROMPT Creating Table STATI_CIVILI
CREATE TABLE stati_civili(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 cat_fiscale                     VARCHAR(1)       NULL,
 presenza_coniuge                VARCHAR(2)       NULL
)
;

COMMENT ON TABLE stati_civili
    IS 'STCI - Tipi di stato civile anagrafico';


REM
REM 
REM
PROMPT
PROMPT Creating Index STCI_PK on Table STATI_CIVILI
CREATE UNIQUE INDEX STCI_PK ON STATI_CIVILI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
