REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      BASI_VOCE
REM INDEX
REM      BAVO_CONT_FK
REM      BAVO_PK
REM      BAVO_VOEC_BAS_FK
REM      BAVO_VOEC_ECC_FK

REM
REM     BAVO - Caratteristiche storiche delle voci economiche tabellari
REM
PROMPT 
PROMPT Creating Table BASI_VOCE
CREATE TABLE basi_voce(
 voce                            VARCHAR(10)      NOT NULL,
 classe                          VARCHAR(1)       NOT NULL,
 contratto                       VARCHAR(4)       NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 note                            VARCHAR(240)     NULL,
 flag_inqv                       VARCHAR(1)       NULL,
 voce_base                       VARCHAR(10)      NULL,
 voce_ecce                       VARCHAR(10)      NULL,
 beneficio_anzianita             VARCHAR(1)       NULL,
 mm_inizio                       NUMBER(4,0)      NULL,
 mm_periodo                      NUMBER(4,0)      NULL,
 max_percentuale                 NUMBER(5,2)      NULL,
 max_periodi                     NUMBER(2,0)      NULL,
 min_periodi                     NUMBER(2,0)      NULL,
 gg_periodo                      NUMBER(2,0)      NULL,
 moltiplica                      NUMBER(15,5)     NULL,
 divide                          NUMBER(15,5)     NULL,
 decimali                        NUMBER(1,0)      NULL
)
;

COMMENT ON TABLE basi_voce
    IS 'BAVO - Caratteristiche storiche delle voci economiche tabellari';


REM
REM 
REM
PROMPT
PROMPT Creating Index BAVO_CONT_FK on Table BASI_VOCE
CREATE INDEX BAVO_CONT_FK ON BASI_VOCE
(
      contratto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index BAVO_PK on Table BASI_VOCE
CREATE UNIQUE INDEX BAVO_PK ON BASI_VOCE
(
      voce ,
      contratto ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index BAVO_VOEC_BAS_FK on Table BASI_VOCE
CREATE INDEX BAVO_VOEC_BAS_FK ON BASI_VOCE
(
      voce_base )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index BAVO_VOEC_ECC_FK on Table BASI_VOCE
CREATE INDEX BAVO_VOEC_ECC_FK ON BASI_VOCE
(
      voce_ecce )
PCTFREE  10
;

REM
REM  End of command file
REM
