REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      GESTIONI
REM INDEX
REM      GEST_COMU_NAS_FK
REM      GEST_COMU_RES_FK
REM      GEST_PK

REM
REM     GEST - Dati anagrafici e fiscali delle gestioni nell"ambito dell"ente
REM
PROMPT 
PROMPT Creating Table GESTIONI
CREATE TABLE GESTIONI(
 codice                          VARCHAR2(8)       NOT NULL,
 nome                            VARCHAR2(40)      NULL,
 nome_al1                        VARCHAR2(40)      NULL,
 nome_al2                        VARCHAR2(40)      NULL,
 note                            VARCHAR2(2000)    NULL,
 note_al1                        VARCHAR2(2000)    NULL,
 note_al2                        VARCHAR2(2000)    NULL,
 gestito                         VARCHAR2(2)   NOT NULL,
 sesso                           VARCHAR2(1)       NULL,
 data_nas                        DATE              NULL,
 provincia_nas                   NUMBER(3,0)       NULL,
 comune_nas                      NUMBER(3,0)       NULL,
 indirizzo_res                   VARCHAR2(40)  NOT NULL,
 indirizzo_res_al1               VARCHAR2(40)      NULL,
 indirizzo_res_al2               VARCHAR2(40)      NULL,
 numero_civico                   VARCHAR2(5)   NOT NULL,
 provincia_res                   NUMBER(3,0)   NOT NULL,
 comune_res                      NUMBER(3,0)   NOT NULL,
 cap                             VARCHAR2(5)   NOT NULL,
 codice_attivita                 VARCHAR2(5)   NOT NULL,
 codice_fiscale                  VARCHAR2(16)  NOT NULL,
 partita_iva                     VARCHAR2(11)  NOT NULL,
 posizione_inps                  VARCHAR2(12)  NOT NULL,
 provincia_inps                  VARCHAR2(3)   NOT NULL,
 contratto_inps                  VARCHAR2(4)   NOT NULL,
 csc_dm10                        VARCHAR2(5)       NULL,
 aut_dm10                        VARCHAR2(20)      NULL,
 aut_01m                         VARCHAR2(8)       NULL,
 data_aut_01m                    DATE              NULL,
 provincia_sede_inps             NUMBER(2,0)       NULL,
 zona_sede_inps                  NUMBER(2,0)       NULL,
 descrizione_sede_inps           VARCHAR2(20)      NULL,
 posizione_cpd                   VARCHAR2(12)      NULL,
 posizione_cps                   VARCHAR2(12)      NULL,
 posizione_inadel                VARCHAR2(12)      NULL,
 fascia                          VARCHAR2(2)       NULL,
 raccolta                        VARCHAR2(2)       NULL,
 prospetto_po                    VARCHAR2(1)       NULL,
 sintetico_po                    VARCHAR2(1)       NULL,
 legame_po                       VARCHAR2(2)   NOT NULL,
 tel_res                         VARCHAR2(12)      NULL,
 stampa_cf_inpdap                VARCHAR2(2)       NULL,
 fax_res                         VARCHAR2(12)      NULL,
 e_mail                          VARCHAR2(2000)    NULL,
 codice_inail                    varchar2(11)      null,
 CC_INAIL              		 VARCHAR2(2)       NULL,
 CONTROLLI_DO         		 VARCHAR2(1)       NULL,
 PERC_ORE_LAVORATE               NUMBER(4,2)       NULL,
 CONTROLLI_DO_GRLI               VARCHAR2(1)       NULL,
 SOSTITUZIONI_NON_RUOLO          VARCHAR2(2)       NULL,
 GG_SOST_ANTE_ASSENZA            NUMBER(3)         NULL,
 GG_SOST_POST_ASSENZA            NUMBER(3)         NULL,
 ORE_DO                          VARCHAR2(1)       NULL,
 PROGRESSIVO_INPDAP              NUMBER(5)         NULL,
 COMPARTO                        VARCHAR2(2)       NULL,
 SOTTOCOMPARTO                   VARCHAR2(2)       NULL,
 FORMA_GIURIDICA                 VARCHAR2(2)       NULL,
 FIRMATARIO_DMA                  NUMBER(8)         NULL,
 MITTENTE_EMENS                  NUMBER(8)         NULL,
 PERC_COPERTURA                  NUMBER(5,2)       NULL,
 FILTRO_SETTORI                  VARCHAR2(2)           ,
 POSIZIONE_INAIL                 VARCHAR2(12)      NULL,
 DOTAZIONE                       VARCHAR2(2) default 'SI'
)
;

COMMENT ON TABLE gestioni
    IS 'GEST - Dati anagrafici e fiscali delle gestioni nell"ambito dell"ente';


REM
REM 
REM
PROMPT
PROMPT Creating Index GEST_COMU_NAS_FK on Table GESTIONI
CREATE INDEX GEST_COMU_NAS_FK ON GESTIONI
(
      provincia_nas ,
      comune_nas )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index GEST_COMU_RES_FK on Table GESTIONI
CREATE INDEX GEST_COMU_RES_FK ON GESTIONI
(
      provincia_res ,
      comune_res )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index GEST_PK on Table GESTIONI
CREATE UNIQUE INDEX GEST_PK ON GESTIONI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
