REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RELAZIONE_OGGETTI_ESTRAZIONE
REM INDEX
REM      REOE_PK
REM      REOE_REOG_FK

REM
REM     REOE - Oggetti richiesti dalle Estrazioni Parametriche
REM
PROMPT 
PROMPT Creating Table RELAZIONE_OGGETTI_ESTRAZIONE
CREATE TABLE relazione_oggetti_estrazione(
 estrazione                      VARCHAR(20)      NOT NULL,
 oggetto                         VARCHAR(10)      NOT NULL
)
;

COMMENT ON TABLE relazione_oggetti_estrazione
    IS 'REOE - Oggetti richiesti dalle Estrazioni Parametriche';


REM
REM 
REM
PROMPT
PROMPT Creating Index REOE_PK on Table RELAZIONE_OGGETTI_ESTRAZIONE
CREATE UNIQUE INDEX REOE_PK ON RELAZIONE_OGGETTI_ESTRAZIONE
(
      estrazione ,
      oggetto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index REOE_REOG_FK on Table RELAZIONE_OGGETTI_ESTRAZIONE
CREATE INDEX REOE_REOG_FK ON RELAZIONE_OGGETTI_ESTRAZIONE
(
      oggetto )
PCTFREE  10
;

REM
REM  End of command file
REM
