REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system GIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CENTRI_COSTO
REM INDEX
REM      CECO_PK

REM
REM     CECO - Centri di imputazione del costo
REM
PROMPT 
PROMPT Creating Table CENTRI_COSTO
CREATE TABLE centri_costo(
 codice                          VARCHAR(8)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL
)
;

COMMENT ON TABLE centri_costo
    IS 'CECO - Centri di imputazione del costo';


REM
REM 
REM
PROMPT
PROMPT Creating Index CECO_PK on Table CENTRI_COSTO
CREATE UNIQUE INDEX CECO_PK ON CENTRI_COSTO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
