CREATE TABLE RIGHE_SETTORI_STATISTICI ( 
  STATISTICA  VARCHAR2 (6)  NOT NULL, 
  CODICE      VARCHAR2 (6)  NOT NULL, 
  SEQUENZA    NUMBER (3), 
  SETTORE     NUMBER (6), 
  SEDE        NUMBER (6), 
  CDC         VARCHAR2 (8), 
  FUNZIONALE  VARCHAR2 (8))
   ; 

CREATE INDEX RSST_IK ON 
  RIGHE_SETTORI_STATISTICI(CODICE, STATISTICA) 
; 
CREATE INDEX RQST_SETT_FK
 ON RIGHE_SETTORI_STATISTICI (CODICE, STATISTICA, SETTORE);
CREATE INDEX RQST_SEDE_FK
 ON RIGHE_SETTORI_STATISTICI (CODICE, STATISTICA, SEDE);
CREATE INDEX RQST_CDC_FK
 ON RIGHE_SETTORI_STATISTICI (CODICE, STATISTICA, CDC);
CREATE INDEX RQST_FUNZ_FK
 ON RIGHE_SETTORI_STATISTICI (CODICE, STATISTICA, FUNZIONALE);
