REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RUOLI
REM INDEX
REM      RUOL_PK

REM
REM     RUOL - Ruoli di ripartizione funzionale della spesa in bilancio
REM
PROMPT 
PROMPT Creating Table RUOLI
CREATE TABLE ruoli(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL
)
;

COMMENT ON TABLE ruoli
    IS 'RUOL - Ruoli di ripartizione funzionale della spesa in bilancio';


REM
REM 
REM
PROMPT
PROMPT Creating Index RUOL_PK on Table RUOLI
CREATE UNIQUE INDEX RUOL_PK ON RUOLI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
