REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  15-SEP-94
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      AUTOMATISMI_PRESENZA

REM
REM     AUPA - Automatismi colletivi di Presenza / Assenza
REM
PROMPT 
PROMPT Creating Table AUTOMATISMI_PRESENZA
CREATE TABLE automatismi_presenza(
 sequenza                        NUMBER(3,0)      NULL,
 attivo                          VARCHAR(2)       NOT NULL,
 causale                         VARCHAR(8)       NOT NULL,
 motivo                          VARCHAR(8)       NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 attribuzione                    VARCHAR(1)       NOT NULL,
 specie                          VARCHAR(1)       NOT NULL,
 gg_ratei                        NUMBER(3)        NULL,
 quantita                        NUMBER(12,2)     NOT NULL,
 condizione                      VARCHAR(1)       NOT NULL,
 stato_condizione                VARCHAR(1)       NULL,
 automatismo                     VARCHAR(1)       NULL,
 stato_automatismo               VARCHAR(1)       NULL,
 ufficio                         VARCHAR(20)      NULL,
 sede                            NUMBER(6,0)      NULL,
 cdc                             VARCHAR(8)       NULL,
 fattore_produttivo              VARCHAR(6)       NULL,
 gestione                        VARCHAR(8)       NULL,
 settore                         NUMBER(6,0)      NULL,
 funzionale                      VARCHAR(8)       NULL,
 posizione                       VARCHAR(4)       NULL,
 ruolo                           VARCHAR(4)       NULL,
 figura                          NUMBER(6,0)      NULL,
 attivita                        VARCHAR(4)       NULL,
 contratto                       VARCHAR(4)       NULL,
 qualifica                       NUMBER(6,0)      NULL,
 livello                         VARCHAR(4)       NULL,
 tipo_rapporto                   VARCHAR(4)       NULL,
 ore                             NUMBER(5,2)      NULL,
 gg_set                          NUMBER(1,0)      NULL,
 min_gg                          NUMBER(4,0)      NULL,
 assistenza                      VARCHAR(6)       NULL
)
;

COMMENT ON TABLE automatismi_presenza
    IS 'AUPA - Automatismi colletivi di Presenza / Assenza';

REM
REM  End of command file
REM
