CREATE TABLE VALORI_ATTRIBUTI_GIURIDICI ( 
  ATGI_ID   NUMBER (10)   NOT NULL, 
  VAAT_ID   NUMBER (10)   NOT NULL, 
  VALORE    VARCHAR2 (20)  NOT NULL, 
  UTENTE    VARCHAR2 (8), 
  DATA_AGG  DATE)
   ; 


CREATE INDEX VAAG_VAAT_FK ON 
  VALORI_ATTRIBUTI_GIURIDICI(VAAT_ID) 
; 

CREATE INDEX VAAG_ATGI_FK ON 
  VALORI_ATTRIBUTI_GIURIDICI(ATGI_ID) 
; 

CREATE UNIQUE INDEX VAAG_PK ON 
  VALORI_ATTRIBUTI_GIURIDICI(ATGI_ID, VAAT_ID) 
; 



COMMENT ON TABLE VALORI_ATTRIBUTI_GIURIDICI IS 'Valori attribuiti alle variabili dei valori giuridici';
