REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIFERIMENTO_ELABORAZIONI
REM INDEX
REM      RIEL_DIAC_FK
REM      RIEL_PK
REM      RIEL_PROC_FK

REM
REM     RIEL - Registrazione di riferimento per le elaborazioni IMMEDIATE
REM
PROMPT 
PROMPT Creating Table RIFERIMENTO_ELABORAZIONI
CREATE TABLE riferimento_elaborazioni(
 terminale                       VARCHAR(20)      NOT NULL,
 data                            DATE             NOT NULL,
 voce_menu                       VARCHAR(8)       NOT NULL,
 utente                          VARCHAR(8)       NOT NULL,
 ambiente                        VARCHAR(8)       NOT NULL,
 ente                            VARCHAR(4)       NOT NULL,
 gruppo_ling                     VARCHAR(1)       NOT NULL,
 errore                          VARCHAR(6)       NULL,
 precisazione                    VARCHAR(50)      NULL
)
;

COMMENT ON TABLE riferimento_elaborazioni
    IS 'RIEL - Registrazione di riferimento per le elaborazioni IMMEDIATE';


REM
REM 
REM
PROMPT
PROMPT Creating Index RIEL_DIAC_FK on Table RIFERIMENTO_ELABORAZIONI
CREATE INDEX RIEL_DIAC_FK ON RIFERIMENTO_ELABORAZIONI
(
      utente ,
      ambiente ,
      ente ,
      gruppo_ling )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIEL_PK on Table RIFERIMENTO_ELABORAZIONI
CREATE UNIQUE INDEX RIEL_PK ON RIFERIMENTO_ELABORAZIONI
(
      terminale ,
      data ,
      voce_menu )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIEL_PROC_FK on Table RIFERIMENTO_ELABORAZIONI
CREATE INDEX RIEL_PROC_FK ON RIFERIMENTO_ELABORAZIONI
(
      voce_menu )
PCTFREE  10
;

REM
REM  End of command file
REM
