REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PAM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      GRUPPI_RAPPORTO
REM INDEX
REM      GRRA_DELI_FK
REM      GRRA_PK

REM
REM     GRRA - Riferimenti specifici di raggruppamento per aggregazione di pers
REM - onale
REM
PROMPT 
PROMPT Creating Table GRUPPI_RAPPORTO
CREATE TABLE gruppi_rapporto(
 gruppo                          VARCHAR(12)      NOT NULL,
 rilevanza                       VARCHAR(3)       NOT NULL,
 descrizione                     VARCHAR(60)      NULL,
 descrizione_al1                 VARCHAR(60)      NULL,
 descrizione_al2                 VARCHAR(60)      NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 note                            VARCHAR(60)      NULL,
 note_al1                        VARCHAR(60)      NULL,
 note_al2                        VARCHAR(60)      NULL,
 oggetto                         VARCHAR(240)     NULL,
 oggetto_al1                     VARCHAR(240)     NULL,
 oggetto_al2                     VARCHAR(240)     NULL,
 sede                            VARCHAR(4)       NULL,
 anno                            NUMBER(4,0)      NULL,
 numero                          NUMBER(7,0)      NULL,
 cat_fiscale                     VARCHAR(2)       NULL
)
;

COMMENT ON TABLE gruppi_rapporto
    IS 'GRRA - Riferimenti specifici di raggruppamento per aggregazione di personale';


REM
REM 
REM
PROMPT
PROMPT Creating Index GRRA_DELI_FK on Table GRUPPI_RAPPORTO
CREATE INDEX GRRA_DELI_FK ON GRUPPI_RAPPORTO
(
      sede ,
      anno ,
      numero )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index GRRA_PK on Table GRUPPI_RAPPORTO
CREATE UNIQUE INDEX GRRA_PK ON GRUPPI_RAPPORTO
(
      gruppo )
PCTFREE  10
;

REM
REM  End of command file
REM
