REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PAM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CATEGORIE_PROTETTE
REM INDEX
REM      CAPR_CAPR_FK
REM      CAPR_PK

REM
REM     CAPR - Categorie sociali che godono di trattamento particolare
REM
PROMPT 
PROMPT Creating Table CATEGORIE_PROTETTE
CREATE TABLE categorie_protette(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 area_protetta                   VARCHAR(4)       NULL
)
;

COMMENT ON TABLE categorie_protette
    IS 'CAPR - Categorie sociali che godono di trattamento particolare';


REM
REM 
REM
PROMPT
PROMPT Creating Index CAPR_CAPR_FK on Table CATEGORIE_PROTETTE
CREATE INDEX CAPR_CAPR_FK ON CATEGORIE_PROTETTE
(
      area_protetta )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CAPR_PK on Table CATEGORIE_PROTETTE
CREATE UNIQUE INDEX CAPR_PK ON CATEGORIE_PROTETTE
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
