REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLO_VALORI

REM
REM     CAVA - Calcolo transitorio dei valori contabili per Estrazioni Parametr
REM - iche
REM
PROMPT 
PROMPT Creating Table CALCOLO_VALORI
CREATE TABLE calcolo_valori(
 prenotazione                    NUMBER(6,0)      NOT NULL,
 ci                              NUMBER(8,0)      NULL,
 anno                            NUMBER(4,0)      NULL,
 mese                            NUMBER(2,0)      NULL,
 col1                            NUMBER(15,5)     NULL,
 col2                            NUMBER(15,5)     NULL,
 col3                            NUMBER(15,5)     NULL,
 col4                            NUMBER(15,5)     NULL,
 col5                            NUMBER(15,5)     NULL,
 col6                            NUMBER(15,5)     NULL,
 col7                            NUMBER(15,5)     NULL,
 col8                            NUMBER(15,5)     NULL,
 col9                            NUMBER(15,5)     NULL,
 col10                           NUMBER(15,5)     NULL,
 col11                           NUMBER(15,5)     NULL,
 col12                           NUMBER(15,5)     NULL,
 col13                           NUMBER(15,5)     NULL,
 col14                           NUMBER(15,5)     NULL,
 s1                              VARCHAR(240)     NULL,
 c1                              VARCHAR(240)     NULL,
 d1                              VARCHAR(240)     NULL,
 s2                              VARCHAR(240)     NULL,
 c2                              VARCHAR(240)     NULL,
 d2                              VARCHAR(240)     NULL,
 s3                              VARCHAR(240)     NULL,
 c3                              VARCHAR(240)     NULL,
 d3                              VARCHAR(240)     NULL,
 s4                              VARCHAR(240)     NULL,
 c4                              VARCHAR(240)     NULL,
 d4                              VARCHAR(240)     NULL,
 s5                              VARCHAR(240)     NULL,
 c5                              VARCHAR(240)     NULL,
 d5                              VARCHAR(240)     NULL,
 s6                              VARCHAR(240)     NULL,
 c6                              VARCHAR(240)     NULL,
 d6                              VARCHAR(240)     NULL
)
;

COMMENT ON TABLE calcolo_valori
    IS 'CAVA - Calcolo transitorio dei valori contabili per Estrazioni Parametriche';

REM
REM  End of command file
REM
