REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  24-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CAUSALI_GIUSTIFICATIVO
REM INDEX
REM      CAGI_CAEV_FK
REM      CAGI_PK

REM
REM     CAGI - Causali Giustificativi di Rilevazione Presenza
REM
PROMPT 
PROMPT Creating Table CAUSALI_GIUSTIFICATIVO
CREATE TABLE causali_giustificativo(
 codice                          VARCHAR(8)       NOT NULL,
 da_a                            VARCHAR(2)       NOT NULL,
 causale                         VARCHAR(8)       NOT NULL,
 motivo                          VARCHAR(8)      
)
;

COMMENT ON TABLE causali_giustificativo
    IS 'CAGI - Causali Giustificativi di Rilevazione Presenza';


REM
REM 
REM
PROMPT
PROMPT Creating Index CAGI_CAEV_FK on Table CAUSALI_GIUSTIFICATIVO
CREATE INDEX CAGI_CAEV_FK ON CAUSALI_GIUSTIFICATIVO
(
      causale )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CAGI_PK on Table CAUSALI_GIUSTIFICATIVO
CREATE UNIQUE INDEX CAGI_PK ON CAUSALI_GIUSTIFICATIVO
(
      da_a ,
      codice ,
      causale ,
      motivo )
PCTFREE  10
;

REM
REM  End of command file
REM
