CREATE TABLE DOTAZIONE_ESAURIMENTO ( 
  CI               NUMBER (8)    NOT NULL, 
  DATA_CESSAZIONE  DATE, 
  REVISIONE        NUMBER (8)    NOT NULL, 
  DOOR_ID          NUMBER (10)   NOT NULL, 
  UTENTE           VARCHAR2 (8), 
  DATA_AGG         DATE, 
  NUMERO           NUMBER (1), 
  NUMERO_ORE       NUMBER (5,2));


CREATE INDEX DOES_DOOR_FK ON 
  DOTAZIONE_ESAURIMENTO(REVISIONE, DOOR_ID);

CREATE UNIQUE INDEX DOES_PK ON 
  DOTAZIONE_ESAURIMENTO(CI) ;