REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  04-AUG-94
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLO_DOTAZIONE
REM INDEX
REM      CADON_IK

REM
REM     CAPO - Tabella di servizio per prospetti di Dotazione Organica
REM
PROMPT 
PROMPT Creating Table CALCOLO_DOTAZIONE
CREATE TABLE calcolo_dotazione(
 cado_prenotazione               NUMBER(6,0)      NOT NULL,
 cado_rilevanza                  NUMBER(2,0)      NOT NULL,
 cado_lingue                     VARCHAR(3)       NULL,
 rior_data                       DATE             NOT NULL,
 popi_sede_posto                 VARCHAR(4)       NULL,
 popi_anno_posto                 NUMBER(4,0)      NULL,
 popi_numero_posto               NUMBER(7,0)      NULL,
 popi_posto                      NUMBER(5,0)      NULL,
 popi_gruppo                     VARCHAR(12)      NULL,
 popi_dal                        DATE             NULL,
 popi_ricopribile                VARCHAR(1)       NULL,
 popi_pianta                     NUMBER(6,0)      NULL,
 setp_sequenza                   NUMBER(6,0)      NULL,
 setp_codice                     VARCHAR(15)      NULL,
 popi_settore                    NUMBER(6,0)      NULL,
 sett_sequenza                   NUMBER(6,0)      NULL,
 sett_codice                     VARCHAR(15)      NULL,
 sett_suddivisione               NUMBER(1,0)      NULL,
 sett_settore_g                  NUMBER(6,0)      NULL,
 setg_sequenza                   NUMBER(6,0)      NULL,
 setg_codice                     VARCHAR(15)      NULL,
 sett_settore_a                  NUMBER(6,0)      NULL,
 seta_sequenza                   NUMBER(6,0)      NULL,
 seta_codice                     VARCHAR(15)      NULL,
 sett_settore_b                  NUMBER(6,0)      NULL,
 setb_sequenza                   NUMBER(6,0)      NULL,
 setb_codice                     VARCHAR(15)      NULL,
 sett_settore_c                  NUMBER(6,0)      NULL,
 setc_sequenza                   NUMBER(6,0)      NULL,
 setc_codice                     VARCHAR(15)      NULL,
 sett_gestione                   VARCHAR(4)       NULL,
 gest_prospetto_po               VARCHAR(1)       NULL,
 gest_sintetico_po               VARCHAR(1)       NULL,
 sett_sede                       NUMBER(6,0)      NULL,
 sedi_codice                     VARCHAR(8)       NULL,
 sedi_sequenza                   NUMBER(6)        NULL,
 popi_figura                     NUMBER(6,0)      NULL,
 figi_dal                        DATE             NULL,
 figu_sequenza                   NUMBER(6,0)      NULL,
 figi_codice                     VARCHAR(8)       NULL,
 figi_qualifica                  NUMBER(6,0)      NULL,
 qugi_dal                        DATE             NULL,
 qual_sequenza                   NUMBER(6,0)      NULL,
 qugi_codice                     VARCHAR(8)       NULL,
 qugi_contratto                  VARCHAR(4)       NULL,
 cost_dal                        DATE             NULL,
 cont_sequenza                   NUMBER(3,0)      NULL,
 cost_ore_lavoro                 NUMBER(5,2)      NULL,
 qugi_livello                    VARCHAR(4)       NULL,
 figi_profilo                    VARCHAR(4)       NULL,
 prpr_sequenza                   NUMBER(3,0)      NULL,
 prpr_suddivisione_po            VARCHAR(1)       NULL,
 figi_posizione                  VARCHAR(4)       NULL,
 pofu_sequenza                   NUMBER(3,0)      NULL,
 qugi_ruolo                      VARCHAR(4)       NULL,
 ruol_sequenza                   NUMBER(3,0)      NULL,
 popi_attivita                   VARCHAR(4)       NULL,
 atti_sequenza                   NUMBER(6,0)      NULL,
 pegi_posizione                  VARCHAR(4)       NULL,
 posi_sequenza                   NUMBER(3,0)      NULL,
 pegi_tipo_rapporto              VARCHAR(4)       NULL,
 pegi_sede_del                   VARCHAR(4)       NULL,
 pegi_anno_del                   NUMBER(4,0)      NULL,
 pegi_numero_del                 NUMBER(7,0)      NULL,
 pegi_evento                     VARCHAR(6)       NULL,
 evgi_sequenza                   NUMBER(3,0)      NULL,
 pegi_figura_compl               NUMBER(6,0)      NULL,
 figu_sequenza_compl             NUMBER(6,0)      NULL,
 figi_dal_compl                  DATE             NULL,
 figi_codice_compl               VARCHAR(8)       NULL,
 pegi_attivita_compl             VARCHAR(4)       NULL,
 atti_sequenza_compl             NUMBER(6)        NULL,
 pegi_settore_compl              NUMBER(6)        NULL,
 sett_sequenza_compl             NUMBER(6)        NULL,
 sett_codice_compl               VARCHAR(15)      NULL,
 pegi_ore                        NUMBER(5,2)      NULL,
 pegi_ore_compl                  NUMBER(5,2)      NULL,
 pegi_rilevanza                  VARCHAR(1)       NULL,
 cado_previsti                   NUMBER(7,2)      NULL,
 cado_ore_previsti               NUMBER(9,2)      NULL,
 cado_in_pianta                  NUMBER(7,2)      NULL,
 cado_in_deroga                  NUMBER(7,2)      NULL,
 cado_in_sovrannumero            NUMBER(7,2)      NULL,
 cado_in_rilascio                NUMBER(7,2)      NULL,
 cado_in_acquisizione            NUMBER(7,2)      NULL,
 cado_in_istituzione             NUMBER(7,2)      NULL,
 cado_assegnazioni_ruolo_l1      NUMBER(7,2)      NULL,
 cado_ore_assegnazioni_ruolo_l1  NUMBER(9,2)      NULL,
 cado_assegnazioni_ruolo_l2      NUMBER(7,2)      NULL,
 cado_ore_assegnazioni_ruolo_l2  NUMBER(9,2)      NULL,
 cado_assegnazioni_ruolo_l3      NUMBER(7,2)      NULL,
 cado_ore_assegnazioni_ruolo_l3  NUMBER(9,2)      NULL,
 cado_assegnazioni_ruolo         NUMBER(7,2)      NULL,
 cado_ore_assegnazioni_ruolo     NUMBER(9,2)      NULL,
 cado_assegnazioni               NUMBER(7,2)      NULL,
 cado_ore_assegnazioni           NUMBER(9,2)      NULL,
 cado_assenze_incarico           NUMBER(7,2)      NULL,
 cado_assenze_assenza            NUMBER(7,2)      NULL,
 cado_disponibili                NUMBER(7,2)      NULL,
 cado_ore_disponibili            NUMBER(9,2)      NULL,
 cado_coperti_ruolo_1            NUMBER(7,2)      NULL,
 cado_ore_coperti_ruolo_1        NUMBER(9,2)      NULL,
 cado_coperti_ruolo_2            NUMBER(7,2)      NULL,
 cado_ore_coperti_ruolo_2        NUMBER(9,2)      NULL,
 cado_coperti_ruolo_3            NUMBER(7,2)      NULL,
 cado_ore_coperti_ruolo_3        NUMBER(9,2)      NULL,
 cado_coperti_ruolo              NUMBER(7,2)      NULL,
 cado_ore_coperti_ruolo          NUMBER(9,2)      NULL,
 cado_coperti_no_ruolo           NUMBER(7,2)      NULL,
 cado_ore_coperti_no_ruolo       NUMBER(9,2)      NULL,
 cado_vacanti                    NUMBER(7,2)      NULL,
 cado_ore_vacanti                NUMBER(9,2)      NULL,
 cado_vacanti_coperti            NUMBER(7,2)      NULL,
 cado_ore_vacanti_coperti        NUMBER(9,2)      NULL,
 cado_vacanti_non_coperti        NUMBER(7,2)      NULL,
 cado_ore_vacanti_non_coperti    NUMBER(9,2)      NULL,
 cado_vacanti_non_ricopribili    NUMBER(7,2)      NULL,
 cado_indisponibili              NUMBER(7,2)      NULL,
 cado_ore_indisponibili          NUMBER(9,2)      NULL,
 cado_ore_straordinari           NUMBER(9,2)      NULL,
 CADO_STRAORDINARI               NUMBER (7,2), 
 CADO_SOSTITUIBILI               NUMBER (7,2), 
 CADO_ORE_SOSTITUIBILI           NUMBER (9,2), 
 CADO_SUPPLENTI                  NUMBER (7,2), 
 CADO_ORE_SUPPLENTI              NUMBER (9,2), 
 CADO_INCARICATI                 NUMBER (7,2), 
 CADO_ORE_INCARICATI             NUMBER (9,2), 
 CADO_TP                         NUMBER (7,2), 
 CADO_TD                         NUMBER (7,2), 
 CADO_MANSIONI_SUP               NUMBER (5,2), 
 CADO_INC_AQ                     NUMBER (5,2), 
 CADO_ASSENZE_NON_RETR           NUMBER (5,2), 
 CADO_UNIVERSITARI               NUMBER (5) ) 
;

COMMENT ON TABLE calcolo_dotazione
    IS 'CADO - Tabella di servizio per prospetti di Dotazione Organica';


REM
REM 
REM
PROMPT
PROMPT Creating Index CADON_IK on Table CALCOLO_DOTAZIONE
CREATE INDEX CADON_IK ON CALCOLO_DOTAZIONE
(
      cado_prenotazione )
PCTFREE  10
;

REM
REM  End of command file
REM
