REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VALIDITA_FISCALE
REM INDEX
REM      VAFI_PK

REM
REM     VAFI - Periodi di validita` di scaglioni e detrazioni fiscali
REM
PROMPT 
PROMPT Creating Table VALIDITA_FISCALE
CREATE TABLE validita_fiscale(
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 note                            VARCHAR(240)     NULL,
 aliquota_irpef_comunale         NUMBER(7,4)      NULL,
 aliquota_irpef_regionale        NUMBER(7,4)      NULL,
 aliquota_irpef_provinciale      NUMBER(7,4)      NULL,
 riduzioni_tfr                   NUMBER(12,2)     NULL,
 detrazioni_tfr                  NUMBER(12,2)     NULL,
 val_conv_ded                    NUMBER(12,2)     NULL,
 ded_fis_base                    NUMBER(12,2)     NULL,
 val_conv_ded_fam                NUMBER(12,2)     NULL,
 val_conv_det_fam                NUMBER(12,2)     NULL,
 val_conv_det_agg_fig            NUMBER(12,2)     NULL,
 val_conv_det_dip                NUMBER(12,2)     NULL,
 val_conv_det_pen1               NUMBER(12,2)     NULL,
 val_conv_det_pen2               NUMBER(12,2)     NULL,
 val_min_det_dip                 NUMBER(12,2)     NULL,
 val_min_det_pen1                NUMBER(12,2)     NULL,
 val_min_det_pen2                NUMBER(12,2)     NULL
);

COMMENT ON TABLE validita_fiscale
    IS 'VAFI - Periodi di validita` di scaglioni e detrazioni fiscali';


REM
REM 
REM
PROMPT
PROMPT Creating Index VAFI_PK on Table VALIDITA_FISCALE
CREATE UNIQUE INDEX VAFI_PK ON VALIDITA_FISCALE
(
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
