REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      SOTTOCODICI_DOCUMENTO
REM INDEX
REM      SODO_PK

REM
REM     SODO - Sottoclassificazione degli eventi giuridici di documentazione
REM
PROMPT 
PROMPT Creating Table SOTTOCODICI_DOCUMENTO
CREATE TABLE sottocodici_documento(
 evento                          VARCHAR(6)       NOT NULL,
 codice                          VARCHAR(6)       NOT NULL,
 descrizione                     VARCHAR(120)     NULL,
 descrizione_al1                 VARCHAR(120)     NULL,
 descrizione_al2                 VARCHAR(120)     NULL,
 nota_del                        VARCHAR(15)      NULL,
 nota_del_al1                    VARCHAR(15)      NULL,
 nota_del_al2                    VARCHAR(15)      NULL,
 nota_descrizione                VARCHAR(15)      NULL,
 nota_descrizione_al1            VARCHAR(15)      NULL,
 nota_descrizione_al2            VARCHAR(15)      NULL,
 nota_numero                     VARCHAR(15)      NULL,
 nota_numero_al1                 VARCHAR(15)      NULL,
 nota_numero_al2                 VARCHAR(15)      NULL,
 nota_categoria                  VARCHAR(15)      NULL,
 nota_categoria_al1              VARCHAR(15)      NULL,
 nota_categoria_al2              VARCHAR(15)      NULL,
 nota_presso                     VARCHAR(7 )      NULL,
 nota_presso_al1                 VARCHAR(7 )      NULL,
 nota_presso_al2                 VARCHAR(7 )      NULL,
 NOTA_N1               		 VARCHAR2(15)	  NULL,
 NOTA_N1_AL1           		 VARCHAR2(15)	  NULL,
 NOTA_N1_AL2           		 VARCHAR2(15)	  NULL,
 NOTA_N2               		 VARCHAR2(15)	  NULL,
 NOTA_N2_AL1           		 VARCHAR2(15)	  NULL,
 NOTA_N2_AL2           		 VARCHAR2(15)	  NULL,
 NOTA_A1               		 VARCHAR2(15)	  NULL,
 NOTA_A1_AL1           		 VARCHAR2(15)	  NULL,
 NOTA_A1_AL2           		 VARCHAR2(15)	  NULL,
 NOTA_A2               		 VARCHAR2(15)	  NULL,
 NOTA_A2_AL1           		 VARCHAR2(15)	  NULL,
 NOTA_A2_AL2           		 VARCHAR2(15)	  NULL,
 NOTA_N3               		 VARCHAR2(15)	  NULL,
 NOTA_N3_AL1           		 VARCHAR2(15)	  NULL,
 NOTA_N3_AL2           		 VARCHAR2(15)	  NULL,
 NOTA_A3               		 VARCHAR2(15)	  NULL,
 NOTA_A3_AL1           		 VARCHAR2(15)	  NULL,
 NOTA_A3_AL2           		 VARCHAR2(15)	  NULL,
 NOTA_N4               		 VARCHAR2(15)	  NULL,
 NOTA_N4_AL1           		 VARCHAR2(15)	  NULL,
 NOTA_N4_AL2           		 VARCHAR2(15)	  NULL,
 NOTA_A4              		 VARCHAR2(15)	  NULL,
 NOTA_A4_AL1         		 VARCHAR2(15)	  NULL,
 NOTA_A4_AL2         		 VARCHAR2(15)	  NULL
)
;

COMMENT ON TABLE sottocodici_documento
    IS 'SODO - Sottoclassificazione degli eventi giuridici di documentazione';


REM
REM 
REM
PROMPT
PROMPT Creating Index SODO_PK on Table SOTTOCODICI_DOCUMENTO
CREATE UNIQUE INDEX SODO_PK ON SOTTOCODICI_DOCUMENTO
(
      evento ,
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
