REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      MENSILITA
REM INDEX
REM      MENS_PK
REM      MENS_UK

REM
REM     MENS - Mensilita` retributive elaborabili
REM
PROMPT 
PROMPT Creating Table MENSILITA
CREATE TABLE mensilita(
 mese                            NUMBER(2,0)      NOT NULL,
 mensilita                       VARCHAR(3)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 codice                          VARCHAR(4)       NOT NULL,
 tipo                            VARCHAR(1)       NOT NULL,
 estrazione                      VARCHAR(1)       NOT NULL,
 giorno                          NUMBER(2,0)      NOT NULL,
 mese_liq                        NUMBER(2,0)      NOT NULL,
 periodo                         VARCHAR(1)       NULL,	   
 cod_sequenza                    VARCHAR(1)       NULL
)
;

COMMENT ON TABLE mensilita
    IS 'MENS - Mensilita` retributive elaborabili';


REM
REM 
REM
PROMPT
PROMPT Creating Index MENS_PK on Table MENSILITA
CREATE UNIQUE INDEX MENS_PK ON MENSILITA
(
      mese ,
      mensilita )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index MENS_UK on Table MENSILITA
CREATE UNIQUE INDEX MENS_UK ON MENSILITA
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
