REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RITENUTE_VOCE
REM INDEX
REM      RIVO_PK
REM      RIVO_VOCO_IPN_FK
REM      RIVO_VOCO_RID_FK

REM
REM     RIVO - Caratteristiche storiche delle voci retributive a ritenuta
REM
PROMPT 
PROMPT Creating Table RITENUTE_VOCE
CREATE TABLE ritenute_voce(
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 note                            VARCHAR(240)     NULL,
 val_voce_ipn                    VARCHAR(1)       NOT NULL,
 cod_voce_ipn                    VARCHAR(10)      NOT NULL,
 sub_voce_ipn                    VARCHAR(2)       NOT NULL,
 moltiplica                      NUMBER(15,5)     NULL,
 divide                          NUMBER(15,5)     NULL,
 per_ipn                         NUMBER(5,2)      NULL,
 lim_inf                         NUMBER(15,5)     NULL,
 lim_sup                         NUMBER(15,5)     NULL,
 per_rit_ac                      NUMBER(7,4)      NOT NULL,
 per_rit_ap                      NUMBER(7,4)      NOT NULL,
 arrotonda                       NUMBER(15,5)     NULL,
 val_voce_rid                    VARCHAR(1)       NULL,
 cod_voce_rid                    VARCHAR(10)      NULL,
 sub_voce_rid                    VARCHAR(2)       NULL
)
;

COMMENT ON TABLE ritenute_voce
    IS 'RIVO - Caratteristiche storiche delle voci retributive a ritenuta';


REM
REM 
REM
PROMPT
PROMPT Creating Index RIVO_PK on Table RITENUTE_VOCE
CREATE UNIQUE INDEX RIVO_PK ON RITENUTE_VOCE
(
      voce ,
      sub ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIVO_VOCO_IPN_FK on Table RITENUTE_VOCE
CREATE INDEX RIVO_VOCO_IPN_FK ON RITENUTE_VOCE
(
      cod_voce_ipn ,
      sub_voce_ipn )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RIVO_VOCO_RID_FK on Table RITENUTE_VOCE
CREATE INDEX RIVO_VOCO_RID_FK ON RITENUTE_VOCE
(
      cod_voce_rid ,
      sub_voce_rid )
PCTFREE  10
;

REM
REM  End of command file
REM
