REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VALORI_BASE_VOCE
REM INDEX
REM      VBVO_CONT_FK
REM      VBVO_GEST_FK
REM      VBVO_PK

REM
REM     VBVO - Importi delle voci tabellari base
REM
PROMPT 
PROMPT Creating Table VALORI_BASE_VOCE
CREATE TABLE valori_base_voce(
 voce                            VARCHAR(10)      NOT NULL,
 contratto                       VARCHAR(4)       NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 gestione                        VARCHAR(8)       NOT NULL,
 ruolo                           VARCHAR(4)       NOT NULL,
 livello                         VARCHAR(4)       NOT NULL,
 qualifica                       VARCHAR(8)       NOT NULL,
 tipo_rapporto                   VARCHAR(4)       NOT NULL,
 valore                          NUMBER(15,5)     NOT NULL
)
;

COMMENT ON TABLE valori_base_voce
    IS 'VBVO - Importi delle voci tabellari base';


REM
REM 
REM
PROMPT
PROMPT Creating Index VBVO_CONT_FK on Table VALORI_BASE_VOCE
CREATE INDEX VBVO_CONT_FK ON VALORI_BASE_VOCE
(
      contratto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VBVO_GEST_FK on Table VALORI_BASE_VOCE
CREATE INDEX VBVO_GEST_FK ON VALORI_BASE_VOCE
(
      gestione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index VBVO_PK on Table VALORI_BASE_VOCE
CREATE UNIQUE INDEX VBVO_PK ON VALORI_BASE_VOCE
(
      voce ,
      contratto ,
      dal ,
      gestione ,
      ruolo ,
      livello ,
      qualifica ,
      tipo_rapporto )
PCTFREE  10
;

REM
REM  End of command file
REM
