REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-Apr-93 15:05
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      VALORI_PROGRESSIONE_VOCE_BP
REM INDEX
REM      VPVP_PK

REM
REM    VPVP - Importo delle voci tabellari a progressione per Bilancio di Previsione
REM
PROMPT 
PROMPT Creating Table VALORI_PROGRESSIONE_VOCE_BP
CREATE TABLE valori_progressione_voce_bp(
 voce                            VARCHAR (10)     NOT NULL,
 contratto                       VARCHAR (4)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 livello                         VARCHAR (4)      NOT NULL,
 tipo_rapporto                   VARCHAR (4)      NOT NULL,
 periodo                         NUMBER (2,0)     NOT NULL,
 per_pro                         NUMBER (7,4)     NULL,
 imp_fis                         NUMBER (15,5)    NULL
)
PCTFREE  10
PCTUSED  40
INITRANS 1
MAXTRANS 255
;

COMMENT ON TABLE valori_progressione_voce_bp
    IS 'VPVP - Importo delle voci tabellari a progressione per Bilancio di Previsione';


REM
REM 
REM
REM 
REM

PROMPT
PROMPT Creating Index VPVP_PK on Table VALORI_PROGRESSIONE_VOCE_BP
CREATE UNIQUE INDEX VPVP_PK ON VALORI_PROGRESSIONE_VOCE_BP
(
      voce ,
      contratto ,
      dal ,
      livello ,
      tipo_rapporto ,
      periodo )
PCTFREE  50
INITRANS 2
MAXTRANS 255
;

REM
REM  End of command file
REM
