REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      PROGETTI_INCENTIVO
REM INDEX
REM      PRIP_PK

REM
REM     PRIP - Definizione dei Progetti di incentivazione
REM
PROMPT 
PROMPT Creating Table PROGETTI_INCENTIVO
CREATE TABLE progetti_incentivo(
 progetto                        VARCHAR(8)       NOT NULL,
 assegnazione                    VARCHAR(1)       NOT NULL,
 situazione                      VARCHAR(1)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL
)
;

COMMENT ON TABLE progetti_incentivo
    IS 'PRIP - Definizione dei Progetti di incentivazione';


REM
REM 
REM
PROMPT
PROMPT Creating Index PRIP_PK on Table PROGETTI_INCENTIVO
CREATE UNIQUE INDEX PRIP_PK ON PROGETTI_INCENTIVO
(
      progetto )
PCTFREE  10
;

REM
REM  End of command file
REM
