REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  24-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIFERIMENTO_PRESENZA
REM INDEX
REM      RIPA_PK

REM
REM     RIPA - Riferimento gestione Presenze/Assenze
REM
PROMPT 
PROMPT Creating Table RIFERIMENTO_PRESENZA
CREATE TABLE riferimento_presenza(
 ripa_id                         VARCHAR(4)       NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 mese                            NUMBER(2,0)      NOT NULL,
 ini_mes                         DATE             NOT NULL,
 fin_mes                         DATE             NOT NULL
)
;

COMMENT ON TABLE riferimento_presenza
    IS 'RIPA - Riferimento gestione Presenze/Assenze';


REM
REM 
REM
PROMPT
PROMPT Creating Index RIPA_PK on Table RIFERIMENTO_PRESENZA
CREATE UNIQUE INDEX RIPA_PK ON RIFERIMENTO_PRESENZA
(
      ripa_id )
PCTFREE  10
;

REM
REM  End of command file
REM
