REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      DETRAZIONI_FISCALI
REM INDEX
REM      DEFI_PK
REM      DEFI_VADF_FK

REM
REM     DEFI - Importi di detrazione fiscale
REM
PROMPT 
PROMPT Creating Table DETRAZIONI_FISCALI
CREATE TABLE detrazioni_fiscali(
 codice                          VARCHAR(4)       NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 tipo                            VARCHAR(2)       NOT NULL,
 numero                          NUMBER(2,0)      NULL,
 scaglione                       NUMBER(2,0)      NOT NULL,
 importo                         NUMBER(15,5)     NOT NULL,
 imponibile                      NUMBER(15,5)     NULL,
 aumento                         NUMBER(15,5)     NULL
)
;

COMMENT ON TABLE detrazioni_fiscali
    IS 'DEFI - Importi di detrazione fiscale';


REM
REM 
REM
PROMPT
PROMPT Creating Index DEFI_PK on Table DETRAZIONI_FISCALI
CREATE UNIQUE INDEX DEFI_PK ON DETRAZIONI_FISCALI
(
      codice ,
      tipo ,
      scaglione ,
      numero ,
      dal )
PCTFREE  10
;

REM
REM 
REM
PROMPT
PROMPT Creating Index DEFI_VADF_FK on Table DETRAZIONI_FISCALI
CREATE INDEX DEFI_VADF_FK ON DETRAZIONI_FISCALI
(
      dal )
PCTFREE  10
;

REM
REM  End of command file
REM
