REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RELAZIONE_COND_ESTRAZIONE
REM INDEX
REM      RECE_PK

REM
REM     RECE - Condizioni di estrazione richieste sulle Estrazioni Parametriche
REM
PROMPT 
PROMPT Creating Table RELAZIONE_COND_ESTRAZIONE
CREATE TABLE relazione_cond_estrazione(
 estrazione                      VARCHAR(20)      NOT NULL,
 oggetto                         VARCHAR(10)      NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 condizione                      VARCHAR(60)      NULL
)
;

COMMENT ON TABLE relazione_cond_estrazione
    IS 'RECE - Condizioni di estrazione richieste sulle Estrazioni Parametriche';


REM
REM 
REM
PROMPT
PROMPT Creating Index RECE_PK on Table RELAZIONE_COND_ESTRAZIONE
CREATE UNIQUE INDEX RECE_PK ON RELAZIONE_COND_ESTRAZIONE
(
      estrazione ,
      oggetto ,
      sequenza )
PCTFREE  10
;

REM
REM  End of command file
REM
