REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  02-DEC-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      PROSPETTI_PRESENZA
REM INDEX
REM      PRPA_PK

REM
REM     PRPA - Prospetti parametrici di caricamento e stampa
REM
PROMPT 
PROMPT Creating Table PROSPETTI_PRESENZA
CREATE TABLE prospetti_presenza(
 codice                          VARCHAR(8)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL,
 rilevanza                       VARCHAR(1)       NOT NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL
)
;

COMMENT ON TABLE prospetti_presenza
    IS 'PRPA - Prospetti parametrici di caricamento e stampa';


REM
REM 
REM
PROMPT
PROMPT Creating Index PRPA_PK on Table PROSPETTI_PRESENZA
CREATE UNIQUE INDEX PRPA_PK ON PROSPETTI_PRESENZA
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
