CREATE TABLE VARIABILI_ATTRIBUTO ( 
  VAAT_ID      		NUMBER (10)   NOT NULL, 
  COAT_ID      		NUMBER (10)   NOT NULL, 
  VARIABILE    		VARCHAR2 (10)  NOT NULL, 
  TIPO         		VARCHAR2 (1)  NOT NULL, 
  DESCRIZIONE  		VARCHAR2 (120)  NOT NULL,
  valore_default 	varchar2(30)
)
  ; 

CREATE INDEX VAAT_COAT_FK ON 
  VARIABILI_ATTRIBUTO(COAT_ID) 
; 

CREATE UNIQUE INDEX VAAT_PK ON 
  VARIABILI_ATTRIBUTO(VAAT_ID) 
; 


COMMENT ON TABLE VARIABILI_ATTRIBUTO IS 'Grandezze variabili relative agli attributi giuridici';

COMMENT ON COLUMN VARIABILI_ATTRIBUTO.TIPO IS 'A(alfanumerico)/N(numerico)';
