REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  15-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIPARTIZIONE_CAUSALI
REM INDEX
REM      RICA_PK

REM
REM     Created from Entity RIPARTIZIONE CAUSALE by P00 on 10-NOV-93
REM
PROMPT 
PROMPT Creating Table RIPARTIZIONE_CAUSALI
CREATE TABLE ripartizione_causali(
 classe                          VARCHAR(8)       NOT NULL,
 causale                         VARCHAR(8)       NOT NULL,
 ripartizione                    NUMBER(6,0)          NULL,
 sequenza                        NUMBER(6,0)      NOT NULL
)
;

COMMENT ON TABLE ripartizione_causali
    IS 'Created from Entity RIPARTIZIONE CAUSALE by P00 on 10-NOV-93';


REM
REM 
REM
PROMPT
PROMPT Creating Index RICA_PK on Table RIPARTIZIONE_CAUSALI
CREATE UNIQUE INDEX RICA_PK ON RIPARTIZIONE_CAUSALI
(
      classe ,
      causale )
PCTFREE  10
;

REM
REM  End of command file
REM
