REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      QUALIFICHE
REM INDEX
REM      QUAL_PK

REM
REM     QUAL - Qualifiche retributive che differenziano il trattamento economic
REM - o
REM
PROMPT 
PROMPT Creating Table QUALIFICHE
CREATE TABLE qualifiche(
 numero                          NUMBER(6,0)      NOT NULL,
 definizione                     VARCHAR(120)     NULL,
 definizione_al1                 VARCHAR(120)     NULL,
 definizione_al2                 VARCHAR(120)     NULL,
 sequenza                        NUMBER(6,0)      NULL,
 descrizione                     VARCHAR(15)      NULL,
 descrizione_al1                 VARCHAR(15)      NULL,
 descrizione_al2                 VARCHAR(15)      NULL,
 qua_inps                        NUMBER(1,0)      NULL,
 inq_inps                        VARCHAR(4)       NULL,
 con_inadel                      VARCHAR(2)       NULL,
 cat_inadel                      VARCHAR(2)       NULL,
 qua_inadel                      VARCHAR(2)       NULL,
 fattore                         VARCHAR(6)       NULL,
 fattore_td                      VARCHAR(6)       NULL,
 cat_fiscale                     VARCHAR(2)       NULL,
 cod_previdenza                  VARCHAR(5)       NULL,
 cat_minimale                    NUMBER(1,0)      NULL,
 qua_inpdap                      VARCHAR(3)       NULL
)
;

COMMENT ON TABLE qualifiche
    IS 'QUAL - Qualifiche retributive che differenziano il trattamento economico';


REM
REM 
REM
PROMPT
PROMPT Creating Index QUAL_PK on Table QUALIFICHE
CREATE UNIQUE INDEX QUAL_PK ON QUALIFICHE
(
      numero )
PCTFREE  10
;

REM
REM  End of command file
REM
