CREATE TABLE SMT_IMPORTI
(
	ANNO	    NUMBER(4)    NOT NULL,
	CI	        NUMBER(8)    NOT NULL,
	GESTIONE	VARCHAR2(8)  NOT NULL,
	DAL	        DATE         NOT NULL,
	TABELLA	    VARCHAR2(4)  NOT NULL,
	COLONNA	    VARCHAR2(30) NOT NULL,
	IMPORTO	    NUMBER(12,2),
	UTENTE	    VARCHAR2(8),
	TIPO_AGG	VARCHAR2(1),
	DATA_AGG	DATE
)
;

CREATE UNIQUE INDEX SMIM_PK ON 
  SMT_IMPORTI(ANNO, GESTIONE, CI, DAL, TABELLA, COLONNA) 
;
