REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      PARTI_APPLICATIVE
REM INDEX
REM      PAAP_PK

REM
REM     PAAP - Dizionario delle Parti Applicative
REM
PROMPT 
PROMPT Creating Table PARTI_APPLICATIVE
CREATE TABLE parti_applicative(
 codice                          VARCHAR(4)       NOT NULL,
 fondo                           VARCHAR(2)       NOT NULL,
 per_liq                         NUMBER(5,2)      NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL
)
;

COMMENT ON TABLE parti_applicative
    IS 'PAAP - Dizionario delle Parti Applicative';


REM
REM 
REM
PROMPT
PROMPT Creating Index PAAP_PK on Table PARTI_APPLICATIVE
CREATE UNIQUE INDEX PAAP_PK ON PARTI_APPLICATIVE
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
