REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  03-NOV-95
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      NORMATIVA_VOCE
REM INDEX
REM      NOVO_PK

REM
REM     NOVO - Normativa di trattamento della voce per Qualifica Retributiva
REM
PROMPT 
PROMPT Creating Table NORMATIVA_VOCE
create table NORMATIVA_VOCE
(
  VOCE              VARCHAR2(10) not null,
  CONTRATTO         VARCHAR2(4)  not null,
  QUALIFICA         VARCHAR2(8)  not null,
  DAL               DATE,
  AL                DATE,
  NOVO_ID           NUMBER(10) not null,
  LIVELLO           VARCHAR2(4) default '%' not null,
  RUOLO             VARCHAR2(4) default '%' not null,
  TIPO_RAPPORTO     VARCHAR2(4) default '%' not null,
  FIGURA            VARCHAR2(8) default '%' not null,
  POSIZIONE         VARCHAR2(4) default '%' not null,
  DI_RUOLO          VARCHAR2(2) default '%' not null,
  TEMPO_DETERMINATO VARCHAR2(2) default '%' not null,
  PART_TIME         VARCHAR2(2) default '%' not null
)
;

COMMENT ON TABLE normativa_voce
    IS 'NOVO - Normativa di trattamento della voce per Qualifica Retributiva';


create index NOVO_IK on NORMATIVA_VOCE (VOCE)
;
create unique index NOVO_PK on NORMATIVA_VOCE (NOVO_ID)
;

REM
REM  End of command file
REM
