REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIGHE_FORMULA_CAUSALE
REM INDEX
REM      RFCA_PK
REM      RFCA_VOCO_FK

REM
REM     RFCA - Dettaglio di formula di calcolo voci contabili di evento
REM
PROMPT 
PROMPT Creating Table RIGHE_FORMULA_CAUSALE
CREATE TABLE righe_formula_causale(
 formula                         VARCHAR(8)       NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 voce                            VARCHAR(10)      NULL,
 sub                             VARCHAR(2)       NULL,
 segno1                          VARCHAR(1)       NULL,
 dato1                           NUMBER(15,5)     NULL,
 segno2                          VARCHAR(1)       NULL,
 dato2                           NUMBER(15,5)     NULL
)
;

COMMENT ON TABLE righe_formula_causale
    IS 'RFCA - Dettaglio di formula di calcolo voci contabili di evento';


REM
REM 
REM
PROMPT
PROMPT Creating Index RFCA_PK on Table RIGHE_FORMULA_CAUSALE
CREATE UNIQUE INDEX RFCA_PK ON RIGHE_FORMULA_CAUSALE
(
      formula ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RFCA_VOCO_FK on Table RIGHE_FORMULA_CAUSALE
CREATE INDEX RFCA_VOCO_FK ON RIGHE_FORMULA_CAUSALE
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
