CREATE TABLE DEF_DELIBERE_RETRIBUTIVE ( 
  SEDE         VARCHAR2 (4)  NOT NULL, 
  ANNO         NUMBER (4)    NOT NULL, 
  NUMERO       NUMBER (7)    NOT NULL, 
  CAUSALE      VARCHAR2 (30), 
  CAUSALE_AL1  VARCHAR2 (30), 
  CAUSALE_AL2  VARCHAR2 (30))
 ; 


CREATE INDEX DDRE_PK ON 
  DEF_DELIBERE_RETRIBUTIVE(SEDE, ANNO, NUMERO) 
; 

