REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONE_CONTRIBUTI
REM INDEX
REM      ESCO_IK
REM      ESCO_VOCO_CON_FK
REM      ESCO_VOCO_FK

REM
REM     ESCO - Parametri di estrazione del Riepilogo Contributi
REM
PROMPT 
PROMPT Creating Table ESTRAZIONE_CONTRIBUTI
CREATE TABLE estrazione_contributi(
 quadro                          VARCHAR(1)       NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 voce                            VARCHAR(10)      NOT NULL,
 sub                             VARCHAR(2)       NOT NULL,
 codice                          VARCHAR(4)       NULL,
 descrizione                     VARCHAR(20)      NULL,
 numero                          VARCHAR(1)       NULL,
 giorni                          VARCHAR(1)       NULL,
 imponibile                      VARCHAR(2)       NOT NULL,
 contributo                      VARCHAR(2)       NOT NULL,
 tipo                            VARCHAR(1)       NULL,
 arrotondamento                  NUMBER(12,2)     NULL,
 con_voce                        VARCHAR(10)      NOT NULL,
 con_sub                         VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE estrazione_contributi
    IS 'ESCO - Parametri di estrazione del Riepilogo Contributi';


REM
REM 
REM
PROMPT
PROMPT Creating Index ESCO_IK on Table ESTRAZIONE_CONTRIBUTI
CREATE INDEX ESCO_IK ON ESTRAZIONE_CONTRIBUTI
(
      quadro ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESCO_VOCO_CON_FK on Table ESTRAZIONE_CONTRIBUTI
CREATE INDEX ESCO_VOCO_CON_FK ON ESTRAZIONE_CONTRIBUTI
(
      con_voce ,
      con_sub )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index ESCO_VOCO_FK on Table ESTRAZIONE_CONTRIBUTI
CREATE INDEX ESCO_VOCO_FK ON ESTRAZIONE_CONTRIBUTI
(
      voce ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
