REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CLASSIFICAZIONI_FUNZIONALI
REM INDEX
REM      CLFU_PK

REM
REM     CLFU - Classificazioni funzionali di spesa
REM
PROMPT 
PROMPT Creating Table CLASSIFICAZIONI_FUNZIONALI
CREATE TABLE classificazioni_funzionali(
 codice                          VARCHAR(8)       NOT NULL,
 descrizione                     VARCHAR(30)      NULL,
 descrizione_al1                 VARCHAR(30)      NULL,
 descrizione_al2                 VARCHAR(30)      NULL,
 sequenza                        NUMBER(3,0)      NULL
)
;

COMMENT ON TABLE classificazioni_funzionali
    IS 'CLFU - Classificazioni funzionali di spesa';


REM
REM 
REM
PROMPT
PROMPT Creating Index CLFU_PK on Table CLASSIFICAZIONI_FUNZIONALI
CREATE UNIQUE INDEX CLFU_PK ON CLASSIFICAZIONI_FUNZIONALI
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
