REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIFERIMENTO_INCENTIVO
REM INDEX
REM      RIIP_PK

REM
REM     RIIP - Riferimento periodo Incentivazione Produttivita`
REM
PROMPT 
PROMPT Creating Table RIFERIMENTO_INCENTIVO
CREATE TABLE riferimento_incentivo(
 riip_id                         VARCHAR(4)       NOT NULL,
 anno                            NUMBER(4,0)      NOT NULL,
 mese                            NUMBER(2,0)      NOT NULL,
 ini_mes                         DATE             NOT NULL,
 fin_mes                         DATE             NOT NULL,
 stato_pgm                       VARCHAR(2)       NOT NULL,
 stato_pip                       VARCHAR(2)       NOT NULL,
 stato_pec                       VARCHAR(2)       NOT NULL
)
;

COMMENT ON TABLE riferimento_incentivo
    IS 'RIIP - Riferimento periodo Incentivazione Produttivita`';


REM
REM 
REM
PROMPT
PROMPT Creating Index RIIP_PK on Table RIFERIMENTO_INCENTIVO
CREATE UNIQUE INDEX RIIP_PK ON RIFERIMENTO_INCENTIVO
(
      riip_id )
PCTFREE  10
;

REM
REM  End of command file
REM
