REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  04-AUG-94
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      CALCOLO_NOMINATIVO_POSTI
REM INDEX
REM      CNPON_IK
REM      CNPON_IK2
REM      CNPON_IK3

REM
REM     
REM
PROMPT 
PROMPT Creating Table CALCOLO_NOMINATIVO_POSTI
CREATE TABLE calcolo_nominativo_posti(
 cnpo_prenotazione               NUMBER(6,0)      NOT NULL,
 cnpo_rilevanza                  NUMBER(2)        NOT NULL,
 rior_data                       DATE             NOT NULL,
 popi_sede_posto                 VARCHAR(4)       NULL,
 popi_anno_posto                 NUMBER(4,0)      NULL,
 popi_numero_posto               NUMBER(7,0)      NULL,
 popi_posto                      NUMBER(5,0)      NULL,
 popi_gruppo                     VARCHAR(12)      NULL,
 popi_dal                        DATE             NULL,
 popi_ricopribile                VARCHAR(1)       NULL,
 popi_pianta                     NUMBER(6,0)      NULL,
 setp_sequenza                   NUMBER(6,0)      NULL,
 setp_codice                     VARCHAR(15)      NULL,
 popi_settore                    NUMBER(6,0)      NULL,
 sett_sequenza                   NUMBER(6,0)      NULL,
 sett_codice                     VARCHAR(15)      NULL,
 sett_suddivisione               NUMBER(1,0)      NULL,
 sett_settore_g                  NUMBER(6,0)      NULL,
 setg_sequenza                   NUMBER(6,0)      NULL,
 setg_codice                     VARCHAR(15)      NULL,
 sett_settore_a                  NUMBER(6,0)      NULL,
 seta_sequenza                   NUMBER(6,0)      NULL,
 seta_codice                     VARCHAR(15)      NULL,
 sett_settore_b                  NUMBER(6,0)      NULL,
 setb_sequenza                   NUMBER(6,0)      NULL,
 setb_codice                     VARCHAR(15)      NULL,
 sett_settore_c                  NUMBER(6,0)      NULL,
 setc_sequenza                   NUMBER(6,0)      NULL,
 setc_codice                     VARCHAR(15)      NULL,
 sett_gestione                   VARCHAR(4)       NULL,
 gest_prospetto_po               VARCHAR(1)       NULL,
 gest_sintetico_po               VARCHAR(1)       NULL,
 popi_figura                     NUMBER(6,0)      NULL,
 figi_dal                        DATE             NULL,
 figu_sequenza                   NUMBER(6,0)      NULL,
 figi_codice                     VARCHAR(8)       NULL,
 figi_qualifica                  NUMBER(6,0)      NULL,
 qugi_dal                        DATE             NULL,
 qual_sequenza                   NUMBER(6,0)      NULL,
 qugi_codice                     VARCHAR(8)       NULL,
 qugi_contratto                  VARCHAR(4)       NULL,
 cost_dal                        DATE             NULL,
 cont_sequenza                   NUMBER(3,0)      NULL,
 cost_ore_lavoro                 NUMBER(5,2)      NULL,
 qugi_livello                    VARCHAR(4)       NULL,
 figi_profilo                    VARCHAR(4)       NULL,
 prpr_sequenza                   NUMBER(3,0)      NULL,
 prpr_suddivisione_po            VARCHAR(1)       NULL,
 figi_posizione                  VARCHAR(4)       NULL,
 pofu_sequenza                   NUMBER(3,0)      NULL,
 qugi_ruolo                      VARCHAR(4)       NULL,
 ruol_sequenza                   NUMBER(3,0)      NULL,
 popi_attivita                   VARCHAR(4)       NULL,
 atti_sequenza                   NUMBER(6,0)      NULL,
 pegi_posizione                  VARCHAR(4)       NULL,
 posi_sequenza                   NUMBER(3,0)      NULL,
 pegi_tipo_rapporto              VARCHAR(4)       NULL,
 pegi_ore                        NUMBER(5,2)      NULL,
 pegi_ci                         NUMBER(8,0)      NULL,
 pegi_sostituto                  NUMBER(8,0)      NULL,
 pegi_rilevanza                  VARCHAR(1)       NULL,
 pegi_assenza                    VARCHAR(4)       NULL,
 pegi_gruppo_ling                VARCHAR(1)       NULL,
 cnpo_mm_eta                     NUMBER(4,0)      NULL,
 cnpo_aa_eta                     NUMBER(4,0)      NULL,
 cnpo_gg_anz                     NUMBER(4,0)      NULL,
 cnpo_mm_anz                     NUMBER(4,0)      NULL,
 cnpo_aa_anz                     NUMBER(4,0)      NULL,
 cnpo_dal                        DATE             NULL,
 cnpo_al                         DATE             NULL,
 popi_sede_posto_inc             VARCHAR(4)       NULL,
 popi_anno_posto_inc             NUMBER(4,0)      NULL,
 popi_numero_posto_inc           NUMBER(7,0)      NULL,
 popi_posto_inc                  NUMBER(5,0)      NULL
)
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CNPON_IK on Table CALCOLO_NOMINATIVO_POSTI
CREATE INDEX CNPON_IK ON CALCOLO_NOMINATIVO_POSTI
(
      cnpo_prenotazione )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CNPON_IK2 on Table CALCOLO_NOMINATIVO_POSTI
CREATE INDEX CNPON_IK2 ON CALCOLO_NOMINATIVO_POSTI
(
      popi_sede_posto ,
      popi_anno_posto ,
      popi_numero_posto ,
      popi_posto )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index CNPON_IK3 on Table CALCOLO_NOMINATIVO_POSTI
CREATE INDEX CNPON_IK3 ON CALCOLO_NOMINATIVO_POSTI
(
      pegi_ci )
PCTFREE  10
;

REM
REM  End of command file
REM
