REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      EVENTI_RAPPORTO
REM INDEX
REM      EVRA_PK

REM
REM     EVRA - Eventi e motivazioni di inizio e termine del rapporto di lavoro
REM
PROMPT 
PROMPT Creating Table EVENTI_RAPPORTO
CREATE TABLE eventi_rapporto(
 codice                          VARCHAR(4)       NOT NULL,
 descrizione                     VARCHAR(120)     NULL,
 descrizione_al1                 VARCHAR(120)     NULL,
 descrizione_al2                 VARCHAR(120)     NULL,
 sequenza                        NUMBER(3,0)      NULL,
 rilevanza                       VARCHAR(1)       NOT NULL,
 cod_previdenza                  VARCHAR(3)       NULL,
 conto_annuale                   NUMBER(2,0)      NULL,
 cat_inpdap                      VARCHAR(2)       NULL,
 onaosi                          NUMBER(2)        NULL,
 inps					   VARCHAR2(3)       NULL
) 
;

COMMENT ON TABLE eventi_rapporto
    IS 'EVRA - Eventi e motivazioni di inizio e termine del rapporto di lavoro';


REM
REM 
REM
PROMPT
PROMPT Creating Index EVRA_PK on Table EVENTI_RAPPORTO
CREATE UNIQUE INDEX EVRA_PK ON EVENTI_RAPPORTO
(
      codice )
PCTFREE  10
;

REM
REM  End of command file
REM
