REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  26-NOV-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIGHE_QUALIFICA_MINISTERIALE
REM INDEX
REM      RQMI_FIGU_FK
REM      RQMI_PK
REM      RQMI_QUAL_FK

REM
REM     RQMI - Figure professionali che compongono le Qualifiche Ministeriali
REM
PROMPT 
PROMPT Creating Table RIGHE_QUALIFICA_MINISTERIALE
CREATE TABLE righe_qualifica_ministeriale(
 codice                          VARCHAR(6)       NOT NULL,
 sequenza                        NUMBER(3,0)      NOT NULL,
 qualifica                       NUMBER(6,0)      NULL,
 tipo_rapporto                   VARCHAR(4)       NULL,
 figura                          NUMBER(6,0)      NULL,
 di_ruolo                        VARCHAR(1)       NULL,
 tempo_determinato               VARCHAR(2)       NULL,
 part_time                       VARCHAR(2)       NULL,
 rapporto_gg                     VARCHAR(2)       NULL,
 formazione_lavoro               VARCHAR2(2)      NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 posizione			 VARCHAR2(4)      NULL
)
;

COMMENT ON TABLE righe_qualifica_ministeriale
    IS 'RQMI - Figure professionali che compongono le Qualifiche Ministeriali';


REM
REM 
REM
PROMPT
PROMPT Creating Index RQMI_FIGU_FK on Table RIGHE_QUALIFICA_MINISTERIALE
CREATE INDEX RQMI_FIGU_FK ON RIGHE_QUALIFICA_MINISTERIALE
(
      figura )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RQMI_PK on Table RIGHE_QUALIFICA_MINISTERIALE
CREATE UNIQUE INDEX RQMI_PK ON RIGHE_QUALIFICA_MINISTERIALE
(     dal,
      codice ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RQMI_QUAL_FK on Table RIGHE_QUALIFICA_MINISTERIALE
CREATE INDEX RQMI_QUAL_FK ON RIGHE_QUALIFICA_MINISTERIALE
(
      qualifica )
PCTFREE  10
;

REM
REM  End of command file
REM
