REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONE_NOTE_CEDOLINI
REM INDEX
REM      ESNC_PK

REM
REM     ESNC - Note da indicare nelle righe di dettaglio del Cedolino
REM
PROMPT 
PROMPT Creating Table ESTRAZIONE_NOTE_CEDOLINI
CREATE TABLE estrazione_note_cedolini(
 sequenza                        NUMBER(4,0)      NOT NULL,
 sub                             NUMBER(2,0)      NOT NULL,
 descrizione                     VARCHAR(37)      NULL,
 descrizione_al1                 VARCHAR(37)      NULL,
 descrizione_al2                 VARCHAR(37)      NULL,
 tariffa                         VARCHAR(11)      NULL,
 tariffa_al1                     VARCHAR(11)      NULL,
 tariffa_al2                     VARCHAR(11)      NULL,
 quantita                        VARCHAR(8)       NULL,
 quantita_al1                    VARCHAR(8)       NULL,
 quantita_al2                    VARCHAR(8)       NULL,
 importo                         VARCHAR(17)      NULL,
 importo_al1                     VARCHAR(17)      NULL,
 importo_al2                     VARCHAR(17)      NULL
)
;

COMMENT ON TABLE estrazione_note_cedolini
    IS 'ESNC - Note da indicare nelle righe di dettaglio del Cedolino';


REM
REM 
REM
PROMPT
PROMPT Creating Index ESNC_PK on Table ESTRAZIONE_NOTE_CEDOLINI
CREATE UNIQUE INDEX ESNC_PK ON ESTRAZIONE_NOTE_CEDOLINI
(
      sequenza ,
      sub )
PCTFREE  10
;

REM
REM  End of command file
REM
