REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RAPPORTI_PRESENZA
REM INDEX
REM      RAPA_IK
REM      RAPA_PK
REM      RAPA_SEDE_FK

REM
REM     RAPA - Rapporti individuali di Presenza
REM
PROMPT 
PROMPT Creating Table RAPPORTI_PRESENZA
CREATE TABLE rapporti_presenza(
 ci                              NUMBER(8,0)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 ufficio                         VARCHAR(20)      NULL,
 badge                           NUMBER(5,0)      NULL,
 sede                            NUMBER(6,0)      NULL,
 cartellino                      VARCHAR(6)       NULL,
 gg_set                          NUMBER(1,0)      NULL,
 min_gg                          NUMBER(4,0)      NULL,
 cdc                             VARCHAR(8)       NULL,
 fattore_produttivo              VARCHAR(6)       NULL,
 assistenza                      VARCHAR(6)       NULL,
 automatismo                     VARCHAR(1)       NULL,
 flag_ec                         VARCHAR(1)       NULL,
 utente                          VARCHAR(8)       NULL,
 DATA_AGG                        DATE, 
 RESPONSABILE                    NUMBER (1), 
 ORARIO                          VARCHAR2 (4), 
 STRAORDINARIO                    VARCHAR2 (1)
)
;

COMMENT ON TABLE rapporti_presenza
    IS 'RAPA - Rapporti individuali di Presenza';


REM
REM 
REM
PROMPT
PROMPT Creating Index RAPA_IK on Table RAPPORTI_PRESENZA
CREATE INDEX RAPA_IK ON RAPPORTI_PRESENZA
(
      badge )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RAPA_PK on Table RAPPORTI_PRESENZA
CREATE UNIQUE INDEX RAPA_PK ON RAPPORTI_PRESENZA
(
      ci ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index RAPA_SEDE_FK on Table RAPPORTI_PRESENZA
CREATE INDEX RAPA_SEDE_FK ON RAPPORTI_PRESENZA
(
      sede )
PCTFREE  10
;

REM
REM  End of command file
REM
