REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  18-Jan-93 11:21
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      ESTRAZIONE_CREA_REPORT

REM
REM    ESCR - Creazione temporanea dei Report parametrici personalizzabili
REM
PROMPT 
PROMPT Creating Table ESTRAZIONE_CREA_REPORT
CREATE TABLE estrazione_crea_report(
 estrazione                      VARCHAR (20)     NOT NULL,
 tipo                            VARCHAR(1)       NOT NULL,
 sequenza                        NUMBER (8,0)     NULL,
 oggetto                         VARCHAR (10)     NULL,
 colonna                         VARCHAR (240)    NULL,
 attributo                       VARCHAR (20)     NULL
)
;

COMMENT ON TABLE estrazione_crea_report
    IS 'ESCR - Creazione temporanea dei Report parametrici personalizzabili';

REM
REM  End of command file
REM
