REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TOTALIZZAZIONI_VOCE
REM INDEX
REM      TOVO_PK
REM      TOVO_VOCO_FK
REM      TOVO_VOEC_ACC_FK

REM
REM     TOVO - Totalizzazioni delle voci retributive su voci di accumulo
REM
PROMPT 
PROMPT Creating Table TOTALIZZAZIONI_VOCE
CREATE TABLE totalizzazioni_voce(
 voce                            VARCHAR(10)      NOT NULL,
 voce_acc                        VARCHAR(10)      NOT NULL,
 dal                             DATE             NULL,
 al                              DATE             NULL,
 sub                             VARCHAR(2)       NULL,
 anno                            VARCHAR(1)       NULL,
 tipo                            VARCHAR(1)       NULL,
 per_tot                         NUMBER(7,4)      NULL
)
;

COMMENT ON TABLE totalizzazioni_voce
    IS 'TOVO - Totalizzazioni delle voci retributive su voci di accumulo';


REM
REM 
REM
PROMPT
PROMPT Creating Index TOVO_PK on Table TOTALIZZAZIONI_VOCE
CREATE UNIQUE INDEX TOVO_PK ON TOTALIZZAZIONI_VOCE
(
      voce ,
      voce_acc ,
      dal ,
      sub ,
      anno ,
      tipo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TOVO_VOCO_FK on Table TOTALIZZAZIONI_VOCE
CREATE INDEX TOVO_VOCO_FK ON TOTALIZZAZIONI_VOCE
(
      voce ,
      sub )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TOVO_VOEC_ACC_FK on Table TOTALIZZAZIONI_VOCE
CREATE INDEX TOVO_VOEC_ACC_FK ON TOTALIZZAZIONI_VOCE
(
      voce_acc )
PCTFREE  10
;

REM
REM  End of command file
REM
