REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  08-SEP-93
REM
REM For application system PEC version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RELAZIONE_CHIAVI_ESTRAZIONE
REM INDEX
REM      REES_PK
REM      REES_RECH_FK

REM
REM     REES - Chiavi di ordinamento richieste sulle Estrazioni Parametriche
REM
PROMPT 
PROMPT Creating Table RELAZIONE_CHIAVI_ESTRAZIONE
CREATE TABLE relazione_chiavi_estrazione(
 estrazione                      VARCHAR(20)      NOT NULL,
 sequenza                        NUMBER(1,0)      NOT NULL,
 chiave                          VARCHAR(20)      NOT NULL
)
;

COMMENT ON TABLE relazione_chiavi_estrazione
    IS 'REES - Chiavi di ordinamento richieste sulle Estrazioni Parametriche';


REM
REM 
REM
PROMPT
PROMPT Creating Index REES_PK on Table RELAZIONE_CHIAVI_ESTRAZIONE
CREATE UNIQUE INDEX REES_PK ON RELAZIONE_CHIAVI_ESTRAZIONE
(
      estrazione ,
      sequenza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index REES_RECH_FK on Table RELAZIONE_CHIAVI_ESTRAZIONE
CREATE INDEX REES_RECH_FK ON RELAZIONE_CHIAVI_ESTRAZIONE
(
      chiave )
PCTFREE  10
;

REM
REM  End of command file
REM
