REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  30-Mar-93 08:20
REM
REM For application system PPO version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      RIPARTIZIONI_LINGUISTICHE
REM INDEX
REM      RILI_PK
REM      RILI_SETT_FK

REM
REM    RILI - Ripartizione percentuale di copertura posti in organico
REM
PROMPT 
PROMPT Creating Table RIPARTIZIONI_LINGUISTICHE
CREATE TABLE ripartizioni_linguistiche(
 ripartizione                    VARCHAR (8)      NOT NULL,
 settore                         NUMBER (6,0)     NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 descrizione                     VARCHAR (30)     NULL,
 descrizione_al1                 VARCHAR (30)     NULL,
 descrizione_al2                 VARCHAR (30)     NULL,
 perc_posti                      NUMBER (7,4)     NULL,
 perc_posti_al1                  NUMBER (7,4)     NULL,
 perc_posti_al2                  NUMBER (7,4)     NULL
)
;

COMMENT ON TABLE ripartizioni_linguistiche
    IS 'RILI - Ripartizione percentuale di copertura posti in organico';

COMMENT ON COLUMN ripartizioni_linguistiche.ripartizione
    IS 'Codice di ripartizione del personale';

COMMENT ON COLUMN ripartizioni_linguistiche.settore
    IS 'Numero identificativo della suddivisione';

COMMENT ON COLUMN ripartizioni_linguistiche.dal
    IS 'Data di inizio validita` della ripartizione';

COMMENT ON COLUMN ripartizioni_linguistiche.al
    IS 'Data di fine validita` della ripartizione';

COMMENT ON COLUMN ripartizioni_linguistiche.descrizione
    IS 'Descrizione della ripartizione percentuale del personale';

COMMENT ON COLUMN ripartizioni_linguistiche.descrizione_al1
    IS 'Descrizione della ripartizione percentuale del personale';

COMMENT ON COLUMN ripartizioni_linguistiche.descrizione_al2
    IS 'Descrizione della ripartizione percentuale del personale';

COMMENT ON COLUMN ripartizioni_linguistiche.perc_posti
    IS 'Percentuale di copertura posti';

COMMENT ON COLUMN ripartizioni_linguistiche.perc_posti_al1
    IS 'Percentuale di copertura posti';

COMMENT ON COLUMN ripartizioni_linguistiche.perc_posti_al2
    IS 'Percentuale di copertura posti';


REM
REM 
REM
REM GENERATED CANDIDATE INDEX
REM

PROMPT
PROMPT Creating Index RILI_PK on Table RIPARTIZIONI_LINGUISTICHE
CREATE UNIQUE INDEX RILI_PK ON RIPARTIZIONI_LINGUISTICHE
(
      ripartizione ,
      settore ,
      dal )
PCTFREE  10
;


REM
REM 
REM
REM GENERATED CANDIDATE INDEX
REM

PROMPT
PROMPT Creating Index RILI_SETT_FK on Table RIPARTIZIONI_LINGUISTICHE
CREATE INDEX RILI_SETT_FK ON RIPARTIZIONI_LINGUISTICHE
(
      settore )
PCTFREE  10
;

REM
REM  End of command file
REM
