REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  29-JUL-93
REM
REM For application system PIP version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      TETTI_RETRIBUTIVI_INCENTIVO
REM INDEX
REM      TRIP_IK
REM      TRIP_QUAL_FK

REM
REM     TRIP - Tetti retributivi individuali
REM
PROMPT 
PROMPT Creating Table TETTI_RETRIBUTIVI_INCENTIVO
CREATE TABLE tetti_retributivi_incentivo(
 ci                              NUMBER(8,0)      NOT NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 rilevanza                       VARCHAR(1)       NOT NULL,
 decorrenza                      DATE             NOT NULL,
 di_ruolo                        VARCHAR(2)       NOT NULL,
 qualifica                       NUMBER(6,0)      NOT NULL,
 tipo_rapporto                   VARCHAR(4)       NULL,
 tetto                           NUMBER(12,2)     NOT NULL,
 tetto_prec                      NUMBER(12,2)     NULL,
 utente                          VARCHAR(8)       NULL,
 data_agg                        DATE             NULL
)
;

COMMENT ON TABLE tetti_retributivi_incentivo
    IS 'TRIP - Tetti retributivi individuali';


REM
REM 
REM
PROMPT
PROMPT Creating Index TRIP_IK on Table TETTI_RETRIBUTIVI_INCENTIVO
CREATE INDEX TRIP_IK ON TETTI_RETRIBUTIVI_INCENTIVO
(
      ci ,
      dal ,
      rilevanza )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index TRIP_QUAL_FK on Table TETTI_RETRIBUTIVI_INCENTIVO
CREATE INDEX TRIP_QUAL_FK ON TETTI_RETRIBUTIVI_INCENTIVO
(
      qualifica )
PCTFREE  10
;

REM
REM  End of command file
REM
