REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  21-DEC-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM TABLE
REM      EVENTI_PRESENZA
REM INDEX
REM      EVPA_CAEV_FK
REM      EVPA_CECO_FK
REM      EVPA_CLPA_FK
REM      EVPA_IK1
REM      EVPA_IK2
REM      EVPA_IK3
REM      EVPA_MOEV_FK
REM      EVPA_PK
REM      EVPA_SEDE_FK
REM SEQUENCE
REM      EVPA_SQ

REM
REM     EVPA - Eventi individuali di Presenza/Assenza
REM
PROMPT 
PROMPT Creating Table EVENTI_PRESENZA
CREATE TABLE eventi_presenza(
 evento                          NUMBER(10,0)     NOT NULL,
 ci                              NUMBER(8,0)      NOT NULL,
 causale                         VARCHAR(8)       NOT NULL,
 motivo                          VARCHAR(8)       NULL,
 dal                             DATE             NOT NULL,
 al                              DATE             NULL,
 riferimento                     DATE             NOT NULL,
 chiuso                          VARCHAR(2)       NOT NULL,
 input                           VARCHAR(1)       NOT NULL,
 classe                          NUMBER(10,0)     NULL,
 dalle                           NUMBER(4,0)      NULL,
 alle                            NUMBER(4,0)      NULL,
 valore                          NUMBER(12,2)     NULL,
 cdc                             VARCHAR(8)       NULL,
 sede                            NUMBER(6,0)      NULL,
 note                            VARCHAR(240)     NULL,
 note_al1                        VARCHAR(240)     NULL,
 note_al2                        VARCHAR(240)     NULL,
 utente                          VARCHAR(8)       NULL,
 data_agg                        DATE             NULL
)
STORAGE    (INITIAL          30K)
;

COMMENT ON TABLE eventi_presenza
    IS 'EVPA - Eventi individuali di Presenza/Assenza';


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_CAEV_FK on Table EVENTI_PRESENZA
CREATE INDEX EVPA_CAEV_FK ON EVENTI_PRESENZA
(
      causale )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_CECO_FK on Table EVENTI_PRESENZA
CREATE INDEX EVPA_CECO_FK ON EVENTI_PRESENZA
(
      cdc )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_CLPA_FK on Table EVENTI_PRESENZA
CREATE INDEX EVPA_CLPA_FK ON EVENTI_PRESENZA
(
      classe )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_IK1 on Table EVENTI_PRESENZA
CREATE INDEX EVPA_IK1 ON EVENTI_PRESENZA
(
      ci ,
      dal )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_IK2 on Table EVENTI_PRESENZA
CREATE INDEX EVPA_IK2 ON EVENTI_PRESENZA
(
      chiuso )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_IK3 on Table EVENTI_PRESENZA
CREATE INDEX EVPA_IK3 ON EVENTI_PRESENZA
(
      data_agg )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_MOEV_FK on Table EVENTI_PRESENZA
CREATE INDEX EVPA_MOEV_FK ON EVENTI_PRESENZA
(
      motivo )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_PK on Table EVENTI_PRESENZA
CREATE UNIQUE INDEX EVPA_PK ON EVENTI_PRESENZA
(
      evento )
PCTFREE  10
;


REM
REM 
REM
PROMPT
PROMPT Creating Index EVPA_SEDE_FK on Table EVENTI_PRESENZA
CREATE INDEX EVPA_SEDE_FK ON EVENTI_PRESENZA
(
      sede )
PCTFREE  10
;


REM
REM  End of command file
REM
