REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  04-AUG-95
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM VIEW
REM      SUDDIVISIONI_SETTORIALI

REM
REM  SUDDIVISIONI_SETTORIALI
REM
REM  SUSE - Gerarchia delle suddivisioni settoriali
REM
PROMPT
PROMPT Creating SUDDIVISIONI_SETTORIALI 
CREATE OR REPLACE VIEW SUDDIVISIONI_SETTORIALI
(sett_numero
,sett_suddivisione
,sett_codice
,sett_descrizione
,sett_sequenza
,sett_gestione
,gest_nome
,gest_gestito
,sett_assegnabile
,sett_settore_g
,sett_settore_a
,sett_settore_b
,sett_settore_c
,sett_sede
,sede_codice
,sede_descrizione
,sede_sequenza
,setg_numero
,setg_codice
,setg_descrizione
,setg_sequenza
,setg_assegnabile
,seta_numero
,seta_codice
,seta_descrizione
,seta_sequenza
,seta_assegnabile
,setb_numero
,setb_codice
,setb_descrizione
,setb_sequenza
,setb_assegnabile
,setc_numero
,setc_codice
,setc_descrizione
,setc_sequenza
,setc_assegnabile
,setd_numero
,setd_codice
,setd_descrizione
,setd_sequenza
,setd_assegnabile
,atomico
) AS
SELECT sett.numero
      ,sett.suddivisione
      ,sett.codice
      ,sett.descrizione
      ,sett.sequenza
      ,sett.gestione
      ,gest.nome
      ,gest.gestito
      ,sett.assegnabile
      ,sett.settore_g
      ,sett.settore_a
      ,sett.settore_b
      ,sett.settore_c
      ,sett.sede
      ,sede.codice
      ,sede.descrizione
      ,sede.sequenza
      ,setg.numero
      ,setg.codice
      ,setg.descrizione
      ,nvl(setg.sequenza,999999)
      ,setg.assegnabile
      ,nvl(seta.numero,setg.numero)
      ,nvl(seta.codice,setg.codice)
      ,nvl(seta.descrizione,setg.descrizione)
      ,decode(sett.suddivisione
             ,0,0
               ,nvl(seta.sequenza,999999)
             )
      ,nvl(seta.assegnabile,setg.assegnabile)
      ,nvl(setb.numero
          ,nvl(seta.numero,setg.numero)
          )
      ,nvl(setb.codice
          ,nvl(seta.codice,setg.codice)
          )
      ,nvl(setb.descrizione
          ,nvl(seta.descrizione,setg.descrizione)
          )
      ,decode(sett.suddivisione
             ,0,0
             ,1,0
               ,nvl(setb.sequenza,999999)
             )
      ,nvl(setb.assegnabile
          ,nvl(seta.assegnabile,setg.assegnabile)
          )
      ,nvl(setc.numero
          ,nvl(setb.numero
              ,nvl(seta.numero,setg.numero)
              )
          )
      ,nvl(setc.codice
          ,nvl(setb.codice
              ,nvl(seta.codice,setg.codice)
              )
          )
      ,nvl(setc.descrizione
          ,nvl(setb.descrizione
              ,nvl(seta.descrizione,setg.descrizione)
              )
          )
      ,decode(sett.suddivisione
             ,0,0
             ,1,0
             ,2,0
               ,nvl(setc.sequenza,999999)
             )
      ,nvl(setc.assegnabile
          ,nvl(setb.assegnabile
              ,nvl(seta.assegnabile,setg.assegnabile)
              )
          )
      ,nvl(setd.numero
          ,nvl(setc.numero
              ,nvl(setb.numero
                  ,nvl(seta.numero,setg.numero)
                  )
              )
          )
      ,nvl(setd.codice
          ,nvl(setc.codice
              ,nvl(setb.codice
                  ,nvl(seta.codice,setg.codice)
                  )
              )
          )
      ,nvl(setd.descrizione
          ,nvl(setc.descrizione
              ,nvl(setb.descrizione
                  ,nvl(seta.descrizione,setg.descrizione)
                  )
              )
          )
      ,decode(sett.suddivisione
             ,0,0
             ,1,0
             ,2,0
             ,3,0
               ,nvl(setd.sequenza,999999)
             )
      ,nvl(setd.assegnabile
          ,nvl(setc.assegnabile
              ,nvl(setb.assegnabile
                  ,nvl(seta.assegnabile,setg.assegnabile)
                  )
              )
          )
      ,1
  FROM sedi         sede
      ,gestioni     gest
      ,settori      setg
      ,settori      seta
      ,settori      setb
      ,settori      setc
      ,settori      setd
      ,settori      sett
 WHERE sede.numero (+)   = sett.sede
   AND gest.codice       = sett.gestione
   AND setg.numero (+)   = nvl(sett.settore_g,sett.numero)
   AND seta.numero (+)   = decode(sett.suddivisione
                                 ,0,0
                                 ,1,sett.numero
                                   ,sett.settore_a
                                 )
   AND setb.numero (+)   = decode(sett.suddivisione
                                 ,0,0,1,0
                                 ,2,sett.numero
                                   ,sett.settore_b
                                 )
   AND setc.numero (+)   = decode(sett.suddivisione
                                 ,0,0,1,0,2,0
                                 ,3,sett.numero
                                   ,sett.settore_c
                                 )
   AND setd.numero (+)   = decode(sett.suddivisione
                                 ,0,0,1,0,2,0,3,0
                                   ,sett.numero
                                 )
   AND exists
       (select 'x'
          from settori set2
         where sett.numero in (set2.settore_g
                              ,set2.settore_a
                              ,set2.settore_b
                              ,set2.settore_c
                              )
       )
UNION
SELECT sett.numero
      ,sett.suddivisione
      ,sett.codice
      ,sett.descrizione
      ,sett.sequenza
      ,sett.gestione
      ,gest.nome
      ,gest.gestito
      ,sett.assegnabile
      ,sett.settore_g
      ,sett.settore_a
      ,sett.settore_b
      ,sett.settore_c
      ,sett.sede
      ,sede.codice
      ,sede.descrizione
      ,sede.sequenza
      ,setg.numero
      ,setg.codice
      ,setg.descrizione
      ,nvl(setg.sequenza,999999)
      ,setg.assegnabile
      ,nvl(seta.numero,setg.numero)
      ,nvl(seta.codice,setg.codice)
      ,nvl(seta.descrizione,setg.descrizione)
      ,decode(sett.suddivisione
             ,0,0
               ,nvl(seta.sequenza,999999)
             )
      ,nvl(seta.assegnabile,setg.assegnabile)
      ,nvl(setb.numero
          ,nvl(seta.numero,setg.numero)
          )
      ,nvl(setb.codice
          ,nvl(seta.codice,setg.codice)
          )
      ,nvl(setb.descrizione
          ,nvl(seta.descrizione,setg.descrizione)
          )
      ,decode(sett.suddivisione
             ,0,0
             ,1,0
               ,nvl(setb.sequenza,999999)
             )
      ,nvl(setb.assegnabile
          ,nvl(seta.assegnabile,setg.assegnabile)
          )
      ,nvl(setc.numero
          ,nvl(setb.numero
              ,nvl(seta.numero,setg.numero)
              )
          )
      ,nvl(setc.codice
          ,nvl(setb.codice
              ,nvl(seta.codice,setg.codice)
              )
          )
      ,nvl(setc.descrizione
          ,nvl(setb.descrizione
              ,nvl(seta.descrizione,setg.descrizione)
              )
          )
      ,decode(sett.suddivisione
             ,0,0
             ,1,0
             ,2,0
               ,nvl(setc.sequenza,999999)
             )
      ,nvl(setc.assegnabile
          ,nvl(setb.assegnabile
              ,nvl(seta.assegnabile,setg.assegnabile)
              )
          )
      ,nvl(setd.numero
          ,nvl(setc.numero
              ,nvl(setb.numero
                  ,nvl(seta.numero,setg.numero)
                  )
              )
          )
      ,nvl(setd.codice
          ,nvl(setc.codice
              ,nvl(setb.codice
                  ,nvl(seta.codice,setg.codice)
                  )
              )
          )
      ,nvl(setd.descrizione
          ,nvl(setc.descrizione
              ,nvl(setb.descrizione
                  ,nvl(seta.descrizione,setg.descrizione)
                  )
              )
          )
      ,decode(sett.suddivisione
             ,0,0
             ,1,0
             ,2,0
             ,3,0
               ,nvl(setd.sequenza,999999)
             )
      ,nvl(setd.assegnabile
          ,nvl(setc.assegnabile
              ,nvl(setb.assegnabile
                  ,nvl(seta.assegnabile,setg.assegnabile)
                  )
              )
          )
      ,0
  FROM sedi         sede
      ,gestioni     gest
      ,settori      setg
      ,settori      seta
      ,settori      setb
      ,settori      setc
      ,settori      setd
      ,settori      sett
 WHERE sede.numero (+)   = sett.sede
   AND gest.codice       = sett.gestione
   AND setg.numero (+)   = nvl(sett.settore_g,sett.numero)
   AND seta.numero (+)   = decode(sett.suddivisione
                                 ,0,0
                                 ,1,sett.numero
                                   ,sett.settore_a
                                 )
   AND setb.numero (+)   = decode(sett.suddivisione
                                 ,0,0,1,0
                                 ,2,sett.numero
                                   ,sett.settore_b
                                 )
   AND setc.numero (+)   = decode(sett.suddivisione
                                 ,0,0,1,0,2,0
                                 ,3,sett.numero
                                   ,sett.settore_c
                                 )
   AND setd.numero (+)   = decode(sett.suddivisione
                                 ,0,0,1,0,2,0,3,0
                                   ,sett.numero
                                 )
   AND not exists
       (select 'x'
          from settori set2
         where sett.numero in (set2.settore_g
                              ,set2.settore_a
                              ,set2.settore_b
                              ,set2.settore_c
                              )
       )
;

COMMENT ON TABLE suddivisioni_settoriali
    IS 'SUSE - Gerarchia delle suddivisioni settoriali';

REM
REM  End of command file
REM
