CREATE OR REPLACE VIEW WORD_ANAGRAFICI ( NI, 
COGNOME, NOME, SESSO, DATA_NAS, 
PROVINCIA_NAS, COMUNE_NAS, DES_COMUNE_NAS, DES_SIGLA_NAS, 
LUOGO_NAS, CODICE_FISCALE, CODICE_FISCALE_ESTERO, PARTITA_IVA, 
CITTADINANZA, DES_CITTADINANZA, GRUPPO_LING, INDIRIZZO_RES, 
PROVINCIA_RES, COMUNE_RES, DES_COMUNE_RES, DES_SIGLA_RES, 
CAP_RES, TEL_RES, FAX_RES, PRESSO, 
INDIRIZZO_DOM, PROVINCIA_DOM, COMUNE_DOM, DES_COMUNE_DOM, 
DES_SIGLA_DOM, CAP_DOM, TEL_DOM, FAX_DOM, 
NOTE, DAL, AL, STATO_CIVILE, 
DES_STATO_CIVILE, COGNOME_CONIUGE, TITOLO_STUDIO, DES_TITOLO_STUDIO, 
TITOLO, CATEGORIA_PROTETTA, DES_CATEGORIA_PROTETTA, TESSERA_SAN, 
NUMERO_USL, PROVINCIA_USL, TIPO_DOC, DES_TIPO_DOC, 
NUMERO_DOC, PROVINCIA_DOC, COMUNE_DOC, DES_COMUNE_DOC, 
DES_SIGLA_DOC, CI, RAPPORTO, DES_RAPPORTO, 
CC, RAIN_DAL, RAIN_AL, GRUPPO, 
RAIN_NOTE, AMBIENTE, TIPO_NI, FASCICOLO, 
TELEFONO_UFFICIO, FAX_UFFICIO, E_MAIL, MATRICOLA, 
ISTITUTO, DES_ITITUTO, SPORTELLO, DES_SPORTELLO, 
CONTO_CORRENTE, DELEGA, SPESE, ULTERIORI, 
POSIZIONE_INAIL, DES_POS_INAIL, DATA_INAIL, TRATTAMENTO, 
DES_TRATTAMENTO, CODICE_CPD, POSIZIONE_CPD, DATA_CPD, 
CODICE_CPS, POSIZIONE_CPS, DATA_CPS, CODICE_INPS, 
CODICE_IAD, DATA_IAD, STATISTICO1, STATISTICO2, 
STATISTICO3 ) AS SELECT ANAG.NI,    
         ANAG.COGNOME,    
         ANAG.NOME,    
         ANAG.SESSO,    
         to_char(ANAG.DATA_NAS,'dd/mm/yyyy'),    
         ANAG.PROVINCIA_NAS,    
         ANAG.COMUNE_NAS,    
         CNAS.DENOMINAZIONE DES_COMUNE_NAS,    
         PNAS.SIGLA         DES_SIGLA_NAS,    
         ANAG.LUOGO_NAS,    
         ANAG.CODICE_FISCALE,    
         ANAG.CODICE_FISCALE_ESTERO,    
         ANAG.PARTITA_IVA,    
         ANAG.CITTADINANZA,    
         STTE.DESC_CITTADINANZA,    
         ANAG.GRUPPO_LING,    
         ANAG.INDIRIZZO_RES,    
         ANAG.PROVINCIA_RES,    
         ANAG.COMUNE_RES,    
         CRES.DENOMINAZIONE DES_COMUNE_RES,    
         PRES.SIGLA         DES_SIGLA_RES,    
         ANAG.CAP_RES,    
         ANAG.TEL_RES,    
         ANAG.FAX_RES,    
         ANAG.PRESSO,    
         ANAG.INDIRIZZO_DOM,    
         ANAG.PROVINCIA_DOM,    
         ANAG.COMUNE_DOM,    
         CDOM.DENOMINAZIONE DES_COMUNE_DOM,    
         PDOM.SIGLA         DES_SIGLA_DOM,    
         ANAG.CAP_DOM,    
         ANAG.TEL_DOM,    
         ANAG.FAX_DOM,    
         replace(ANAG.NOTE,chr(10),' '),    
         decode( greatest( nvl(ANAG.DAL,to_date('2222222','j'))    
                         , nvl(ANAG.DAL,to_date('2222222','j'))    
                         )    
               , to_date('2222222','j'), ANAG.DATA_NAS    
                 , greatest( nvl(ANAG.DAL,to_date('2222222','j'))    
                           , nvl(ANAG.DAL,to_date('2222222','j'))    
                           )    
               ) DAL,    
         decode( least( nvl(ANAG.AL,to_date('3333333','j'))    
                      , nvl(ANAG.AL,to_date('3333333','j'))    
                      )    
               , to_date('3333333','j'), to_date(null)    
                 , least( nvl(ANAG.AL,to_date('3333333','j'))    
                        , nvl(ANAG.AL,to_date('3333333','j'))    
                        )    
               ) AL,    
         ANAG.STATO_CIVILE,    
         STCI.DESCRIZIONE DES_STATO_CIVILE,    
         ANAG.COGNOME_CONIUGE,    
         ANAG.TITOLO_STUDIO,    
         TIST.DESCRIZIONE DES_TITOLO_STUDIO,    
         ANAG.TITOLO,    
         ANAG.CATEGORIA_PROTETTA,    
         CAPR.DESCRIZIONE DES_CATEGORIA_PROTETTA,    
         ANAG.TESSERA_SAN,    
         ANAG.NUMERO_USL,    
         ANAG.PROVINCIA_USL,    
         ANAG.TIPO_DOC,    
         EVGI.DESCRIZIONE DES_TIPO_DOC,    
         ANAG.NUMERO_DOC,    
         ANAG.PROVINCIA_DOC,    
         ANAG.COMUNE_DOC,    
         CDOC.DENOMINAZIONE DES_COMUNE_DOC,    
         PDOC.SIGLA         DES_SIGLA_DOC,  
		 RAIN.CI,RAIN.RAPPORTO,CLRA.DESCRIZIONE,RAIN.CC,RAIN.DAL,RAIN.AL,  
		 RAIN.GRUPPO,replace(RAIN.NOTE,chr(10),' '),RAIN.AMBIENTE,  
RAIN.TIPO_NI,RAIN.FASCICOLO,RAIN.TELEFONO_UFFICIO,RAIN.FAX_UFFICIO,RAIN.E_MAIL, 
RARE.MATRICOLA,RARE.ISTITUTO,ISCR.DESCRIZIONE,RARE.SPORTELLO,SPOR.DESCRIZIONE, 
RARE.CONTO_CORRENTE,RARE.DELEGA,RARE.SPESE,RARE.ULTERIORI,RARE.POSIZIONE_INAIL, 
ASIN.DESCRIZIONE,RARE.DATA_INAIL,RARE.TRATTAMENTO,TRPR.DESCRIZIONE, 
RARE.CODICE_CPD,RARE.POSIZIONE_CPD,RARE.DATA_CPD, 
RARE.CODICE_CPS,RARE.POSIZIONE_CPS,RARE.DATA_CPS, 
RARE.CODICE_INPS,RARE.CODICE_IAD,RARE.DATA_IAD, 
RARE.STATISTICO1,RARE.STATISTICO2,RARE.STATISTICO3  
    FROM STATI_CIVILI        STCI    
       , TITOLI_STUDIO       TIST    
       , CATEGORIE_PROTETTE  CAPR    
       , EVENTI_GIURIDICI    EVGI    
       , A_COMUNI          CDOC    
       , A_PROVINCIE       PDOC    
       , A_COMUNI          CNAS    
       , A_PROVINCIE       PNAS    
       , A_STATI_TERRITORI STTE    
       , A_COMUNI          CRES    
       , A_PROVINCIE       PRES    
       , A_COMUNI          CDOM    
       , A_PROVINCIE       PDOM    
	   , CLASSI_RAPPORTO   CLRA  
	   , ISTITUTI_CREDITO  ISCR 
	   , SPORTELLI         SPOR 
	   , ASSICURAZIONI_INAIL ASIN 
	   , TRATTAMENTI_PREVIDENZIALI TRPR 
	   , RAPPORTI_RETRIBUTIVI RARE 
	   , RAPPORTI_INDIVIDUALI RAIN  
       , ANAGRAFICI        ANAG    
   WHERE STCI.CODICE (+) = ANAG.STATO_CIVILE    
     AND TIST.CODICE (+) = ANAG.TITOLO_STUDIO    
     AND CAPR.CODICE (+) = ANAG.CATEGORIA_PROTETTA    
     AND EVGI.CODICE (+) = ANAG.TIPO_DOC    
     AND CDOC.PROVINCIA_STATO (+) = ANAG.PROVINCIA_DOC    
     AND CDOC.COMUNE          (+) = ANAG.COMUNE_DOC    
     AND PDOC.PROVINCIA (+)       = CDOC.PROVINCIA_STATO    
     AND CNAS.PROVINCIA_STATO (+) = ANAG.PROVINCIA_NAS    
     AND CNAS.COMUNE          (+) = ANAG.COMUNE_NAS    
     AND PNAS.PROVINCIA (+)       = CNAS.PROVINCIA_STATO    
     AND STTE.sigla(+) = decode( greatest(ANAG.CITTADINANZA,'999')    
                                          , '999', ANAG.CITTADINANZA    
                                                 , null    
                                          )    
     AND CRES.PROVINCIA_STATO (+) = ANAG.PROVINCIA_RES    
     AND CRES.COMUNE          (+) = ANAG.COMUNE_RES    
     AND PRES.PROVINCIA (+)       = CRES.PROVINCIA_STATO    
     AND CDOM.PROVINCIA_STATO (+) = ANAG.PROVINCIA_DOM    
     AND CDOM.COMUNE          (+) = ANAG.COMUNE_DOM    
     AND PDOM.PROVINCIA (+)       = CDOM.PROVINCIA_STATO  
     AND RAIN.NI                  = ANAG.NI  
     AND RAIN.RAPPORTO = CLRA.CODICE 
     AND RARE.CI (+) = RAIN.CI 
     AND NVL(RARE.ISTITUTO,' ') = ISCR.CODICE (+) 
     AND NVL(RARE.ISTITUTO,' ') = SPOR.ISTITUTO (+) 
     AND NVL(RARE.SPORTELLO,' ') = SPOR.SPORTELLO (+) 
     AND NVL(RARE.TRATTAMENTO,' ') = TRPR.CODICE (+) 
     AND NVL(RARE.POSIZIONE_INAIL,' ') = ASIN.CODICE (+)
     AND ANAG.AL IS NULL
/