CREATE OR REPLACE view VISTA_URP as
select 
 VIAN.COGNOME
,VIAN.NOME
,VIAN.SESSO
,VIAN.NI
,VIAN.DATA_NAS
,VIAN.PROVINCIA_NAS
,VIAN.COMUNE_NAS
,VIAN.DES_COMUNE_NAS
,VIAN.DES_SIGLA_NAS
,VIAN.LUOGO_NAS
,VIAN.CODICE_FISCALE
,VIAN.CODICE_FISCALE_ESTERO
,VIAN.PARTITA_IVA
,VIAN.CITTADINANZA
,VIAN.DES_CITTADINANZA
,VIAN.GRUPPO_LING
,VIAN.INDIRIZZO_RES
,VIAN.PROVINCIA_RES
,VIAN.COMUNE_RES
,VIAN.DES_COMUNE_RES
,VIAN.DES_SIGLA_RES
,VIAN.CAP_RES
,VIAN.TEL_RES
,VIAN.FAX_RES
,VIAN.PRESSO
,VIAN.INDIRIZZO_DOM
,VIAN.PROVINCIA_DOM
,VIAN.COMUNE_DOM
,VIAN.DES_COMUNE_DOM
,VIAN.DES_SIGLA_DOM
,VIAN.CAP_DOM
,VIAN.TEL_DOM
,VIAN.FAX_DOM
,VIAN.STATO_CIVILE
,VIAN.DES_STATO_CIVILE
,VIAN.COGNOME_CONIUGE
,VIAN.TITOLO_STUDIO
,VIAN.DES_TITOLO_STUDIO
,VIAN.TITOLO
,VIAN.CATEGORIA_PROTETTA
,VIAN.DES_CATEGORIA_PROTETTA
,VIAN.TESSERA_SAN
,VIAN.NUMERO_USL
,VIAN.PROVINCIA_USL
,VIAN.TIPO_DOC
,VIAN.DES_TIPO_DOC
,VIAN.NUMERO_DOC
,VIAN.PROVINCIA_DOC
,VIAN.COMUNE_DOC
,VIAN.DES_COMUNE_DOC
,VIAN.DES_SIGLA_DOC
,VICA.CI
,VICA.POSIZIONE
,VICA.DES_POSIZIONE
,VICA.DAL
,VICA.AL AL
,VICA.EVENTO
,VICA.DES_EVENTO
,VICA.FIGURA
,VICA.DES_FIGURA
,VICA.TIPO_RAPPORTO
,VICA.ORE
,VICA.ATTIVITA
,VICA.DES_ATTIVITA
,VICA.QUALIFICA
,VICA.DES_QUALIFICA
,VICA.LIVELLO
,VICA.GESTIONE
,VISE.DESCRIZIONE_G des_gestione
,VISE.CODICE_A      settore_a
,VISE.DESCRIZIONE_A des_settore_a
,VISE.CODICE_B      settore_b
,VISE.DESCRIZIONE_B des_settore_b
,VISE.CODICE_C      settore_c
,VISE.DESCRIZIONE_C des_settore_c
,VISE.CODICE        settore_d
,VISE.DESCRIZIONE_S des_settore_d
,SEDI.CODICE        sede
,SEDI.DESCRIZIONE   des_sede
  from VISTA_ANAGRAFICI VIAN
     , VISTA_CARRIERE VICA
     , VISTA_SETTORI VISE
     , SEDI
 where vian.al is null
   and vian.ni = vica.ni
   and vica.rilevanza = 'S'
   and vise.numero (+) = vica.settore
   and sedi.numero (+) = vica.sede
/
