CREATE OR REPLACE FORCE VIEW vista_rapporti_individuali (ci,
                                                         cognome,
                                                         nome,
                                                         ni,
                                                         data_nas,
                                                         codice_rapporto,
                                                         descrizione_rapporto,
                                                         retributivo,
                                                         presenza,
                                                         giuridico,
                                                         concorso,
                                                         categoria_fiscale,
                                                         categoria_inail,
                                                         vortale,
                                                         cc,
                                                         dal,
                                                         al,
                                                         codice_gruppo,
                                                         descrizione_gruppo,
                                                         rilevanza_gruppo,
                                                         note_gruppo,
                                                         oggetto_gruppo,
                                                         note,
                                                         ambiente,
                                                         tipo_ni,
                                                         fascicolo,
                                                         telefono_ufficio,
                                                         fax_ufficio,
                                                         e_mail,
                                                         indirizzo_rec,
                                                         indirizzo_rec_al1,
                                                         indirizzo_rec_al2,
                                                         provincia_rec,
                                                         comune_rec,
                                                         cap_rec,
                                                         tel_rec,
                                                         fax_rec,
                                                         mail_cedolino
                                                        )
AS
   SELECT rain.ci, rain.cognome, rain.nome, rain.ni, rain.data_nas,
          rain.rapporto, clra.descrizione, clra.retributivo, clra.presenza,
          clra.giuridico, clra.concorso, clra.cat_fiscale, clra.cat_inail,
          clra.vortale, rain.cc, rain.dal, rain.al, rain.gruppo,
          grra.descrizione, grra.rilevanza, grra.note, grra.oggetto,
          rain.note, rain.ambiente, rain.tipo_ni, rain.fascicolo,
          rain.telefono_ufficio, rain.fax_ufficio, rain.e_mail,
          rain.indirizzo_rec, rain.indirizzo_rec_al1, rain.indirizzo_rec_al2,
          rain.provincia_rec, rain.comune_rec, rain.cap_rec, rain.tel_rec,
          rain.fax_rec,
          DECODE (ente.pubblicazione_cedolino,
                  1, DECODE (rain.mail_cedolino, 1, 'Posta', 'E-Mail'),
                  DECODE (rain.mail_cedolino, 1, 'E-Mail', 'Posta')
                 )
     FROM rapporti_individuali rain,
          classi_rapporto clra,
          gruppi_rapporto grra,
          ente
    WHERE rain.rapporto = clra.codice(+) AND rain.gruppo = grra.gruppo(+)
          AND ente.ente_id = 'ENTE'
/

