/*==============================================================*/
/* Database name:  UNITA_ORGANIZZATIVE_FASE_2                   */
/* DBMS name:      ORACLE V7 Version for SI4                    */
/* Created on:     28/10/02 11.16.49                            */
/*==============================================================*/


/*==============================================================*/
/* View: ANAGRAFE                                               */
/*==============================================================*/
CREATE OR REPLACE VIEW ANAGRAFE ( NI, 
COGNOME, NOME, SESSO, DATA_NAS, 
PROVINCIA_NAS, COMUNE_NAS, LUOGO_NAS, DAL, 
AL, CODICE_FISCALE, CITTADINANZA, INDIRIZZO_RES, 
INDIRIZZO_RES_AL1, INDIRIZZO_RES_AL2, PROVINCIA_RES, COMUNE_RES, 
CAP_RES, TEL_RES, PRESSO, INDIRIZZO_DOM, 
INDIRIZZO_DOM_AL1, INDIRIZZO_DOM_AL2, PROVINCIA_DOM, COMUNE_DOM, 
CAP_DOM, TEL_DOM, STATO_CIVILE, COGNOME_CONIUGE, 
TITOLO_STUDIO, TITOLO, CATEGORIA_PROTETTA, GRUPPO_LING, 
PARTITA_IVA, TESSERA_SAN, NUMERO_USL, PROVINCIA_USL, 
TIPO_DOC, NUMERO_DOC, PROVINCIA_DOC, COMUNE_DOC, 
NOTE, UTENTE, DATA_AGG, CODICE_FISCALE_ESTERO, 
FAX_RES, FAX_DOM, AMBIENTE_PROP, TELEFONO_UFFICIO, 
FAX_UFFICIO, E_MAIL, DENOMINAZIONE, DENOMINAZIONE_AL1, 
DENOMINAZIONE_AL2, COMPETENZA_ESCLUSIVA, FLAG_TRG, STATO_CEE, 
TIPO_SOGGETTO, FINE_VALIDITA ) AS select "NI","COGNOME","NOME","SESSO","DATA_NAS","PROVINCIA_NAS","COMUNE_NAS","LUOGO_NAS","DAL","AL","CODICE_FISCALE","CITTADINANZA","INDIRIZZO_RES","INDIRIZZO_RES_AL1","INDIRIZZO_RES_AL2","PROVINCIA_RES","COMUNE_RES","CAP_RES","TEL_RES","PRESSO","INDIRIZZO_DOM","INDIRIZZO_DOM_AL1","INDIRIZZO_DOM_AL2","PROVINCIA_DOM","COMUNE_DOM","CAP_DOM","TEL_DOM","STATO_CIVILE","COGNOME_CONIUGE","TITOLO_STUDIO","TITOLO","CATEGORIA_PROTETTA","GRUPPO_LING","PARTITA_IVA","TESSERA_SAN","NUMERO_USL","PROVINCIA_USL","TIPO_DOC","NUMERO_DOC","PROVINCIA_DOC","COMUNE_DOC","NOTE","UTENTE","DATA_AGG","CODICE_FISCALE_ESTERO","FAX_RES","FAX_DOM","AMBIENTE_PROP","TELEFONO_UFFICIO","FAX_UFFICIO","E_MAIL","DENOMINAZIONE","DENOMINAZIONE_AL1","DENOMINAZIONE_AL2","COMPETENZA_ESCLUSIVA","FLAG_TRG","STATO_CEE","TIPO_SOGGETTO","FINE_VALIDITA" from anagrafici where al is null
/


