REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  07-SEP-93
REM
REM For application system PGM version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM VIEW
REM      VISTA_SETTORI

REM
REM  VISTA_SETTORI
REM
REM  VISE - Elenco delle suddivisioni settoriale con sequenza di ordinamento
REM
PROMPT
PROMPT Creating View VISTA_SETTORI
CREATE OR REPLACE VIEW vista_settori
(
     codice
    ,descrizione
    ,descrizione_al1
    ,descrizione_al2
    ,definizione
    ,numero
    ,sequenza
    ,suddivisione
    ,gestione
    ,settore_g
    ,settore_a
    ,settore_b
    ,settore_c
    ,codice_g
    ,codice_a
    ,codice_b
    ,codice_c
    ,descrizione_g
    ,descrizione_a
    ,descrizione_b
    ,descrizione_c
    ,descrizione_s
    ,sequenza_g
    ,sequenza_a
    ,sequenza_b
    ,sequenza_c
    ,assegnabile
    ,sede
    ,cod_reg
)
AS SELECT
       sett.codice                                     
     , sett.descrizione,sett.descrizione_al1,sett.descrizione_al2
     , nota_gestione||': '||
       decode
       (settg.descrizione,null,sett.descrizione
                              ,settg.descrizione||', '||nota_settore_a||': ')||
       decode
       (setta.descrizione,null,decode(sett.suddivisione,1,sett.descrizione,null)
                              ,setta.descrizione||', '||nota_settore_b||': ')||
       decode
       (settb.descrizione,null,decode(sett.suddivisione,2,sett.descrizione,null)
                              ,settb.descrizione||', '||nota_settore_c||': ')||
       decode
       (settc.descrizione,null,decode(sett.suddivisione,3,sett.descrizione,null)
                              ,settc.descrizione||', '||nota_settore||': ')||
       decode(sett.suddivisione,4,sett.descrizione,null)
     , sett.numero                                     
     , sett.sequenza                                   
     , sett.suddivisione                               
     , sett.gestione                                   
     , sett.settore_g                                  
     , sett.settore_a                                  
     , sett.settore_b                                  
     , sett.settore_c                                  
     , decode(sett.suddivisione,0,sett.codice,settg.codice)
     , decode(sett.suddivisione,1,sett.codice,setta.codice)
     , decode(sett.suddivisione,2,sett.codice,settb.codice)
     , decode(sett.suddivisione,3,sett.codice,settc.codice)
     , decode(sett.suddivisione,0,sett.descrizione,settg.descrizione)
     , decode(sett.suddivisione,1,sett.descrizione,setta.descrizione)
     , decode(sett.suddivisione,2,sett.descrizione,settb.descrizione)
     , decode(sett.suddivisione,3,sett.descrizione,settc.descrizione)
     , decode(sett.suddivisione,4,sett.descrizione,null)
     , decode(sett.suddivisione,0,sett.sequenza,settg.sequenza)
     , decode(sett.suddivisione,0,0,1,sett.sequenza,setta.sequenza)
     , decode(sett.suddivisione,0,0,1,0,2,sett.sequenza,settb.sequenza)
     , decode(sett.suddivisione,0,0,1,0,2,0,3,sett.sequenza,settc.sequenza)
     , sett.assegnabile                                
     , sett.sede
     , sett.cod_reg                                       
FROM
    settori  sett,
    settori  settc,
    settori  settb,
    settori  setta,
    settori  settg,
    ente     ente
 where settc.numero (+) = sett.settore_c
   and settb.numero (+) = sett.settore_b
   and setta.numero (+) = sett.settore_a
   and settg.numero (+) = sett.settore_g
   and ente.ente_id     = 'ENTE'
;

COMMENT ON TABLE vista_settori
    IS 'VISE - Elenco delle suddivisioni settoriale con sequenza di ordinamento';

REM
REM  End of command file
REM
