REM
REM This ORACLE V6 RDBMS command file was generated by CASE*Dictionary
REM                            on  30-NOV-93
REM
REM For application system PPA version 1
REM
SET SCAN OFF

REM  Objects being generated in this file are:-
REM VIEW
REM      TOTALI_CATEGORIE_PRESENZA

REM
REM  TOTALI_CATEGORIE_PRESENZA
REM
REM  TCPA - Totali individuali per Categorie di Presenze / Assenze
REM
PROMPT
PROMPT Creating View TOTALI_CATEGORIE_PRESENZA 
CREATE OR REPLACE VIEW totali_categorie_presenza
(
       ci
     , anno
     , mese
     , categoria
     , sequenza
     , causale
     , riferimento
     , dal
     , al
     , valore
     , sede
     , cdc
)
AS SELECT pspa.ci
        , mese.anno
        , mese.mese
        , toca.categoria
        , ctev.sequenza
        , evpa.causale
        , evpa.riferimento
        , evpa.dal
        , evpa.al
        , decode(toca.gestione,'G',(nvl(evpa.al,to_date('3333333','j'))
                                     -  evpa.dal + 1)
                                  ,evpa.valore
                ) * decode(toca.segno,'-',-1,1) 
          * decode(ctev.gestione||caev.gestione
                  ,'HG',nvl(pspa.min_gg,0)
                  ,'OG',nvl(pspa.min_gg,0)
                       ,1
                  )
          / decode(ctev.gestione||caev.gestione
                  ,'GH',nvl(pspa.min_gg,1)
                  ,'GO',nvl(pspa.min_gg,1)
                       ,1
                  )
        , nvl(evpa.sede,pspa.sede)
        , nvl(evpa.cdc ,nvl(rapa.cdc,rifu.cdc))
     from causali_evento            caev
        , categorie_evento          ctev
        , sedi                      sedr
        , sedi                      sede
        , eventi_presenza           evpa
        , mesi                      mese
        , ripartizioni_funzionali   rifu
        , rapporti_presenza         rapa
        , totalizzazione_causali    toca
        , periodi_servizio_presenza pspa
    where evpa.ci              = pspa.ci
      and rapa.ci              = pspa.ci
      and rapa.dal             = pspa.dal_rapporto
      and rifu.sede        (+) = nvl(pspa.sede_cdc,0)
      and rifu.settore     (+) = pspa.settore
      and caev.codice          = evpa.causale
      and ctev.codice          = toca.categoria
      and evpa.causale         = toca.causale
      and nvl(evpa.motivo,' ')
                            like toca.motivo
      and evpa.dal       between pspa.dal
                             and nvl(pspa.al,to_date('3333333','j'))
      and evpa.riferimento
                         between nvl(ctev.dal,to_date('2222222','j'))
                             and nvl(ctev.al ,to_date('3333333','j')) 
      and (mese.fin_mese - evpa.dal + 1)
                              <= decode(to_char(toca.riferimento_mm)||
                                        to_char(toca.riferimento_gg)
                                       ,null,9999
                                            ,nvl(toca.riferimento_mm,0) * 30 +
                                             nvl(toca.riferimento_gg,0)
                                       )
      and evpa.dal            <= mese.fin_mese
      and sedr.numero (+)      = nvl(pspa.sede,0)
      and sede.numero (+)      = nvl(evpa.sede,0)
      and nvl(sede.codice,nvl(sedr.codice,' ')) 
                            like ctev.sede
      and nvl(evpa.cdc,nvl(rapa.cdc,nvl(rifu.cdc,' ')))
                            like ctev.cdc
      and decode( ctev.opzione
                , 'M', to_char( add_months( evpa.dal
                                          , decode(caev.riferimento,'P',1,0) )
                              , 'YYYYMM' )
                , 'A', to_char( add_months( evpa.dal
                                          , decode(caev.riferimento,'P',1,0) )
                              , 'YYYY' )
                , 'T', to_char( mese.fin_mese, 'YYYY' )
                , 'P', to_char( add_months( evpa.dal
                                          , decode(caev.riferimento,'P',1,0) )
                              , 'YYYY' )
                     , null
                )
                               =
          decode( ctev.opzione
                , 'M', to_char( mese.fin_mese,'YYYYMM' )
                , 'A', to_char( mese.fin_mese,'YYYY' )
                , 'T', to_char( mese.fin_mese,'YYYY' )
                , 'P', to_char( to_number(to_char(mese.fin_mese,'YYYY') ) -1 )
                     , null
                )
;
