CREATE OR REPLACE VIEW astensioni2
(
 CODICE          ,
 DESCRIZIONE     ,
 DESCRIZIONE_AL1 ,
 DESCRIZIONE_AL2 ,
 SEQUENZA        ,
 EVENTO          ,
 CONFERMA        ,
 PER_RET         ,
 INCIDE_GEPE     ,
 INCIDE_GIPE     ,
 MAT_ANZ         ,
 MAT_FER         ,
 MAT_INPS        ,
 MAT_ASSFAM      ,
 MAT_DETFAM      ,
 CONGUAGLIO      ,
 DETRAZIONI      ,
 AUTOMATISMI     ,
 SOSTITUIBILE    ,
 SERVIZIO        ,
 SERVIZIO_INPDAP ,
 RILEVANZA
)
AS select CODICE          ,
          DESCRIZIONE     ,
          DESCRIZIONE_AL1 ,
          DESCRIZIONE_AL2 ,
          SEQUENZA        ,
          EVENTO          ,
          CONFERMA        ,
          PER_RET         ,
          INCIDE_GEPE     ,
          INCIDE_GIPE     ,
          MAT_ANZ         ,
          MAT_FER         ,
          MAT_INPS        ,
          MAT_ASSFAM      ,
          MAT_DETFAM      ,
          CONGUAGLIO      ,
          DETRAZIONI      ,
          AUTOMATISMI     ,
          SOSTITUIBILE    ,
          SERVIZIO        ,
          SERVIZIO_INPDAP ,
          1
     from astensioni
UNION
   select CODICE          ,
          DESCRIZIONE     ,
          DESCRIZIONE_AL1 ,
          DESCRIZIONE_AL2 ,
          SEQUENZA        ,
          EVENTO          ,
          CONFERMA        ,
          PER_RET         ,
          INCIDE_GEPE     ,
          INCIDE_GIPE     ,
          MAT_ANZ         ,
          MAT_FER         ,
          MAT_INPS        ,
          MAT_ASSFAM      ,
          MAT_DETFAM      ,
          CONGUAGLIO      ,
          DETRAZIONI      ,
          AUTOMATISMI     ,
          SOSTITUIBILE    ,
          SERVIZIO        ,
          SERVIZIO_INPDAP ,
          2
     from astensioni
;
