INSERT INTO TIPI_SOGGETTO ( TIPO_SOGGETTO, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2 ) VALUES ( 
'I', 'Individuo', NULL, NULL); 
INSERT INTO TIPI_SOGGETTO ( TIPO_SOGGETTO, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2 ) VALUES ( 
'E', 'Ente', NULL, NULL); 
INSERT INTO TIPI_SOGGETTO ( TIPO_SOGGETTO, DESCRIZIONE, DESCRIZIONE_AL1,
DESCRIZIONE_AL2 ) VALUES ( 
'S', 'Soggetto', NULL, NULL); 
commit;
 
