CREATE TABLE GIP_REF_CODES ( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240), 
  RV_ABBREVIATION  VARCHAR2(240), 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240), 
  RV_TYPE          VARCHAR2(10), 
  RV_MEANING_AL1   VARCHAR2(240), 
  RV_MEANING_AL2   VARCHAR2(240)) 
 STORAGE ( 
   INITIAL 14336 NEXT 4096 PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 99 )
   NOCACHE; 

CREATE UNIQUE INDEX X_GIP_REF_CODES_1 ON 
  GIP_REF_CODES(RV_DOMAIN, RV_LOW_VALUE) 
  STORAGE(INITIAL 8192 NEXT 4096 PCTINCREASE 50 ) ; 

CREATE TABLE PAM_REF_CODES ( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240), 
  RV_ABBREVIATION  VARCHAR2(240), 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240), 
  RV_TYPE          VARCHAR2(10), 
  RV_MEANING_AL1   VARCHAR2(240), 
  RV_MEANING_AL2   VARCHAR2(240)) 
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 14336 NEXT 4096 PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 99 )
   NOCACHE; 

CREATE UNIQUE INDEX X_PAM_REF_CODES_1 ON 
  PAM_REF_CODES(RV_DOMAIN, RV_LOW_VALUE) 
  STORAGE(INITIAL 8192 NEXT 6144 PCTINCREASE 50 ) ; 

CREATE TABLE PEC_REF_CODES ( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240), 
  RV_ABBREVIATION  VARCHAR2(240), 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240), 
  RV_TYPE          VARCHAR2(10), 
  RV_MEANING_AL1   VARCHAR2(240), 
  RV_MEANING_AL2   VARCHAR2(240)) 
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 102400 NEXT 4096 PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 99 )
   NOCACHE; 

CREATE UNIQUE INDEX X_PEC_REF_CODES_1 ON 
  PEC_REF_CODES(RV_DOMAIN, RV_LOW_VALUE) 
  STORAGE(INITIAL 51200 NEXT 18432 PCTINCREASE 50 ) ; 

CREATE TABLE PGC_REF_CODES ( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240), 
  RV_ABBREVIATION  VARCHAR2(240), 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240), 
  RV_MEANING_AL1   VARCHAR2(240), 
  RV_MEANING_AL2   VARCHAR2(240),
  RV_TYPE          VARCHAR2(10)) 
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 8192 NEXT 4096 PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 100 )
   NOCACHE; 

CREATE INDEX X_PGC_REF_CODES_1 ON 
  PGC_REF_CODES(RV_DOMAIN, RV_LOW_VALUE) 
  STORAGE(INITIAL 14336 NEXT 4096 PCTINCREASE 50 ) ; 

CREATE TABLE PGM_REF_CODES ( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240), 
  RV_ABBREVIATION  VARCHAR2(240), 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240), 
  RV_TYPE          VARCHAR2(10), 
  RV_MEANING_AL1   VARCHAR2(240), 
  RV_MEANING_AL2   VARCHAR2(240)) 
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 40960 NEXT 4096 PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 99 )
   NOCACHE; 

CREATE UNIQUE INDEX X_PGM_REF_CODES_1 ON 
  PGM_REF_CODES(RV_DOMAIN, RV_LOW_VALUE) 
  STORAGE(INITIAL 28672 NEXT 4096 PCTINCREASE 50 ) ; 

CREATE TABLE PIP_REF_CODES ( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240), 
  RV_ABBREVIATION  VARCHAR2(240), 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240), 
  RV_TYPE          VARCHAR2(10), 
  RV_MEANING_AL1   VARCHAR2(240), 
  RV_MEANING_AL2   VARCHAR2(240)) 
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 24576 NEXT 4096 PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 99 )
   NOCACHE; 

CREATE INDEX X_PIP_REF_CODES_1 ON 
  PIP_REF_CODES(RV_DOMAIN, RV_LOW_VALUE) 
  STORAGE(INITIAL 18432 NEXT 4096 PCTINCREASE 50 ) ; 

CREATE TABLE PPA_REF_CODES ( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240), 
  RV_ABBREVIATION  VARCHAR2(240), 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240), 
  RV_TYPE          VARCHAR2(10), 
  RV_MEANING_AL1   VARCHAR2(240), 
  RV_MEANING_AL2   VARCHAR2(240)) 
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 40960 NEXT 10240 PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 99 )
   NOCACHE; 

CREATE TABLE PPO_REF_CODES ( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240), 
  RV_ABBREVIATION  VARCHAR2(240), 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240), 
  RV_TYPE          VARCHAR2(10), 
  RV_MEANING_AL1   VARCHAR2(240), 
  RV_MEANING_AL2   VARCHAR2(240)) 
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 24576 NEXT 4096 PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 99 )
   NOCACHE; 

CREATE UNIQUE INDEX X_PPO_REF_CODES_1 ON 
  PPO_REF_CODES(RV_DOMAIN, RV_LOW_VALUE) 
  STORAGE(INITIAL 14336 NEXT 4096 PCTINCREASE 50 ) ; 

/*==============================================================*/
/* Table: PMT_REF_CODES                                         */
/*==============================================================*/


create table PMT_REF_CODES  (
   RV_LOW_VALUE         VARCHAR2(240)                    not null,
   RV_HIGH_VALUE        VARCHAR2(240),
   RV_ABBREVIATION      VARCHAR2(240),
   RV_DOMAIN            VARCHAR2(100)                    not null,
   RV_MEANING           VARCHAR2(240),
   RV_TYPE              VARCHAR2(10),
   RV_MEANING_AL1       VARCHAR2(240),
   RV_MEANING_AL2       VARCHAR2(240)
)
PCTFREE 10   
PCTUSED 40
INITRANS 1   
MAXTRANS 255
STORAGE 
( 
  INITIAL 40k 
  NEXT 4k
  PCTINCREASE 50
  MINEXTENTS 1 
  MAXEXTENTS 99 
)
NOCACHE;

/*==============================================================*/
/* Index: X_PMT_REF_CODES_1                                     */
/*==============================================================*/
create unique index X_PMT_REF_CODES_1 on PMT_REF_CODES (
   RV_DOMAIN ASC,
   RV_LOW_VALUE ASC
)
STORAGE
(
  INITIAL 10k
  NEXT 4k 
  PCTINCREASE 50 
);

/*==============================================================*/
/* Table: PEB_REF_CODES                                         */
/*==============================================================*/


CREATE TABLE PEB_REF_CODES 
( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240)      NULL, 
  RV_ABBREVIATION  VARCHAR2(240)      NULL, 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240)      NULL, 
  RV_TYPE          VARCHAR2(10)       NULL,  
  RV_MEANING_AL1   VARCHAR2(240)      NULL, 
  RV_MEANING_AL2   VARCHAR2(240)
)
; 

CREATE INDEX X_PEB_REF_CODES_1 ON 
  PEB_REF_CODES(RV_DOMAIN, RV_LOW_VALUE);    

/*==============================================================*/
/* Table: PCW_REF_CODES                                         */
/*==============================================================*/


CREATE TABLE PCW_REF_CODES 
( 
  RV_LOW_VALUE     VARCHAR2(240)  NOT NULL, 
  RV_HIGH_VALUE    VARCHAR2(240)      NULL, 
  RV_ABBREVIATION  VARCHAR2(240)      NULL, 
  RV_DOMAIN        VARCHAR2(100)  NOT NULL, 
  RV_MEANING       VARCHAR2(240)      NULL, 
  RV_TYPE          VARCHAR2(10)       NULL,  
  RV_MEANING_AL1   VARCHAR2(240)      NULL, 
  RV_MEANING_AL2   VARCHAR2(240)
)
; 

CREATE INDEX X_PCW_REF_CODES_1 ON 
  PCW_REF_CODES(RV_DOMAIN, RV_LOW_VALUE);    
