-- Script di Generazione delle viste sulla Base Dati: GP4

start crv_ast2.sql
start crv_caaf_ret.sql
start crv_cppa.sql
start crv_coea.sql
start crv_cosi.sql
start crv_decp.sql
start crv_diva.sql
start crv_dogi.sql
start crv_dtra.sql
start crv_emens.sql
start crv_gp_vica.sql
start crv_grdi.sql
start crv_indi.sql
start crv_mbii.sql
start crv_mobi.sql
start crv_peai.sql
start crv_peas.sql
start crv_pese.sql
start crv_prco.sql
start crv_psec.sql
start crv_psei.sql
start crv_psep.sql
start crv_pspa.sql
start crv_prfi.sql
start crv_quin.sql
start crv_rigi.sql
start crv_scaf.sql
start crv_sepr.sql
start crv_suse.sql
start crv_tdma.sql
start crv_tipe.sql
start crv_trei.sql
start crv_vaca.sql
start crv_vacm.sql
start crv_vaev.sql
start crv_vevc.sql
start crv_vidm.sql
start crv_viei.sql
start crv_vimi.sql
start crv_vipi.sql
start crv_vise.sql
start crv_voci_caaf.sql
start crv_vpir.sql
start crv_vpri.sql
start crv_vpsm.sql
start crv_vscf.sql