-- WHEN ERROR IGNORE 24344,00000

-- Creazione Package di funzionalità standard che presentano il problema di richiami
--   intrecciati tra procedure di packages diversi: questi vengo creati invalidi e successivamente 
--   validati dalla compile_all. Sono stati separati dagli altri per non avere le segnalazioni di errore 

start crp_peccinec.sql
start crp_peccinec2.sql
start crp_peccinec3.sql
start crp_peccineg.sql
start crp_peccineg2.sql
start crp_peccinep.sql
start crp_peccinep2.sql
start crp_peccinep3.sql
start crp_peccmocp.sql
start crp_peccmocp_autofam.sql
start crp_peccmocp_ritenuta.sql
start crp_peccmocp_tariffa.sql
start crp_peccmocp1.sql
start crp_peccmocp10.sql
start crp_peccmocp11.sql
start crp_peccmocp12.sql
start crp_peccmocp2.sql
start crp_peccmocp3.sql
start crp_peccmocp4.sql
start crp_peccmocp5.sql
start crp_peccmocp6.sql
start crp_peccmocp7.sql
start crp_peccmocp8.sql
start crp_peccmocp9.sql
start crp_peccmoct.sql
start crp_peccmore.sql
start crp_pxxcmore.sql
start crp_peccmore_autofam.sql
start crp_peccmore_ritenuta.sql
start crp_peccmore_tariffa.sql
start crp_peccmore_onaosi.sql
start crp_peccmore_veneto.sql
start crp_peccmore_addizionali.sql
start crp_peccmore1.sql
start crp_peccmore10.sql
start crp_peccmore11.sql
start crp_peccmore12.sql
start crp_peccmore2.sql
start crp_peccmore3.sql
start crp_peccmore4.sql
start crp_peccmore5.sql
start crp_peccmore6.sql
start crp_peccmore7.sql
start crp_peccmore8.sql
start crp_peccmore9.sql
start crp_peccpere.sql
start crp_peccpere2.sql
start crp_peccpere3.sql
start crp_peccperp.sql
start crp_peccperp2.sql
start crp_peccperp3.sql
start crp_pgmcdope.sql
start crp_pgmcdope2.sql
start crp_ppaccapa.sql
start crp_ppaccapa2.sql
start crp_ppacdppa.sql
start crp_ppacdppa2.sql
start crp_ppoccspo.sql
start crp_ppoccspo2.sql
start crp_ppoccsso.sql
start crp_ppoccsso2.sql
start crp_ppoccsso3.sql
start crp_ppocdipo.sql
start crp_ppocdipo2.sql
start crp_ppocsido.sql
start crp_ppocsido2.sql
start crp_ppocsido3.sql
start crp_ppocsidp.sql
start crp_ppocsidp2.sql
start crp_ppocsidp3.sql
start crp_ppocsoor.sql
start crp_ppocsoor2.sql
start crp_ppocsoor3.sql
