/* Creazione Package di funzionalità standard e di utilità generale */

start crp_comp.sql
start crp_pectrova.sql
start crp_trace.sql
start sia_periodo_crp.sql

start crp_chk_apst.sql
start crp_chk_err.sql
start crp_CHK_DEDI.sql
start crp_CHK_MAIL.sql
start crp_chk_scad.sql
start crp_codice_fiscale.sql
start crp_gp4_crea_viste.sql
start crp_p00updpp.sql
start crp_p00updsp.sql
start crp_pec_reco.sql

/* Creazione Package di applicativo modulo EC */
start crp_cursore_dma.sql
start crp_cursore_fiscale.sql
start crp_cursore_fiscale_05.sql
start crp_cursore_fiscale_06.sql
start crp_cursore_emens.sql
start crp_denunce_inpdap.sql
start crp_pecaelpr.sql
start crp_pecamore.sql
start crp_pecargla.sql
start crp_pecatits.sql
start crp_PECCA730.sql
start crp_peccaddi.sql
start crp_peccadfa.sql
start crp_peccadma.sql
start crp_peccadmi.sql
start crp_PECCADNA.sql
start crp_PECCAINP.sql
start crp_peccarcp.sql
start crp_peccardd.sql
start crp_peccardo.sql
start crp_peccarst.sql
start crp_peccasfi.sql
start crp_PECCAO1M.sql
start crp_peccadpm.sql
start crp_peccaedp.sql
start crp_peccalap.sql
start crp_peccalpi.sql
start crp_PECCARCC.sql
start crp_PECCARDP.sql
start crp_peccarfi.sql
start crp_peccarsm.sql
start crp_peccatfr.sql
start crp_peccbarp.sql
start crp_PECCCAAF.sql
start crp_pecccafa.sql
start crp_PECCCAVA.sql
start crp_peccdeid.sql
start crp_peccdnag.sql
start crp_peccud05.sql
start crp_peccud06.sql
start crp_pecdprev.sql
start crp_peccds22.sql
start crp_peccepda.sql
start crp_peccepre.sql
start crp_PECCF770.sql
start crp_peccfdma.sql
start crp_peccimcc.sql
start crp_PECCIMCE.sql
start crp_peccimci.sql
start crp_peccimco.sql
start crp_peccmoco.sql
start crp_peccmopr.sql
start crp_peccnocu.sql
start crp_peconarf.sql
start crp_pecconfr.sql
start crp_pecco1md.sql    
start crp_peccoced.sql
start crp_peccovar.sql
start crp_peccraad.sql
start crp_peccrein.sql
start crp_peccrtfr.sql
start crp_PECCSDNA.sql
start crp_peccsbrf.sql
start crp_PECCSBSE.sql
start crp_PECCSMDL.sql
start crp_peccsmdm.sql
start crp_peccsmdo.sql
start crp_PECCSMDP.sql
start crp_peccsmep.sql
start crp_PECCSMFC.sql
start crp_PECCSMFD.sql
start crp_PECCSMFE.sql
start crp_Peccsmgm.sql
start crp_PECCSMVB.sql
start crp_peccsr18.sql
start crp_PECCSTVB.sql
start crp_PECCTDMA.SQL
start crp_pecct730.sql
start crp_peccvarm.sql
start crp_PECCVECO.sql
start crp_PECCUDEP.sql
start crp_pecdcava.sql
start crp_pecdcoda.sql
start crp_pecdmarf.sql
start crp_pecdtbfa.sql
start crp_pecepeel.sql
start crp_peclacrd.sql
start crp_PECLADNA.sql
start crp_PECLISDO.sql
start crp_PECLVADP.sql
start crp_PECPREDP.sql
start crp_pecrcnon.sql
start crp_pecsmcud.sql
start crp_pecsmdma.sql
start crp_pecsmdpm.sql
start crp_pecsmdsi.sql
start crp_PECSMFA1.sql
start crp_PECSMFA2.sql
start crp_pecsmgla.sql
start crp_pecsmor6.sql
start crp_PECSMORM.sql
start crp_PECSMT7S.sql
start crp_pecsmtfc.sql
start crp_pecsmt11.sql
start crp_pecsmt12.sql
start crp_pecsmt13.sql
start crp_PECSMTPD.sql
start crp_pecssnsm.sql
start crp_pecssnrf.sql
start crp_pecstrsm.sql
start crp_pecuadma.sql
start crp_pecupere.sql
start crp_pecuragi.sql

/* Creazione Package di applicativo modulo GM */
start crp_cursore_certificato.sql
start crp_PGMAAPEA.sql
start crp_pgmcdodf.sql
start crp_pgmcevpa.sql
start crp_pgmdcado.sql
start crp_pgmicelo.sql
start crp_pgmitelo.sql
start crp_pgmscert.sql
start crp_pgmdcert.sql

/* Creazione Package di applicativo modulo PA */
start crp_ppaaevau.sql
start crp_ppaccalm.sql
start crp_ppacclev.sql
start crp_PPACDERI.sql
start crp_ppacctev.sql
start crp_ppacevgm.sql
start crp_ppacmoev.sql
start crp_ppadcalm.sql
start crp_ppadcapa.sql
start crp_ppaddppa.sql
start crp_PPAEEVEC.sql
start crp_prpcgirp.sql

/* Creazione Package di applicativo modulo PO */
start crp_ppocevpo.sql
start crp_ppocsidf.sql
start crp_ppodcapo.sql

/* Creazione Package di applicativo modulo DO */
start crp_PDOCCADO.sql

/* Creazione Package dello standard */
start crp_acacanas.sql
start crp_acacanrp.sql
start crp_contapag.sql
start crp_leggi_file.sql
start CRP_OBJECT_DATA.sql
start crp_post_handler.sql
start crp_save_si4_accesso.sql
start crp_si4_error_log.sql
start crp_SI4_BASE64.sql
start crp_SI4SCHED.sql
start crp_WEBUTIL_DB.sql

/* Creazione Package di applicativo per Fasi estemporanee */
start crp_pamxrapp.sql
start crp_pecccc07.sql
start crp_pecf2007.sql
start crp_pecsdc07.sql
start crp_pecxadmi.sql
start crp_pecxaggp.sql
start crp_pxxcnper.sql

/* Creazione Package di applicativo Attivazione della MIRGE e funzionalità analoghe */
start crp_p_agfa.sql
start crp_p_anag.sql
start crp_p_asco.sql
start crp_p_asfa.sql
start crp_p_aste.sql
start crp_p_atti.sql
start crp_p_aupa.sql
start crp_p_bavo.sql
start crp_p_bavp.sql
start crp_p_caaf.sql
start crp_p_caev.sql
start crp_p_cafa.sql
start crp_p_cagi.sql
start crp_p_cale.sql
start crp_p_capr.sql
start crp_p_cert.sql
start crp_p_cfis.sql
start crp_p_clpa.sql
start crp_p_cobi.sql
start crp_p_conv.sql
start crp_p_cost.sql
start crp_p_covo.sql
start crp_p_ctev.sql
start crp_p_d1is.sql
start crp_p_d3is.sql
start crp_p_decp.sql
start crp_p_defi.sql
start crp_p_deid.sql
start crp_p_deli.sql
start crp_p_dere.sql
start crp_p_diid.sql
start crp_p_dogi.sql
start crp_p_eapa.sql
start crp_p_ente.sql
start crp_p_esco.sql
start crp_p_esel.sql
start crp_p_esge.sql
start crp_p_eson.sql
start crp_p_esrc.sql
start crp_p_esre.sql
start crp_p_esrm.sql
start crp_p_esvc.sql
start crp_p_esvo.sql
start crp_p_evgi.sql
start crp_p_evpa.sql
start crp_p_fami.sql
start crp_p_figi.sql
start crp_p_foce.sql
start crp_p_gest.sql
start crp_p_grra.sql
start crp_p_imco.sql
start crp_p_imvo.sql
start crp_p_inec.sql
start crp_p_inex.sql
start crp_p_inre.sql
start crp_p_inrp.sql
start crp_p_iscr.sql
start crp_p_moco.sql
start crp_p_mocp.sql
start crp_p_mofi.sql
start crp_p_pegi.sql
start crp_p_pere.sql
start crp_p_perp.sql
start crp_p_pofu.sql
start crp_p_popi.sql
start crp_p_posi.sql
start crp_p_prec.sql
start crp_p_quge.sql
start crp_p_qugi.sql
start crp_p_ragi.sql
start crp_p_rain.sql
start crp_p_ramo.sql
start crp_p_rapa.sql
start crp_p_rare.sql
start crp_p_rarm.sql
start crp_p_rars.sql
start crp_p_rava.sql
start crp_p_reac.sql
start crp_p_reae.sql
start crp_p_reat.sql
start crp_p_rece.sql
start crp_p_reco.sql
start crp_p_rees.sql
start crp_p_reoe.sql
start crp_p_rero.sql
start crp_p_rfca.sql
start crp_p_rica.sql
start crp_p_rico.sql
start crp_p_rifu.sql
start crp_p_rili.sql
start crp_p_rimo.sql
start crp_p_rire.sql
start crp_p_rivo.sql
start crp_p_rppa.sql
start crp_p_rqmi.sql
start crp_p_rrli.sql
start crp_p_rtvo.sql
start crp_p_scaf.sql
start crp_p_scdf.sql
start crp_p_scfi.sql
start crp_p_sede.sql
start crp_p_sett.sql
start crp_p_sodo.sql
start crp_p_sopr.sql
start crp_p_spor.sql
start crp_p_tavo.sql
start crp_p_tefo.sql
start crp_p_toca.sql
start crp_p_tovo.sql
start crp_p_trco.sql
start crp_p_trpo.sql
start crp_p_vapa.sql
start crp_p_vbvo.sql
start crp_p_vbvp.sql
start crp_p_vcev.sql
start crp_p_voco.sql
start crp_p_vode.sql
start crp_p_voec.sql
start crp_p_voin.sql
start crp_p_vpvo.sql
start crp_p_vpvp.sql

start crp_PAAMIRGE.sql
start crp_paamirgm.sql
start crp_paamirec.sql
start crp_PAAMIRPA.sql
start crp_PAAMIRPO.sql

