REM  ===============================================================
REM  Tabella Posizioni 
REM  ===============================================================

INSERT INTO POSIZIONI ( CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, SEQUENZA, POSIZIONE,
RUOLO, STAGIONALE, CONTRATTO_FORMAZIONE, TEMPO_DETERMINATO, PART_TIME, DI_RUOLO, TIPO_FORMAZIONE,
TIPO_DETERMINATO, UNIVERSITARIO, COLLABORATORE, COPERTURA_PART_TIME ) VALUES ( 
'INPD', 'Documenti per I.N.P.D.A.P.', NULL, NULL, 70, NULL, 'D', 'NO', 'NO', 'NO'
, 'NO', 'N', NULL, NULL, NULL, NULL, NULL); 

REM  ===============================================================
REM  Tabella Eventi Giuridici
REM  ===============================================================

INSERT INTO EVENTI_GIURIDICI ( CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, SEQUENZA,
DELIBERA, CERTIFICABILE, PRESSO, STATO_SERVIZIO, RILEVANZA, POSIZIONE, UNICO,
CONTO_ANNUALE, CERT_SETT ) VALUES ( 
'SCON', 'Servizi con onere', NULL, NULL, 900, 'NO', 'SI', 'NO', 'SI', 'D', 'INPD'
, 'NO', NULL, 'NO'); 
INSERT INTO EVENTI_GIURIDICI ( CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, SEQUENZA,
DELIBERA, CERTIFICABILE, PRESSO, STATO_SERVIZIO, RILEVANZA, POSIZIONE, UNICO,
CONTO_ANNUALE , CERT_SETT ) VALUES ( 
'SSON', 'Servizi senza onere', NULL, NULL, 901, 'NO', 'SI', 'NO', 'SI', 'D', 'INPD'
, 'NO', NULL, 'NO'); 

REM  ===============================================================
REM  Tabella Sottocodici Documento
REM  ===============================================================

INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '1', 'Riscatto (ai soli fini cassa pensione)', NULL, NULL, 'Del', NULL, NULL
, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............', NULL, NULL, '.......'
, NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni', NULL, NULL, 'Contr.Unica.So.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '10', 'Ricongiunzione legge 45/90 in sede di pensione (ai soli fini cassa pensione)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '101', 'Riscatto (ai fini cassa pensione e TFS)', NULL, NULL, 'Del', NULL
, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............', NULL, NULL
, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni', NULL, NULL
, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '102', 'Ricongiunzione art.2 L.29/79 (ai fini cassa pensione e TFS)', NULL
, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '103', 'Ricongiunzione legge 45/90 (ai fini cassa pensione e TFS)', NULL, NULL
, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '104', 'Riscatto per iscrizione facoltativa (ai fini cassa pensione e TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '105', 'Ric. Art.2 L.29/79 per iscrizione facoltativa (ai fini cassa pensione e TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '106', 'Riscatto in sede di pensione (ai fini cassa pensione e TFS)', NULL
, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '107', 'Ric. Art.2 L.29/79 in sede di pensione (ai fini cassa pensione e TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '108', 'Riscatto in sede di pensione per iscrizione facoltativa (ai fini cassa pensione e TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '109', 'Ric. Art.2 L.29/79 in sede di pensione per iscr.facoltativa (ai fini cassa pensione e TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '110', 'Ricongiunzione legge 45/90 in sede di pensione (ai fini cassa pensione e TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '2', 'Ricongiunzione art.2 L.29/79 (ai soli fini cassa pensione)', NULL, NULL
, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '201', 'Riscatto (solo ai fini TFS)', NULL, NULL, 'Del', NULL, NULL, 'Riferimento'
, NULL, NULL, NULL, NULL, NULL, '...............', NULL, NULL, '.......', NULL, NULL
, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni', NULL, NULL, 'Contr.Unica.So.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '202', 'Ricongiunzione art.2 L.29/79 (solo ai fini TFS)', NULL, NULL, 'Del'
, NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............', NULL
, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni', NULL
, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '203', 'Ricongiunzione legge 45/90 (solo ai fini TFS)', NULL, NULL, 'Del'
, NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............', NULL
, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni', NULL
, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '204', 'Riscatto per iscrizione facoltativa (solo ai fini TFS)', NULL, NULL
, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '205', 'Ric. Art.2 L.29/79 per iscrizione facoltativa (solo ai fini TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '206', 'Riscatto in sede di pensione (solo ai fini TFS)', NULL, NULL, 'Del'
, NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............', NULL
, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni', NULL
, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '207', 'Ric. Art.2 L.29/79 in sede di pensione (solo ai fini TFS)', NULL, NULL
, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '208', 'Riscatto in sede di pensione per iscrizione facoltativa (solo ai fini TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '209', 'Ric. Art.2 L.29/79 in sede di pensione per iscr.facoltativa (solo ai fini TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '210', 'Ricongiunzione legge 45/90 in sede di pensione (solo ai fini TFS)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '3', 'Ricongiunzione legge 45/90 (ai soli fini cassa pensione)', NULL, NULL
, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '4', 'Riscatto per iscrizione facoltativa (ai soli fini cassa pensione)', NULL
, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '5', 'Ric. Art.2 L.29/79 per iscrizione facoltativa (ai soli fini cassa pensione)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '6', 'Riscatto in sede di pensione (ai soli fini cassa pensione)', NULL, NULL
, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '7', 'Ric. Art.2 L.29/79 in sede di pensione (ai soli fini cassa pensione)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '8', 'Riscatto in sede di pensione per iscrizione facoltativa (ai soli fini cassa pensione)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SCON', '9', 'Ric. Art.2 L.29/79 in sede di pensione per iscr.facoltativa (ai soli fini cassa pensione)'
, NULL, NULL, 'Del', NULL, NULL, 'Riferimento', NULL, NULL, NULL, NULL, NULL, '...............'
, NULL, NULL, '.......', NULL, NULL, 'Anni', NULL, NULL, 'Mesi', NULL, NULL, 'Giorni'
, NULL, NULL, 'Contr.Unica.So.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '0', 'Servizio di Istituto (ai soli fini cassa pensione)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '1', 'Servizio Militare art. 1 legge 274/91 (ai soli fini cassa pensione)'
, NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, '.......', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '10', 'Maternit` con retribuzione ridotta', NULL, NULL, NULL, NULL, NULL, 'Servizio'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL, NULL, 'Ore', NULL
, NULL, 'Ore Cont.', NULL, NULL, 'Qualifica', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '100', 'Servizio di Istituto (ai fini cassa pensione e TFS)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '101', 'Servizio Militare art. 1 legge 274/91 (ai fini cassa pensione e TFS)'
, NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, '.......', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '102', 'Ricongiunzione art. 6 legge 29/79 (ai fini cassa pensione e TFS)'
, NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, '.......', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica'
, NULL, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '104', 'Ricong.D.P.R.1092/73 (ai fini cassa pensione e TFS)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '105', 'Ricong.L.761/73 (ai fini cassa pensione e TFS)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '106', 'Servizio Militare a carico dello Stato (ai fini cassa pensione e TFS)'
, NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, '.......', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '11', 'Maternit` in assenza di retribuzione', NULL, NULL, NULL, NULL, NULL
, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '12', 'Mandati Sindacali', NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '.......', NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '13', 'Mandati Parlamentari', NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '.......', NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '130', 'Ricongiunzione L.523/54 Stato (ai fini cassa pensione e TFS)', NULL
, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, 'Ente', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL
, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '132', 'Ricongiunzione L.523/54 Cpdel (ai fini cassa pensione e TFS)', NULL
, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, 'Ente', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL
, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '133', 'Ricongiunzione L.523/54 Cpi (ai fini cassa pensione e TFS)', NULL
, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, 'Ente', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL
, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '134', 'Ricongiunzione L.523/54 Cpug (ai fini cassa pensione e TFS)', NULL
, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, 'Ente', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL
, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '135', 'Ricongiunzione L.523/54 Cps (ai fini cassa pensione e TFS)', NULL
, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, 'Ente', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL
, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '136', 'Serv. Militare art.1 legge 274/91 in sede di pensione (ai fini cassa pensione e TFS)'
, NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, '.......', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '14', 'Formazione Lavoro con iscr. obblig. dopo 01/01/1991', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore Cont.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '15', 'Formazione Lavoro con iscr. obblig. prima 01/01/1991', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore Cont.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '16', 'Contribuzione volonataria', NULL, NULL, NULL, NULL, NULL, 'Servizio'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '.......', NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '17', 'Maternit` art.25 D.Lg.vo n 151/2001', NULL, NULL, NULL, NULL, NULL
, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL, NULL, 'Ore'
, NULL, NULL, 'Ore Cont.', NULL, NULL, 'Qualifica', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '2', 'Ricongiunzione art. 6 legge 29/79 (ai soli fini cassa pensione)', NULL
, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, '.......', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica'
, NULL, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '200', 'Servizio di Istituto (ai soli fini TFS)', NULL, NULL, NULL, NULL, NULL
, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL, NULL, 'Ore'
, NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.', NULL
, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '201', 'Servizio Militare art. 1 legge 274/91 (ai soli fini TFS)', NULL, NULL
, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '.......'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '202', 'Ricongiunzione art. 6 legge 29/79 (ai soli fini TFS)', NULL, NULL
, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '.......'
, NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL
, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '204', 'Ricong.D.P.R.1092/73 (solo ai fini TFS)', NULL, NULL, NULL, NULL, NULL
, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL, NULL, 'Ore'
, NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.', NULL
, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '205', 'Ricong.L.761/73 (solo ai fini TFS)', NULL, NULL, NULL, NULL, NULL
, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL, NULL, 'Ore'
, NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.', NULL
, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '206', 'Servizio Militare a carico dello Stato (ai soli fini TFS)', NULL, NULL
, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '.......'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '230', 'Ricongiunzione L.523/54 Stato (ai soli fini TFS)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '232', 'Ricongiunzione L.523/54 Cpdel (ai soli fini TFS)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '233', 'Ricongiunzione L.523/54 Cpi (ai soli fini TFS)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '234', 'Ricongiunzione L.523/54 Cpug (ai soli fini TFS)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '235', 'Ricongiunzione L.523/54 Cps (ai soli fini TFS)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '236', 'Serv. Militare art.1 legge 274/91 in sede di pensione (ai soli fini TFS)'
, NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, '.......', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '30', 'Ricongiunzione L.523/54 Stato (ai soli fini cassa pensione)', NULL
, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, 'Ente', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL
, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '32', 'Ricongiunzione L.523/54 Cpdel (ai soli fini cassa pensione)', NULL
, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, 'Ente', NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL
, NULL, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '33', 'Ricongiunzione L.523/54 Cpi (ai soli fini cassa pensione)', NULL, NULL
, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente'
, NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL
, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '34', 'Ricongiunzione L.523/54 Cpug (ai soli fini cassa pensione)', NULL, NULL
, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente'
, NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL
, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '35', 'Ricongiunzione L.523/54 Cps (ai soli fini cassa pensione)', NULL, NULL
, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente'
, NULL, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL
, 'Motivo Cess.', NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '36', 'Serv. Militare art.1 legge 274/91 in sede di pensione (ai soli fini cassa pensione)'
, NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, '.......', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '4', 'Ricong.D.P.R.1092/73 (solo ai fini cassa pensione)', NULL, NULL, NULL
, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL
, NULL, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '5', 'Ricong.L.761/73 (solo ai fini cassa pensione)', NULL, NULL, NULL, NULL
, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ente', NULL, NULL
, 'Ore', NULL, NULL, 'Ore contr.', NULL, NULL, 'Qualifica', NULL, NULL, 'Motivo Cess.'
, NULL, NULL); 
INSERT INTO SOTTOCODICI_DOCUMENTO ( EVENTO, CODICE, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2,
NOTA_DEL, NOTA_DEL_AL1, NOTA_DEL_AL2, NOTA_DESCRIZIONE, NOTA_DESCRIZIONE_AL1, NOTA_DESCRIZIONE_AL2,
NOTA_NUMERO, NOTA_NUMERO_AL1, NOTA_NUMERO_AL2, NOTA_CATEGORIA, NOTA_CATEGORIA_AL1,
NOTA_CATEGORIA_AL2, NOTA_PRESSO, NOTA_PRESSO_AL1, NOTA_PRESSO_AL2, NOTA_N1, NOTA_N1_AL1,
NOTA_N1_AL2, NOTA_N2, NOTA_N2_AL1, NOTA_N2_AL2, NOTA_A1, NOTA_A1_AL1, NOTA_A1_AL2, NOTA_A2,
NOTA_A2_AL1, NOTA_A2_AL2 ) VALUES ( 
'SSON', '6', 'Servizio Militare a carico dello Stato (ai soli fini cassa pensione)'
, NULL, NULL, NULL, NULL, NULL, 'Servizio', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, '.......', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL); 

 

