INSERT INTO OTTICHE ( OTTICA, DESCRIZIONE, SEQUENZA, NOTE ) VALUES ( 
'CF4', 'Contabilità Finanziaria', 1, 'OTTICA DELLA CONTABILITA'); 
INSERT INTO OTTICHE ( OTTICA, DESCRIZIONE, SEQUENZA, NOTE ) VALUES ( 
'GS4', 'GESTIONE SEGRETERIA', 2, 'OTTICA DELLA SEGRETERIA'); 
INSERT INTO OTTICHE ( OTTICA, DESCRIZIONE, SEQUENZA, NOTE ) VALUES ( 
'GP4', 'GESTIONE DEL PERSONALE', 3, 'OTTICA DEL PERSONALE'); 
commit;
 
