REM ============================================================
REM    Extract TABLE :   PCW_REF_CODES
REM ============================================================

WHENEVER SQLERROR EXIT

ALTER TABLE pcw_ref_codes DISABLE ALL TRIGGERS;

DELETE FROM pcw_ref_codes;

WHENEVER SQLERROR CONTINUE

INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_ANAGRAFICI',NULL,NULL,'MODELLI_WORD.VISTE',NULL,'CFG',NULL,NULL);
INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_ASSENZE',NULL,NULL,'MODELLI_WORD.VISTE',NULL,'CFG',NULL,NULL);
INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_CARRIERA',NULL,NULL,'MODELLI_WORD.VISTE',NULL,'CFG',NULL,NULL);
INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_CONTRATTI',NULL,NULL,'MODELLI_WORD.VISTE',NULL,NULL,NULL,NULL);
INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_FAMILIARI',NULL,NULL,'MODELLI_WORD.VISTE',NULL,'CFG',NULL,NULL);
INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_PEGI_D',NULL,NULL,'MODELLI_WORD.VISTE',NULL,'CFG',NULL,NULL);
INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_PEGI_QI',NULL,NULL,'MODELLI_WORD.VISTE',NULL,'CFG',NULL,NULL);
INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_PEGI_SE',NULL,NULL,'MODELLI_WORD.VISTE',NULL,'CFG',NULL,NULL);
INSERT INTO pcw_ref_codes ( RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_DOMAIN, RV_MEANING, RV_TYPE, RV_MEANING_AL1, RV_MEANING_AL2) VALUES ('WORD_SEDI',NULL,NULL,'MODELLI_WORD.VISTE',NULL,'CFG',NULL,NULL);

WHENEVER SQLERROR EXIT

ALTER TABLE pcw_ref_codes ENABLE ALL TRIGGERS;

WHENEVER SQLERROR CONTINUE