REM ============================================================
REM    Progetto:   GP4 - Gestione Integrata Personale
REM    Istanza:    GP4PAL - Gestione del Personale - Parametri PAL
REM    ServerName: svi
REM    DBMS:       O73
REM    DBUser:     PAL
REM 
REM    Extract:    c:\si4\gp4\gipv4\ins\Gp4eb.ext
REM    On File:    c:\si4\gp4\gipv4\ins\gp4eb_ins.sql
REM    Date:       23/11/2007  15.04.42
REM ============================================================

SET TERMOUT OFF 

REM ============================================================
REM    Extract SYNONYM :   A_MENU
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE

INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013861,1013887,'PEBCASBA',20,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','*',1013861,1013887,'PEBCASBA',20,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013861,1013888,'PEBDMOBA',30,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','*',1013861,1013888,'PEBDMOBA',30,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013861,1013886,'PEBDPABA',10,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','*',1013861,1013886,'PEBDPABA',10,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013861,1013889,'PEBDSTBA',40,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','*',1013861,1013889,'PEBDSTBA',40,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',0,1013861,'PEBEB',50,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','*',0,1013861,'PEBEB',50,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013861,1013862,'PEBSBACO',1,NULL);
INSERT INTO A_MENU ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','*',1013861,1013862,'PEBSBACO',1,NULL);
WHENEVER SQLERROR CONTINUE

REM ============================================================
REM    End Extract: c:\si4\gp4\gipv4\ins\gp4eb_ins.sql
REM ============================================================
