REM ============================================================
REM    Progetto:   GP4 - Gestione Integrata Personale
REM    Istanza:    GP4PAL - Gestione del Personale - Parametri PAL
REM    ServerName: svi
REM    DBMS:       O73
REM    DBUser:     PAL
REM 
REM    Extract:    c:\si4\gp4\gipv4\ins\Gp4ir_uno.ext
REM    On File:    c:\si4\gp4\gipv4\ins\gp4ir_ins_menu.sql
REM    Date:       13/11/2007  12.52.02
REM ============================================================

SET TERMOUT OFF 

REM ============================================================
REM    Extract SYNONYM :   A_CATALOGO_STAMPE
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE

INSERT INTO A_CATALOGO_STAMPE ( STAMPA, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO_PROPRIETA, TIPO_VISURA, CLASSE, STAMPA_BLOCCATA, STAMPA_PROTETTA, SEQUENZIALE) VALUES ('PXIRISLA','Periodi di assenza da IRIS',NULL,NULL,'U','U','A_C','N','N','S');
INSERT INTO A_CATALOGO_STAMPE ( STAMPA, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO_PROPRIETA, TIPO_VISURA, CLASSE, STAMPA_BLOCCATA, STAMPA_PROTETTA, SEQUENZIALE) VALUES ('PXIRISLV','Variazioni di reparto da IRIS',NULL,NULL,'U','U','A_C','N','N','S');

REM ============================================================
REM    Extract SYNONYM :   A_PASSI_PROC
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE

INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA, STAMPA, GRUPPO_LING) VALUES ('PXIRISCV',1,'Caricamento variazioni settore da IRIS',NULL,NULL,'Q','PXIRISCV',NULL,NULL,'N');
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA, STAMPA, GRUPPO_LING) VALUES ('PXIRISCV',2,'Caricamento assenze da IRIS',NULL,NULL,'Q','PXIRISCA',NULL,NULL,'N');
INSERT INTO A_PASSI_PROC ( VOCE_MENU, PASSO, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO, MODULO, STRINGA, STAMPA, GRUPPO_LING) VALUES ('PXIRISCV',3,'Caricamento assenze da IRIS',NULL,NULL,'R','PXIRISLA',NULL,'PXIRISLA','N');

REM ============================================================
REM    Extract SYNONYM :   A_SELEZIONI
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE

INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_ASSPTV','PXIRISCV',0,'Codice Assenza per PTV',NULL,NULL,2,'C','N','XXXX',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_BLOCCO','PXIRISCV',0,'Blocco per cedolino SI/NO',NULL,NULL,2,'C','N','NO',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_CESSATI','PXIRISCV',0,'Cessati SI/NO',NULL,NULL,2,'C','N','NO',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_CONGUAGLIO','PXIRISCV',0,'Attiva conguaglio SI/NO',NULL,NULL,2,'C','N','NO',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_DATA_INIZIO','PXIRISCV',1,'Acquisizione Modifiche Dal',NULL,NULL,10,'D','N',NULL,NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_EVENTO','PXIRISCV',0,'codice evento giuridico',NULL,NULL,4,'C','N','MOBI',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_INTERSEZIONI','PXIRISCV',0,'Assesta Intersezioni SI/NO',NULL,NULL,2,'C','N','NO',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_PROLUNGAMENTI','PXIRISCV',0,'Prolungamenti SI/NO',NULL,NULL,2,'C','N','NO',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_PTV','PXIRISCV',0,'Part-time verticali SI/NO',NULL,NULL,2,'C','N','NO',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_RILEVANZE','PXIRISCV',0,'Rilevanze per var.settori',NULL,NULL,2,'C','N','SQEI',NULL,NULL,NULL,NULL);
INSERT INTO A_SELEZIONI ( PARAMETRO, VOCE_MENU, SEQUENZA, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2, LUNGHEZZA, FORMATO, OBBLIGO, VALORE_DEFAULT, DOMINIO, ALIAS, GRUPPO_ALIAS, NUMERO_FK) VALUES ('P_SEGNALAZIONI','PXIRISCV',0,'Stampa Segnalazioni (A/C)',NULL,NULL,1,'C','N','C',NULL,NULL,NULL,NULL);

REM ============================================================
REM    Extract SYNONYM :   A_VOCI_MENU
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE

INSERT INTO A_VOCI_MENU ( VOCE_MENU, AMBIENTE, ACRONIMO, ACRONIMO_AL1, ACRONIMO_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, TIPO_VOCE, TIPO, MODULO, STRINGA, IMPORTANZA, GUIDA_O, PROPRIETA) VALUES ('PXIRISCV','P00','CIRIS',NULL,NULL,'Caricamento variazioni settore da IRIS',NULL,NULL,'F','D','ACAPARPR',NULL,1,'A_PARA',NULL);

REM ============================================================
REM    Extract SYNONYM :   A_DOMINI_SELEZIONI
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE


REM ============================================================
REM    Extract SYNONYM :   A_GUIDE_O
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE

INSERT INTO A_GUIDE_O ( GUIDA_O, SEQUENZA, ALIAS, LETTERA, LETTERA_AL1, LETTERA_AL2, TITOLO, TITOLO_AL1, TITOLO_AL2, GUIDA_V, VOCE_MENU, VOCE_RIF, PROPRIETA, TITOLO_ESTESO, TITOLO_ESTESO_AL1, TITOLO_ESTESO_AL2) VALUES ('A_PARA',1,'PREN','P',NULL,NULL,'Prenot...',NULL,NULL,NULL,'ACAEPRPA','*','X',NULL,NULL,NULL);

REM ============================================================
REM    Extract SYNONYM :   A_GUIDE_O
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE


REM ============================================================
REM    Extract SYNONYM :   A_GUIDE_V
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE


REM ============================================================
REM    Extract SYNONYM :   A_GUIDE_V
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE


REM ============================================================
REM    End Extract: c:\si4\gp4\gipv4\ins\gp4ir_ins_menu.sql
REM ============================================================
