INSERT INTO PARAMETRI_MISSIONI( SE_MODIFICA_RICHIESTE_IN_EC, SE_GESTIONE_ACCONTI,
                                VOCE_ECONOMICA_ACCONTO, SUB_ACCONTO, SEGNO_ACCONTO_IN_EC,
                                MINUTI_ARROTONDAMENTO ) 
SELECT 0, 0, null, null, '-', 59
  FROM DUAL
 WHERE NOT EXISTS (SELECT 'x' FROM PARAMETRI_MISSIONI)
;
commit;
 
