REM ============================================================
REM    Progetto:   GP4 - Gestione Integrata Personale
REM    Istanza:    GP4PAL - Gestione del Personale - Parametri PAL
REM    ServerName: svi
REM    DBMS:       O73
REM    DBUser:     PAL
REM 
REM    Extract:    c:\si4\gp4\gipv4\ins\Gp4mt.ext
REM    On File:    c:\si4\gp4\gipv4\ins\gp4mt_ins.sql
REM    Date:       23/11/2007  15.04.47
REM ============================================================

SET TERMOUT OFF

REM ============================================================
REM    Extract SYNONYM :   A_MENU
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE

INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004025,1004358,'P00EDELI',94,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004025,1006843,'P00RANAG',99,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004365,1004461,'PECEVOEC',97,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1000221,1000237,'PGMDCONT',1,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013228,1013232,'PGMDGEST',2,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1000220,1000224,'PGMDGEST',20,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1000221,1000243,'PGMDQUAL',7,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013698,'PMTCAULI',8,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013675,'PMTCCOUF',5,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013695,'PMTCGLUF',6,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013702,'PMTCPAEC',11,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013658,'PMTCRIDI',3,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013696,'PMTCRIST',7,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013619,'PMTDPARA',1,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013620,'PMTDTAVA',2,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013664,'PMTEACER',4,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013701,'PMTIDIST',10,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013699,'PMTIRICH',9,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',0,1013618,'PMTMT',45,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013704,'PMTSDIST',13,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1013618,1013703,'PMTSRIRI',12,NULL);
WHENEVER SQLERROR CONTINUE

REM ============================================================
REM    End Extract: c:\si4\gp4\gipv4\ins\gp4mt_ins.sql
REM ============================================================
