REM ============================================================
REM    Progetto:   GP4 - Gestione Integrata Personale
REM    Istanza:    GP4PAL - Gestione del Personale - Parametri PAL
REM    ServerName: svi
REM    DBMS:       O73
REM    DBUser:     PAL
REM 
REM    Extract:    c:\si4\gp4\gipv4\ins\Gp4pi.ext
REM    On File:    c:\si4\gp4\gipv4\ins\gp4pi_ins.sql
REM    Date:       23/11/2007  15.04.47
REM ============================================================

SET TERMOUT OFF

REM ============================================================
REM    Extract SYNONYM :   A_MENU
REM ============================================================

WHENEVER SQLERROR EXIT

WHENEVER SQLERROR CONTINUE

INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004025,1006844,'P00RINDI',99,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004365,1004463,'PECECOVO',97,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004365,1004449,'PGMEGEST',96,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004362,1004411,'PGMEGEST',71,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004362,1004404,'PGMEQUAL',84,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1013050,'PGPCIMPO',10,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1012553,'PGPCINPD',1,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1012554,'PGPCISCR',2,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1013049,'PGPCPERI',9,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1012555,'PGPCPRAT',3,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1012560,'PGPCQUAL',8,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1012558,'PGPCRETR',6,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1012556,'PGPCSCON',4,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,15605,'PGPCSSON',15,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1012559,'PGPCVOCI',7,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1013661,'PGPDQUS7',18,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1013660,'PGPDVOS7',17,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',0,1012552,'PGPIP',85,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1013723,'PGPLQUS7',20,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1012552,1013722,'PGPLVOS7',19,NULL);
INSERT INTO a_menu ( APPLICAZIONE, RUOLO, PADRE, FIGLIO, VOCE_MENU, SEQUENZA, STAMPANTE) VALUES ('GP4','AMM',1004363,1006839,'PPAECONT',91,NULL);
WHENEVER SQLERROR CONTINUE

REM ============================================================
REM    End Extract: c:\si4\gp4\gipv4\ins\gp4pi_ins.sql
REM ============================================================
