CREATE TABLE SIA_DEFAULT_INDICI
( TABLE_NAME  VARCHAR2(30), 
  INDEX_NAME  VARCHAR2(30),
  UNIQUENESS  VARCHAR2(9)
) ;

CREATE TABLE SIA_DEFAULT_INDICI_COL
( TABLE_NAME        VARCHAR2(30), 
  INDEX_NAME        VARCHAR2(30),
  COLUMN_NAME       VARCHAR2(4000),
  COLUMN_POSITION   NUMBER
) ;
